### ISSUE TITLE
Pulsar 1178 freezes Mixbus when re-opening session

### ISSUE THREAD

**Issue by durutti** [robbert-vdh/yabridge#100]
**Problem description**
When I re-open  a session with the plugin in a track Mixbus7 freezes

**What did you expect to happen?**
work

**What actually happened?**
see attached log
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/6407269/yabridge.log)

**System information**
- Plugin: Pulsar 1178
- Plugin type: VST3
- Host: Mixbus7
- Operating system: Ubuntu 20.04
- Wine version: 6.7.r0.gdeed76f3 ( TkG Staging Esync Fsync )'
- Audio:  ALSA
- Installation method: yabridgctl
- yabridge version: 3.1.0-67-g0f506f7
- yabridgectl version: 3.1.0-67-g0f506f7
**Debug log**
Please also include a debug log if possible. If you are reporting an issue with yabridgectl, then you can omit this section.

**Comment by robbert-vdh** [comment]
Okay, I haven't tested the actual plugin but I think this should fix it. Ardour/Mixbus is doing some weird things and it tried to set a parameter on the plugin that the plugin has just automated (while loading the preset). This resulted in a deadlock. Can you try the very latest master branch build? It may take a few more minutes to build. And of course don't forget the `yabridgectl sync`. :grinning:

**Comment by durutti** [comment]
Okay the latest master branch build fixed the deadlock
Thank you

**Comment by robbert-vdh** [comment]
With yabridge 3.2.0's release this issue should be fixed! Let me know if it is not.
