### ISSUE TITLE
Cannot activate Gainmatch vst3 by Letitmix

### ISSUE THREAD

**Issue by durutti** [robbert-vdh/yabridge#101]
**Problem description**
Deadlock when click on license option

**What did you expect to happen?**
open and activate plugin

**What actually happened?**
dealock

**System information**
- Plugin: Gainmatch vst3 
- Plugin type: VST3
- Host:Mixbus7
- Operating system: Ubuntu 20.04
- Wine version: 6.7.r0.gdeed76f3 ( TkG Staging Esync Fsync )
- Audio: ALSA
- Installation method: yabridgectl
- yabridge version: 3.1.0-80-g177431e

- yabridgectl version:3.1.0-80-g177431e

**Debug log**
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/6409457/yabridge.log)

**Comment by robbert-vdh** [comment]
I have no experience with the plugin, but this must just be a Wine compatibility issue. There are no deadlocks in the log output. Some plugins, like the TDR plugins, would in the past freeze after selecting a license file requiring a restart (but I think a recent-ish Wine update fixed that). You can check if this works in the Windows version of REAPER running under Wine, but as a rule of thumb GUI related crashes and freezes when just interacting with the GUI are Wine compatibility issues.

But for what it's worth, the plugin doesn't freeze here with wine-tkg 6.4 when installed to a clean Wine prefix with nothing else in it:

![afbeelding](https://user-images.githubusercontent.com/748520/116781270-22b9bb80-aa82-11eb-9dac-f4629d8eeea2.png)

Wine 6.7 introduced some regressions, so maybe this plugin is also affected by that.

**Comment by durutti** [comment]
yes 6.7 doesn't seem to play well. I will live it for the moment and wait for the 6.8
Thank you

**Comment by robbert-vdh** [comment]
This is also a Wine issue that we cannot fix on our side. But if you run into another issue with a plugin, then feel free to open another ticket!
