### ISSUE TITLE
README documentation needs some updates re: Native Instruments setup

### ISSUE THREAD

**Issue by ScottGarman** [robbert-vdh/yabridge#102]
I'm running Ubuntu 20.04 and tonight managed to get my Native Instruments installed (Kontact, Reaktor, etc), but I ran into a couple of problems following the README instructions I wanted to report:

* I was unable to use Native Access to download any instruments ISOs, and the NA app showed the error "Downloading XYZ failed: could not find the downloader". I found a [post on the NI forum](https://www.native-instruments.com/forum/threads/running-via-wine-on-linux-systems.373433/#post-2090607) that explained that wine-stable was required for this to work (not wine-staging). When I switched to wine-stable, the ISO downloads succeeded. In fact, the Kontact player install was able to run to completion as well, though not for any of the other instruments or packs that I tried (which had to be installed using the ISO).

* When I followed the instructions to use udisksctl to mount the ISO files, creating the loopback device worked, but the mount command failed because 'unhide' was not an allowed option. I tried a bunch of things to try to get this enabled, but eventually gave up and instead added an entry to /etc/fstab and mounted the loop device as root, which worked. I'm not sure if there is documentation you could add for Ubuntu 20.04 (and possibly other) users on how to enable unhide, or if you could just mention the /etc/fstab method as a fallback workaround.

Forgive me for not just submitting a doc PR to fix this - I'm not sure what level of detail is preferred here, and I don't know to what extent these issues would be encountered by folks on other Ubuntu releases.

**Comment by robbert-vdh** [comment]
Seems like Wine 6.6 broke the downloads in Native Access. I've submitted a Wine bug report for this [here](https://bugs.winehq.org/show_bug.cgi?id=51098). Wine 6.5+ breaks some other things, so my recommendation still is to stick with Wine Staging 6.4. I did put this in the last release notes, but I forgot to plaster it all over the readme. I did so [here](https://github.com/robbert-vdh/yabridge/commit/e3f65374f439e7df7505708ee6b22482ad864f1b) (along with downgrading instructions), thanks for reminding me!

And I'm not sure why Ubuntu 20.04's `udisksctl` didn't let you specify options. Were you at least able have it use the `udf` file system type? Maybe that version of `udisksctl` requires a fully typed out `--options`. The whole reason why I'm recommending using udisksctl over using `sudo mount` (you don't need to edit fstab), is so you _don't_ need to use `sudo` to mount these ISO files.

**Comment by ScottGarman** [comment]
Yeah, I only downgraded to wine-stable for the install of the NI instruments, then upgraded to wine-staging again when done.

`udisksctl` complains specifically about the `unhide` option, `-o` vs `--options` results in the same message: `Error mounting /dev/loop20: GDBus.Error:org.freedesktop.UDisks2.Error.OptionNotPermitted: Mount option `unhide' is not allowed`

I found some documentation on how udisks is configured, and tried adding lines to `/etc/udisks2/udisks2.conf` and alternately `/etc/udisks2/mount_options.conf` (which doesn't exist by default on my system) and restarting the udisks2 service, but couldn't get it to allow the `unhide` option. I may have missed something there though and am happy to try a suggestion.

**Comment by robbert-vdh** [comment]
`unhide` seems to be allowed on most other distros (including Arch/Manjaro where I tested this on). It would be nice to figure out a way to mount these files without having to run things as root.

**Comment by robbert-vdh** [comment]
Apparently you can tell udisks2 to allow more mounting options to be used by the user, so I've added instructions on how to enable mounting udf files with the unhide option in the readme. More recent versions of udisks2 already have this as a default (I've just copied the line from the default config file), but it seems like Ubuntu 20.04 is stuck with an older version of udisks2.

**Comment by pgcd** [comment]
I couldn't get the instructions in the readme to work for me (Linux Mint Vera) - after the `udisksctl loop-setup` command, the ISO would be mounted and the following `udisksctl mount` command would fail with `Error mounting /dev/loop0: GDBus.Error:org.freedesktop.UDisks2.Error.AlreadyMounted: Device /dev/loop0 is already mounted`

Eventually I managed to solve the problem by creating a new `/etc/udisks2/mount_options.conf` file with
```
[defaults]
udf_defaults=uid=$UID,gid=$GID,iocharset=utf8,unhide
```
so that all NI ISO images are mounted with the appropriate option, and everything seems to work nice.

**Comment by PanieriLorenzo** [comment]
I'd like to add for anyone stumbling on this issue that on Ubuntu `udisksctl loop-setup` will trigger automount, so you should disable automount first so you can mount manually with the `unhide` option
