### ISSUE TITLE
Certain VST3 plugins do not initially display in Reaper while using external monitor

### ISSUE THREAD

**Issue by JonathanTroyer** [robbert-vdh/yabridge#104]
**Problem description**
Some VST3s do not visibly appear until reloaded. Please see [this comment](https://github.com/robbert-vdh/yabridge/issues/89#issuecomment-832264183) in #89. However, since Bitwig always opens plugins in a floating window, there's no problem there.

**What did you expect to happen?**
For plugins to display properly.

**What actually happened?**
Certain plugins would not display unless floated or refocused. This only happened when an external screen was used.

**System information**
Output from loading in Reaper:
```
Initializing yabridge version 3.2.0
host:          '/usr/bin/yabridge-host.exe'
plugin:        '/home/jtroyer/.wine/drive_c/Program Files/Common Files/VST3/MeldaProduction/MCharacter.vst3'
plugin type:   'VST3'
realtime:      'no'
sockets:       '/run/user/60020/yabridge-MCharacter-1IQRWadr'
wine prefix:   '/home/jtroyer/.wine'
wine version:  '6.8'

config from:   '<defaults>'
hosting mode:  'individually, 64-bit'
other options: '<none>'

Enabled features:
- bitbridge support
- VST3 support
```
I did try adding a yabridge.toml in the MeldaProduction VST folder (which is all `.vst3` files).

Additional system info:
```
OS: Arch Linux 
Kernel: x86_64 Linux 5.12.2-xanmod1-1
Shell: zsh 5.8
DE: GNOME 40.1.0
CPU: AMD Ryzen 9 4900HS with Radeon Graphics @ 16x 3GHz
GPU: NVIDIA GeForce RTX 2060 with Max-Q Design
RAM: 7694MiB / 15484MiB
```

**Debug log**
[yabridge.log](https://gist.github.com/JonathanTroyer/c4280220eb844b3705e8378b2ea198a6)

**Comment by robbert-vdh** [comment]
Since I didn't get any responses in #89, yabridge 3.5.0 now contains a potential fix for this. Please let me know if it helps!

**Comment by JonathanTroyer** [comment]
Hey there! Sorry for not responding sooner, I've been terribly busy with a release.

Yabridge 3.5.1 now cannot render any MeldaProduction plugins, either in Reaper or Bitwig, with or without an external monitor, on either integrated or dedicated graphics, with or without `editor_xembed`.

**Comment by robbert-vdh** [comment]
Something has to be off with your setup then. If it says it's loading a 32-bit plugin, then it's definitely loading a 32-bit plugin. Did you rerun `yabridgectl sync` after upgrading? Does this only happen with MeldaProduction plugins? Are you talking about the VST2 or the VST3 versions? Do you have a debug log you can upload? Check the template when creating a new issue for instructions on how to do that!

**Comment by JonathanTroyer** [comment]
1) yes
2) yes
3) VST3

Turns out I _was_ using the 32-bit versions, as I added `Program Files (x86)/Common Files/VST3` instead of `Program Files/Common Files/VST3`. Using the 64-bit VST3 files works _perfectly_ now. Thanks for everything!

**Comment by robbert-vdh** [comment]
Awesome! The 32-bit versions _should_ work fine (they do on my machine), but maybe you were just missing some Wine dependencies then (Wine has a lot of 'optional' dependencies, and you may not have the 32-bit versions of those installed if you didn't do so manually). Not a real issue of course if the 64-bit versions work fine. :grin:
