### ISSUE TITLE
Heads-Up: Upgrading to WINE6 breaks iLok licenses

### ISSUE THREAD

**Issue by lentferj** [robbert-vdh/yabridge#108]
Not strictly yabridge related, but maybe of interest for fellow yabridge users:
When using iLok License Manager with WINE and upgrading from 5 to 6, this changes the location ID for iLok License Manager and it will think you are on a new/different system with no licenses installed. I recommend to deactivate your local licenses (move them to your account) before upgrading to 6 and activating your licenses again after the upgrade.
If you got already hit (like me) - I was able to resolve this by restoring a backup of my WINE Prefix to a different location, downgrading to WINE 5.x and running iLok LM from that location/WINEPREFIX and proceeding as described above.

**Comment by robbert-vdh** [comment]
For these reasons I'll always recommend avoiding invasive DRM like iLoK and Waves' DRM. Even on Windows these things have a non-zero chance of imploding on themselves from time to time. I would post about these things in the Discord though, there's not a lot I can do about this here. :sweat_smile:

**Comment by siborg** [comment]
I agree with your suggestions Robert. Personally if I see the product using
iLok, I simply do not use it and look for alternatives. Period. I realise
this is not ideal for some people but iLok is a terrible technology and
even on Windows things are not straightforward.

Very Best Regards,

Szymon Kosecki
