### ISSUE TITLE
slate drum gui performance on load, stuck

### ISSUE THREAD

**Issue by geekositalia** [robbert-vdh/yabridge#110]
**Problem description**
I, i report slate drum 5 issue, when open vst, gui is black and stuck for 5/6 seconds. Very slow load.

**What did you expect to happen?**
Gui open fast as usual

**What actually happened?**
Very slow load.

**System information**
- Plugin: Slate Drum 5
- Plugin type: vst2
- Host: all daw
- Operating system: openSUSE on GeekosDaw Project 
- Wine version: Wine Staging 6.4
- Audio: Jack
- Installation method: Both
- yabridge version: 3.2.0
- yabridgectl version: 3.2.0

**Comment by geekositalia** [comment]
[yabridge.tar.gz](https://github.com/robbert-vdh/yabridge/files/6587780/yabridge.tar.gz)

**Comment by robbert-vdh** [comment]
The plugin uses hardware accelerated graphics for its GUI. If you're on a laptop or another device with switchable graphics, launching your DAW with your discrete GPU enabled may help. Other than that, what you can try is:

- Adding `d2d1` in winecfg's libraries tab and setting that to disabled. If the plugin has a fallback rendering mode that doesn't use Direct2D then that may help.  There's a good chance that the plugin doesn't and will now show you an error message instead, in which case you'd need to remove the override again.
- You can try using [dxvk](https://github.com/doitsujin/dxvk) which also doesn't implement Direct2D, but at least it's Direct3D implementaiton is much faster than Winie's WineD3D.

**Comment by geekositalia** [comment]
hi rob, no im on ryzen with "semi dedicated" (3400g) hardware. no problem with linvst (i dont use it anymore, yabrdige is more usable), and no problem with other plugin with graphic accelleration (example kontakt with like arcane libraries). Only startup is slow, with black screen, and only with ssd5, after start work good

**Comment by geekositalia** [comment]
p.s. i use native d3d dll's or manager of ssd5 dont work

**Comment by robbert-vdh** [comment]
> no problem with linvst

Did you try this recently? It could be that some Wine update broke the plugin. If you did, then it should at least be solvable. I tried installing SSD5.5 Free, but the installation in their Steven Slate Audio Center won't start for me (if you can tell me how to fix this, that would be great!), so I can't take a look at it for myself. In the logs there's nothing that would indicate that the plugin is hanging or waiting on something, since all of those calls to `effEditGetRect()` are answered immediately, and those can't be answered while the plugin is blocking the event loop. Maybe the plugin is fully functional during those six seconds you mentioned, but Wine/the plugin has some redrawing issues where it only appears to be black? You could easily verify that by clicking on the GUI, or by dragging the FX window around.

**Comment by geekositalia** [comment]
im mantainer of wine for geekosdaw, and i use locked for audio 6.4 version. (for yabrdige 3.3 update what version of wine is reccomended?). all plugin its okay... slate center 
![Screenshot_20210607_171841](https://user-images.githubusercontent.com/55261197/121043032-8e472500-c7b4-11eb-958b-84e4dc81bba3.png)
need, if i remember, dx native dll replacement. Yep, i will try linvst and openup fast

**Comment by robbert-vdh** [comment]
> (for yabrdige 3.3 update what version of wine is reccomended?)

I still pinned Wine Staging 6.4 myself because where hasn't been a more recent version that doesn't break _something_ for me. Wine 6.10 also caused Kontakt and a couple of other plugins to segfault when they shut down.

Oh and apparently there was just a popup stuck in the top left corner of the screen that I just didn't notice. When you close that the installation continues. I'll install everything to a clean Wine prefix and let you know how it went.

**Comment by geekositalia** [comment]
thank you robbert!

**Comment by robbert-vdh** [comment]
To get back to you, I installed the plugins in a clean prefix with no overrides at all. Both the VST2 and the VST3 version of the plugin load and open immediately (both the actual plugin and the editor) in Bitwig Studio 4.0 beta 2, REAPER 6.29, and Carla 2.3.0-5-62a641017. I wouldn't be surprised if those overrides you're using are the problem. Have you tried getting rid of those?

**Comment by geekositalia** [comment]
yes I tried but nothing changes, the strange thing is that all the plugins work correctly (and even the games even if it has nothing to do with it). I don't have the vst3 version, I was only vst3 of slate. I do some checks

**Comment by geekositalia** [comment]
i have an update of ssd5, i will try

**Comment by robbert-vdh** [comment]
Could you also try the free version of SSD5 (if you're using one of the paid versions currently) in a new prefix (so it doesn't end up loading the paid drumkits anyways)? I wouldn't be surprised if the plugin tries to index all drum kits when opening the GUI, and that if you're loading those from a slow hard drive initializing the GUI ends up taking a while.

**Comment by geekositalia** [comment]
I use the free ... then after the update (they have introduced the vst3 version), no problem with the vst3, it works perfectly and opens fast, the vst2 has the same problem

**Comment by geekositalia** [comment]
it almost looks like a specific graphics rendering issue on the vst2 and some hardware (vst3 perfect). 

I recommend you to recommend the vst3 in the tips,  at least until the cause is clear, if I can be useful for tests I am available

**Comment by robbert-vdh** [comment]
Have you tried setting up a clean prefix yet? And have you tried loading the plugin under the Windows version of REAPER running under Wine (preferably loading the same project you're using now). Both the VST2 and the VST3 version behave identically for me, so it must be some configuration issue on your side. Also make sure that you've upgraded to yabridge 3.3.0 of course.

**Comment by geekositalia** [comment]
the problem is not project related :| all is up to date, i dont try to clean prefix becausa i have over 60 plugins installed (and 200 on dedicated portable folder)..but... i try... first i try windows reaper version

**Comment by robbert-vdh** [comment]
No, don't remove your prefix, just install the plugins to a clean Wine prefix. You can use the `WINEPREFIX` environment variable to tell Wine to use that directory for the prefix instead of `~/.wine`. Just make sure that it's not set anymore when you launch your DAW (or all plugins will try to use that prefix).

**Comment by geekositalia** [comment]
reaper win version, work well with both (on my same prefix), for vst3 and vst2 version

**Comment by robbert-vdh** [comment]
I've asked this before, but did you upgrade to the latest version of yabridge yet? So, version 3.3.0, or the latest master branch version (3.3.0-6-gda5f6e9e). There must be something wrong with your setup, unless someone else can reproduce this. In that log you posted there were zero issues and everything appeared to work completely as expected.

**Comment by geekositalia** [comment]
it is not a configuration problem. So, I tried with the new prefix, the gui opens normallybut crashes if opened too many times.

I analyzed the differences, and strangely in my old prefix the dll was in vstplugins. while ssd5 installs it in vstplugin.

i had a duplicate probably old and incompatible dll version, the new one was out of yabridge and reaper path.

Only now has the vst2 version become unstable, that if you put a strain on the gui, it crashes (both clean prefix and my old one)

not a real problem, vst3 is much faster in general and very stable.

**Comment by robbert-vdh** [comment]
> it is not a configuration problem. So, I tried with the new prefix, the gui opens normallybut crashes if opened too many times.

This one I can reproduce, although I did have to open and close the GUI 20-50 times in a row to get to the black screen to appear, and it never happens on the first time when opening the editor. This is sadly either a bug on Steven Slate Drums' side or in Wine though, and only they'd be able to fix it. Yabridge closes the GUI by sending a `WM_CLOSE` message to the Window so the window will be cleaned up when running the Win32 message loop to make sure that closing editors is nice and snappy, and they seem to handle that incorrectly.

**Comment by geekositalia** [comment]
after update problem solved i close

**Comment by robbert-vdh** [comment]
Interesting! I don't think anything has changed here.
