### ISSUE TITLE
Neutron 3 becomes a zumbi

### ISSUE THREAD

**Issue by capoei** [robbert-vdh/yabridge#112]
**Problem description**
Neutron 3 becomes a zumbi
same happens to Tonal Balance control
both Izotope plugins

**System information**
 [VST2/VST3]
REAPER and Ardour
Arch
Wine version 6.4
JACK2
Installation method: yabridgectl
yabridge version: latest AUR
yabridgectl version: latest AUR

**Comment by capoei** [comment]
[yabridge.log.txt](https://github.com/robbert-vdh/yabridge/files/6677685/yabridge.log.txt)

**Comment by robbert-vdh** [comment]
These Neutron plugins used to work fine (after you installed the fonts they needed) a couple of years ago, but I haven't heard of anyone having any luck getting them to work in recent years. Did you check whether there's a WineHQ bug report for Neutron? In any case, I can't help you with this, sorry!
