### ISSUE TITLE
Supporting USB devices

### ISSUE THREAD

**Issue by mikefaille** [robbert-vdh/yabridge#113]
**Feature description**
As describe here, since Wine 6.x there is USB support from Linux USB devices https://www.phoronix.com/scan.php?page=news_item&px=Wine-Wineusb-Merged

It would be awesome if wine could expose Polybrute to the VST then I can use Polybrute Connect. 
![Screenshot from 2021-06-18 21-03-36](https://user-images.githubusercontent.com/978196/122630465-bc601b00-d078-11eb-9257-2e4ddc2281be.png)

 Polybrute Connect  works but it doesn't detect the Polybrute.
 
 Thank you for this project !

**Comment by robbert-vdh** [comment]
Wine has basic USB support now, and they also support simple kernel drivers, but USB devices that require their own drivers likely won't work with Wine just yet. This is something that would have to implemented by Wine so I can't help you with this, sorry!
