### ISSUE TITLE
yabridge-host.exe: line 36: exec: wine: not found

### ISSUE THREAD

**Issue by adabadam** [robbert-vdh/yabridge#114]
**Problem description**
Everything works as expected until the point where I load the plugin in Bitwig Studio. Error log output below.

**What did you expect to happen?**
Expected plugin to load

**What actually happened?**
Plugin does not load.

**What I have tried**
Tried different versions of winehq-staging, no luck. From what I understand yabridge-host.exe isn't able to find the $WINELOADER variable, tried creating one in .bashrc but no luck there either.

**System information**
- Plugin: Serato Sample
- Plugin type: VST2
- Host: Bitwig Studio
- Operating system: Fedora 34
- Wine version: Wine Staging 6.11
- Audio: JACK2
- Installation method: manual/yabridgectl
- yabridge version: 3.3.1
- yabridgectl version: 3.3.1

**Debug log**
<details>
<summary>Click to expand</summary>

```
om.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Communications error with plugin host process
exit code:134
stdout:
PluginHost: Reading VST 2.4 plugin metadata for /home/adam/.wine/drive_c/Program Files/Steinberg/VSTPlugins/Serato Sample.so


stderr:
14:48:13 [Serato Sample-8FMPQbpt] Initializing yabridge version 3.3.1
14:48:13 [Serato Sample-8FMPQbpt] host:          '/home/adam/.local/share/yabridge/yabridge-host.exe'
14:48:13 [Serato Sample-8FMPQbpt] plugin:        '/home/adam/.wine/drive_c/Program Files/Steinberg/VSTPlugins/Serato Sample.dll'
14:48:13 [Serato Sample-8FMPQbpt] plugin type:   'VST2'
14:48:13 [Serato Sample-8FMPQbpt] realtime:      'no'
14:48:13 [Serato Sample-8FMPQbpt] sockets:       '/run/user/1000/yabridge-Serato Sample-8FMPQbpt'
14:48:13 [Serato Sample-8FMPQbpt] wine prefix:   '/home/adam/.wine'
14:48:13 [Serato Sample-8FMPQbpt] wine version:  '<NOT FOUND>'
14:48:13 [Serato Sample-8FMPQbpt] 
14:48:13 [Serato Sample-8FMPQbpt] config from:   '<defaults>'
14:48:13 [Serato Sample-8FMPQbpt] hosting mode:  'individually, 64-bit'
14:48:13 [Serato Sample-8FMPQbpt] other options: '<none>'
14:48:13 [Serato Sample-8FMPQbpt] 
14:48:13 [Serato Sample-8FMPQbpt] Enabled features:
14:48:13 [Serato Sample-8FMPQbpt] - bitbridge support
14:48:13 [Serato Sample-8FMPQbpt] - VST3 support
14:48:13 [Serato Sample-8FMPQbpt] 
14:48:13 [Serato Sample-8FMPQbpt] [Wine STDERR] /home/adam/.local/share/yabridge/yabridge-host.exe: line 36: exec: wine: not found
14:48:13 [Serato Sample-8FMPQbpt] The Wine host process has exited unexpectedly. Check the output above for more information.
terminate called without an active exception
```

</details>

**Comment by robbert-vdh** [comment]
You don't seem to have Wine installed properly. `/usr/bin/wine` likely either doesn't exist, or it's a broken symlink. Fedora (and also Debian and its derivatives) make things a bit difficult since they allow you to install multiple versions of Wine at the same time. You'd either need to use `update-alternatives` to make sure that all of the `/usr/bin/wine*` binaries point to the correct Wine version, or presumably you can also uninstall every Wine related package and then reinstall `winehq-staging`.

**Comment by adabadam** [comment]
Okay, I removed all wine packages, removed the wine links in `update-alternatives --list`, deleted .wine prefix, rebooted and reinstalled `winehq-staging` and the plugin. Still ending up with the same error. Tried setting up my own links with `update-alternatives --install /usr/bin/wine wine /usr/bin/wine 1` and likewise for `wineserver` still nothing.

`wine --version` gives me `wine-6.11 (Staging)` so my system knows where wine is, yabridgectl cant seem to figure it out for some reason.

**Comment by robbert-vdh** [comment]
You said you tried modifying `WINELOADER` first, are you sure that's not interfering now? Can you show me the output of:

```shell
la -l /usr/bin/wine
command -v wine
/usr/bin/wine --version
echo "$WINELOADER"
env -i HOME="$HOME" $SHELL -l -c 'echo $WINELOADER'
```

**Comment by adabadam** [comment]
I removed the entry I made in .bashrc when it didn't work.

`ls -l /usr/bin/wine`
`lrwxrwxrwx. 1 root root 26 Jun 19 14:17 /usr/bin/wine -> /opt/wine-staging/bin/wine`

`command -v wine`
`/usr/bin/wine`

`/usr/bin/wine --version`
`wine-6.11 (Staging)`

`echo "$WINELOADER"`
` `

`env -i HOME="$HOME" $SHELL -l -c 'echo $WINELOADER'`
` `

Both of the last commands gave me an empty line.

**Comment by robbert-vdh** [comment]
Did you reboot after making those changes? (`~/.bashrc` shouldn't be loaded during the login shell, but some distros set up the default profile to do that anyways)

**Comment by adabadam** [comment]
Okay, I gave it one more try from a clean slate. Did the same procedure as before as well as manually deleting as many wine-related files I could find and running BleachBit. Restarted and installed `winehq-staging` again, wine works as expected except for the `$WINELOADER` variable not returning anything when echoed.

**Comment by robbert-vdh** [comment]
That's good, `$WINELOADER` is not supposed to be set!

**Comment by adabadam** [comment]
But how come yabridge-host.exe can't find the wine exec? Obviously there's something odd on my end, can't seem to figure out what.

**Comment by robbert-vdh** [comment]
Does bash still print that `line 36: exec: wine: not found` message when you run `yabridge-host.exe`? Does that also happen when you run `~/.local/share/yabridge/yabridge-host.exe` in a terminal (so just that, no `wine` in front of it or anything)? If not, are you 100% sure you asked Bitwig to rescan Serato Sample?

**Comment by adabadam** [comment]
I'm getting the same error in Bitwig, running `~/.local/share/yabridge/yabridge-host.exe` gives me

> 002c:fixme:winediag:LdrInitializeThunk wine-staging 6.11 is a testing version containing experimental patches.
> 002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
> 0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
> 0064:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
> 006c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
> 0090:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
> 002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
> 00fc:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
> 0024:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
> 0104:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
> Usage: yabridge-host.exe <plugin_type> <plugin_location> <endpoint_base_directory> <parent_pid>

Yeah, everytime I rescan the plugin in Bitwig it gives me a new ID after but the same error.

> com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Communications error with plugin host process
> exit code:134
> stdout:
> PluginHost: Reading VST 2.4 plugin metadata for /home/adam/.wine/drive_c/Program Files/Steinberg/VSTPlugins/Serato Sample.so
> 
> 
> stderr:
> 20:04:14 [Serato Sample-3AEJLTmp] Initializing yabridge version 3.3.1
> 20:04:14 [Serato Sample-3AEJLTmp] host:          '/home/adam/.local/share/yabridge/yabridge-host.exe'
> 20:04:14 [Serato Sample-3AEJLTmp] plugin:        '/home/adam/.wine/drive_c/Program Files/Steinberg/VSTPlugins/Serato Sample.dll'
> 20:04:14 [Serato Sample-3AEJLTmp] plugin type:   'VST2'
> 20:04:14 [Serato Sample-3AEJLTmp] realtime:      'no'
> 20:04:14 [Serato Sample-3AEJLTmp] sockets:       '/run/user/1000/yabridge-Serato Sample-3AEJLTmp'
> 20:04:14 [Serato Sample-3AEJLTmp] wine prefix:   '/home/adam/.wine'
> 20:04:14 [Serato Sample-3AEJLTmp] wine version:  '<NOT FOUND>'
> 20:04:14 [Serato Sample-3AEJLTmp] 
> 20:04:14 [Serato Sample-3AEJLTmp] config from:   '<defaults>'
> 20:04:14 [Serato Sample-3AEJLTmp] hosting mode:  'individually, 64-bit'
> 20:04:14 [Serato Sample-3AEJLTmp] other options: '<none>'
> 20:04:14 [Serato Sample-3AEJLTmp] 
> 20:04:14 [Serato Sample-3AEJLTmp] Enabled features:
> 20:04:14 [Serato Sample-3AEJLTmp] - bitbridge support
> 20:04:14 [Serato Sample-3AEJLTmp] - VST3 support
> 20:04:14 [Serato Sample-3AEJLTmp] 
> 20:04:14 [Serato Sample-3AEJLTmp] [Wine STDERR] /home/adam/.local/share/yabridge/yabridge-host.exe: line 36: exec: wine: not found
> 20:04:14 [Serato Sample-3AEJLTmp] The Wine host process has exited unexpectedly. Check the output above for more information.
> terminate called without an active exception

Could be that Bitwig is sandboxed?

**Comment by robbert-vdh** [comment]
So everything _should_ be working fine. That's good to know at least!

You're not accidentally using the Flatpak version of Bitwig, right?

**Comment by adabadam** [comment]
I AM

Holy shit is that the problem? Must've missed that in the readme, thanks for the help! Will try installing from Bitwigs website.

**Comment by robbert-vdh** [comment]
Yeah, a DAW running under Flatpak is not going to play well with other things running on the system, since the whole idea behind sandboxing is that it's completely isolated from the rest of your system. So any plugins would need to be installed to the same Flatpak runtime, and you won't be able to use things like JACK/JACK2 which use shared memory to communicate. Bitwig's Flatpak may try to break the sandbox a little and pass through your home directory, but any libraries, files, and other things from outside of your home directory won't be accessible within the sandbox.

**Comment by adabadam** [comment]
That was it, rescanned using the extracted deb from [https://www.bitwig.com/](url) and no errors. I will avoid Flatpak moving forward lol. Thanks again.
