### ISSUE TITLE
yabridge doesn't work after latest Arch update

### ISSUE THREAD

**Issue by kamkamkamkamkamkamkamkam** [robbert-vdh/yabridge#116]
**Problem description**
Whenever I try to load plugins, I get this error in the terminal `swell: dlopen() failed: libboost_filesystem.so.1.75.0: cannot open shared object file: No such file or directory
`
This is happening with all bridged plugins inside of all hosts. I'm still on Wine 6.0, everything worked fine until I updated the system today. I'm on version 3.3.1

**Comment by robbert-vdh** [comment]
You'll need to rebuild the yabridge AUR package and rerun `yabridgectl sync`. The Boost package updated to Boost 1.76 today, so you need to rebuild anything that uses it.

**Comment by robbert-vdh** [comment]
There are some tools to notify you of when you need to rebuild packages (like [rebuild-detector](https://github.com/maximbaz/rebuild-detector), but sadly this is just a consequence of how the AUR works.
