### ISSUE TITLE
Yabridge 3.4.0 crash Satin from uh-e windows version

### ISSUE THREAD

**Issue by geekositalia** [robbert-vdh/yabridge#120]
**Problem description**
Yabridge 3.40 crash Satin from uh-e windows versionm when you search for preset

**What did you expect to happen?**
No Crash

**What actually happened?**
Crash

**System information**
- Plugin: uh-e Satin
- Plugin type:vst (vst2 not tested)
- Host: Reaper
- Operating system: openSUSE Tumbleweed
- Wine version: Staging 6.4
- Audio: jack2
- Installation method: from repo
- yabridge version: 3.4.0
-- yabridgectl version: 3.4.0 

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/6834841/yabridge.log)

**Comment by robbert-vdh** [comment]
No issues here with the Windows version of Satin (there's also a native Linux version available that will perform better than running the Windows version through yabridge). The odd thing in your log is the spurious `Plugin wanted to drag-and-drop` messages filled with garbage. So something's causing these drag-and-drop operations to be started from Satin's process filled with. Can you figure out what's triggering this?

**Comment by robbert-vdh** [comment]
Could you try again with the latest master branch build? I still don't know why your Satin would do this, but it should work fine now after 28ab46e3c1a30201f8a4314a216577589a99908c. If you're not compiling from source (or have the repo tracked on OBS or something), then you can grab the latest yabridge and yabridgectl versions from https://github.com/robbert-vdh/yabridge/actions?query=workflow%3A%22Automated+builds%22+branch%3Amaster by logging in to GitHub, selecting the latest build (it's currently still compiling, scrolling down the page, downloading the correct yabridge versions for your system, and overwriting the existing yabridge files in `~/.local/share` with the new ones.

Don't forget to rerun `yabridgectl sync` after the upgrade!

**Comment by geekositalia** [comment]
i will try :)

**Comment by geekositalia** [comment]
i included in geekosdaw, a git version of yabridge, with automated pull, and .. solved :) and for me bbc orchestra has no problems

**Comment by robbert-vdh** [comment]
Great to hear! Still really curious why Satin was using the drag-and-drop system on your PC, but, at least it's fixed now. (I thought about adding this check when I implemented the drag-and-drop feature, but then I promptly forgot about it). I'll do a 3.4.1 with all of the regression fixes sometime this week.
