### ISSUE TITLE
Consider removing/replacing whitespaces in generated path names

### ISSUE THREAD

**Issue by ElArtista** [robbert-vdh/yabridge#121]
Currently each plugin instance gets its own folder in $XDG_RUNTIME_DIR in the format: `yabridge-<plugin-name>-randomId` as seen here:
https://github.com/robbert-vdh/yabridge/blob/ba6b87c790e8240924211cc2539faaa3e2f418cf/src/common/communication/common.cpp#L32

Please consider converting the plugin name part into something that does not contain whitespaces.
This will allow whitespace-free paths to be generated and used, and easier scripting around yabridge paths, e.g. when passing them to some sandboxing application through bash scripts.

**Comment by robbert-vdh** [comment]
I don't think this is needed. Staying true to the original binary name sounds like a better idea to me. Or at least, I consider fewer surprises and less magic going on to be a good thing (arguably replacing characters isn't really magic, but still).

In Bash/Bourne shell scripts you should _always_ quote variables, unless you _want_ them to be split on `$IFS`. So spaces shouldn't cause any issues there. If you need some help with shell script best practices, I recommend setting up [shellcheck](https://github.com/koalaman/shellcheck) for your text editor. That catches a lot of common mistakes if you're not already familiar with them.

**Comment by ElArtista** [comment]
Well in my case I was trying to gather all the plugin yabridge paths, but due to the whitespaces in the plugin name it cannot be done in a single line and it has to be done like this:
```
arr=(); for d in $XDG_RUNTIME_DIR/yabridge-*/; do arr+=("--bind" "$d" "$d"); done
```
and later use it like this:
```
...
    --ro-bind $XDG_RUNTIME_DIR/pipewire-0 $XDG_RUNTIME_DIR/pipewire-0 \
    "${arr[@]}" \
    --dev-bind /dev/shm /dev/shm \
...
```

**Comment by robbert-vdh** [comment]
You're also missing quotes there around `$XDG_RUNTIME_DIR`. :wink: 

But yeah, I don't see how this is a yabridge issue. Bash splits on `$IFS` by default, that's a feature. If you want Bash to use a different field separator, then set `$IFS` to something else.

**Comment by ElArtista** [comment]
Yep I suppose you are right, the proposed feature could be convenient for scripting but for now its out of yabridge's scope.
Closing for now, but in general trying to avoid paths with whitespaces is a good idea in general! Thanks for your help and this awesome adapter!
