### ISSUE TITLE
git another issue - valhalla

### ISSUE THREAD

**Issue by geekositalia** [robbert-vdh/yabridge#122]
**Problem description**
Stuck on plugin scan

**What did you expect to happen?**
Scan

**What actually happened?**
stuck and crash

**System information**
- Plugin: valhalla (freqecho and massive)
- Plugin type: vst3
- Host: Reaper
- Operating system: openSUSE Tumbleweed
- Wine version: staging 6.4
- Audio: nd
- Installation method: git build
- yabridge version: latest git
- yabridgectl version: latest git

VST3 no on valhalla but on subdirectories

**Debug log**
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] Initializing yabridge version 3.4.0.20210718.git0e57f410
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] host:          '/usr/bin/yabridge-host.exe'
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] plugin:        '/home/jo/Musica/DAW/VST/WIN/Valhalla'
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] plugin type:   'VST3'
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] realtime:      'yes'
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] sockets:       '/run/user/1001/yabridge-ValhallaFreqEcho_vst3-ABCMQWdt'
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] wine prefix:   '<default>'
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] wine version:  '6.4 (Staging)'
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] 
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] config from:   '<defaults>'
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] hosting mode:  'individually, 64-bit'
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] other options: '<none>'
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] 
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] Enabled features:
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] - bitbridge support
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] - VST3 support
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] 
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] [Wine STDERR] 0620:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] [Wine STDERR] 0620:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] [Wine STDERR] 0620:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] [Wine STDERR] 0620:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] [Wine STDERR] 0620:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] [Wine STDERR] 0620:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] [Wine STDERR] 0620:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] [Wine STDERR] 0620:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] [Wine STDERR] 0620:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] [Wine STDERR] 0620:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] [Wine STDERR] 0620:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] [Wine STDERR] 0620:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] [Wine STDERR] Initializing yabridge host version 3.4.0.20210718.git0e57f410
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] [Wine STDERR] Preparing to load VST3 plugin at '/home/jo/Musica/DAW/VST/WIN/Valhalla'
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] [Wine STDERR] Error while initializing the Wine plugin host:
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] [Wine STDERR] Could not load the VST3 module for '/home/jo/Musica/DAW/VST/WIN/Valhalla': LoadLibray failed: Modulo non trovato.
01:12:07 [ValhallaFreqEcho_vst3-ABCMQWdt] [Wine STDERR]

**Comment by robbert-vdh** [comment]
Like it says, it cannot load the module. Something went wrong with how you installed the plugin, because `/home/jo/Musica/DAW/VST/WIN/Valhalla` does not sound like a valid Windows VST3 plugin library path. I urge you to keep plugins installed in their default locations, inside of the Wine prefix they're associated with. For VST3 plugins the installation location is not configurable for a reason, because the [VST3 specification](https://developer.steinberg.help/display/VST/Plug-in+Locations#PluginLocations-FortheWindowsplatform) only allows them to be installed in a single location. The installation location for VST2 plugins isn't dictated by a spec, but `~/.wine/drive_c/Program\ Files/Steinberg/VstPlugins` is the most common location and the one I'd recommend sticking with.

**Comment by geekositalia** [comment]
Older version have not problem, and all other bridges, only latest version but... on .vst3 the link is correct on the path on the subfolders. this plugins is dll and vst only standalone without problem first of update... i will try put plugins without subfolders... but other plugins dont have problems with subfolders... the folder i use is portable vst plugins

**Comment by robbert-vdh** [comment]
Like it says in the error, Wine cannot load the module. There's nothing I can do about that to change it. `/home/jo/Musica/DAW/VST/WIN/Valhalla` is not a valid Windows VST3 module name. Those should end with `.vst3`. Steinberg's VST3 loading mechanism won't accept this. You can find the source code for that in the VST3 SDK [here](https://github.com/steinbergmedia/vst3_public_sdk/blob/master/source/vst/hosting/module_win32.cpp).

**Comment by geekositalia** [comment]
plugin is not in that folder.. but, inside Valhalla (brand folder), another 2 sub folder is present, for 2 different plugin (is a organized subfolder structure), and insiede this 2 subfolder, is present corretc .vst3 plugins, and dll for vst2 (vst2 have no problema)... but.. .vst3 folder is correctly created on home/.vst3, with correct LINKING to correct .vst3 folder for plugin (example, Valhalla/supermassive/supermassive.vst3...but on load and scan fail.. i dont know why yabrdige try to load up container brand folder as vst plugin (Preparing to load VST3 plugin at '/home/jo/Musica/DAW/VST/WIN/Valhalla'), plugin is inside Valhalla folder.

it is a similarity error, as if yabridge attempted to load a vst3 plugin as "program files", ignoring that the plugin is inside subdirectories

**Comment by geekositalia** [comment]
![Screenshot_20210720_162155](https://user-images.githubusercontent.com/55261197/126340819-f6059204-d7ac-44d3-a02c-a56993e515b3.png)
As screenshot, correct vst3 name of .vst3 insiede Valhalla folder, is correct.. but stuck (only yabridge 3.4, not the 3.3), with incorrect assign? folder for vst3 (upfolder valhalla) instead of the .vst3 subfolder. this does not happen with .vst2

**Comment by robbert-vdh** [comment]
That sounds like you have an invalid VST3 bundle. You are **not** allowed to have a directory end in .vst3 if it's not a valid VST3 bundle, that goes against the VST3 specification. This is how VST3 bundles should be structured:

https://developer.steinberg.help/display/VST/Plug-in+Format+Structure

If the plugin's .vst3 file is actually located at `$HOME/Musica/DAW/VST/WIN/Valhalla/ValhallaSupermassive.vst3/ValhallaSupermassive.vst3`, then you should move the .vst3 file out of that directory and get rid of the directory. The VST3 specification does not allow this.

**Comment by geekositalia** [comment]
strange.. the path was: home/jo/Musica/DAW/VST/WIN/Valhalla/ValhallaSupermassive/vst3/sumpermassive_vst3.vst3 and changing this to home/jo/Musica/DAW/VST/WIN/Valhalla/ValhallaSupermassive/supermassive.vst3... works.. other plugin  have the same structure and work fine, and old path for this plugin work fine with yabrdige 3.3 (wine prefix is ininlfuent for me with these plugins specifically)... i dont know other my plugins (300 and more), with similar portable structure, dont have this problem

**Comment by geekositalia** [comment]
i close
