### ISSUE TITLE
FabFilter plugins rendering a black window

### ISSUE THREAD

**Issue by sentriz** [robbert-vdh/yabridge#129]
**Problem description**
Hi! For me the FabFilter plugins are rendering a black GUI screen with Renoise 

**What did you expect to happen?**
For example with Pro-Q 3, seeing the eq GUI
...

**What actually happened?**
Rendering a black 900x540 window
...

**System information**
- Plugin: FabFilter Pro-Q 3 (or it seems any FabFilter product)
- Plugin type: 64bit VST2 (see PS.)
- Host: Renoise
- Operating system: Arch
- Wine version: wine-6.14 (Staging)
- Audio: PipeWire JACK
- Installation method: copies, yabridgectl
- yabridge version: 3.5.2 (yabridge-bin AUR)
- yabridgectl version: 3.5.2 (yabridge-bin AUR)

**Debug log**
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/7010501/yabridge.log)

https://user-images.githubusercontent.com/6832539/129980053-82d43f58-1ef9-4c50-a935-203f162fddf8.mp4

any help much appreciated, thanks!

PS. only found this out while making this issue: when scanning for VST3s with Renoise created by yabridge it says so I've only been using VST2 so far 

```
Renoise LOG> Vst3Plugs: Instantiating: /home/senan/.local/share/wine/drive_c/Program Files/Common Files/vst3/FabFilter/FabFilter Pro-Q 3.vst3...
Renoise LOG> Vst3Plugs: Failed to load module: dlopen failed.
/home/senan/.local/share/wine/drive_c/Program Files/Common Files/vst3/FabFilter/FabFilter Pro-Q 3.vst3: invalid ELF header
```

**Comment by robbert-vdh** [comment]
Are your OpenGL drivers working correctly? By default (i.e., without changing some registry values) FabFitler plugins render using OpenGL.

> PS. only found this out while making this issue: when scanning for VST3s with Renoise created by yabridge it says so I've only been using VST2 so far

You added `~/.local/share/wine/drive_c/Program Files/Common Files/vst3` to Renoise's plugin search path, so it tries to `dlopen()` that .vst3 file (which is a Windows PE32+ library, not a Linux ELF binary), so you need to make sure Renoise doesn't try scanning for plugins there.

**Comment by sentriz** [comment]
ah! yes, I see yabridge puts the ELFs in ~/.vst3, not in original folder the windows library was in (?)

updated my VST3_PATH to include ~/.vst3/yabridge, now Renoise picks up VST3s and FabFilter also happens to be working now :+1:  thanks!

P.S. is it possible to ask yabridge to not put them in ~/.vst3 but instead elsewhere? I like to keep my home directory mostly empty and put stuff in XDG dirs

**Comment by sentriz** [comment]
ah! yes, I see yabridge puts the ELFs in ~/.vst3, not in original folder the windows library was in (?)

updated my VST3_PATH to include ~/.vst3/yabridge, now Renoise picks up VST3s and FabFilter also happens to be working now :+1:  thanks!

P.S. is it possible to ask yabridge to not put them in ~/.vst3 but instead elsewhere? I like to keep my home directory mostly empty and put stuff in XDG dirs

**Comment by robbert-vdh** [comment]
`~/.vst3/yabridge` is hardcoded, so no, you can't change that. The VST3 specification [does not allow it](https://developer.steinberg.help/display/VST/Plug-in+Locations#PluginLocations-ForLinuxplatform). Having any VST3 plugins installed outside of `/usr/lib/vst3`, `/usr/local/lib/vst3`, `~/.vst3`, and some per-application directory goes against the VST3 specification, and I'd rather not break an entire plugin spec.
