### ISSUE TITLE
Ubuntu, VST2 not loading in Bitwig

### ISSUE THREAD

**Issue by Polyrhythm** [robbert-vdh/yabridge#130]
**Problem description**
Bitwig fails to load a VST plugin synced by yabridge.

**System information**
- Plugin: PrismAudio Atmos Piano/Atmos Piano.dll/
   :: VST2, 64-bit, not yet installed
- Host: Bitwig Studio
- Operating system: Ubuntu 20.04
- Wine version: 6.4 staging
- Audio: JACK
- Installation method: yabridgectl
- yabridge version: [
- yabridgectl version: 3.5.2

**Debug log**
```
/home/ryan/development/music/PrismAudio Atmos Piano/Atmos Piano.so

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Communications error with plugin host process
exit code:134
stdout:
PluginHost: Reading VST 2.4 plugin metadata for /home/ryan/development/music/PrismAudio Atmos Piano/Atmos Piano.so


stderr:

20:19:46 [Atmos Piano-1ABGJLmu] config from:   '<defaults>'
20:19:46 [Atmos Piano-1ABGJLmu] hosting mode:  'individually, 64-bit'
20:19:46 [Atmos Piano-1ABGJLmu] other options: '<none>'
20:19:46 [Atmos Piano-1ABGJLmu] 
20:19:46 [Atmos Piano-1ABGJLmu] Enabled features:
20:19:46 [Atmos Piano-1ABGJLmu] - bitbridge support
20:19:46 [Atmos Piano-1ABGJLmu] - VST3 support
20:19:46 [Atmos Piano-1ABGJLmu] 
20:19:47 [Atmos Piano-1ABGJLmu] [Wine STDERR] 002c:fixme:winediag:LdrInitializeThunk wine-staging 6.4 is a testing version containing experimental patches.
20:19:47 [Atmos Piano-1ABGJLmu] [Wine STDERR] 002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
20:19:47 [Atmos Piano-1ABGJLmu] [Wine STDERR] 002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
20:19:47 [Atmos Piano-1ABGJLmu] [Wine STDERR] 002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
20:19:47 [Atmos Piano-1ABGJLmu] [Wine STDERR] 0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
20:19:47 [Atmos Piano-1ABGJLmu] [Wine STDERR] 0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
20:19:47 [Atmos Piano-1ABGJLmu] [Wine STDERR] 005c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
20:19:47 [Atmos Piano-1ABGJLmu] [Wine STDERR] 005c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
20:19:47 [Atmos Piano-1ABGJLmu] [Wine STDERR] 006c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
20:19:47 [Atmos Piano-1ABGJLmu] [Wine STDERR] 006c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
20:19:47 [Atmos Piano-1ABGJLmu] [Wine STDERR] 0024:err:process:exec_process failed to load L"Z:\\home\\ryan\\.local\\share\\yabridge\\yabridge-host.exe.so" error c000035a
20:19:47 [Atmos Piano-1ABGJLmu] The Wine host process has exited unexpectedly. Check the output above for more information.
terminate called without an active exception


-------------------------------------------------------------------

```

Note that even using YABRIDGE_DEBUG_FILE to launch bitwig doesn't result in a log file from yabridge.

Running yabridge-host manually seems to work:

```
~/.local/share/yabridge/yabridge-host.exe
002c:fixme:winediag:LdrInitializeThunk wine-staging 6.4 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0050:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0050:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0070:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0070:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00f8:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00f8:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0100:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0100:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
Usage: yabridge-host.exe <plugin_type> <plugin_location> <endpoint_base_directory> <parent_pid>

```

**Comment by robbert-vdh** [comment]
Wine cannot load `yabridge-host.exe.so` because it's a 64-bit binary and your Wine prefix was created with `WINEARCH=win32`. Error `c000035a` from Wine's loader is for `STATUS_INVALID_IMAGE_WIN_64`, which means you're trying to use a 64-bit binary in a 32-bit Wine prefix. The path to the Wine prefix in use is cut off in your log file (you'd need to launch Bitwig from the command line with `env=YABRIDGE_DEBUG_FILE=/tmp/yabridge.log bitwig-studio` to obtain the full log), but you need to make sure that that prefix was not created with `WINEARCH=win32` set. If in doubt, just rename that prefix to something else and Wine will recreate it for you.

**Comment by Polyrhythm** [comment]
Thank you for the prompt reply.

```
$ echo $WINEARCH
win64

$ echo $WINEPREFIX
/home/ryan/.wine64
```
I am familiar with how to use the `YABRIDGE_DEBUG_FILE` argument but using it in this way (`env=YABRIDGE_DEBUG_FILE=/tmp/yabridge.log bitwig-studio`) still results in no log file being generated.

I also tried once again to make sure I had nothing misconfigured by using `wineserver -k` and doing the dance again. Same error coming from Bitwig. If you have any other ideas for tests I can do, I'd be very appreciative. Thanks!

**Comment by robbert-vdh** [comment]
Sorry, I made a typo. That first `=` should not have been there. It should have been `env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log bitwig-studio`. If you do that, you'll find the full output (including the Wine prefix in use) at `/tmp/yabridge.log`. I don't know where you're setting `$WINEARCH` and `$WINEPREFIX`, but you should get rid of that. That's going to break a lot of things.

**Comment by Polyrhythm** [comment]
Thanks, getting rid of the `$WINEARCH` and `$WINEPREFIX` defines seems to have cleared up the error loading the VST plugin. 

Bitwig still doesn't seem to see the plugin despite there being no errors reported (and no log generated from yabridge) but perhaps it's a configuration or plugin-specific issue. Do you want me to make a separate issue for this problem if I can't resolve it?

![Screenshot from 2021-08-22 21-31-12](https://user-images.githubusercontent.com/1242927/130355268-34f5adb5-42f4-4c2f-a34e-0efd79ea6502.png)

**Comment by robbert-vdh** [comment]
Go to the settings, plug-ins, show plug-in errors, and rescan the plugins that failed to scan last time.

**Comment by Polyrhythm** [comment]
![Screenshot from 2021-08-22 21-36-19](https://user-images.githubusercontent.com/1242927/130355422-32577df1-268d-4b11-9e70-9d9cf35ee7e9.png)


Yep, did that...

**Comment by robbert-vdh** [comment]
Are you using the Flatpak version of Bitwig? If so, then that's the issue. If not, just restart Bitwig. I think in some older versions plugins didn't show up immediately in the browser if the plugin failed to scan the first time, and if you opened the browser before the plugin has been rescanned (don't think that happens anymore in 4.0.1).

**Comment by Polyrhythm** [comment]
I think I might know the problem. Not using the flatpak version or anything like that.
Since getting rid of the `$WINEARCH` and `$WINEPREFIX` env variables, I can no longer run yabridge.

```
$ ~/.local/share/yabridge/yabridge-host.exe
wine: invalid directory  in WINEPREFIX: not an absolute path
```

If I define `WINEPREFIX`, it then complains about not having `WINEARCH` defined too. So should I have them defined or not in my `~/.profile`?

**Comment by robbert-vdh** [comment]
No, those two should never be defined as a default. If you want to use a specific prefix for a single Wine command, then you should just define WINEPREFIX for that command or for the shell session only when you need it.
