### ISSUE TITLE
Arturia DX7 V crashes when clicking knobs or sliders

### ISSUE THREAD

**Issue by sadata7** [robbert-vdh/yabridge#131]
Arturia's DX7 V works perfectly (keys, sound, presets, etc.) EXCEPT if you click on any of the slider or knob controls, at which point it crashes. I'm using yabridge 3.5.2 under Wine 6.0.1 on Linux Mint 20.1 Cinnamon (5.8.0-63-generic).  BTW, absolutely LOVE yabridge. I was never able to get carla working properly, so this is a godsend.  Thanks for your efforts.

Details and free demo version here: https://www.arturia.com/dx7-v/overview
...

**System information**
- Plugin: Aturia DX7 V (demo version: https://www.arturia.com/component/com_myarturia/id,194/view,demo/)
- Plugin type: not sure
- Host: Bitwig Studio
- Operating system: Linux Mint 20.1 Cinnamon
- Wine version: Wine 6.0.1
- Audio: pulseaudio
- Installation method: manual/yabridgectl
- yabridge version: 3.5.2 (?)
- yabridgectl version: 3.5.2

**Crash log**

couldn't load main module (0)
Unhandled exception: page fault on execute access to 0x00000000 in 64-bit code (0x0000000000000000).
Register dump:
 rip:0000000000000000 rsp:000000000021cbd8 rbp:000000000021cce0 eflags:00010246 (  R- --  I  Z- -P- )
 rax:0000000000020085 rbx:000000000a9ca480 rcx:00000000000100de rdx:0000000000000000
 rsi:0000000000000000 rdi:0000000000000000  r8:000000000021cc78  r9:000000000021cc70 r10:000000000000043f
 r11:0000000000000000 r12:0000000000000000 r13:00000000000000ff r14:00000000000100de r15:0000000000210080
Stack dump:
0x000000000021cbd8:  000000018099d7b8 00000000025b37d0
0x000000000021cbe8:  00000000025b37d0 00000000025b37d0
0x000000000021cbf8:  00000000025b37d0 0000000000020085
0x000000000021cc08:  000000000021cc60 0000000000000000
0x000000000021cc18:  000000000021cc54 0000000000000002
0x000000000021cc28:  00007fee73b6ad7c 00000000000f0190
0x000000000021cc38:  4919e6b3ed3e5700 0000000000000002
0x000000000021cc48:  00007fee75d15192 01ff000000000000
0x000000000021cc58:  4919e6b300000000 0000000000000000
0x000000000021cc68:  00000000025b37d0 000000150000003c
0x000000000021cc78:  0000043f000003af 000000007d6ac168
0x000000000021cc88:  0000000000000000 000000150000003c
Backtrace:
=>0 0x0000000000000000 (0x000000000021cce0)
0x0000000000000000: -- no code accessible --
Modules:
Module	Address					Debug info	Name (60 modules)
PE	          220000-          45b000	Deferred        setupapi
PE	          a90000-          d2f000	Deferred        comdlg32
PE	          d30000-         1282000	Deferred        comctl32
PE	         13a0000-         154e000	Deferred        winmm
PE	         1550000-         155f000	Deferred        api-ms-win-crt-heap-l1-1-0
PE	         1560000-         156e000	Deferred        api-ms-win-crt-time-l1-1-0
PE	         1570000-         157f000	Deferred        api-ms-win-crt-utility-l1-1-0
PE	         18b0000-         1a2a000	Deferred        wbemprox
PE	         1d80000-         1e2f000	Deferred        sqlite
PE	         5f50000-         6003000	Deferred        dx7processor
PE	        61540000-        61663000	Deferred        advapi32
PE	        61d00000-        61d10000	Deferred        api-ms-win-crt-convert-l1-1-0
PE	        61d80000-        61d91000	Deferred        api-ms-win-crt-math-l1-1-0
PE	        62100000-        6218d000	Deferred        msvcp140
PE	        62980000-        6298f000	Deferred        api-ms-win-core-localization-l1-2-1
PE	        62b40000-        62b4e000	Deferred        api-ms-win-crt-environment-l1-1-0
PE	        62dc0000-        6306b000	Deferred        rpcrt4
PE	        63280000-        632a0000	Deferred        version
PE	        63400000-        634e3000	Deferred        sapi
PE	        63540000-        63550000	Deferred        api-ms-win-crt-runtime-l1-1-0
PE	        639c0000-        63a11000	Deferred        shcore
PE	        64840000-        6498e000	Deferred        shlwapi
PE	        64cc0000-        651cd000	Deferred        oleaut32
PE	        659c0000-        659df000	Deferred        midimap
PE	        65b40000-        65b4f000	Deferred        api-ms-win-crt-filesystem-l1-1-0
PE	        66040000-        6608d000	Deferred        bcrypt
PE	        67140000-        6722f000	Deferred        msvcr120
PE	        67b40000-        67bd9000	Deferred        mmdevapi
PE	        68300000-        68490000	Deferred        combase
PE	        684c0000-        6850e000	Deferred        concrt140
PE	        684c0000-        6850e000	Deferred        uxtheme
PE	        69200000-        6920c000	Deferred        vcruntime140_1
PE	        69e40000-        69eb8000	Deferred        msacm32
PE	        6a200000-        6a7b8000	Deferred        ole32
PE	        6aa80000-        6aa8e000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	        6b5c0000-        6b5d0000	Deferred        api-ms-win-crt-stdio-l1-1-0
PE	        6ba00000-        6bac9000	Deferred        sechost
PE	        6c7c0000-        6ce96000	Deferred        gdi32
PE	        6dc80000-        6dc8f000	Deferred        api-ms-win-core-synch-l1-2-0
PE	        6e6c0000-        6ea19000	Deferred        crypt32
PE	        6eb00000-        6f2aa000	Deferred        user32
PE	        6fd00000-        6fd10000	Deferred        api-ms-win-crt-string-l1-1-0
PE	        6fe40000-        6fe6c000	Deferred        msacm32
PE	        70040000-        7005b000	Deferred        vcruntime140
PE	        70940000-        70ca7000	Deferred        ucrtbase
PE	        71000000-        71058000	Deferred        imm32
PE	        7a850000-        7a854000	Deferred        opengl32
PE	        7b000000-        7b3d2000	Deferred        kernelbase
PE	        7b600000-        7b96c000	Deferred        kernel32
PE	        7bc00000-        7bf88000	Deferred        ntdll
PE	       180000000-       1811e1000	Deferred        dx7 v
PE	    7fee726b0000-    7fee726b3000	Deferred        winealsa
PE	    7fee72ba0000-    7fee72ba4000	Deferred        wined3d
PE	    7fee72de0000-    7fee72de3000	Deferred        winepulse
PE	    7fee72e20000-    7fee72e24000	Deferred        iphlpapi
PE	    7fee72e50000-    7fee72e54000	Deferred        dxgi
PE	    7fee73980000-    7fee7398b000	Deferred        winspool
PE	    7fee739d0000-    7fee739d4000	Deferred        ws2_32
PE	    7fee73f40000-    7fee73f44000	Deferred        winex11
PE	    7fee74330000-    7fee74c07000	Deferred        shell32
Threads:
process  tid      prio (all id:s are in hex)
00000038 services.exe
	0000003c    0
	00000040    0
	0000004c    0
	00000070    0
	00000088    0
	000000b0    0
	000000d8    0
00000044 winedevice.exe
	00000048    0
	00000054    0
	00000058    0
	0000005c    0
00000060 plugplay.exe
	00000064    0
	00000074    0
	00000078    0
	0000007c    0
	00000098    0
00000080 winedevice.exe
	00000084    0
	0000008c    0
	00000090    0
	00000094    0
	000000a0    0
	000000a4    0
000000a8 svchost.exe
	000000ac    0
	000000b4    0
	000000b8    0
000000d0 rpcss.exe
	000000d4    0
	000000e0    0
	000000e4    0
	000000e8    0
	000000ec    0
	00000320    0
00000310 explorer.exe
	00000314    0
	00000318    0
	0000031c    0
0000035c ArturiaSoftwareCenterAgent.exe
	00000360    0
	0000036c    0
	00000370    0
	00000374    1
00000364 conhost.exe
	00000368    0
000003a0 yabridge-host.exe
	000003a4    0
	000003a8    0
	000003ac    0
	000003b4    0
	000003bc    0
	000003c0    0
	000003c4    0
	000003c8    0
	000003cc    0
	000003d0    0
	000003d4    1
	00000514    0
	00000518    0
	00000524    0
0000051c winedbg.exe
	00000520    0
	00000528    0
00000700 (D) Z:\home\sadata\.local\share\yabridge\yabridge-host.exe
	00000704    0 <==
	00000708    0
	0000070c    0
	00000714    0
	0000071c    0
	00000720    0
	00000724    0
	00000728    0
	0000072c    0
	00000730    0
	00000734    1
	0000016c    0
	00000170    0
	0000017c    0
System information:
    Wine build: wine-6.0.1
    Platform: x86_64
    Version: Windows 7
    Host system: Linux
    Host version: 5.8.0-63-generic

**Comment by robbert-vdh** [comment]
Some JUCE plugins do this when displaying tooltips when they detect that you're using Wine. See the [known issues](https://github.com/robbert-vdh/yabridge#known-issues-and-fixes) section in the readme. You'll need Wine Staging 6.14 (or another version that's not 6.15 since the latest version broke yabridge) and you should then just enable the 'Hide Wine version from applications' checkbox in winecfg's Staging tab. See [here](https://github.com/robbert-vdh/yabridge#downgrading-wine) for instructions on how to install an older version of Wine Staging. Just change the version to whatever version you want to install and make sure to remove winehq-stable first.

**Comment by sadata7** [comment]
Thanks Robert. That worked great. At first I tried 6.16 (you did say, "not 6.15"), but yabridge still seems to be broken. I downgraded to 6.14, checked the option to not report the WINE version, and everything works well. Thanks again!
