### ISSUE TITLE
A VST2 plugin that was working recently, now does not show its custom GUI

### ISSUE THREAD

**Issue by rbejar** [robbert-vdh/yabridge#134]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections my issue wasn't listed there

### Problem description

Monster Drum V2 (VST2, Win64), does not show its custom GUI (using Reaper as host).

### What did you expect to happen?

Monster Drum V2 should show its custom GUI.

### What actually happened?

When I try to open the custom GUI nothing shows up. Reaper gets frozen and I have to kill the process.

### Operating system

Kubuntu 20.04

### How did you install yabridge?

Directly from the releases page.

### yabridge version

3.5.2

### yabridgectl version

3.5.2

### Wine version

wine-6.14 (Staging)

### Plugin installation method

copies

### Plugin

Monster Drum V2 <https://monsterdaw.com/monster-drum-the-best-free-drum-vst-plugin-with-multi-kit-genre/>

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Reaper 6.35

### Desktop environment or WM

KDE Plasma

### GPU model

Intel(R) Iris(R) Pro Graphics 580 

### GPU drivers and kernel

Mesa 21.2.1 - kisak-mesa PPA

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/7086084/yabridge.log)

### Anything else?

I have tried also with Reaper 6.33, with yabridge 3.5.0 and with wine 6.4 (and 6.13) without seeing any difference. This was working a few weeks ago, and it is still working in a different computer with a similar setup (Kubuntu 20.04, Reaper 6.35, yabridge 3.5.0, wine 6.14).
The plugin works. If I load a project with this plugin loaded into a track, the track sounds properly. The problem is showing its GUI.
I seem to have the same problem if I try to load the plugin into Carla: it loads, but I can't see its GUI.

**Comment by robbert-vdh** [comment]
There's nothing in that log that would point to anything, and the plugin also works fine here both with my usual Wine prefix and in a clean prefix. I'd try:

- Using a clean Wine prefix. The quickest way to test this would be to just temporarily rename `~/.wine` to `~/.wine2` or something. If that works and you want to keep the rest of your default Wine prefix in tact, then you can just install this plugin to its own Wine prefix and yabridge will then use that prefix for the plugin (see [Wine prefixes](https://github.com/robbert-vdh/yabridge#wine-prefixes)).
- Check your GPU drivers. The crash happens just after `00fc:fixme:dxgi:DXGID3D10CreateDevice Ignoring flags 0x20.`. In other words, just after the plugin tries to initialize Direct3D 10. That may very well have something to do with it.

**Comment by rbejar** [comment]
Using a clean Wine prefix solved the issue. I may need to check what I had installed in that prefix, because the problem was happening with other VSTs too (e.g., sforzando) so I suppose that there is something installed there that created the problem, and maybe is that something what should be moved to a different prefix (or removed for good).

Thanks for your help, and for the great work you do with yabridge.
