### ISSUE TITLE
Yabridge fails to compile with clang++ winegcc

### ISSUE THREAD

**Issue by Nanotwerp** [robbert-vdh/yabridge#138]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

This same compilation error has happened before with wine-related programs, and has been recorded in https://github.com/doitsujin/dxvk/issues/1182 and other issues that mention it. The issues contain various patches and workarounds.

> FAILED: src/wine-host/libhost_common_64bit.a.p/.._common_utils.cpp.o 
> wineg++ -Isrc/wine-host/libhost_common_64bit.a.p -Isrc/wine-host -I../src/wine-host -I../src/include -Isrc/common/config -I../src/common/config -I../subprojects/bitsery-5.2.0/include -I../subprojects/function2-4.1.0/include -I../subprojects/tomlplusplus/include -I/usr/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++2a -O3 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -msse2 -DRELEASE=1 -m64 -DBOOST_FILESYSTEM_DYN_LINK=1 -DBOOST_ALL_NO_LIB -isystem../subprojects/vst3 -isystemsubprojects/vst3 -fvisibility=hidden -fvisibility-inlines-hidden -DBOOST_ASIO_DISABLE_CONCEPTS -DBOOST_POSIX_HAS_VFORK=1 -msse2 -DWITH_BITBRIDGE -DWITH_VST3 -DNOMINMAX -D__WINE_WINSOCKAPI_STDLIB_H -D_WINSOCKAPI_ -D__IFileOperation_INTERFACE_DEFINED__ -m64 -MD -MQ src/wine-host/libhost_common_64bit.a.p/.._common_utils.cpp.o -MF src/wine-host/libhost_common_64bit.a.p/.._common_utils.cpp.o.d -o src/wine-host/libhost_common_64bit.a.p/.._common_utils.cpp.o -c ../src/common/utils.cpp
> In file included from ../src/common/utils.cpp:20:
> In file included from /usr/lib/clang/12.0.1/include/xmmintrin.h:27:
> /usr/lib/clang/12.0.1/include/mm_malloc.h:45:22: error: use of undeclared identifier '_aligned_malloc'; did you mean 'aligned_alloc'?
>   __mallocedMemory = _aligned_malloc(__size, __align);
>                      ^
> /usr/include/stdlib.h:586:14: note: 'aligned_alloc' declared here
> extern void *aligned_alloc (size_t __alignment, size_t __size)
>              ^
> In file included from ../src/common/utils.cpp:20:
> In file included from /usr/lib/clang/12.0.1/include/xmmintrin.h:27:
> /usr/lib/clang/12.0.1/include/mm_malloc.h:60:3: error: use of undeclared identifier '_aligned_free'
>   _aligned_free(__p);
>   ^
> 2 errors generated.
> winegcc: /usr/bin/clang++ failed

### What did you expect to happen?

Successful compilation

### What actually happened?

Unsuccessful compilation

### Operating system

Arch Linux

### How did you install yabridge?

directly from the releases page

### yabridge version

commit ed6a429

### yabridgectl version

commit ed6a429

### Wine version

wine-tkg 6.18

### Plugin installation method

copies

### Plugin

N/A

### Plugin type

both VST2 and VST3

### Plugin architecture

both 64-bit and 32-bit

### Host

N/A

**Comment by robbert-vdh** [comment]
This sounds like either an issue with Clang itself (this particular compiler error is coming from Clang's headers calling `_aligned_free()` without including something that defines it), or with Clang-based winegcc (is that even an officially supported config?), and not something related to yabridge. If the issue is with Clang itself, then you'll need to open a ticket with them, and if it's somehow an interaction caused by clang-based winegcc when you'll need to open a ticket on Wine's bug tracker.
