### ISSUE TITLE
weird incremental ram bug

### ISSUE THREAD

**Issue by ghost** [robbert-vdh/yabridge#140]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

everytime i open the vst the ram increments and theres no something like a garbage collector, my pc runn out of ram one time by this

### What did you expect to happen?

no crazy ran incrementation at opening the vst twice 

### What actually happened?

https://user-images.githubusercontent.com/24663715/138441249-d1873dfa-6efe-479d-8c8a-8aa527b004ce.mp4

### Operating system

XeroLinux

### How did you install yabridge?

aur/yabridge-bin

### yabridge version

3.6.0-1

### yabridgectl version

i think its included in yabridge

### Wine version

aur/wine-ge-custom 6.19.GE.1-2

### Plugin installation method

copies

### Plugin

LoudMax 64bit

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Bitwig Studio 4.0.1

### Desktop environment or WM

Plasma 5.23.1

**Comment by robbert-vdh** [comment]
Closing this since this is not a yabridge issue and the OP has deleted their GitHub account.
