### ISSUE TITLE
Page fault with MSoundFactory in Reaper

### ISSUE THREAD

**Issue by JonathanTroyer** [robbert-vdh/yabridge#144]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

When using MPowerSynth in Reaper, I get a page fault:
[wine.log](https://github.com/robbert-vdh/yabridge/files/7470892/wine.log)

It only happens when audio is playing and the GUI is open.

### What did you expect to happen?

The plugin to work correctly.

### What actually happened?

Reaper freezes until I force quit.

### Operating system

Fedora 34

### How did you install yabridge?

COPR

### yabridge version

3.6.0

### yabridgectl version

3.6.0

### Wine version

wine-6.18 (Staging)

### Plugin installation method

copies

### Plugin

MSoundFactory

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Reaper v6.38

### Desktop environment or WM

Gnome 40.4, X11

### GPU model

NVIDIA Corporation TU106M [GeForce RTX 2060 Max-Q]

### GPU drivers and kernel

NVIDIA 470.74 on Linux 5.14.15

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/7470888/yabridge.log)

### Anything else?

I haven't yet experienced this issue with any other Melda plugins.
(also golly, that's the nicest bug report template I've ever come across)

**Comment by robbert-vdh** [comment]
I haven't been able to get that plugin to have memory corruption issues myself (with various wine-tkg versions), but I've heard about others having the same problem you're having. Some things you can try are:

1. Try it with [wine-tkg](https://github.com/Frogging-Family/wine-tkg-git) (and just follow the instructions to build from source, don't try the prebuilt versions as those include fshack which breaks other things). Not sure how this would work on non-Arch based distros though.
2. If that doesn't work, try it in both a clean prefix and an otherwise clean prefix with only the `vcrun2019` override from winetricks installed.

**Comment by JonathanTroyer** [comment]
1. Built wine-tkg from source, crashes even if GUI is not open: [yabridge.log](https://github.com/robbert-vdh/yabridge/files/7478851/yabridge-tkg.log)
2. Tried winetricks
    1. with a clean prefix: [yabridge-tkg-clean.log](https://github.com/robbert-vdh/yabridge/files/7479111/yabridge.log)
    2. with just vcrun2019: [yabridge-tkg-vcrun2019.log](https://github.com/robbert-vdh/yabridge/files/7479086/yabridge.log)
    
I've noticed in scenarios 1 and 2.i, Reaper continues to respond for a little while after the audio cuts out, whereas with 2.ii, Reaper freezes as soon as the audio does. Not sure if that helps.

Let me know if I messed anything up or if you need any more info.

**Comment by robbert-vdh** [comment]
Not sure what's magically wrong between our systems then, or maybe I just haven't clicked around enough in MSoundFactory Have you submitted a bug report for this on https://bugs.winehq.org/? I think wine-tkg actually disables Wine's crash reporter, but if you can somehow get a crash report for this then they would probably appreciate it.

**Comment by JonathanTroyer** [comment]
[Bug created](https://bugs.winehq.org/show_bug.cgi?id=51973), linking here to cross-reference.

**Comment by robbert-vdh** [comment]
You can try loading the plugin in the Windows version of REAPER running under Wine to see if the problem also happens there, but the odds of the problem being related to yabridge itself are essentially 0%. (and that would be the first yabridge bug in a long long time, which would be fun in a way I guess :grin:)

**Comment by JonathanTroyer** [comment]
Closing as this is a Wine-specific issue.
