### ISSUE TITLE
Reason Rack 12 black box

### ISSUE THREAD

**Issue by DaKingof** [robbert-vdh/yabridge#145]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Opening the rack extention with a new reason updated to 12 I am now getting a black box just like the previous scaler 2 plugin issue.

### What did you expect to happen?

The UI to open.

### What actually happened?

A black box appears but I can still right click to open a menu and add instruments. Instruments still work, but I can't see what I am doing or use my mouse to tweak the UI.

### Operating system

Arch

### How did you install yabridge?

AUR

### yabridge version

3.6.0.r8.g0382b0a4-1

### yabridgectl version

3.6.0.r8.g0382b0a4-1

### Wine version

wine-6.20-360-g46367d1ecc8 (Staging)

### Plugin installation method

copies

### Plugin

Reason RE

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Bitwig Studio 4.0.1

### Desktop environment or WM

Tried on x11 and Wayland

### GPU model

6700xt

### GPU drivers and kernel

Mesa

**Comment by DaKingof** [comment]
I just tried running Bitwig through terminal and it seems that fixes the issue for some reason so I am not sure how I can find out what is causing this.

**Comment by robbert-vdh** [comment]
There are probably some environment variables being set by your shell that aren't set on the shell your DE is using (which will be your login shell if you use SDDM, or `/bin/sh -l` if you use LightDM or GDM). You can also compare the log files in `~/.BitwigStudio/logs` to see if you can spot any differences there.

**Comment by DaKingof** [comment]
I just opened up the new beta and it seems the issue has been fixed. Now the plugin opens as it should both with and without terminal. Thanks guys!

**Comment by robbert-vdh** [comment]
Yeah, it should work fine (although people mentioned a while ago that third party rack extensions wouldn't load properly, but maybe some Wine updates have fixed that in the meantime). Closing this since it isn't a yabridge issue.
