### ISSUE TITLE
Archlinux package yabridge-bin - wrong install location libyabridge-vst*

### ISSUE THREAD

**Issue by rustikus** [robbert-vdh/yabridge#147]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Sorry, I was not able to figure out how to post this via AUR.

I think there is a typo in the latest change of the PKGBUILD which leads to:

```
Error: Could not find 'libyabridge-vst2.so' in either '/usr/lib' or '/home/username/.local/share/yabridge/'. 
You can override the default search path using 'yabridgectl set --path=<path>'.
```
I suppose the files libyabridge-vst* should be installed to /usr/lib not /usr/bin 

This is the latest change according to AUR 

```
index 88441bd576f..cf004e8b914 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -21,11 +21,12 @@ sha256sums=('46a68052157bd30c4aeb5b0eb84154582408eb099377716e3690518dec048384')
 package() {
   cd "$srcdir/$_pkgname"
 
-  install -dm755 "${pkgdir}"/usr/lib
-  install libyabridge-{vst2,vst3}.so "${pkgdir}"/usr/lib
+  install -dm755 "$pkgdir/usr/lib"
+  install libyabridge-{vst2,vst3}.so "$pkgdir/usr/bin"
 
 }
```
Thanks a lot for the very useful software!

### What did you expect to happen?

Install files to /usr/lib

### What actually happened?

Installed to /usr/bin

### Operating system

Arch

### How did you install yabridge?

AUR

### yabridge version

3.7.0-2

### yabridgectl version

3.7.0-2

### Wine version

latest

### Plugin installation method

copies

### Plugin

all

### Plugin type

both VST2 and VST3

### Plugin architecture

both 64-bit and 32-bit

### Host

all

**Comment by robbert-vdh** [comment]
Oops, I updated my AUR packages today and copy-pasted some things I shouldn't have. I've fixed all PKGBUILDs. Thanks for letting me know!
