### ISSUE TITLE
RFC: Plugin groups

### ISSUE THREAD

**Issue by robbert-vdh** [robbert-vdh/yabridge#15]
I thought it would be nice to be able to support plugins that use inter-plugin communication. Fabfilter ProQ 3 as well as several other mixing plugins allow you to reference other instances of the same plugin without having to do any manual audio routing. Yabridge runs every plugin in its own process both for ease of use and to provide an extra degree of stability by preventing one crashing plugin from affecting the other plugins. These plugins however expect all of their instances (and sometimes also all plugins from the same manufacturer) to be hosted in the same process so they can use global variables to share state. I had an idea on how to fairly easily allow specific groups of plugins to be hosted in a single process without affecting the general usability and stability of yabridge. Before I actually implement this I would love to hear if anyone has any thoughts on how this could be made more user friendly or just implemented better. My current idea is as follows:

1. First of all there has to be a way to specify which plugins should be hosted in a 'group process' rather than individually. For this my idea was to add a configuration file called `yabridge.toml`. This file can be located in the plugin's .dll file's directory or in any of the parent directories. This TOML file will be used to associate certain plugins with groups and the format will look like the following:

   ```toml
   ["FabFilter Pro-Q 3.dll"]
   group = "fabfilter"
   
   # This will match everything under the 'ToneBoosters/' directory
   ["ToneBoosters"]
   group = "toneboosters"
   
   ["iZotope*/RX *"]
   group = "izotope"
   
   ["iZotope*/Neutron 2 Mix Tap.dll"]
   group = "izotope"
   ```

   The keys are simple case sensitive glob patterns that should either match the filename or a prefix of the file path relative to the directory of the `yabridge.toml` file. This file will be parsed from top to bottom, and the section with the first matching glob pattern will determine a plugin's group settings.

2. Once yabridge gets loaded by a VST host and the plugin's .dll has been located we'll start looking for this configuration file. If a `yabridge.toml` configuration file is found then we'll print its location and the the options that will be used according to this file, if any of the glob patterns match as described above.

3. If a group has been set for a plugin, then we'll first need to determine the socket file path for that group so we can actually launch new plugins within the group. The name of this socket would be based on a combination of both the current Wine prefix and the name of the group. Then, instead of launching either `yabridge-host.exe` or `yabridge-host-32.exe`, we will either:

   - Launch `yabridge-group.exe` or `yabridge-group-32.exe` if there is no process already listening on the socket. This may require a way to differentiate between active and stale socket files. The socket endpoint file should be created immediately to prevent race conditions, although it will likely be fine in either case since the later process won't be able to listen on the socket. The newly launched process will have to be detached immediately after starting.
   - Not do anything if a group process is already listening on the socket.

4. Once the group process for the current group is up and running (or if it already was running), we'll connect to the group's socket and send a request to open the current plugin in the group process. For this we will send the exact same arguments as used for the regular `yabridge-host.exe` so we can use the exact same handling for plugins hosted individually and for plugins hosted inside of a group process.

5. From here on out everything works the same as the regular operation of yabridge.

In short, to implement these group processes we will need:

1. A way to specify which plugins should be grouped together into a single process.
2. To determine whether a plugin should be hosted in a group process, and if it should, then instead of launching a new process we will either start a new group process or connect to an existing one. We will then tell that process to load a plugin's .dll file exactly like we would normally, except that it happens inside of a new thread rather than a new process.
3. Everything else works exactly the same.

The only thing I haven't figured out yet is how the group process's STDOUT and STDERR streams should be handled. At the moment yabridge will capture these streams so it can prefix the messages with timestamps and write them to a log file. This easy approach sadly won't be possible with group processes since they are run independently from `libyabridge.so` instances.

Does anyone have any thoughts on this?

**Comment by siborg** [comment]
Hi Robert,

Thanks for trying to improve this even further!

.toml file looks easy to read and set up. Will Bitwig's plugin sandboxing
won't mess this up?

The only thing I haven't figured out yet is how the group process's STDOUT
> and STDERR streams should be handled. At the moment yabridge will capture
> these streams so it can prefix the messages with timestamps and write them
> to a log file. This easy approach sadly won't be possible with group
> processes since they are run independently from libyabridge.so instances.
>


Would inserting a <group name>:<plugin name> to STDOUT/STERROR is an
option? e.g.

izotope:neutron2.so/dll etc...

Cheers,

Very Best Regards,

Szymon Kosecki

**Comment by robbert-vdh** [comment]
Thanks for the response! This should have no interaction with the sandboxing done by Bitwig or any other host since the part of yabridge running under a seperate Wine is separate anyway, so if it works now then  it should also work with grouped plugins.

> Would inserting a <group name>:<plugin name> to STDOUT/STERROR is an option?

I guess the hard part is that it's not possible anymore to know which plugin is generating the output. But if it's possible to redirect the own process's STDERR/STDOUT streams to some kind of function that prefixes every line with the group name and just reuses the same logging code we use in the Linux plugin then that would probably be the best option, thanks!

**Comment by anoadragon453** [comment]
I like the idea of pairing the toml file alongside your dll's as it makes it simple to backup all of your VSTs and your yabridge configuration. Does this also allow you to have multiple configuration files spread across your VST collection? And if so, in what order will these files be parsed?

I initially though it would be messy to have multiple configuration files, as you may lose track of them, but if yabridge prints out their location on startup this doesn't seem to be much of a concern. That alongside the allure of keeping all of your files together and having short, relative reference paths in the file tipped the scale.

**Comment by robbert-vdh** [comment]
I would go for the simplest approach and only use values from the first `yabridge.toml` file it finds, and then from the first matching glob pattern within that configuration file. Finding the file would work similarly to the `locate-dominating-file` function in Emacs and the way that the Wine prefix detection is currently implemented. This way you could have a configuration file for both your entire VST plugins directory and for specific subdirectories within that directory without having any confusing moving parts that would come from merging configuration from multiple sources (not that that would really be a thing at the moment with only a single setting).

**Comment by anoadragon453** [comment]
Ah ok, that sounds like it indeed will be simpler for everyone.

**Comment by cameronleger** [comment]
I really appreciate the thought behind this. I think everything sounds great to me, though I wonder about Step 2 and how the configuration is really found, since there's little description and the way that it's chosen seems contentious.

In my setup, it sounds like it would work as-is, and I can already imagine an easy way to set this up, which is as-described _much_ easier than the LinVSTX:

```
== .local/share/VST ==
vst1.so -> /path/to/prefix/vst1.{so,dll}
vst2.so -> /path/to/prefix/vst2.{so,dll}
group1/vst3.so -> /path/to/prefix/vst3.{so,dll}
group1/vst4.so -> /path/to/prefix/vst4.{so,dll}
```

```
["group1"]
group = "group1"
```

**Comment by robbert-vdh** [comment]
My original plan was to make searching for the configuration file relative to the actual `plugin.dll` file (after folloowing symlinks). So in your example it would first try `/path/to/prefix/yabridge.toml`, then `/path/to/yabridge.toml`, then '/path/yabridge.toml' and so forth. Although with setups like yours where you symlink all `.so` files to a single directory it would make more sense to have the search be relative to the .so file, with glob patterns matching those `.so` files and without following any symlinks. I'm not sure which of the two approaches I prefer, although I hadn't really considered such a setup yet! I may just have to go with making it relative to the `.so` files since otherwise a setup like yours would become unnecessarily complicated from having the configuration file be in a completely separate location. Thanks for the input!

**Comment by cameronleger** [comment]
Another option I haven't seen discussed, and would require that the Configuration's Paths _not_ be relative to the Configuration File, is to just put it somewhere known like `/etc/yabridge/groups.conf`.

**Comment by robbert-vdh** [comment]
That would be the obvious approach, although I do feel like having a global configuration file would make things a bit harder since then you would either need to use long absolute paths that change whenever you move your plugins around or you would need to match plugins based on regular expressions or some kind of fuzzy matching (or just match the path suffix, but that can also get a bit unclear). To me that sounds like it would be less ergonomic than having a configuration file that's stored along with the files it's providing configuration for using short relative paths. It's also the reason why I went with the '`./plugin.so` bridges `./plugin.dll`' approach rather than having those associations stored in a configuration file somewhere.

**Comment by siborg** [comment]
How about symlinking a  global configuration file to the plugin directory?
It probably be better for it to be somewhere in ~/.config folder ... what
do you think?

Very Best Regards,

Szymon Kosecki

**Comment by cameronleger** [comment]
Yes, I was presuming REGEX would be used for this instead of the absolute paths. Either way works, with pros/cons for each.

**Comment by robbert-vdh** [comment]
It took quite a bit more effort than I figured it would take, but I've implemented this feature and it's now in a state I would consider to be feature complete and stable! (or at least, it is stable On My Machine:tm: :grin:) There's still some refactoring work left to do since I had to modify a not insignificant chunk of the internals to account for running multiple plugins and Win32 GUI applications within a single process, so I would really appreciate it if anyone could try it out to see if I missed anything obvious here. If anyone does feels like testing it out, you can either build directly from the master branch or you can grab a prebuilt version from [this page](https://github.com/robbert-vdh/yabridge/actions?query=workflow%3A%22Automated+builds%22+branch%3Amaster).

Cheers.

**Comment by cameronleger** [comment]
Awesome! I just built master, updated the existing plugins, and swapped everything that was on LinVST-X to this. For now, I just verified that the config was loaded and the plugins could communicate (FabFilter Pro-Q 3 in this case), and all seemed great! I'll be testing it more as I work on my current project, so I'll let you know if anything comes up.

**Comment by robbert-vdh** [comment]
I finished the refactoring and cleanup I still wanted to do, and this feature along with some more quality of life improvements is now part of [yabridge 1.2.0](https://github.com/robbert-vdh/yabridge/releases). I'm closing this now, but please don't hesitate to open a new issue if anyone runs into problems or has suggestions on how things could be done better!

**Comment by prez** [comment]
Just a thought: 
Shipping a configuration file as part of yabridge (which could be placed in /etc) with group descriptions that are known to be correct would be of immense value, since it'd be a nice usability improvement for new users and would enable crowdsourcing this kind of information by allowing users to contribute it directly into the repository. 
The local definitions in .config would then overwrite the global ones on an individual basis.

**Comment by robbert-vdh** [comment]
@prez The example configuration file in the readme contains examples for some  common plugins. In practice you don't need plugin groups much anymore since most plugins come with a VST3 version nowadays.
