### ISSUE TITLE
Cytomic The Glue - drag and drop activation

### ISSUE THREAD

**Issue by ste1590** [robbert-vdh/yabridge#153]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I can't activate the plugin. It works but drag and drop auth.txt file over plugin window is not possible. Already tried some workarounds like yabridge.toml and winetricks gdiplus, different wine version but without success. Any advice?

### What did you expect to happen?

Activate the plugin.

### What actually happened?

Drag and drop auth.txt file over plugin window is not possible.

### Operating system

Ubuntu Mate 20.04.3

### How did you install yabridge?

Releases page

### yabridge version

3.7

### yabridgectl version

3.7

### Wine version

wine-staging 6.14

### Plugin installation method

copies

### Plugin

Cytomic The Glue

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Bitwig Studio 4.01

**Comment by robbert-vdh** [comment]
What application are you trying to drag the file from? And does the plugin not let you just select the file instead? There should not be any issues with dragging things to Wine applications. I would recommend upgrading your Bitwig version though, I don't know why you're still at 4.0.1 but 4.0.8 contains a lot of fixes (or 4.1.2 of course if your upgrade plan is still active).

**Comment by ste1590** [comment]
- What application are you trying to drag the file from? 
From desktop (caja 1.24) and it's just txt file for activation.

- And does the plugin not let you just select the file instead?
No, it must be dragged to the plugin window. On windows 10 there was similar issue but running DAW just for the activation with "run as administrator" unchecked from the shortcut fixed this. Since I already do not run Bitwig as sudo on Ubuntu, I do not know how to fix this.

- I would recommend upgrading your Bitwig version though, I don't know why you're still at 4.0.1 but 4.0.8 contains a lot of fixes (or 4.1.2 of course if your upgrade plan is still active).
I did not upgrade the version because everything is working properly on this version for now, I doubt it is due to the version 4.0.1.

**Comment by robbert-vdh** [comment]
Try dragging from a different file browser, like Dolphin or Nautilus. If that still doesn't work, then you may need to file a bug report on winehq.org.

**Comment by ste1590** [comment]
Actually, you were right, problem was in Bitwig. I found a workaround until they fix this. I installed StudioOne in separate wine prefix, installed plugin, activated, then just moved all plugin files to wine prefix I use for Bitwig, sync with yabridge and it's activated. :)

**Comment by robbert-vdh** [comment]
And that's why it's usually a good idea to just update your software.
