### ISSUE TITLE
WARNING: Unknown options: "build.cpp_std" and "cpp_std"

### ISSUE THREAD

**Issue by plaimbock** [robbert-vdh/yabridge#16]
Thanks for yabridge! I was trying to package latest git on Fedora 32 and see these warnings in the output:

meson setup --buildtype=release --cross-file cross-wine.conf -Duse-bitbridge=true build
The Meson build system
Version: 0.54.0
Source dir: /home/patrick/rpmbuild/BUILD/yabridge-master
Build dir: /home/patrick/rpmbuild/BUILD/yabridge-master/build
Build type: cross build
WARNING: Unknown options: "build.cpp_std"
The value of new options can be set with:
meson setup <builddir> --reconfigure -Dnew_option=new_value ...
Project name: yabridge
Project version: 1.1.4 (it's actually latest git)
C++ compiler for the build machine: c++ (gcc 10.1.1 "c++ (GCC) 10.1.1 20200507 (Red Hat 10.1.1-1)")
C++ linker for the build machine: c++ ld.bfd 2.34-2
000b:fixme:winediag:__wine_start_process Wine Staging 5.7 is a testing version containing experimental patches.
000b:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
C++ compiler for the host machine: wineg++ (gcc 10.1.1 "g++ (GCC) 10.1.1 20200507 (Red Hat 10.1.1-1)")
C++ linker for the host machine: wineg++ ld.bfd 2.34-2
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Configuring config.h using configuration
Run-time dependency Boost found: YES 1.69.0 (/usr)
Run-time dependency Boost (found: filesystem) found: YES 1.69.0 (/usr)
Using bitsery source from cache.
Downloading bitsery patch from file:./subprojects/bitsery-patch.tar.xz
Download size: 340
Downloading: ..........

|Executing subproject bitsery method meson 
|
|Project name: bitsery
|Project version: 5.0.3
|C++ compiler for the build machine: c++ (gcc 10.1.1 "c++ (GCC) 10.1.1 20200507 (Red Hat 10.1.1-1)")
|C++ linker for the build machine: c++ ld.bfd 2.34-2
|C++ compiler for the host machine: wineg++ (gcc 10.1.1 "g++ (GCC) 10.1.1 20200507 (Red Hat 10.1.1-1)")
|C++ linker for the host machine: wineg++ ld.bfd 2.34-2
|Build targets in project: 1
|Subproject bitsery finished.

Run-time dependency threads found: YES
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Run-time dependency xcb found: YES 1.13.1
Message: Bitbridge enabled, configuring a 32-bit host application
Library xcb found: YES
Build targets in project: 4

yabridge 1.1.4

  Subprojects
    bitsery: YES

Found ninja-1.10.0 at /usr/bin/ninja
+ /usr/bin/meson --buildtype=plain --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=default --auto-features=enabled . x86_64-redhat-linux-gnu
The Meson build system
Version: 0.54.0
Source dir: /home/patrick/rpmbuild/BUILD/yabridge-master
Build dir: /home/patrick/rpmbuild/BUILD/yabridge-master/x86_64-redhat-linux-gnu
Build type: native build
Using 'PKG_CONFIG_PATH' from environment with value: ':/usr/lib64/pkgconfig:/usr/share/pkgconfig'
Using 'PKG_CONFIG_PATH' from environment with value: ':/usr/lib64/pkgconfig:/usr/share/pkgconfig'
WARNING: Unknown options: "cpp_std"
The value of new options can be set with:
meson setup <builddir> --reconfigure -Dnew_option=new_value ...

**Comment by robbert-vdh** [comment]
The actual build works fine, right? There's an issue with Meson where the specified C/C++ standard option only gets applied to the cross compilation target (i.e. the Wine VST host) when cross compiling (https://github.com/mesonbuild/meson/issues/5590). The workaround is to use the `build.<option_name>` syntax to explicitly tell Meson to also use that option for the native target (the Linux VST2 plugin) when cross compiling, But even though Meson understands those `build.*` options just fine it will still give a warning. It should not affect the actual build though!

**Comment by plaimbock** [comment]
Thanks for the explanation. Yes the build is unaffected and I see the compiler using c++17 so case closed.
