### ISSUE TITLE
Momentum from big fish audio loads fine in carla, but throws a 'installation corrupted' error with yabridge.

### ISSUE THREAD

**Issue by TheGuyWhoo** [robbert-vdh/yabridge#163]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I've attached photos that show what happens. Everything goes smoothly until I try to actually open the vst.

![Screenshot from 2022-02-16 17-14-32](https://user-images.githubusercontent.com/72744967/154295979-1f421e2b-a4df-4ff6-812c-8fd77a53949d.png)
![Screenshot from 2022-02-16 17-14-44](https://user-images.githubusercontent.com/72744967/154296009-2af3258a-09c4-492f-9462-4a4d32d57bdd.png)

### What did you expect to happen?

The vst to load.

### What actually happened?

See the attached images above.

### Operating system

Linux Mint 20

### How did you install yabridge?

From releases page.

### yabridge version

3.8.0

### yabridgectl version

3.8.0

### Wine version

7,1 (staging)

### Plugin

Momentum by Big Fish Audio

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Reaper linux version 6.44

**Comment by robbert-vdh** [comment]
The plugin uses ujam's Gorilla Engine. Ctrl+F the error (`JS_EXEC_FAILED`) in the [known issues and fixes](https://github.com/robbert-vdh/yabridge#known-issues-and-fixes) readme section for a workaround. You'll need to disable yabridge's use of pipes and have the plugin's output be written to a file instead because these plugins somehow check for that and throw an obscure error when their output is piped somewhere else.

**Comment by TheGuyWhoo** [comment]
unfortunately drag and drop doesn't work, even with "editor_force_dnd = true"

**Comment by robbert-vdh** [comment]
Are you sure that option is enabled? Check the yabridge's output in your terminal (or whatever you've set `YABRIDGE_DEBUG_FILE` to) when loading the plugin. If you're using the `Track -> Insert virtual instrument on new track...` option in REAPER then you need to either reopen the editor window or switch to yabridge's latest [development build](https://github.com/robbert-vdh/yabridge#installing-a-development-build). Alternatively, try it in a host that doesn't interfere with drag-and-drop (so anything that isn't REAPER or Carla, like Bitwig or Ardour).

**Comment by TheGuyWhoo** [comment]
Yes, definitely enabled and the latest build didn't make a difference. I could always just use the windows version of reaper.

**Comment by robbert-vdh** [comment]
So have you tried it under Bitwig to make sure it's REAPER eating the drop?

**Comment by TheGuyWhoo** [comment]
No, I don't have bitwig. I am able to drag and drop in Carla, though, so it must be reaper.

**Comment by robbert-vdh** [comment]
Closing this since the original issue was solved (ujam plugins need an option in yabridge.toml to be set). Feel free to create a new issue if you think you ran into something else.
