### ISSUE TITLE
Problem Compiling yabridge 3.8.0

### ISSUE THREAD

**Issue by muziker** [robbert-vdh/yabridge#164]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I'm having problems compiling yabridge  3.8.0. The system version of libboost uses g++-9 but g++-10 is a requirement for compiling yabridge. I've got a separate boost library installed in another include, lib directory. How do i specify yabridge to use this libboost version instead or the system provided ones? 

### What did you expect to happen?

NA

### What actually happened?

NA

### Operating system

ubuntu 20.04

### How did you install yabridge?

Github

### yabridge version

3.8.0

### yabridgectl version

3.8.0

### Wine version

wine staging 7.2

### Plugin

NA

### Plugin type

both VST2 and VST3

### Plugin architecture

both 64-bit and 32-bit

### Host

NA

**Comment by robbert-vdh** [comment]
Do you have a specific reason for wanting to compile ysbridge from scratch instead of using the builds from the Releases page? Refer to the usage section for more information:

https://github.com/robbert-vdh/yabridge#usage

**Comment by muziker** [comment]
I'm familiarising myself with the rather many different ways github projects are compiled and installed. In this case the surprise was the gcc-10 requirement meant the repo libboost could not be used and has to be compiled with the gcc-10, after which yabridge compilation would need to point to the new libboost.

**Comment by muziker** [comment]
For some reason BOOST_INCLUDEDIR and BOOST_LIBDIR don't work when using meson. So i created a pkgconfig file instead. However while building yabridge-host-32, the "file in wrong format" error appeared. Does this mean i need a 32 bit libboost library as well ? Just found the docker-yabridge file. I'll follow that to rebuild 64 & 32 bit versions of boost.

**Comment by robbert-vdh** [comment]
Your Boost libraries don't need to be compiled with GCC 10. The GCC version they're compiled with is irrelevant as long as that GCC version support C++11 and the system that compiled the library doesn't have a more recent glibc version than the system you're compiling yabridge on. The boost libraries in Ubuntu 20.94's should be recent enough to compile yabridge with though (exact minimum versionsnare in the readme and in the meson.buikd file), so I don't know why you'd need to compile your own Boost first. 

And yes to be able to build the 32 bit host binaries you need the 32 bit version of libboost-filesystem.

**Comment by muziker** [comment]
Looking through some of the errors and the build.ninja file. Doesn't this mean the system needs to have 32 bit versions of libxcb and every other linkable library specified by build instructions for -m32?

**Comment by muziker** [comment]
Ok managed to compile this. It appears src/wine-host/bridges/group.h needs this line

>#include `<fstream>`

for compilation to complete

**Comment by robbert-vdh** [comment]
> The readme says the requirements for building yabridge is a gcc10+ compiler. There's a few errors if using gcc9 though, that was resolved once using gcc10. 

Yes you need GCC10 (for C++20 support), but you don't need a special 'GCC 10' version of Boost. The version of Boost in Ubuntu 30.04's repos should be recent enough to compile yabridge with. 

.> Looking through some of the errors and the build.ninja file. Doesn't this mean the system needs to have 32 bit versions of libxcb and every other linkable library specified by build instructions for -m32? 

Yes you indeed need the 32 bit versions of those libraries to link the 32 bit host binaries to. The Dockerfile contains everything needed to compile yabridge on Ubuntu. But again, if you just want to use yabridge you van just download a build from the releases page or the CI for a nightly build. That what those are for! :)

**Comment by muziker** [comment]
There were a few symbol errors, which indicated either a 32/64 bit error or a problem due to compiler differences used for libboost, which is why boost had to be compiled with gcc-10

**Comment by muziker** [comment]
Ok so managed to get everything working. The different yabridge.so files needed to be linked to the correct libboost_filesystems. They needed to have their rpaths patched to point to the right lib directories, so 32 bit libboost library directory for sofiles that are loading 32bit win plugins.
