### ISSUE TITLE
Yabridge && Reaper configuration

### ISSUE THREAD

**Issue by mpalourdio** [robbert-vdh/yabridge#165]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Hello,

I have a `focusrite 212 3rd gen`, native linux `reaper`, and installed `yabridge` in order to use `Helix Native` on `mint 20.3` + `wine 7.0` . I have some questions regarding performane (I have read the README but, heh)

- `Reaper` can add FX in 4 ways : `Automatic`, `Separated process`, `Dedicated process`, `Native only (prevent bridges)`. What would be the more performant way to init the plugins ? I have tested all of them, without a real difference regarding performance.
- I am using `alsa` (because `jack` does not seem to make any difference regarding performance). After about adding 5/6 tracks with a single plugin (`Helix Native vst3`), things begin to stutter on playback. Sometimes, changing buffering and others voodoo parameters fixes the problem on the project, sometimes not. CPU and RAM look quite okish (16 Go Ram, i7-10510U), but it's a little painful. Restarting reaper can fix it sometimes.

I understand that bridging plugins by wine is not comparable to have native linux plugins, but I think there's something I miss to be very fluid.

Anyway, thanks a LOT for this great library. If you need more information, feel free to ask!

### Operating system

Mint 20.3

### How did you install yabridge?

tar.gz from release page

### yabridge version

3.8.0

### yabridgectl version

3.8.0

### Wine version

7.0

### Plugin

Helix Native

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Reaper

### Desktop environment or WM

Cinnamon

### GPU model

Intel

### GPU drivers and kernel

5.4.0-100-generic

**Comment by geekositalia** [comment]
for me all similar comparable to windows native. Helix Native require gdiplus...

I also recommend installing wine tkg, and adding d3d9 and dxgi as native dlls (some plugins will use vulkan with this system)

**Comment by geekositalia** [comment]
with this system I had a lot of difference with ssl of brainworks (which uses vulkan for 2d acceleration)

**Comment by geekositalia** [comment]
Reaper can add FX in 4 ways : Automatic, Separated process, Dedicated process, Native only (prevent bridges). What would be the more performant way to init the plugins ? I have tested all of them, without a real difference regarding performance.

this not add performance advantages, but only in term of stability, if one or more plugins as problem

**Comment by robbert-vdh** [comment]
> Reaper can add FX in 4 ways...

REAPER does not have any plugin bridges for VST3 on Linux, so those options shouldn't do anything.

Those plugins are likely just very resource intensive, but if you haven't done so already then you should try the things mentioned in the [performance tweaking](https://github.com/robbert-vdh/yabridge#performance-tuning) section of the readme.

**Comment by mpalourdio** [comment]
@geekositalia  @robbert-vdh  thanks for your feedbacks, I suppose the CPU intensive plugin is just the culprit here. Closing now!
