### ISSUE TITLE
win plugs do not work if wine doesn't have a z drive.

### ISSUE THREAD

**Issue by muziker** [robbert-vdh/yabridge#166]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

The z drive in a wine installation grants access to programs running with wine access to the entire filesytem. I removed the entry with winecfg, but now the vst plugins don't work. Is there any way to not require the z drive mapping? Or to tighten it down to a subset directory of the user? 

### What did you expect to happen?

The vst to load 

### What actually happened?

It didn't load

### Operating system

ubuntu 20.03

### How did you install yabridge?

compiled 

### yabridge version

3.8.0-15-gb3ceebf1

### yabridgectl version

3.8.0

### Wine version

wine staging 7.2

### Plugin

Valhallasupermassive

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

reaper

**Comment by robbert-vdh** [comment]
Wine needs to be able to launch the `yabridge-host.exe.so` application. And if that cannot be accessed by Wine, then there's no way for yabridge to work. In theory adding a disk station in Winecfg that contains just the directory the `yabridge-*.exe*` files are in should also allow Wine to find them and map them to a Windows path.

**Comment by muziker** [comment]
I just tried it by allowing wine to use the .local/share/yabridge directory. It works !

**Comment by robbert-vdh** [comment]
Great!
