### ISSUE TITLE
Plugin GUI won't load

### ISSUE THREAD

**Issue by benshurts** [robbert-vdh/yabridge#169]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I have gone through all the steps and it almost works. I can get the window manager for the plugin to show up but it freezes there and won't load the GUI, and crashes the DAW/sandbox. Interestingly I can play notes and get audio still.
When I initially started serum I got the serial prompt and everything seemed to work. Then I killed the program and no longer got it load. 

### Operating system

Pop-OS

### How did you install yabridge?

directly from release page

### yabridge version

3.8.1

### yabridgectl version

3.8.1

### Wine version

7.0

### Plugin

serum

### Plugin type

VST2

### Plugin architecture

both 64-bit and 32-bit

### Host

bitwig studio 4.2

### Desktop environment or WM

Xorg, Gnome

### GPU model

NVIDIA RTX 3060

### GPU drivers and kernel

nvidia

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/8240657/yabridge.log)

### Anything else?

n/a

**Comment by robbert-vdh** [comment]
There's no crash or any apparently issue in the log you posted. And if you can still play notes and hear audio, nothing has crashed.

Have you tried this with a clean Wine prefix (rename `~/.wine` to something else and reinstall the plugin) and with the tweaks mentioned in [the readme](https://github.com/robbert-vdh/yabridge#known-issues-and-fixes)?

**Comment by robbert-vdh** [comment]
Closing this since there has not been a response in a while. Please reply if this needs to be reopened.
