### ISSUE TITLE
FAILED: libyabridge.so - relocation R_X86_64_PC32 against symbol can not be used

### ISSUE THREAD

**Issue by plaimbock** [robbert-vdh/yabridge#17]
The build (default, no 32bit bridge) fails in mock and I have no idea if it's something in boost, yabridge or something else. From searching I tried building with redhat-lsb-cxx (same problem) and adding standard Fedora/Red Hat hardened build flags so linking works with hardened boost. But meson does not seem to use those flags. The flags + meson command is one big line. Any idea?

Start: rpmbuild yabridge-1.1.5-0.1.20200517.gite728dbe.src.rpm
Building target platforms: x86_64
Building for target x86_64
setting SOURCE_DATE_EPOCH=1589673600
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.DhvJlu
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf yabridge-master
+ /usr/bin/unzip -qq /builddir/build/SOURCES/yabridge-master.zip
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd yabridge-master
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ mkdir -p subprojects/packagecache
+ cp -v /builddir/build/SOURCES/bitsery-d24dfe14f5a756c0f8ad3d56ae6949ecc2c99b2e.zip subprojects/packagecache
'/builddir/build/SOURCES/bitsery-d24dfe14f5a756c0f8ad3d56ae6949ecc2c99b2e.zip' -> 'subprojects/packagecache/bitsery-d24dfe14f5a756c0f8ad3d56ae6949ecc2c99b2e.zip'
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.OBAcbu
+ umask 022
+ cd /builddir/build/BUILD
+ cd yabridge-master
+ CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ CXXFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ FFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ FCFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'
+ meson setup --buildtype=release --cross-file cross-wine.conf build
wine: created the configuration directory '/builddir/.wine'
000b:fixme:winediag:__wine_start_process Wine Staging 5.7 is a testing version containing experimental patches.
000b:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0012:err:ole:get_local_server_stream Failed: 80004002
0014:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0014:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 14007
0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x800736b7
0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 800736b7
0014:err:ole:get_local_server_stream Failed: 800736b7
000b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
000b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0010:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0010:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0016:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0016:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0018:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0018:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Could not find Wine Gecko. HTML rendering will be disabled.
0010:err:vulkan:wine_vk_init Failed to load Wine graphics driver supporting Vulkan.
0025:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0025:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0027:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0027:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0029:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0029:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Could not find Wine Gecko. HTML rendering will be disabled.
0025:err:vulkan:wine_vk_init Failed to load Wine graphics driver supporting Vulkan.
wine: configuration in L"/builddir/.wine" has been updated.
The Meson build system
Version: 0.54.0
Source dir: /builddir/build/BUILD/yabridge-master
Build dir: /builddir/build/BUILD/yabridge-master/build
Build type: cross build
WARNING: Unknown options: "build.cpp_std"
The value of new options can be set with:
meson setup <builddir> --reconfigure -Dnew_option=new_value ...
Project name: yabridge
Project version: 1.1.4
C++ compiler for the build machine: c++ (gcc 10.1.1 "c++ (GCC) 10.1.1 20200507 (Red Hat 10.1.1-1)")
C++ linker for the build machine: c++ ld.bfd 2.34-2
C++ compiler for the host machine: wineg++ (gcc 10.1.1 "g++ (GCC) 10.1.1 20200507 (Red Hat 10.1.1-1)")
C++ linker for the host machine: wineg++ ld.bfd 2.34-2
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Configuring config.h using configuration
Run-time dependency Boost found: YES 1.69.0 (/usr)
Run-time dependency Boost (found: filesystem) found: YES 1.69.0 (/usr)
Using bitsery source from cache.
Downloading bitsery patch from file:./subprojects/bitsery-patch.tar.xz
Download size: 340
Downloading: ..........

|Executing subproject bitsery method meson 
|
|Project name: bitsery
|Project version: 5.0.3
|C++ compiler for the build machine: c++ (gcc 10.1.1 "c++ (GCC) 10.1.1 20200507 (Red Hat 10.1.1-1)")
|C++ linker for the build machine: c++ ld.bfd 2.34-2
|C++ compiler for the host machine: wineg++ (gcc 10.1.1 "g++ (GCC) 10.1.1 20200507 (Red Hat 10.1.1-1)")
|C++ linker for the host machine: wineg++ ld.bfd 2.34-2
|Build targets in project: 1
|Subproject bitsery finished.

Run-time dependency threads found: YES
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Run-time dependency xcb found: YES 1.13.1
Build targets in project: 3

yabridge 1.1.4

  Subprojects
    bitsery: YES

Found ninja-1.10.0 at /usr/bin/ninja
+ ninja -v -j1 -C build
ninja: Entering directory `build'
[1/14] /usr/bin/meson --internal vcstagger ../src/common/config/version.h.in src/common/config/version.h 1.1.4 /builddir/build/BUILD/yabridge-master/src/common/config @VCS_VERSION@ '(.*)' /usr/bin/git describe --always
fatal: not a git repository (or any of the parent directories): .git
[2/14] c++ -Iyabridge@sha -I. -I.. -I../src/include -I../subprojects/bitsery-d24dfe14f5a756c0f8ad3d56ae6949ecc2c99b2e/include -Isrc/common/config -I/usr/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -fPIC -pthread -DBOOST_FILESYSTEM_STATIC_LINK=1 -DBOOST_ALL_NO_LIB -MD -MQ 'yabridge@sha/src_common_logging.cpp.o' -MF 'yabridge@sha/src_common_logging.cpp.o.d' -o 'yabridge@sha/src_common_logging.cpp.o' -c ../src/common/logging.cpp
[3/14] c++ -Iyabridge@sha -I. -I.. -I../src/include -I../subprojects/bitsery-d24dfe14f5a756c0f8ad3d56ae6949ecc2c99b2e/include -Isrc/common/config -I/usr/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -fPIC -pthread -DBOOST_FILESYSTEM_STATIC_LINK=1 -DBOOST_ALL_NO_LIB -MD -MQ 'yabridge@sha/src_common_serialization.cpp.o' -MF 'yabridge@sha/src_common_serialization.cpp.o.d' -o 'yabridge@sha/src_common_serialization.cpp.o' -c ../src/common/serialization.cpp
[4/14] c++ -Iyabridge@sha -I. -I.. -I../src/include -I../subprojects/bitsery-d24dfe14f5a756c0f8ad3d56ae6949ecc2c99b2e/include -Isrc/common/config -I/usr/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -fPIC -pthread -DBOOST_FILESYSTEM_STATIC_LINK=1 -DBOOST_ALL_NO_LIB -MD -MQ 'yabridge@sha/src_plugin_plugin.cpp.o' -MF 'yabridge@sha/src_plugin_plugin.cpp.o.d' -o 'yabridge@sha/src_plugin_plugin.cpp.o' -c ../src/plugin/plugin.cpp
[5/14] c++ -Iyabridge@sha -I. -I.. -I../src/include -I../subprojects/bitsery-d24dfe14f5a756c0f8ad3d56ae6949ecc2c99b2e/include -Isrc/common/config -I/usr/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -fPIC -pthread -DBOOST_FILESYSTEM_STATIC_LINK=1 -DBOOST_ALL_NO_LIB -MD -MQ 'yabridge@sha/src_plugin_plugin-bridge.cpp.o' -MF 'yabridge@sha/src_plugin_plugin-bridge.cpp.o.d' -o 'yabridge@sha/src_plugin_plugin-bridge.cpp.o' -c ../src/plugin/plugin-bridge.cpp
[6/14] c++ -Iyabridge@sha -I. -I.. -I../src/include -I../subprojects/bitsery-d24dfe14f5a756c0f8ad3d56ae6949ecc2c99b2e/include -Isrc/common/config -I/usr/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -fPIC -pthread -DBOOST_FILESYSTEM_STATIC_LINK=1 -DBOOST_ALL_NO_LIB -MD -MQ 'yabridge@sha/src_plugin_utils.cpp.o' -MF 'yabridge@sha/src_plugin_utils.cpp.o.d' -o 'yabridge@sha/src_plugin_utils.cpp.o' -c ../src/plugin/utils.cpp
[7/14] c++  -o libyabridge.so 'yabridge@sha/src_common_logging.cpp.o' 'yabridge@sha/src_common_serialization.cpp.o' 'yabridge@sha/src_plugin_plugin.cpp.o' 'yabridge@sha/src_plugin_plugin-bridge.cpp.o' 'yabridge@sha/src_plugin_utils.cpp.o' -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libyabridge.so -ldl /usr/lib64/libboost_filesystem.a -Wl,--end-group -pthread
FAILED: libyabridge.so 
c++  -o libyabridge.so 'yabridge@sha/src_common_logging.cpp.o' 'yabridge@sha/src_common_serialization.cpp.o' 'yabridge@sha/src_plugin_plugin.cpp.o' 'yabridge@sha/src_plugin_plugin-bridge.cpp.o' 'yabridge@sha/src_plugin_utils.cpp.o' -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libyabridge.so -ldl /usr/lib64/libboost_filesystem.a -Wl,--end-group -pthread
/usr/bin/ld: /usr/lib64/libboost_filesystem.a(operations.o): relocation R_X86_64_PC32 against symbol `_ZTIN5boost10filesystem16filesystem_errorE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by robbert-vdh** [comment]
I'll have to confess that I know very little about hardening (or Fedora for that matter haha)! I'm not really sure what the problem is though. I hadn't tried building on Fedora yet, but I just attempted to build yabridge in the `fedora` docker image and I didn't have any linking errors. Not sure if that image is any different from the environment in Mock though. I've been able to build yabridge both with and without those hardening flags you pasted, and also both with and without the `-Duse-bitbridge=true` option to enable the 32-bit host application. Starting from the clean image, I only had to install these packages to be able to compile:

```shell
dnf install boost-devel gcc-c++ git libxcb-devel.x86_64 meson wine-devel boost.i686 glibc-devel.i686 libxcb-devel.i686 wine-devel.i686  # or just boost-filesystem.i686 instead of boost.i686

# With the mentioned Red Hat hardening flags
dnf install redhat-rpm-config  # Needed for the /usr/lib/rpm/redhat/redhat-* specs
export CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
export CXXFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
export FFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
export FCFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
export LDFLAGS='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'

# And then I just compiled with
git clone https://github.com/robbert-vdh/yabridge.git
cd yabridge
meson setup --buildtype=release --cross-file cross-wine.conf -Duse-bitbridge=true build
ninja -C build
```

And the `*.i686` packages are of course only necessary when with compiling with `-Duse-bitbridge=true`. Are the regular Boost packages I installed from the Fedora repos any different from the hardened versions used in Mock?

**Comment by plaimbock** [comment]
Thanks for your elaborate feedback. Good to know that it works fine on Fedora 31. The difference between your F31 container and F32 which I'm using seems to be meson 0.52 versus 0.54 and gcc 9.x.x versus 10.0.0. And I build inside mock (chroot build environment manager for building RPMs).

I made some progress as I got it to build with this change:
sed -i -e's|, static : true||g' meson.build
Without that change, boost_filesystem is not found.

Also meson does not pick up exported CFLAGS/CXXFLAGS/LDFLAGS from the environment or running $ CXXFLAGS=... meson .... so not there yet.

**Comment by plaimbock** [comment]
Related? https://github.com/mesonbuild/meson/commit/d5e25b2914f891ead3d8ee0f461eeb1967c3f296
This is not in 0.54 but in 0.54.2 and there are a number of other boost fixes so guess I should try a newer meson.

**Comment by plaimbock** [comment]
More progress. Tried meson 0.54.2 and now the FLAGS are picked up. But boost-filesystem is still not found with 'static : true' in meson.build:
Configuring config.h using configuration
Run-time dependency Boost found: YES 1.69.0 (/usr)
Run-time dependency Boost (missing: filesystem) found: NO 
meson.build:46:0: ERROR: Dependency "boost" not found

**Comment by robbert-vdh** [comment]
That's strange! So with Meson 0.54.0 it did pick up `/usr/lib64/libboost_filesystem.a` and compilation failed with a linking error, and with Meson 0.54.2 it couldn't find the static archive? On my machine Meson is still at 0.54.1, and I think that's also the version I'm using for building on Ubuntu 18.04 and Ubuntu 20.04. I just briefly tried building using Meson 0.54.2 on Manjaro, and for me it did correctly find `/usr/lib64/libboost_filesystem.a`. Is Boost installed through the regular `boost-devel` package from the repositories? From a quick search that linking error would only occur if the version if Boost you're trying to link to was not built with `-fPIC`, but that should definitely be the case so that's weird.

**Comment by plaimbock** [comment]
> Is Boost installed through the regular boost-devel package from the repositories?
The regular boost-devel rpm does not install any static libs, only dynamic/.so libs (and include files, etc). For static boost you need to install the boost-static rpm which provides e.g. /usr/lib64/libboost_filesystem.a. Works: remove 'static : true' and build with boost-devel, boost-filesystem installed. Does not work: 'static : true' and build with boost-static. The first works and results in an rpm so that works for me. If you want to further investigate I'm available. Thank you for all your help!

**Comment by robbert-vdh** [comment]
Maybe downstream just broke something? Or it's some issue with GCC 10? Since static linking both 32-bit and 64-bit Boost works fine with `boost-devel` in Fedora 31. I just tried doing the same with both Fedora 32 and Rawhide and I'm getting the exact same linking error you were getting. But statically linking Boost only really matters anyway if you're distributing the binaries to somehow who does not have that exact version of (32-bit) Boost installed. 

Anyways, nice to see that you've managed to at least somewhat figure it out! Let me know if you run into any issues with yabridge.
