### ISSUE TITLE
Bottles wineprefix not detected

### ISSUE THREAD

**Issue by AnteKronos** [robbert-vdh/yabridge#170]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I have used yabridge almost for an entire year without problems (almost), and is a great piece of software. I have all my plugins in a wineprefix made with [bottles](https://github.com/bottlesdevs/Bottles), i use this manager to manage all my prefixes, and bottles manage different versions of wine linking those versions with the prefixes, not using only the system version installed. Yabridge uses only the wine version installed on the system and not the wine version linked throug bottles, where i have set a protong version with some patches suggested by you. I have read the wiki, the section where is described the [wineprefix](https://github.com/robbert-vdh/yabridge#wine-prefixes) environment variable, but i would prefer not to set globally with the env. It's possible to use the bottles runner instead of the default wine version?

### Operating system

ArchLinux

### How did you install yabridge?

AUR Package

### yabridge version

3.8.1-2  

### yabridgectl version

3.8.1-2  

### Wine version

7.4.1

### Host

Reaper

**Comment by robbert-vdh** [comment]
> It's possible to use the bottles runner instead of the default wine version?

You can set the standard `WINELOADER` environment variable to the `wine` binary you want to use. There's no built in way to use a different Wine version per prefix though for a couple reasons, although you still do that by using a custom script in conjunction with `WINELOADER`.

**Comment by AnteKronos** [comment]
Sounds good, but i was not able to find nothing useful about wineloader and how to use it with the wine binary, you can suggest me some resource to achieve the goal?

**Comment by robbert-vdh** [comment]
It's just an absolute path to a `wine` binary. It's mentioned in Wine's manual: https://www.winehq.org/docs/wine

**Comment by AnteKronos** [comment]
Ok, but i have to set the env locally for my user or globally for the system? Would let use that wine binary for all the wine programs executed, even outside the bottles prefix?

**Comment by robbert-vdh** [comment]
Setting that in your login shell's profile (so don't set that in your shell's interactive configuration or it won't affect GUI applications launched from your desktop environment) will cause all Wine invocations to use that Wine binary, yes.

**Comment by AnteKronos** [comment]
Ok, I'll try, thank you for your advice, I will update the issue with the updates.

**Comment by robbert-vdh** [comment]
Closing this since it's not a yabridge issue and there hasn't been a response in a couple months.
