### ISSUE TITLE
VSTs load with terminal emulator

### ISSUE THREAD

**Issue by joefiorini** [robbert-vdh/yabridge#172]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

When I load a project in my DAW (Bitwig) that uses yabridge controlled VSTs each plugin loads with a terminal. That means if I have 8 plugins in my project I get 8 terminals as well. This was not a problem until a recent upgrade to the latest yabridge & wine.

### What did you expect to happen?

I expect the plugins to not open a terminal; this is the behavior I've seen in the past.

### What actually happened?

I see a terminal for each plugin in my project. This does _not_ happen when I start a stand-alone application.

### Operating system

Garuda Linux

### How did you install yabridge?

AUR package

### yabridge version

3.8.1

### yabridgectl version

3.8.1

### Wine version

7.5

### Plugin

All plugins

### Plugin type

both VST2 and VST3

### Plugin architecture

both 64-bit and 32-bit

### Host

Bitwig Studio 4.2.2

### Desktop environment or WM

Awesome 4.3

**Comment by robbert-vdh** [comment]
You're using an older version the Arch package. Arch had a [packaging error](https://bugs.archlinux.org/task/74260?string=yabridge&project=5&search_name=&type%5B0%5D=&sev%5B0%5D=&pri%5B0%5D=&due%5B0%5D=&reported%5B0%5D=&cat%5B0%5D=&status%5B0%5D=&percent%5B0%5D=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=) where they accidentally overwrite some of the linking options. You'll need to upgrade to the latest `yabridge-3.8.1-3` package. 

You may also want to join the Discord, I posted about this in the announcements channel there a week ago.

**Comment by joefiorini** [comment]
Thanks! I'll do that.
