### ISSUE TITLE
Support iLok STL Tones Amphub Licenses

### ISSUE THREAD

**Issue by avanzzzi** [robbert-vdh/yabridge#173]
### Feature description

yabridge is able to launch and the plugin Amphub Player by STL Tones works as expected.

The license for the Player is working but it is unable to identify the Individual Amp Licenses active in iLok. So the amps I own are not avaiable for use inside the player.

Maybe not a problem in yabridge but if someone have some insight that might help get this working I appreciate. Maybe it's something related to the communication between the plugin and iLok.

### Anything else?

Other iLok plugins I own, like Neural DSP Amps works fine. But none of them work with this scheme of one or more licenses in the plugin.

**Comment by robbert-vdh** [comment]
This would be a Wine issue so I can't help with this, sorry. Have you already checked whether there's a matched bug report on Wine's [bug tracker](https://bugs.winehq.org/)?

**Comment by avanzzzi** [comment]
> 

Didn't found anything related, I'll fire a bug there. Thanks for pointing this!
