### ISSUE TITLE
Qtractor Successes and Challenges

### ISSUE THREAD

**Issue by hijinio** [robbert-vdh/yabridge#174]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

1. Missing Presets - VSTs will load successfully, but when I hover over the presets context menu, nothing appears other than "(default)". For example, I tried this with Claw and Unknown Pro 64.

2. Stacking VSTs - Within a single track, when I load more than one VST, only one plays at a time. I'd like to be able to create new instruments by stacking them (or even running FX on top.)

3. Hang on Reload - If I duplicate a track with a VST, more often than not, the entire project will hang on reload (unless I remember to manually remove the VST and manually reinsert it.)

### What did you expect to happen?

1. Missing Presets - When I right-click on the plugin and choose "Preset" from the context menu, I should be able to see all available presets.

2. Stacking VSTs - When I place multiple winVSTs within the same track, then should all play the MIDI file.

3. Hang on Reload - Regardless of the workflow, the VSTs should not prevent the loading of a project, even though they did not crash the project while working on it.

### What actually happened?

1. Missing Presets - I only see the "(default)" option.

2. Stacking VSTs - I only hear the bottom most instrument, if there is more than one. Otherwise, if I disable it, the other one plays.

3. Hang on Reload - I ran Qtractor via terminal. There was no output there or on output log. The project just got stuck on a loop trying to load. I've only experience this with yabridge VSTs.

### Operating system

Pop!_OS 21.10

### How did you install yabridge?

Directly from the releases page

### yabridge version

3.8.1

### yabridgectl version

3.8.1

### Wine version

wine-7.6

### Plugin

Claw, Unknown Pro 64, Cheeze Machine, etc.

### Plugin type

VST2

### Plugin architecture

32-bit

### Host

Qtractor 0.9.24

### Desktop environment or WM

Default Pop_OS

### GPU model

n/a

### GPU drivers and kernel

n/a

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/8461501/yabridge.log)

### Anything else?

Thank you for making this project a reality. I'm very excited about your objective to bring winVSTs as close to the DAW as possible. I've been using Carla for some time now, and I thought I'd try out yabridge. Overall, I'm thrilled about what you're doing.

**Comment by robbert-vdh** [comment]
> Missing Presets - VSTs will load successfully, but when I hover over the presets context menu, nothing appears other than "(default)". For example, I tried this with Claw and Unknown Pro 64.

That's a bug in Qtractor, not quite sure what it's doing. If you'd check with any other host, you'd see they'd fetch the plugin's program list just fine: 
![afbeelding](https://user-images.githubusercontent.com/748520/162725370-3f506c9a-2080-49bb-aed5-1f9c3694a8e5.png)

> Stacking VSTs - Within a single track, when I load more than one VST, only one plays at a time. I'd like to be able to create new instruments by stacking them (or even running FX on top.)

That's just how Qtractor (and most DAWs actually) behaves. You'll need to submit a feature request with Qtractor's creator about this.

> Hang on Reload - I ran Qtractor via terminal. There was no output there or on output log. The project just got stuck on a loop trying to load. I've only experience this with yabridge VSTs.

That's a bug in Unknown Pro 64 in combination with a bug in Qtractor. While reopening the project Qtractor will call `effSetProgram` for every single one of the plugin's presets. And Unknown Pro 64 takes a second to switch to a new preset, so loading takes a while. On top of that the plugin's GUI cannot be interacted with in Qtractor while this works fine in any other host, so that's like likely also specific to Qtractor.

**Comment by hijinio** [comment]
1. Got it! I'll submit this to him. BTW, I'm glad you are comparing against Carla because that's what I had been using.

2. Oh wow! I really did not notice this before, and I thought I had two stacking with Carla - but it was really just an ongoing delay on one of the instruments (notes weren't changing). I suppose on my previous workflow, I had been putting them on different tracks, and this worked fine.

![Screenshot from 2022-04-11 08-09-28](https://user-images.githubusercontent.com/24835215/162770812-2509d7d4-af22-41c0-9e69-8858ccd760dd.png)

3. Very interesting. I am able to interact with GUI or through Qtractor's direct access, but to your point, this specific plugin hangs on reload (although it inserts fine). I likely did not notice before because, like you said, it doesn't do this on other hosts (Carla).

I appreciate your swift and candid response. I look forward to continuing to test yabridge. This is really exciting work! Thank you for everything that you're doing.

**Comment by hijinio** [comment]
So, it turns out that Qtractor CAN control which preset/program to use. "Preset" is language used in a specific way for and within Qtractor in a way that I haven't wrapped my head around yet.

So, to choose a "program", we must do this at the track level, not the VST level. In other words, right-click on track > "Instrument" menu item > choose the VST > choose the bank > choose the instrument. Alternatively, a user can double-click the track to get a dialogue to choose the VST instrument + bank + program.

Now that I have this, I will continue to test yabridge.
