### ISSUE TITLE
Tokyo Dawn Record plugin GUIs don't display correctly

### ISSUE THREAD

**Issue by Repartee41** [robbert-vdh/yabridge#175]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I've tried the TDR plugins Nova, Kotelnikov, and SlickEQ, and all of their GUIs display incorrectly. All other plugins work perfectly fine.

No errors are shown in Reaper's log when launched from the terminal. Here is the output, alongside the issue:
![image](https://user-images.githubusercontent.com/16549042/165129712-5343df6b-6562-4683-9422-1d4c821bcbf4.png)

### What did you expect to happen?

In Windows, these plugins have the full GUI, with no crop.

### What actually happened?

The GUI is cropped, cutting off some of the useful area.

### Operating system

Manjaro

### How did you install yabridge?

AUR package using yay

### yabridge version

3.8.1-3

### yabridgectl version

3.8.1

### Wine version

wine-7.5 (Staging)

### Plugin

Tokyo Dawn Records

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Reaper

### Desktop environment or WM

Tested on i3 and XFCE

### GPU model

AMD Radeon Integrated Graphics (AMD Ryzen 7 5850U CPU)

### GPU drivers and kernel

video-linux 2018.05.04 -- 5.17.1-3-MANJARO #1 SMP PREEMPT

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/8556328/yabridge.log)

**Comment by robbert-vdh** [comment]
Kotelnikov thinks it should apply DPI scaling, REAPER thinks it shouldn't (and it ignores REAPER's request to not apply any scaling). So you need to look at your Wine font DPI settings in the graphics tab of winecfg. Try setting that to 96 or 192, or some other values inbetween.

**Comment by Repartee41** [comment]
> Kotelnikov thinks it should apply DPI scaling, REAPER thinks it shouldn't (and it ignores REAPER's request to not apply any scaling). So you need to look at your Wine font DPI settings in the graphics tab of winecfg. Try setting that to 96 or 192, or some other values inbetween.

Thank you for your reply, setting my dpi to 96 works for these plugins. Can I set this value only for these plugins, and keep it at another value for everything else?

**Comment by robbert-vdh** [comment]
No, you cannot. This is just a case of Wine's HiDPI implementation not being entirely up to par yet and Windows' (or anything that's not macOS' or a mobile operating system's) DPI scaling story being kind of a mess.
