### ISSUE TITLE
Fuse Audio Labs plugins GUI lag

### ISSUE THREAD

**Issue by jams3223** [robbert-vdh/yabridge#176]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Hi guys i was using the fuse audio labs vcl-4 and the knob where not showing so i would think it's a graphical issue.

### What did you expect to happen?

i expected the knobs to fully show.

### What actually happened?

while using the plugin inside the reaper the knob wouldn't appear.

### Operating system

Fedora 36

### How did you install yabridge?

using the terminal on fedora

### yabridge version

3.8.1

### yabridgectl version

3.8.1

### Wine version

wine staging 7.5

### Plugin

Fuse Audio Labs VCL-4

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Reaper 6.56

### Desktop environment or WM

Gnome on Wayland

### GPU model

Intel HD Graphics 4400

### GPU drivers and kernel

Mesa 22 on Linux 5.17.4

**Comment by robbert-vdh** [comment]
I downloaded the demo of VPRE-31A and it works just like you'd expect with a clean Wine prefix and both Wine Staging 7.7 and a wine-tkg version somewhere between 7.6 and 7.7. So try reinstalling the plugin in a clean Wine prefix.

I'm closing the issue since this is not a yabridge issue.
