### ISSUE TITLE
Does not build with -Dvst3=false

### ISSUE THREAD

**Issue by nidefawl** [robbert-vdh/yabridge#180]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

> src/plugin/meson.build:17:0: ERROR: Unknown variable "vst3_sdk_native_dep".

After commenting that line I also had to move this dependency:
```patch
diff --git a/src/wine-host/meson.build b/src/wine-host/meson.build
index 8ab34796..b7052f1a 100644
--- a/src/wine-host/meson.build
+++ b/src/wine-host/meson.build
@@ -39,11 +39,11 @@ if with_bitbridge
     tomlplusplus_dep,
     wine_threads_dep,
     xcb_32bit_dep,
+    wine_ole32_dep,
   ]
   if with_vst3
     host_32bit_deps += [
       vst3_sdk_hosting_wine_32bit_dep,
-      wine_ole32_dep,
       wine_shell32_dep,
       wine_uuid_dep,
     ]
```

### What did you expect to happen?

See description

### What actually happened?

See description

### Operating system

Arch Linux

### How did you install yabridge?

build git HEAD

### yabridge version

git HEAD

### yabridgectl version

git HEAD

### Wine version

0

### Plugin

0

### Plugin type

both VST2 and VST3

### Plugin architecture

both 64-bit and 32-bit

### Host

0

**Comment by robbert-vdh** [comment]
Fixed in 6efc69071e2b281c3fcf9124c99b2ac57ab2e2a3, thanks.
