### ISSUE TITLE
Superior drummer 3 freezes on GUI open

### ISSUE THREAD

**Issue by Levitanus** [robbert-vdh/yabridge#181]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Currently, I face the problem only with `Superior Drummer` and only running it through `yabridge`. The host and everything freezes on opening of GUI, while the plugin works if opened with existing project. The problem disappears within loading though `LinVST`

I don't understand what the error is...

### What did you expect to happen?

GUI is opened

### What actually happened?

I forced to kill reaper

### Operating system

Manjaro

### How did you install yabridge?

yabridge-gir from aur

### yabridge version

3.8.1

### yabridgectl version

3.8.1

### Wine version

7.7

### Plugin

Superior Drummer 3

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Reaper

### Desktop environment or WM

XFCE

### GPU model

NVIDIA 970

### GPU drivers and kernel

4.6.0 NVIDIA 510.73.05 

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/8790590/yabridge.log)

**Comment by robbert-vdh** [comment]
What version of Superior Drummer 3 are you using? I know a dozen people using Superior Drummer 3 without issues, so perhaps this is simply a bug in the particular version you're using. There's nothing odd in the logs, your Superior Drummer just stalls indefinitely when it's asked for the size of its editor for the second time. Also give the VST3 version of Superior Drummer a try.

**Comment by robbert-vdh** [comment]
If your particular version does work with LinVst then that doesn't seem surprising because LinVst doesn't actually bridge the `effEditGetSize` function call correctly:

https://github.com/osxmidi/LinVst/blob/9d94c02e8226b17501b0e4cf47d72173ba4fd78a/linvst.cpp#L76-L84

It always returns the last known size (which at this point would be its default of 200x200 pixels) without asking the plugin about it.

**Comment by Levitanus** [comment]
Thank You, I'll inspect it later today. Actually, I didn't touch this wine installation of SD for ages: «do not touch the thing, which works» :)
It is 3.1.5 at the moment.

**Comment by Levitanus** [comment]
Update helped, thank You
