### ISSUE TITLE
Could not locate yabridge-host.exe.so

### ISSUE THREAD

**Issue by rzn-unvrs** [robbert-vdh/yabridge#182]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Warning: 'yabridge-host.exe' is not present in your login shell's search path. Yabridge won't be
    able to run using the copy-based installation method until this is fixed.
    Add '/usr/lib' to bash's login shell PATH environment variable. See the
    troubleshooting section of the readme for more details. Rerun this command to verify that the
    variable has been set correctly, and then reboot your system to complete the setup.
    
    https://github.com/robbert-vdh/yabridge#troubleshooting-common-issues
Error: Could not locate 'yabridge-host.exe.so'

### What did you expect to happen?

yabridgectl to scan for plugins

### What actually happened?

warning and error

### Operating system

Linux

### How did you install yabridge?

to /usr/bin and ~/.local

### yabridge version

3.5.2

### yabridgectl version

3.5.2

### Wine version

7.9

### Plugin

n/a

### Plugin type

both VST2 and VST3

### Plugin architecture

both 64-bit and 32-bit

### Host

n/a

**Comment by robbert-vdh** [comment]
First of all, don't install anything to `/usr/bin`. That directory is owned by your package manager, and you should never ever modify any files yourself there. You didn't mention which distro you're using, so I'll assume you're using Ubuntu or Debian. Make sure you extracted the archive correctly. Run `ls ~/.local/share/yabridge` in a terminal, does that list all of yabridge's files (including `yabridge-host.exe`)?

**Comment by rzn-unvrs** [comment]
It seems I placed the files in ~/.local/share/yabridge/yabridgectl/yabridge and that was the issue
