### ISSUE TITLE
Synthedit plugin UIs aren't loading correctly, just a whiteish window in linux mint 20 64 bit cinnamon, reaper 6.44

### ISSUE THREAD

**Issue by TheGuyWhoo** [robbert-vdh/yabridge#183]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

![Screenshot from 2022-05-31 15-38-00](https://user-images.githubusercontent.com/72744967/171187348-fc52628d-e0b0-4f60-a6dd-e179e8cd9446.png)
 
^

### What did you expect to happen?

The ui to load correctly.

### What actually happened?

It didn't load correctly.

### Operating system

linux mint 20

### How did you install yabridge?

Action tab

### yabridge version

3.8.0

### yabridgectl version

3.8.0

### Wine version

7.1 staging

### Plugin

all synthedit plugins

### Plugin type

both VST2 and VST3

### Plugin architecture

both 64-bit and 32-bit

### Host

reaper 6.44

**Comment by TheGuyWhoo** [comment]
The problem seems to be related to synthedit vsts that use .png files, like CXSM-V in this case. Synthedit plugins that don't use ,png files, like https://plugins4free.com/plugin/3262/, works as it should.

**Comment by robbert-vdh** [comment]
Sorry for the delay, I had a couple of busy days. These plugins work just fine under Wine, and to my knowledge they always have:

![afbeelding](https://user-images.githubusercontent.com/748520/171674118-76d5fe2d-9266-4d1e-8ada-a6c09006234e.png)

You'll want to either take a look at Wine's output (the debug log step you skipped in the issue template), or just:

1. Try a clean Wine prefix (temporarily rename `~/.wine` to something else, install the plugin, give that a try)
2. Update to a more recent version of Wine. You're using old versions for everything. You should probably also update to yabridge 3.8.1 (and rerun `yabridgectl sync` after you do).

**Comment by TheGuyWhoo** [comment]
updated everything, still no joy. Here's the output.

    14:22:48 [CX5M-V-49Oinotv] Initializing yabridge version 3.8.1
    14:22:48 [CX5M-V-49Oinotv] host:          '/home/user/.local/share/yabridge/yabridge-host.exe'
    14:22:48 [CX5M-V-49Oinotv] plugin:        '/home/user/Desktop/WINVST3/CX5M-V VST3/CX5M-V.vst3'
    14:22:48 [CX5M-V-49Oinotv] plugin type:   'VST3'
    14:22:48 [CX5M-V-49Oinotv] realtime:      'yes'
    14:22:48 [CX5M-V-49Oinotv] sockets:       '/run/user/1000/yabridge-CX5M-V-49Oinotv'
    14:22:48 [CX5M-V-49Oinotv] wine prefix:   '<default>'
    14:22:48 [CX5M-V-49Oinotv] wine version:  '7.9 (Staging)'
    14:22:48 [CX5M-V-49Oinotv] 
    14:22:48 [CX5M-V-49Oinotv] config from:   '<defaults>'
    14:22:48 [CX5M-V-49Oinotv] hosting mode:  'individually, 64-bit'
    14:22:48 [CX5M-V-49Oinotv] other options: '<none>'
    14:22:48 [CX5M-V-49Oinotv] 
    14:22:48 [CX5M-V-49Oinotv] Enabled features:
    14:22:48 [CX5M-V-49Oinotv] - bitbridge support
    14:22:48 [CX5M-V-49Oinotv] - VST3 support
    14:22:48 [CX5M-V-49Oinotv] 
    14:22:49 [CX5M-V-49Oinotv] [Wine STDERR] 002c:fixme:winediag:LdrInitializeThunk wine-staging 7.9 is a testing version containing experimental patches.
    14:22:49 [CX5M-V-49Oinotv] [Wine STDERR] 002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
    14:22:55 [CX5M-V-49Oinotv] [Wine STDERR] Initializing yabridge host version 3.8.1
    14:22:55 [CX5M-V-49Oinotv] [Wine STDERR] Preparing to load VST3 plugin at '/home/user/Desktop/WINVST3/CX5M-V VST3/CX5M-V.vst3'
    14:22:55 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E8B0 1 C) semi-stub
    14:22:55 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E540 1 C) semi-stub
    14:22:55 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E510 1 C) semi-stub
    14:22:55 [CX5M-V-49Oinotv] [Wine STDERR] Finished initializing '/home/user/Desktop/WINVST3/CX5M-V VST3/CX5M-V.vst3'
    14:22:55 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F0B0 1 C) semi-stub
    14:22:55 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F590 1 C) semi-stub
    14:22:55 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F0E0 1 C) semi-stub
    14:22:55 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F220 1 C) semi-stub
    14:22:55 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011EF30 1 C) semi-stub
    14:22:56 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F460 1 C) semi-stub
    14:22:56 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F1E0 1 C) semi-stub
    14:22:56 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F000 1 C) semi-stub
    14:22:56 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F000 1 C) semi-stub
    14:22:56 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
    14:22:56 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:dxgi:DXGID3D10CreateDevice Ignoring flags 0x20.
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:d3d11:d3d11_device_CheckFormatSupport iface 0000000000259650, format 91, format_support 000000000011F4F8 partial-stub!
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:dxgi:wined3d_swapchain_desc_from_dxgi Ignoring alpha mode 0.
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:d3d:wined3d_swapchain_init The application requested more than one back buffer, this is not properly supported.
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] Please configure the application to use double buffering (1 back buffer) if possible.
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:dwrite:dwritefactory_CreateMonitorRenderingParams (0000000000000001): monitor setting ignored
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 00c8:fixme:imm:ImeSetActiveContext (0000000000059120, 0): stub
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 00c8:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000059120): stub
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:imm:ImeSetActiveContext (0000000000325D20, 1): stub
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:imm:ImmReleaseContext (0000000000010066, 0000000000325D20): stub
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:dxgi:DXGID3D10CreateDevice Ignoring flags 0x20.
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:d3d11:d3d11_device_context_SwapDeviceContextState D3D10 interface emulation not fully implemented yet!
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:d2d:d2d_device_context_Flush iface 0000000006643960, tag1 0000000000000000, tag2 0000000000000000 stub!
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log Info log received from GLSL shader #3:
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     Vertex info
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     -----------
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[0].zw" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[2].zw" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[3].zw" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[5]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[6]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[7]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[8]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[9]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[10]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[11]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[12]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[13]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[14]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[15]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     Fragment info
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     -------------
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0144:fixme:d3d_shader:print_glsl_info_log     0(36) : warning C7050: "R1.yzw" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 000000000011E060.
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log Info log received from GLSL shader #3:
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     Vertex info
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     -----------
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[0].zw" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[2].zw" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[3].zw" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[5]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[6]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[7]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[8]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[9]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[10]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[11]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[12]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[13]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[14]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     0(23) : warning C7050: "vs_out[15]" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     Fragment info
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     -------------
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 0138:fixme:d3d_shader:print_glsl_info_log     0(36) : warning C7050: "R1.yzw" might be used before being initialized
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:d2d:d2d_device_context_Flush iface 0000000006643960, tag1 0000000000000000, tag2 0000000000000000 stub!
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 000000000011E060.
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:d2d:d2d_device_context_Flush iface 0000000006643960, tag1 0000000000000000, tag2 0000000000000000 stub!
    14:22:57 [CX5M-V-49Oinotv] [Wine STDERR] 011c:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 000000000011E060.

**Comment by robbert-vdh** [comment]
And that's with a clean Wine prefix? Nothing else installed there, Wine recreated it from scratch?

**Comment by TheGuyWhoo** [comment]
A-ha! Forgot to do that. I apologise, it's working now. What do I do now with the old prefix, do I just copy my files from it and then delete?

**Comment by robbert-vdh** [comment]
Either remove it if you don't need it anymore, or keep it if you do. :smile:
