### ISSUE TITLE
Plugins not being found by Bitwig + `Error: Could not locate 'yabridge-host.exe.so'`

### ISSUE THREAD

**Issue by jfaz08** [robbert-vdh/yabridge#186]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Running `yabridgectl sync` yields:
```
Finished setting up 1 plugins (0 new), skipped 0 non-plugin .dll files
Error: Could not locate 'yabridge-host.exe.so'
```
Files are created, but when using Bitwig, the folder for the VST is there without a plugin. The error in Bitwig when rescanning is: `Could not find 'libyabridge-vst3.so`

I have included the install dir in my `PATH` and running `yabridgectl` without full path works fine.

`yabridgectl status` outputs:
```
libyabridge-chainloader-vst2.so: '/home/jfaz/.local/share/yabridge/libyabridge-chainloader-vst2.so' (64-bit)
libyabridge-chainloader-vst3.so: '/home/jfaz/.local/share/yabridge/libyabridge-chainloader-vst3.so' (64-bit)

yabridge-host.exe: <not found>
yabridge-host-32.exe: <not found>
```
So it seems for some reason it can't find either two, even though `ls ~/.local/share/yabridge` has both there. Any clue what I can do?

Thank you for your time!

### What did you expect to happen?

Plugin shows up in editor and can be loaded

### What actually happened?

Nothing shows up other than plugin folder

### Operating system

Xubuntu

### How did you install yabridge?

Releases page, extracted to `local/share/`

### yabridge version

4.0.1

### yabridgectl version

4.0.1

### Wine version

wine-7.11 (Staging)

### Plugin

Any

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Bitwig

**Comment by robbert-vdh** [comment]
Can you show me the output of running the following command in a terminal?

```bash
ls -Al "${XDG_DATA_HOME:-$HOME/.local/share}/yabridge"
```

**Comment by jfaz08** [comment]
> Can you show me the output of running the following command in a terminal?
> 
> ```shell
> ls -Al "${XDG_DATA_HOME:-$HOME/.local/share}/yabridge"
> ```

Thanks for the reply! Here's the output:
```
ls -Al "${XDG_DATA_HOME:-$HOME/.local/share}/yabridge"
total 9628
-rw-rw-r-- 1 jfaz jfaz   85061 jun 12 10:38 CHANGELOG.md
-rw-rw-r-- 1 jfaz jfaz   88912 jun 12 10:38 libyabridge-chainloader-vst2.so
-rw-rw-r-- 1 jfaz jfaz   88904 jun 12 10:38 libyabridge-chainloader-vst3.so
-rw-rw-r-- 1 jfaz jfaz  651704 jun 12 10:38 libyabridge-vst2.so
-rw-rw-r-- 1 jfaz jfaz 1758488 jun 12 10:38 libyabridge-vst3.so
-rw-rw-r-- 1 jfaz jfaz   51175 jun 12 10:38 README.md
drwx------ 2 jfaz jfaz    4096 jun 12 10:40 yabridge
-rwxrwxr-x 1 jfaz jfaz 2193776 jun 12 10:36 yabridgectl
-rw-rw-r-- 1 jfaz jfaz     708 jun 12 10:38 yabridge-host-32.exe
-rw-rw-r-- 1 jfaz jfaz 2488040 jun 12 10:38 yabridge-host-32.exe.so
-rw-rw-r-- 1 jfaz jfaz     705 jun 12 10:38 yabridge-host.exe
-rw-rw-r-- 1 jfaz jfaz 2421728 jun 12 10:38 yabridge-host.exe.so
```

**Comment by robbert-vdh** [comment]
That doesn't explain the `Could not find 'libyabridge-vst3.so'`, but it seems like the executable bits were stripped from all of those files. I don't know how you extracted the archive, but something went wrong there. I'd completely `rm -rf ~/.local/share/yabridge`, and then extract the file again there. As a quick oneliner you could do `curl -L https://github.com/robbert-vdh/yabridge/releases/download/4.0.1/yabridge-4.0.1.tar.gz | tar -C ~/.local/share -xzvf -` to get the files where they need to be.

**Comment by jfaz08** [comment]
Yup, that did it! First time something like this happens, pretty crazy. Thank you so much!
