### ISSUE TITLE
Some VST Plugins can cause Xruns on MIDI Program Changes via MIDI Controller

### ISSUE THREAD

**Issue by nine7nine** [robbert-vdh/yabridge#187]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Some VST plugins cause xruns, when using MIDI Program Changes.

Steps to reproduce issue: (In this example, I will use NI Reaktor 6 + Kontour, as it causes 1 xrun per MIDI Program Change).

- Launch Kushview Element (in WIne) via Carla-single binary + Yabridge
- Open Reaktor in Yabridge.
- Load Kontour Instrument
- Switch Preset via MIDI Program change on your MIDI controller
- it will produce 1 xrun per program change

note: this is a longstanding issue that happens in pretty much any version of Wine with any winelib VST host.

While, I'm using Reaktor 6 + Kontour as an example, there are lots of plugins that can probably exhibit this issue. And some will exhibit this issue: without using MIDI Program Change, but simply changing the preset (NI Kontakt + certain instruments, being an example).

In this scenario, I'm using JACK. (Unfortunately, I haven't found Pipewire to be reliable enough for my general use yet).

### What did you expect to happen?

When I use MIDI Program Changes to switch preset, I expect it to switch presets without any xruns.

### What actually happened?

the VST plugin switches presets, but get I get xruns in the process.

note: the xruns will vary depending on the VST. In Reaktor 6 + Kontour - it is a single xrun per MIDI Program Change, while in others it may be more or less.

### Operating system

Archlinux

### How did you install yabridge?

AUR / git

### yabridge version

687bee34d511486e61e2fc3cc08eef336d0516f8

### yabridgectl version

687bee34d511486e61e2fc3cc08eef336d0516f8

### Wine version

wine-7.5.r0.g1e792e2d ( NSPA ) - but happens in any version of wine

### Plugin

NI Reaktor 6 (but happens with other plugins)

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Kushview Element / Carla-single, but happens in any host

### Desktop environment or WM

687bee34d511486e61e2fc3cc08eef336d0516f8

### GPU model

[15d8] AMDGPU/ATI Picasso/Raven 2 (AMD Ryzen 3500u's APU)

### GPU drivers and kernel

Mesa 22.1.1 + Linux-5.18.2-nspa (PREEMPT_RT_FULL)

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/8935519/yabridge.log)

**Comment by robbert-vdh** [comment]
That's kind of an unavoidable issue with the way program changes are handled in something like Reaktor, and sadly not something a plugin bridge can fix. MIDI program changes were intended for quickly switching between different already loaded programs. In those situations handling a MIDI program change message simply involves changing some coefficients out at the start of the next process function and that's it.

In plugin development there is this this notion of 'realtime safeness'. A function is realtime safe iff it cannot block, and thus has a fixed upper bound in its running time. This is essentially the same thing as 'wait free' in algorithm design, and it implies that these functions should not do any IO, wait on mutexes, allocate memory, or perform other system calls. Anything that happens on the audio thread should be realtime safe (or as close to it as it can be). But if handling a program change involves any of the aforementioned things, it thus cannot be realtime safe and you may see xruns as a result if the whole program loading sequence ended up blocking for longer than the DSP load headroom left in the current processing cycle.

One thing you can try to perhaps somewhat mitigate this if you haven't already is to use a Wine build with the fsync patches (which are now based on the `futex_waitv` patch set merged in Linux 5.16). Since you're on Arch, you can just build wine-tkg from this repo: https://github.com/Frogging-Family/wine-tkg-git/tree/master/wine-tkg-git Just **build** it with the default settings form `customization.cfg` (don't try the builds from the releases page, they use some potentially problematic settings). Then make sure [WINEFSYNC is enabled](https://github.com/robbert-vdh/yabridge#environment-configuration) and you should be good to go.

**Comment by nine7nine** [comment]
Thanks for the insights, Robbert. I appreciate the time you took to write this: it's very informative.

Yeah, proaudio stuff is tricky to support in Wine / xrun free. ~ to my knowledge there was only ever one company/set of developers to do that (rather successfully) and that was years ago. Their hardware/software didn't produce xruns with Kontakt, Reaktor or any of those plugins, when using MIDI program changes or loading up plugins... But they heavily modified wine and their own software host likely worked around the the aforementioned issues to do with real-time safeness. (eg: I think they had some trickery with being able to disable/enable threaded plugin windows in their host app, which requires a patch for wine).

It's interesting, pretty much all of Reaktor's instrument libraries that allow MIDI Program Changes don't xrun at all. - It really just seems to be Kontour (on my end, anyway). Even the Forms library (which doesn't allow MIDI Program Change) and it is fairly heavy, doesn't actually cause buffer underruns when changing presets (on my system, anyway).

Oh ya, I'm aware of Wine-TKG, Fsync and futex_waitv. Wine-TKG is a nice build system. super handy! However, I have my own patched and very customized builds of Wine-TKG. (and my own kernel to go along with it).

Found here: https://github.com/nine7nine/Wine-NSPA

I pull in a bunch of optimizations, out-of-tree patches (from proton, rbernon's patchwork and elsewhere) that aren't in the default wine-TKG builds. I also modify Wine's Scheduling and policies capabilities, as well. ~ I support setting nice priorities, on top of also implementing support for both Round-Robin and FIFO linux RT scheduling policies (for various types threads). this includes how they may apply to Fsync and related threading... 

it's all WIP, but for my own-use case:  playing VST instruments live (Komplete 13 + AAS and U-he suites), hosted in Kushview Element via carla-single+yabridge) -- it all works pretty well, already...  I do some lite recording in Bitwig and also some (mostly) live recording into Non-Timeline. but I have more emphasis on actual playing of instruments... That said; Yabridge is pretty great, these days! -- The only thing I wish is that it had it's own single-plugin host, like carla-single.

**Comment by robbert-vdh** [comment]
Ah didn't notice it was you, I didn't recognize the name in the GitHub notification email and I scrolled down before noticing your GitHub username. :)

Yeah if you've gone through all of those lengths already then presumably those libraries just need to perform a non-trivial amount of IO as part of those program changes. That (and the fact that program lists are almost per definition limited to factory content) is also part of the reason why modern plugin APIs like CLAP just don't have the notion of 'programs' at all (although plugins may still do whatever they want if they receive a MIDI program change message).

And yeah yabridge+carla-single is indeed the Unix-philosophy equivalent of a standalone yabridge host. :wink: That's also what I used for quick testing when working on yabridge.

**Comment by nine7nine** [comment]
Hey man! Figured you probably remembered me, after a slight clarification.

Recently, i rebased all of my code and started hacking on Wine again - I wanted an updated build + all of the futex_waitv stuff landed. It was time to do a big update... There's still some bits that I'd like to re-implement from some rather ancient patches (there are some VST threads in Wine that should actually be set as TIME_CRITICAL, but there is no easy way to do it, atm. The old method doesn't work anymore and wine's unixlib migration kind of complicated a few things; as it can't easily be set from wineserver anymore, either... but i digress. 

Well, Reaktor 6 is a bit strange, as they changed some things around - but with some instrument libraries, the reason they don't have MIDI program changes isn't because it isn't allowed/prohibited -- it's because by default they may not have Reaktor "Snapshots" set up (.ssf files) - Forms is an example of this. 

the gist is you actually have to go into "edit" mode, then go back to the 'preset browser' and create banks, manually. then you populate it with presets /snapshots - at that point, Midi Program Changes do work. So they really aren't limited to factory content at all... As an aside; Reaktor is a difficult VST to wrap one's brain around. it's very complex, but it's very flexible / powerful. -- I actually just tested this with Forms and it works fine. zero xruns when changing programs/snapshots.

you are probably right though; Kontour is likely doing something non-rt friendly. (or it simply doesn't have enough headroom...

I do wonder how much of this non-rt friendly stuff is happening in the UI / Window though? It seems like the Muse Receptor engineers went to some effort to implement how their wine VST plugin windows were being handled;

https://github.com/nine7nine/Wine-NSPA/blob/main/wine-tkg-git/wine-tkg-userpatches/0005-HACK-Fix_order_to_enable_application_window.mypatch

no consumers of this code, but i do carry/apply the patch in my builds anyway.

yabridge+carla-single is dope. given that I host most things in Kushview Element/Windows Version it works quite well. I even get Midi timecode + jack transport OOTB, which is handy. If you look at the VST-as-Standalone stuff in my Wiki, you'll also appreciate why I like it.

**Comment by robbert-vdh** [comment]
> I do wonder how much of this non-rt friendly stuff is happening in the UI / Window though? It seems like the Muse Receptor engineers went to some effort to implement how their wine VST plugin windows were being handled;

No idea! But if something needs to happen on the main/UI thread during the program change then things will start getting messy real quick. The easiest way to avoid this would be to simply not use program changes to load the different presets and to just have multiple instances of Reaktor ready to go and to switch between those (so in Bitwig you'd use the Instrument Selector set to MIDI Program Change mode). But that may obviously result in a substantial increase in memory usage.

**Comment by robbert-vdh** [comment]
Anyways, I'm closing this since I sadly can't do anything about it.

**Comment by nine7nine** [comment]
Yeah, I can avoid the UI / MIDI PC stuff to an extent, even when using Element.

more long-term, I might try to implement using that linked code / patch in a host app - I suspect there was a reason that they used msgbox with the threaded vs. non-threaded options. possibly some distinct property/behaviour of msgbox windows that was advantageous, specifically to do with plugin / application windows.

Yup, it doesn't look like Yabridge can solve this particular issue, atm. I definitely appreciate all of your help and information though. super good. thanks!

quick question: all of your wine-side window/editor code is handled here? (I'm fairly unfamiliar with your code)

https://github.com/robbert-vdh/yabridge/blob/master/src/wine-host/editor.cpp

**Comment by robbert-vdh** [comment]
> quick question: all of your wine-side window/editor code is handled here? (I'm fairly unfamiliar with your code)

Yes. Everything is there (and in the header of course), except for the Wine->X11 drag-and-drop bit, that's in `xdnd-proxy.{h,cpp}`. And depending on how you count, the main Win32 message loop is in `HostBridge::handle_events()`, that's called on an Asio timer:

https://github.com/robbert-vdh/yabridge/blob/master/src/wine-host/editor.h
https://github.com/robbert-vdh/yabridge/blob/master/src/wine-host/editor.cpp
https://github.com/robbert-vdh/yabridge/blob/master/src/wine-host/xdnd-proxy.h
https://github.com/robbert-vdh/yabridge/blob/master/src/wine-host/xdnd-proxy.cpp
https://github.com/robbert-vdh/yabridge/blob/master/src/wine-host/bridges/common.cpp#L60-L74
