### ISSUE TITLE
vst plugins stopped loading

### ISSUE THREAD

**Issue by 34fishyy** [robbert-vdh/yabridge#188]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

the issue is that my vst plugins just stopped working after I did *something*, bitwig simply can't scan the plugins anymore. I'm not really sure what I did because I was just using my PC for internet browsing past week, not doing any music stuff and just updating things from time to time.
I tried to completely reinstall wine and yabridge, still doesn't work. wineserver -k doesn't do anything neither.

### What did you expect to happen?

for plugins to load as they should

### What actually happened?

the plugins just stopped loading at all

### Operating system

Arch

### How did you install yabridge?

pacman

### yabridge version

4.0.1

### yabridgectl version

4.0.1

### Wine version

wine-7.11 (staging)

### Plugin

any

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Bitwig Studio 4.2.5

### Desktop environment or WM

KDE Plasma X11

### Debug log

this is what bitwig says when I try to load plugins, as well as I can understand, the issue is somehow related to wine not being able to host the vst.

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException:` could not read metadata: Plugin host did not respond for 20.0 seconds
stdout:
Successfully set thread realtime priority to 50
Successfully set thread realtime priority to 50
Successfully set thread realtime priority to 50
Successfully set thread realtime priority to 50
PluginHost: Reading VST 3 plugin metadata for /home/yegor/.vst3/yabridge/FabFilter/FabFilter Pro-R.vst3

stderr:

WARNING: Your locale is broken. Yabridge was kind enough to monkey patch it for you in this DAW session, but you should probably take a look at it ;)

00:48:36 [FabFilter Pro-R-457DTYip] Initializing yabridge version 4.0.1
00:48:36 [FabFilter Pro-R-457DTYip] library:       '/usr/lib/libyabridge-vst3.so'
00:48:36 [FabFilter Pro-R-457DTYip] host:          '/usr/bin/yabridge-host.exe'
00:48:36 [FabFilter Pro-R-457DTYip] plugin:        '/home/yegor/.local/share/PortWINE/PortProton/data/prefixes/DEFAULT/drive_c/Program Files/Common Files/VST3/FabFilter/FabFilter Pro-R.vst3'
00:48:36 [FabFilter Pro-R-457DTYip] plugin type:   'VST3'
00:48:36 [FabFilter Pro-R-457DTYip] realtime:      'yes'
00:48:36 [FabFilter Pro-R-457DTYip] sockets:       '/run/user/1000/yabridge-FabFilter Pro-R-457DTYip'
00:48:36 [FabFilter Pro-R-457DTYip] wine prefix:   '/home/yegor/.local/share/PortWINE/PortProton/data/prefixes/DEFAULT'
00:48:36 [FabFilter Pro-R-457DTYip] wine version:  '7.11 (Staging)'
00:48:36 [FabFilter Pro-R-457DTYip] 
00:48:36 [FabFilter Pro-R-457DTYip] config from:   '<defaults>'
00:48:36 [FabFilter Pro-R-457DTYip] hosting mode:  'individually, 64-bit'
00:48:36 [FabFilter Pro-R-457DTYip] other options: '<none>'
00:48:36 [FabFilter Pro-R-457DTYip] 
00:48:36 [FabFilter Pro-R-457DTYip] Enabled features:
00:48:36 [FabFilter Pro-R-457DTYip] - bitbridge support
00:48:36 [FabFilter Pro-R-457DTYip] - VST3 support
00:48:36 [FabFilter Pro-R-457DTYip]

and this is what yabridge.log prints out
01:01:24 [FabFilter Volcano 3-6AJSehjm] Initializing yabridge version 4.0.1
01:01:24 [FabFilter Volcano 3-6AJSehjm] library:       '/usr/lib/libyabridge-vst3.so'
01:01:24 [FabFilter Volcano 3-6AJSehjm] host:          '/usr/bin/yabridge-host.exe'
01:01:24 [FabFilter Volcano 3-6AJSehjm] plugin:        '/home/yegor/.local/share/PortWINE/PortProton/data/prefixes/DEFAULT/drive_c/Program Files/Common Files/VST3/FabFilter/FabFilter Volcano 3.vst3'
01:01:24 [FabFilter Volcano 3-6AJSehjm] plugin type:   'VST3'
01:01:24 [FabFilter Volcano 3-6AJSehjm] realtime:      'yes'
01:01:24 [FabFilter Volcano 3-6AJSehjm] sockets:       '/run/user/1000/yabridge-FabFilter Volcano 3-6AJSehjm'
01:01:24 [FabFilter Volcano 3-6AJSehjm] wine prefix:   '/home/yegor/.local/share/PortWINE/PortProton/data/prefixes/DEFAULT'
01:01:24 [FabFilter Volcano 3-6AJSehjm] wine version:  '7.11 (Staging)'
01:01:24 [FabFilter Volcano 3-6AJSehjm] 
01:01:24 [FabFilter Volcano 3-6AJSehjm] config from:   '<defaults>'
01:01:24 [FabFilter Volcano 3-6AJSehjm] hosting mode:  'individually, 64-bit'
01:01:24 [FabFilter Volcano 3-6AJSehjm] other options: '<none>'
01:01:24 [FabFilter Volcano 3-6AJSehjm] 
01:01:24 [FabFilter Volcano 3-6AJSehjm] Enabled features:
01:01:24 [FabFilter Volcano 3-6AJSehjm] - bitbridge support
01:01:24 [FabFilter Volcano 3-6AJSehjm] - VST3 support
01:01:24 [FabFilter Volcano 3-6AJSehjm] 
01:02:32 [FabFilter Pro-DS-5CNPWnpr] Initializing yabridge version 4.0.1
01:02:32 [FabFilter Pro-DS-5CNPWnpr] library:       '/usr/lib/libyabridge-vst3.so'
01:02:32 [FabFilter Pro-DS-5CNPWnpr] host:          '/usr/bin/yabridge-host.exe'
01:02:32 [FabFilter Pro-DS-5CNPWnpr] plugin:        '/home/yegor/.local/share/PortWINE/PortProton/data/prefixes/DEFAULT/drive_c/Program Files/Common Files/VST3/FabFilter/FabFilter Pro-DS.vst3'
01:02:32 [FabFilter Pro-DS-5CNPWnpr] plugin type:   'VST3'
01:02:32 [FabFilter Pro-DS-5CNPWnpr] realtime:      'yes'
01:02:32 [FabFilter Pro-DS-5CNPWnpr] sockets:       '/run/user/1000/yabridge-FabFilter Pro-DS-5CNPWnpr'
01:02:32 [FabFilter Pro-DS-5CNPWnpr] wine prefix:   '/home/yegor/.local/share/PortWINE/PortProton/data/prefixes/DEFAULT'
01:02:32 [FabFilter Pro-DS-5CNPWnpr] wine version:  '7.11 (Staging)'
01:02:32 [FabFilter Pro-DS-5CNPWnpr] 
01:02:32 [FabFilter Pro-DS-5CNPWnpr] config from:   '<defaults>'
01:02:32 [FabFilter Pro-DS-5CNPWnpr] hosting mode:  'individually, 64-bit'
01:02:32 [FabFilter Pro-DS-5CNPWnpr] other options: '<none>'
01:02:32 [FabFilter Pro-DS-5CNPWnpr] 
01:02:32 [FabFilter Pro-DS-5CNPWnpr] Enabled features:
01:02:32 [FabFilter Pro-DS-5CNPWnpr] - bitbridge support
01:02:32 [FabFilter Pro-DS-5CNPWnpr] - VST3 support
01:02:32 [FabFilter Pro-DS-5CNPWnpr] 

### Anything else?

I just wanted to make some music :(

**Comment by 34fishyy** [comment]
this just repeats after I do the command
I'm going to google on how to fix my locale now cause I've had some problems not being able to drag and drop in bitwig and now I understand that it was a locale problem
the thing is that everything worked fine until yesterday I just opened up bitwig and my plugins stopped loading at all

```
env YABRIDGE_DEBUG_LEVEL=1+editor carla-single vst3 ~/.vst3/yabridge/FabFilter/FabFilter\ Pro-DS.vst3
['/usr/lib/carla/carla-bridge-native', 'vst3', '/home/yegor/.vst3/yabridge/FabFilter/FabFilter Pro-DS.vst3', '(none)', '0']
libjack.so.0 loaded successfully!

WARNING: Your locale is broken. Yabridge was kind enough to monkey patch it for you in this DAW session, but you should probably take a look at it ;)

16:29:43 [FabFilter Pro-DS-1ENSZdgq] Initializing yabridge version 4.0.1
16:29:43 [FabFilter Pro-DS-1ENSZdgq] library:       '/usr/lib/libyabridge-vst3.so'
16:29:43 [FabFilter Pro-DS-1ENSZdgq] host:          '/usr/bin/yabridge-host.exe'
16:29:43 [FabFilter Pro-DS-1ENSZdgq] plugin:        '/home/yegor/.local/share/PortWINE/PortProton/data/prefixes/DEFAULT/drive_c/Program Files/Common Files/VST3/FabFilter/FabFilter Pro-DS.vst3'
16:29:43 [FabFilter Pro-DS-1ENSZdgq] plugin type:   'VST3'
16:29:43 [FabFilter Pro-DS-1ENSZdgq] realtime:      'yes'
16:29:43 [FabFilter Pro-DS-1ENSZdgq] sockets:       '/run/user/1000/yabridge-FabFilter Pro-DS-1ENSZdgq'
16:29:43 [FabFilter Pro-DS-1ENSZdgq] wine prefix:   '/home/yegor/.local/share/PortWINE/PortProton/data/prefixes/DEFAULT'
16:29:43 [FabFilter Pro-DS-1ENSZdgq] wine version:  '7.11 (Staging)'
16:29:43 [FabFilter Pro-DS-1ENSZdgq] 
16:29:43 [FabFilter Pro-DS-1ENSZdgq] config from:   '<defaults>'
16:29:43 [FabFilter Pro-DS-1ENSZdgq] hosting mode:  'individually, 64-bit'
16:29:43 [FabFilter Pro-DS-1ENSZdgq] other options: '<none>'
16:29:43 [FabFilter Pro-DS-1ENSZdgq] 
16:29:43 [FabFilter Pro-DS-1ENSZdgq] Enabled features:
16:29:43 [FabFilter Pro-DS-1ENSZdgq] - bitbridge support
16:29:43 [FabFilter Pro-DS-1ENSZdgq] - VST3 support
16:29:43 [FabFilter Pro-DS-1ENSZdgq] 
16:29:43 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 002c:fixme:winediag:LdrInitializeThunk wine-staging 7.11 is a testing version containing experimental patches.
16:29:43 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
16:29:45 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00bc:err:module:import_dll Library WDFLDR.SYS (which is needed by L"C:\\windows\\system32\\drivers\\vjoy.sys") not found
16:29:45 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00bc:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\vjoy": c0000142
16:29:45 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 003c:fixme:service:scmdatabase_autostart_services Auto-start service L"vjoy" failed to start: 1114
16:29:50 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 0050:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0050, blocked by 003c, retrying (60 sec)
16:29:55 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00c8:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00c8, blocked by 003c, retrying (60 sec)
16:29:55 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00ac:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00ac, blocked by 003c, retrying (60 sec)
16:29:55 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00c4:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00c4, blocked by 003c, retrying (60 sec)
16:30:55 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 0050:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0050, blocked by 003c, retrying (60 sec)
16:31:00 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00c8:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00c8, blocked by 003c, retrying (60 sec)
16:31:00 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00ac:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00ac, blocked by 003c, retrying (60 sec)
16:31:00 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00c4:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00c4, blocked by 003c, retrying (60 sec)
16:32:00 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 0050:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0050, blocked by 003c, retrying (60 sec)
16:32:05 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00c8:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00c8, blocked by 003c, retrying (60 sec)
16:32:05 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00ac:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00ac, blocked by 003c, retrying (60 sec)
16:32:05 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00c4:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00c4, blocked by 003c, retrying (60 sec)
16:33:05 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 0050:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0050, blocked by 003c, retrying (60 sec)
16:33:10 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00c8:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00c8, blocked by 003c, retrying (60 sec)
16:33:10 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00ac:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00ac, blocked by 003c, retrying (60 sec)
16:33:10 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00c4:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00c4, blocked by 003c, retrying (60 sec)
16:34:10 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 0050:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0050, blocked by 003c, retrying (60 sec)
16:34:15 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00c8:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00c8, blocked by 003c, retrying (60 sec)
16:34:15 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00ac:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00ac, blocked by 003c, retrying (60 sec)
16:34:15 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00c4:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00c4, blocked by 003c, retrying (60 sec)
16:34:43 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 0024:err:environ:run_wineboot boot event wait timed out
16:35:15 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 0050:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0050, blocked by 003c, retrying (60 sec)
16:35:20 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00c8:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00c8, blocked by 003c, retrying (60 sec)
16:35:20 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00ac:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00ac, blocked by 003c, retrying (60 sec)
16:35:20 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00c4:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00c4, blocked by 003c, retrying (60 sec)
16:36:20 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 0050:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0050, blocked by 003c, retrying (60 sec)
16:36:25 [FabFilter Pro-DS-1ENSZdgq] [Wine STDERR] 00c8:err:sync:RtlpWaitForCriticalSection section 0000000170068640 "../wine-staging/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00c8, blocked by 003c, retrying (60 sec)

```

**Comment by robbert-vdh** [comment]
That looks like there's something very broken with your Wine prefix. You installed some kernel driver called vjoy that tried to load some libraries that don't exist. If you can somehow uninstall vjoy, then you should do that. Perhaps simply nuking `vjoy.sys` would also work, but who knows what that breaks. Otherwise, renaming `~/.wine` and starting afresh of course also works.

**Comment by 34fishyy** [comment]
I figured out that vjoy is somehow connected to portproton (the thing I use to emulate windows filesystem and for launching windows stuff), works great with games but it's apparently bad for audio stuff and vsts. thank you for your help!
