### ISSUE TITLE
Modular synth ports not connecting - REAPER / Heckscaper

### ISSUE THREAD

**Issue by the-argus** [robbert-vdh/yabridge#193]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Heckscaper plugins with modular synth elements such as the [CT-0W0](https://heckscaper.com/plugins/cb/index.html) do not respond to mouse input.

### What did you expect to happen?

Clicking on the output ports should cause a cable to be connected to the mouse, and then clicking on the input port should connect the cable.

### What actually happened?

Nothing, no response from the ports on click.

### Operating system

NixOS 22.05

### How did you install yabridge?

nixpkgs

### yabridge version

4.0.2

### yabridgectl version

4.0.2

### Wine version

wine 7.0

### Plugin

CT-0W0

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Reaper 6.61

### Desktop environment or WM

Qtile on Xorg

### GPU model

Intel TigerLake-LP GT2 [Iris Xe Graphics]

### GPU drivers and kernel

Drivers: i915, Kernel: Linux evil 5.18.13 #1-NixOS SMP PREEMPT_DYNAMIC Fri Jul 22 08:21:59 UTC 2022 x86_64 GNU/Linux

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/9191373/yabridge.log)

### Anything else?

My system's configuration can be found at [my git repo](https://github.com/the-argus/nix-sys) and the part pertaining to the installation and use of yabridge can be found in [this flake](https://github.com/the-argus/audio-plugins-nix)

**Comment by robbert-vdh** [comment]
Can't help with that, that's not a yabridge issue. Try running the plugin under any other host, the same thing will happen. It's either a plugin bug or something in Wine.
