### ISSUE TITLE
several VST2 plugins failing to load; [Error while parsing string: encountered end of file]

### ISSUE THREAD

**Issue by ThePogoBro** [robbert-vdh/yabridge#196]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

After a recent update, a few VST2 plugins now fail to load upon any plugin scan on Ardour with the error message of "Error while parsing string: encountered end-of-file".

### What did you expect to happen?

for plugins to load and appear normally

### What actually happened?

plugins did not load and now do not appear in available plugin list.

### Operating system

Arch Linux

### How did you install yabridge?

AUR package

### yabridge version

4.0.2

### yabridgectl version

4.0.2

### Wine version

wine-7.15

### Plugin

Crazy Counter, DevilSpring, VREV-666, Genny-x64, Krush, LowBitMonoSyn, MT-PowerDrumKit, MeowSynth, NES VST, NESNoise, NESPulse, NESTri, SFX8, Tape Simulator, pitchproof

### Plugin type

VST2

### Plugin architecture

both 64-bit and 32-bit

### Host

Ardour 6.9-5

### Desktop environment or WM

sway

### GPU model

AMD RX 480

### GPU drivers and kernel

kernel driver, 5.19.3.zen1-1

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/9419138/yabridge.log)

**Comment by robbert-vdh** [comment]
Did you read the [patch notes](https://github.com/robbert-vdh/yabridge/releases/tag/4.0.0) or at least the TL;DR with upgrade instructions? Are you sure you ran `yabridgectl sync --prune` and that you are not loading an old yabridge .so file?

**Comment by ThePogoBro** [comment]
> Did you read the [patch notes](https://github.com/robbert-vdh/yabridge/releases/tag/4.0.0) or at least the TL;DR with upgrade instructions? Are you sure you ran `yabridgectl sync --prune` and that you are not loading an old yabridge .so file?

ah sorry, I had no idea about the new update's migration. Followed the instructions on the changelog and now it works! Thank you.
