### ISSUE TITLE
Fedora COPR disappeared

### ISSUE THREAD

**Issue by rcarmo** [robbert-vdh/yabridge#198]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I noticed today during a `dnf udpdate` that the COPR is gone:

This means that I cannot upgrade my install on Fedora 36, but also that other users on Fedora cannot perform new installs.

### What did you expect to happen?

I expected `dnf update` to work.

### What actually happened?

I got this message:

```
Copr repo for yabridge owned by patrickl                             229  B/s | 341  B     00:01    
Errors during downloading metadata for repository 'copr:copr.fedorainfracloud.org:patrickl:yabridge':
  - Status code: 404 for https://download.copr.fedorainfracloud.org/results/patrickl/yabridge/fedora-36-x86_64/repodata/repomd.xml (IP: 2600:9000:21d6:1400:4:bbc1:1840:93a1)
Error: Failed to download metadata for repo 'copr:copr.fedorainfracloud.org:patrickl:yabridge': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: copr:copr.fedorainfracloud.org:patrickl:yabridge
```

### Operating system

Fedora 36

### How did you install yabridge?

from the COPR

### yabridge version

N/A

### yabridgectl version

N/A

### Wine version

N/A

### Plugin

N/A

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

N/A

**Comment by robbert-vdh** [comment]
That COPR is not maintained by me, so I can't help you with this. You'll need to ask @plaimbock for more details.

**Comment by plaimbock** [comment]
Hi. I don't see any problems with the yabridge COPR. Can you please clear your dnf cache and try again?

# sudo dnf clean all
# sudo dnf update --refresh

**Comment by robbert-vdh** [comment]
@plaimbock The link 404s and it no longer shows up in your profile: https://copr.fedorainfracloud.org/coprs/patrickl/yabridge/

**Comment by plaimbock** [comment]
Thanks @robbert-vdh for pointing that out.
@rcarmo There was a deprecation notice on that COPR for quite a while. Have a look at this link for all the current wine-tkg and yabridge COPRs: [https://copr.fedorainfracloud.org/coprs/patrickl/wine-tkg-testing/](https://copr.fedorainfracloud.org/coprs/patrickl/wine-tkg-testing/)

**Comment by robbert-vdh** [comment]
I can only find a COPR there that builds straight from git HEAD: https://copr.fedorainfracloud.org/coprs/patrickl/yabridge-testing/

**Comment by plaimbock** [comment]
That is correct. All my Wine-related COPRs are latest release or git HEAD. An overview of my COPRs is here:
[https://copr.fedorainfracloud.org/coprs/patrickl/](https://copr.fedorainfracloud.org/coprs/patrickl/)

**Comment by robbert-vdh** [comment]
Any chance to bring back regular release builds? Otherwise I'll need to either look for a different COPR or just tell Fedora users to use the binaries from GitHub.

**Comment by plaimbock** [comment]
No problem. I just added the yabridge-stable COPR at [https://copr.fedorainfracloud.org/coprs/patrickl/yabridge-stable/](https://copr.fedorainfracloud.org/coprs/patrickl/yabridge-stable/) which tracks your releases so currently has 4.0.2.

**Comment by robbert-vdh** [comment]
Thanks, I've updated the link in the readme.

**Comment by rcarmo** [comment]
Thanks both, that should clear up the updates for me.
