### ISSUE TITLE
Is the static boost_filesystem mandatory?

### ISSUE THREAD

**Issue by KottV** [robbert-vdh/yabridge#20]
Hi!

**Problem description**
Meson setup expects the static boost_filesystem. But yabridge works fine without it.

**What did you expect to happen?**

meson setup completes without error

**What actually happened?**

`Run-time dependency Boost (missing: filesystem) found: NO `

**System information**
- Operating system: openSUSE Tumbleweed, gcc 10.1 boost 1.71
- Wine version: Wine 5.7
- Installation method: symlinks/copies
- yabridge version: 1.2.0-13-g9ecb656

But when I disable static link requirement (just delete  **static : tru**e in meson.build)  it passes and building is fine. Yabridge loads dlls and so on, I can use bridged plugins in host/DAW.

```
ldd ./libyabridge.so 
        linux-vdso.so.1 (0x00007ffe0d9bc000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f39b2e40000)
        libboost_filesystem.so.1.71.0 => /usr/lib64/libboost_filesystem.so.1.71.0 (0x00007f39b2e20000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f39b2c48000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f39b2c28000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f39b2c00000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f39b2a38000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f39b2f60000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f39b28f0000)
```
Or am I wrong?

**Comment by robbert-vdh** [comment]
It is definitely not mandatory! I just included it as a default to be able to distribute the binaries, but I could move the static linking of Boost behind a build flag since you probably wouldn't need it anyway if you're compiling from source. Would that be a reasonable default?

**Comment by KottV** [comment]
I guess so! At least not every distro has boost_filesystem-devel-static.

**Comment by robbert-vdh** [comment]
I've changed the defaults so I'll consider this to be closed. Feel free to open a new issue if you run into other compilation issues!
