### ISSUE TITLE
Loading 13 instances of Amplitube 5 VST3 or as a VST2 group brings my computer to a grinding halt

### ISSUE THREAD

**Issue by freddano** [robbert-vdh/yabridge#202]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Loading a file with a lot of instances of Amplitube 5 as VST3 or as a VST2-group will bring my computer to a grinding halt. Sometimes I can CTRL-C Reaper or Ardour6 but most of the time I will have to powercycle the machine.

Loading the same file in Reaper but with un-grouped VST2 works fine. 

### What did you expect to happen?

Reaper or Ardour to finish loading the file and the computer to be responsive. 

### What actually happened?

The computer becomes unresponsive. 

### Operating system

Manjaro

### How did you install yabridge?

AUR-git

### yabridge version

4.0.2-16-g305eaf88

### yabridgectl version

4.0.2-16

### Wine version

wine-7.17.r0.g6d46b1e1 ( TkG Staging Esync Fsync )

### Plugin

Amplitube5 

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Reaper

### Desktop environment or WM

KDE Plasma 5.xx on Xorg

### GPU model

AMD RX5700XT

### GPU drivers and kernel

Mesa on Linux 5.19

### Debug log

[Uploading yabdridge.log…]()

**Comment by freddano** [comment]
[yabdridge.log](https://github.com/robbert-vdh/yabridge/files/9552159/yabdridge.log)

**Comment by robbert-vdh** [comment]
So if your entire system hangs then you're either running out of memory or (realtime) processes are constantly spinning at 100% utilization. Did you check which one it is? Other than that blocked mutex at the very end of your debug.log there's nothing out of the ordinary in there.

**Comment by freddano** [comment]
> So if your entire system hangs then you're either running out of memory or (realtime) processes are constantly spinning at 100% utilization. Did you check which one it is? Other than that blocked mutex at the very end of your debug.log there's nothing out of the ordinary in there.

I haven't checked which one it is. I'd be happy to, though. I just don't know how to do that, the logs shows nothing really strange, apart from Amplitube5 complaining about a thread being locked waiting for another thread. I doubt it's a memory issue, though. The exact same file works flawlessly in both Windows and MacOS, on the same computer. 

So, I'd be glad to help debugging, is there something special you think I should try first? 

Best regards,
Fredrik

**Comment by robbert-vdh** [comment]
Keep two instances of htop or some other system activity viewer open. Have one sorted by CPU usage, and the other sorted by memory usage. And make sure both show threads and custom thread names. If the entire system is hanging then either of those will show excessive usage that starves out the rest of the system.

For the record, it seems much more logical that the problem is that two Amplitube instances that are initializing at the same time end up waiting on each other to do something, but that would not cause the entire computer to lock up. That would just cause your DAW to get stuck. But with the 15 instances in your log it's completely impossible to figure that out just from reading the log. If you can get the same thing to happen with only two instances then that would make debugging a lot simpler.

**Comment by freddano** [comment]
Thank you for your swift reply. I will try and see if I can make the same thing happen by just loading two sessions of Amplitube. (I forgot that I use Amplitube on two more tracks, so you're absolutely right. There are 15 instances of Amplitube5).

**Comment by freddano** [comment]
Ok, so loading six instances of Amplitube 5 seems to be the sweet spot. 
Just before it becomes unresponsive, the output from Wine and yabridge is "Amplitube 5 0230:fixme:sync:SetWaitableTimerEx (an address) semi-stub

One instance of yahost-bridge.exe spikes one CPU at 99.5% and then the computer becomes unresponsive. The screen doesn't update or updates very slowly, no keyboard or mouse-inputs. SSH i
[yabdridge-six-instances.log](https://github.com/robbert-vdh/yabridge/files/9560477/yabdridge-six-instances.log)
n to the machine works and reaper can be killed.

**Comment by freddano** [comment]
Sorry - A new log file with just the amplitube-plugins. 
[yabdridge-six-instances-new.log](https://github.com/robbert-vdh/yabridge/files/9560496/yabdridge-six-instances-new.log)

**Comment by robbert-vdh** [comment]
Can you check the name of the thread with the high CPU usage? In `htop` you can toggle threads with the `H` key, and you can enable thread names with `F2` -> Display options -> Show custom thread names. Is it a named thread (from yabridge), the main thread (will just be Windows file path starting with `Z:\`), or a random thread created by the plugin? If you temporarily edit `/usr/bin/yabridge-host.exe`  and add a new line containing `ulimit -r 0` just above the `exec "$WINELOADER" "$apppath" "$@"` line, does the system still lock up (performance will be significantly worse if you do this, but if the offending thread was a plugin thread then this could be related).

**Comment by robbert-vdh** [comment]
Oh and just to confirm, you didn't happen to set the `STAGING_RT_PRIORITY_SERVER` or `STAGING_RT_PRIORITY_BASE` environment variables, did you? Those could definitely cause something like this to happen.

**Comment by freddano** [comment]
Ok, so editing the /usr/bin/yabridge-host.exe keeps the system running nicely. I have Reaper running in the background editing this :) 
With ulimit -r 0 even that nasty file with 15 instances of Amplitube loads as it should. 

No, I have no STAGING_RT_PRIORITY_SERVER or STAGING_RT_PRIORITY_BASE variables set. 

I will remove the ulimit -r 0 line now and check the thread name that spikes the CPU.

**Comment by freddano** [comment]
The process spiking the CPU at 1598% (I was mislead earlier by the screen not updating) is called Z:\usr\bin\yabridge-host.exe (I think it was).

**Comment by robbert-vdh** [comment]
Oh yeah the main thread there will show the CPU usage for the entire process, so that number is not just the main thread CPU usage. You'll need to check the PRI column (which may be hidden by default) for negative numbers. Those are realtime threads. You'll see a couple `audio-N` threads that are processing audio. Are there any other realtime threads with high CPU usage among them? Those would be the offending threads here. 

Another possibility is that your system simply can't keep up with the actual audio processing, and your system's simply becoming unresponsive from all of those 16 realtime audio threads trying to keep up. If you go to REAPER's Audio -> Buffering settings, disable auto-detection of the number of processing threads, and set both the number of audio processing threads and the number of CPUs for live-FX multiprocessing to 7, does that also prevent the system from locking up?

**Comment by freddano** [comment]
The system keeps up in both Windows 11 and in MacOS on the same machine with the exact same file. And the exact same file, only with the VST3 version of Amplitube5 switched to the VST2 version of Amplitube5 runs fine, in RT with full duplex. 
However, if I put the VST2 version in a group, the same thing happens - the system becomes unresponsive. 
 
Around 18-19 realtime-threads show up with high usage in htop. (Around 90 % each).

And it's just on load-time. If I load the file with all plugins off-line and bring them online one by one, the system keeps up just fine under REAPER in Linux with yabridge as well. Realtime processing, with full duplex.

Changing the suggested settings in REAPER changes nothing, still lock-ups.  
Here are my processor specs (only parts of the last core): 

processor       : 15
vendor_id       : GenuineIntel
cpu family      : 6
model           : 165
model name      : Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
stepping        : 5
microcode       : 0xec
cpu MHz         : 3800.000

**Comment by freddano** [comment]
With the file loaded, after the effects were brought online one by one, I have six -40 audio-N threads using around 20 percent CPU each. The main thread, Z:\usr\bin\yabridge-host.exe uses around 135 percent CPU. Memory utilization is 7.2G of 31.3G, with each yabridge-host.exe using around 12 percent each.

**Comment by freddano** [comment]
With the file loaded, after the effects were brought online one by one, I have six -40 audio-N threads using around 20 percent CPU each. 
The main thread, Z:\usr\bin\yabridge-host.exe uses around 135 percent CPU. Memory utilization is 7.2G of 31.3G, with each yabridge-host.exe using around 12 percent each.

**Comment by freddano** [comment]
I guess you can close this issue now. If I want to use a project heavy with Amplitube5, I can simply use the non-grouped VST2 version of the plugin. 

I sincerly doubt that it's a question of my machine not being able to keep up, though. When it crashes, it does so just after the loading is complete. I created a "Crashtest"-file, and it behaves the same way with six instances loaded (VST3 or VST2 in a group) as a file with 16 instances loaded. If it was a question of the machine not being able to keep up, shouldn't it crash after six instances are loaded, even in the 16-instances file? And also under Windows when the exact same file is loaded? (Or macOS for that matter)

Anyway, what the problem is seems to be very difficult to debug and pinpoint, and I have found a workaround. 

I love this project and I have donated to it in the past, and I will continue to do so in the future. Keep up your awesome work and the best of regards from me!

**Comment by freddano** [comment]
Ardour6 behaves the same way. I haven't tried Bitwig.

What's weird though, is that both my crashtest.rpp, which contains 6 instances of Amplitube5 and the "original offender", which contains 16 instances of Amplitube5 seems to complete loading all of the plugins and only then freeze up the computer. So, it doesn't seem to matter if it's six or sixteen instances, as long as the magical threshold is reached. 

This strange behavior is what lead me to believe it has something to do with the inter-plugin communication. Because, like I said, it does the same thing with the VST2 version grouped together. But the ungrouped version of the file loading sixteen instances of VST2 Amplitube5 works just as expected. And, consumes about 10-12 percent CPU in all, tracking and recording in full duplex. Which, as I understand it, really should be more taxing on the computers resources than grouped VST2's or VST3's. 

Anyway - I'd be happy to try anything that might help you hone in on the issue. But like I said before - I have found a workaround, which is to use the VST2 version of Amplitube5.

**Comment by robbert-vdh** [comment]
Yeah I guess it must be a either Wine bug or a Wine+Amplitube interoperability bug. It's just...odd.

**Comment by freddano** [comment]
Sorry, I didn't answer your question before. Yes, it does seem to be Amplitube5 that's causing trouble. Seven tracks with Blue Cats Chorus VST3 and their Freeamp VST3 plugin on them loaded right up. 

The same with IK Multimedias MixBox VST3 Plugin. Loaded straight up, so it seems to be something weird going on with the VST3 version of Amplitube5. 

Cheers, 
Fredrik

**Comment by freddano** [comment]
Well, I no longer think this is a yabridge-bug but a wine-bug. I decided to try running Reaper (x64) installed in the same prefix as yabridge, and what do you know? Reaper hangs, at the same place as Reaper native does. The difference being, I can still use the computer. (It's sitting in the background as I'm writing this.)

In the console where I started Reaper, I get this message, over and over:

454:err:sync:RtlpWaitForCriticalSection section 000000017006C640 "../wine-mirror-git/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0454, blocked by 0268, retrying (60 sec)
04dc:err:sync:RtlpWaitForCriticalSection section 000000017006C640 "../wine-mirror-git/dlls/ntdll/loader.c: loader_section" wait timed out in thread 04dc, blocked by 0268, retrying (60 sec)
0454:err:sync:RtlpWaitForCriticalSection section 000000017006C640 "../wine-mirror-git/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0454, blocked by 0268, retrying (60 sec)
04dc:err:sync:RtlpWaitForCriticalSection section 000000017006C640 "../wine-mirror-git/dlls/ntdll/loader.c: loader_section" wait timed out in thread 04dc, blocked by 0268, retrying (60 sec)
0454:err:sync:RtlpWaitForCriticalSection section 000000017006C640 "../wine-mirror-git/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0454, blocked by 0268, retrying (60 sec)
04dc:err:sync:RtlpWaitForCriticalSection section 000000017006C640 "../wine-mirror-git/dlls/ntdll/loader.c: loader_section" wait timed out in thread 04dc, blocked by 0268, retrying (60 sec)

**Comment by robbert-vdh** [comment]
Yeah running Windows REAPER under Wine won't use realtime scheduling. So realtime performance will be pretty bad, but in return it also can't starve the system from CPU time (which is of course only an issue when things are misbehaving like this). But I'm glad that at least confirms my suspicion that it has to be a Wine or Amplitube thing, because otherwise it just doesn't make any sense.
