### ISSUE TITLE
Loopcloud Drum and Play doesn't work with disable_pipes true

### ISSUE THREAD

**Issue by Tabinol** [robbert-vdh/yabridge#205]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Loopcloud Drum and Play VST3 doesn't work. For Loopcloud Drum:

Pop up: "Your installation of Loopcloud Drum got corrupted. Restarting your DAW should fix this. If d'oesn't help, try to re-install"

### What did you expect to happen?

Open Loopcloud drum

### What actually happened?

Just the error popup.

### Operating system

Fedora 36

### How did you install yabridge?

From binaries in GitHub

### yabridge version

4.0.2

### yabridgectl version

4.0.2

### Wine version

wine-7.18 (Staging)

### Plugin

Loopcloud Drum

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Ardour 6.9.0

### Desktop environment or WM

XFCE4 on Xorg

### GPU model

AMD Radeon RX480

### GPU drivers and kernel

AMDGPU 22.0.0-1 on Linux 5.19.14-200.fc36.x86_64

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/9749656/yabridge.log)

### Anything else?

I have also:

~/.vst3/yabridge/yabridge.toml 
```
["LoopCloud*"]
disable_pipes = true

```

Probably I'm missing something?

Thank you for your help.

**Comment by robbert-vdh** [comment]
You haven't set the option correctly:

> ```
> 18:20:38 [Loopcloud Drum-BGILcqst] config from:   '<defaults>'
> 18:20:38 [Loopcloud Drum-BGILcqst] hosting mode:  'individually, 64-bit'
> 18:20:38 [Loopcloud Drum-BGILcqst] other options: '<none>'
> ```

Check using `less ~/.vst3/yabridge/yabridge.toml` that the config file indeed exists, and then verify with `ls ~/.vst3/yabridge/LoopCloud*` that those loopcloud plugins are in the correct location (e.g. that you didn't add the entire `Common Files` directory or something to yabridge).

**Comment by Tabinol** [comment]
Working! Thank you.

```
$ ls ~/.vst3/yabridge/
 FAT.vst3  'Loopcloud Drum.vst3'  'Loopcloud Play.vst3'   Loopcloud.vst3   yabridge.toml
$ 
```
On ~/.vst3/yabridge/yabridge.toml
```
["Loopcloud*"]
disable_pipes = true
```
Not `["LoopCloud*"]`

**Comment by robbert-vdh** [comment]
Awesome!
