### ISSUE TITLE
yabridge, Mixbus, BreakTweaker

### ISSUE THREAD

**Issue by Pre24** [robbert-vdh/yabridge#207]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

yabridge crashes in Mixbus 8 with iZotope Breaktweaker 

### What did you expect to happen?

Peaceful coexistence and cooperation

### What actually happened?

Program Error. 

The program yabridge-host.exe has encountered a serious problem and needs to close. We are sorry for the inconvenience.

### Operating system

Manjaro

### How did you install yabridge?

Official Repositories (multilib)

### yabridge version

4.0.2-1

### yabridgectl version

4.0.2-1

### Wine version

7.18 (staging)

### Plugin

iZotope BreakTweaker

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Mixbus 8.1.378

### Debug log

Unhandled exception: page fault on read access to 0x0000000000000000 in 64-bit code (0x000001700298f0).
Register dump:
 rip:00000001700298f0 rsp:00000000039bf8d0 rbp:0000000000000000 eflags:00010206 (  R- --  I   - -P- )
 rax:0000000000000028 rbx:00000000002b3d20 rcx:00000000002300a0 rdx:fffffffffffffff0
 rsi:0000000000230000 rdi:0000000000230000  r8:0000000000000000  r9:0000000000000000 r10:00000000086c0001
 r11:00000000086c0040 r12:00000000002b3d18 r13:000000017007cc80 r14:00000000039bf9d0 r15:00000000002b3f28
Stack dump:
0x000000039bf8d0:  00000000002c8020 000000017005dacd
0x000000039bf8e0:  00000000039bf7c0 000000017006b640
0x000000039bf8f0:  000000017006b4d0 00000000039bfb00
0x000000039bf900:  00000000039bfa48 000000017005fa66
0x000000039bf910:  00000000002b3f18 00000000002b3f18
0x000000039bf920:  0000000170031dc3 0000000000000000
0x000000039bf930:  00000000002b3f00 00000000002b3f28
0x000000039bf940:  00000000002b3d20 00000000002b3f00
0x000000039bf950:  00000000002b3f28 000000017007c520
0x000000039bf960:  00000000039bf9d0 00000001700626fd
0x000000039bf970:  0000000000000000 0000000000000000
0x000000039bf980:  0000000000000000 0000000000000000
Backtrace:
=>0 0x000001700298f0 in ntdll (+0x298f0) (0000000000000000)
  1 0x000001700626fd in ntdll (+0x626fd) (0x0000017007c520)
  2 0x0000007b627c99 in kernel32 (+0x27c99) (0000000000000000)
  3 0x0000017005e128 in ntdll (+0x5e128) (0000000000000000)
0x000001700298f0 ntdll+0x298f0: movq	0x00000000000010(%rdx),%rax
Modules:
Module	Address					Debug info	Name (131 modules)
PE	0000000001d00000-0000000003483000	Deferred        izbreaktweaker
ELF	000000007a800000-000000007aa16000	Deferred        opengl32<elf>
  \-PE	000000007a850000-000000007aa16000	\               opengl32
PE	000000007b000000-000000007b28f000	Deferred        kernelbase
PE	000000007b600000-000000007b65b000	Export          kernel32
ELF	000000007d000000-000000007d005000	Deferred        <wine-loader>
PE	0000000170000000-00000001700a2000	Export          ntdll
PE	0000000180000000-00000001802de000	Deferred        izotope breaktweaker
PE	00000001c4ee0000-00000001c4fb8000	Deferred        winspool
PE	00000001c69e0000-00000001c731c000	Deferred        shell32
PE	00000001c8db0000-00000001c8e47000	Deferred        msvcrt
PE	00000001dd3f0000-00000001dd4bc000	Deferred        crypt32
PE	00000001ec2b0000-00000001ec2d7000	Deferred        ws2_32
PE	000000021a7e0000-000000021a855000	Deferred        setupapi
PE	000000021ff70000-00000002201d0000	Deferred        wined3d
PE	0000000231ae0000-0000000231b62000	Deferred        rpcrt4
PE	000000023d820000-000000023d9cb000	Deferred        user32
PE	0000000243540000-00000002435c3000	Deferred        gdiplus
PE	000000024f470000-000000024f48f000	Deferred        mpr
PE	00000002522e0000-0000000252324000	Deferred        oleacc
PE	000000026b4c0000-000000026b53e000	Deferred        gdi32
PE	00000002739c0000-0000000273af2000	Deferred        oleaut32
PE	000000027f7f0000-000000027f87f000	Deferred        winex11
PE	00000002967b0000-00000002967e4000	Deferred        d3d9
PE	0000000297900000-0000000297912000	Deferred        aclui
PE	00000002bb750000-00000002bb88f000	Deferred        comctl32
PE	00000002d4d40000-00000002d4d57000	Deferred        bcrypt
PE	00000002e3540000-00000002e3591000	Deferred        shlwapi
PE	00000002e8f10000-00000002e902a000	Deferred        ole32
PE	00000002f1fa0000-00000002f1fae000	Deferred        version
PE	00000002f7230000-00000002f7265000	Deferred        uxtheme
PE	00000003126f0000-0000000312709000	Deferred        shcore
PE	000000031f800000-000000031f8fb000	Deferred        comdlg32
PE	0000000327020000-0000000327073000	Deferred        combase
PE	000000032a700000-000000032a729000	Deferred        sechost
PE	0000000330260000-000000033029f000	Deferred        advapi32
PE	0000000375610000-0000000375649000	Deferred        win32u
PE	00000003a0440000-00000003a04c1000	Deferred        wininet
PE	00000003af670000-00000003af72f000	Deferred        ucrtbase
PE	00000003afd00000-00000003afd18000	Deferred        imm32
PE	00000003be590000-00000003be604000	Deferred        dbghelp
ELF	00007fb5ec4b4000-00007fb5edeab000	Deferred        crocus_dri.so
ELF	00007fb5ee6ac000-00007fb5f5768000	Deferred        libllvm-14.so
ELF	00007fb5f5768000-00007fb5f5e43000	Deferred        libvulkan_radeon.so
ELF	00007fb5f5e43000-00007fb5f668d000	Deferred        libvulkan_intel.so
ELF	00007fb5f7c5e000-00007fb5f7c6c000	Deferred        libdrm_radeon.so.1
ELF	00007fb5f7c6c000-00007fb5f7c7d000	Deferred        libsensors.so.5
ELF	00007fb5f7c7d000-00007fb5f7c9b000	Deferred        libxcb-glx.so.0
ELF	00007fb5f7c9b000-00007fb5f7cd5000	Deferred        libglapi.so.0
ELF	00007fb5f7cd5000-00007fb5f7d4f000	Deferred        libglx_mesa.so.0
ELF	00007fb5f7d4f000-00007fb5f7d81000	Deferred        libglx.so.0
ELF	00007fb5f7d81000-00007fb5f7e39000	Deferred        libgldispatch.so.0
ELF	00007fb5f7e39000-00007fb5f7ebf000	Deferred        libgl.so.1
ELF	00007fb624007000-00007fb62407b000	Deferred        libncursesw.so.6
ELF	00007fb62407b000-00007fb6240b6000	Deferred        libedit.so.0
ELF	00007fb6240b6000-00007fb6240d1000	Deferred        libelf.so.1
ELF	00007fb6240d1000-00007fb6240fa000	Deferred        libudev.so.1
ELF	00007fb6240fa000-00007fb624125000	Deferred        libexpat.so.1
ELF	00007fb624142000-00007fb62414c000	Deferred        libdrm_nouveau.so.2
ELF	00007fb62414c000-00007fb624156000	Deferred        libxcb-xfixes.so.0
ELF	00007fb624156000-00007fb624162000	Deferred        libdrm_amdgpu.so.1
ELF	00007fb624162000-00007fb6241df000	Deferred        libvulkan.so.1
ELF	00007fb6242b6000-00007fb6242dc000	Deferred        libgpg-error.so.0
ELF	00007fb6242dc000-00007fb6242fe000	Deferred        liblz4.so.1
ELF	00007fb6242fe000-00007fb624447000	Deferred        libgcrypt.so.20
ELF	00007fb624447000-00007fb624511000	Deferred        libsystemd.so.0
ELF	00007fb624511000-00007fb6245b4000	Deferred        libgmp.so.10
ELF	00007fb6245b4000-00007fb6245fd000	Deferred        libhogweed.so.6
ELF	00007fb6245fd000-00007fb624651000	Deferred        libnettle.so.8
ELF	00007fb624651000-00007fb6247fd000	Deferred        libunistring.so.2
ELF	00007fb6247fd000-00007fb624a00000	Deferred        libgnutls.so.30
ELF	00007fb624a00000-00007fb624c05000	Deferred        libuuid.so.1
ELF	00007fb624c05000-00007fb624c18000	Deferred        libxcb-randr.so.0
ELF	00007fb624c18000-00007fb624c24000	Deferred        libcap.so.2
ELF	00007fb624c24000-00007fb624ccd000	Deferred        libzstd.so.1
ELF	00007fb624ccd000-00007fb624e00000	Deferred        libp11-kit.so.0
ELF	00007fb624e00000-00007fb6251b2000	Deferred        libxml2.so.2
ELF	00007fb6251b4000-00007fb6251bb000	Deferred        libxcb-dri2.so.0
ELF	00007fb6251bb000-00007fb6251de000	Deferred        libbrotlicommon.so.1
ELF	00007fb6251de000-00007fb625200000	Deferred        libidn2.so.0
ELF	00007fb625200000-00007fb625455000	Deferred        libfontconfig.so.1
ELF	00007fb625455000-00007fb62546c000	Deferred        libtasn1.so.6
ELF	00007fb62546c000-00007fb625511000	Deferred        libbrotlienc.so.1
ELF	00007fb625511000-00007fb625562000	Deferred        libdbus-1.so.3
ELF	00007fb625562000-00007fb625600000	Deferred        libcups.so.2
ELF	00007fb625600000-00007fb62581a000	Deferred        libz.so.1
ELF	00007fb62581e000-00007fb62582c000	Deferred        libbrotlidec.so.1
ELF	00007fb62582c000-00007fb625840000	Deferred        libavahi-client.so.3
ELF	00007fb625842000-00007fb625847000	Deferred        libxshmfence.so.1
ELF	00007fb625847000-00007fb62584c000	Deferred        libxcb-shm.so.0
ELF	00007fb62584c000-00007fb62585e000	Deferred        libwayland-client.so.0
ELF	00007fb62585e000-00007fb625874000	Deferred        libdrm.so.2
ELF	00007fb625890000-00007fb62589a000	Deferred        libxcb-sync.so.1
ELF	00007fb6258bd000-00007fb625a00000	Deferred        libx11.so.6
ELF	00007fb625a00000-00007fb625c41000	Deferred        libpng16.so.16
ELF	00007fb625c42000-00007fb625c4d000	Deferred        libffi.so.8
ELF	00007fb625c4f000-00007fb625c54000	Deferred        libxcb-present.so.0
ELF	00007fb625c54000-00007fb625c59000	Deferred        libx11-xcb.so.1
ELF	00007fb625c59000-00007fb625c60000	Deferred        libxcb-dri3.so.0
ELF	00007fb625c70000-00007fb625d02000	Deferred        winex11.so
ELF	00007fb625e00000-00007fb6260b4000	Deferred        libfreetype.so.6
ELF	00007fb6260b7000-00007fb6260c5000	Deferred        libavahi-common.so.3
ELF	00007fb6260c5000-00007fb6260ce000	Deferred        libxfixes.so.3
ELF	00007fb6260ce000-00007fb6260da000	Deferred        libxcursor.so.1
ELF	00007fb6260da000-00007fb6260ee000	Deferred        libxi.so.6
ELF	00007fb6260ee000-00007fb6260f3000	Deferred        libxcomposite.so.1
ELF	00007fb6260f3000-00007fb6262ab000	Deferred        win32u.so
ELF	00007fb6268e2000-00007fb626bd1000	Deferred        yabridge-host<elf>
  \-PE	00007fb626910000-00007fb626bd1000	\               yabridge-host
ELF	00007fb626bd1000-00007fb626d47000	Dwarf           libwine.so.1
ELF	00007fb627400000-00007fb62762f000	Deferred        liblzma.so.5
ELF	00007fb627632000-00007fb62763f000	Deferred        libxrandr.so.2
ELF	00007fb62763f000-00007fb62764c000	Deferred        libxrender.so.1
ELF	00007fb62764c000-00007fb627653000	Deferred        libxxf86vm.so.1
ELF	00007fb627653000-00007fb627658000	Deferred        libxinerama.so.1
ELF	00007fb627658000-00007fb62766d000	Deferred        libxext.so.6
ELF	00007fb627671000-00007fb627677000	Deferred        ws2_32.so
ELF	00007fb627677000-00007fb627682000	Deferred        bcrypt.so
ELF	00007fb627682000-00007fb627688000	Deferred        crypt32.so
ELF	00007fb627688000-00007fb62768e000	Deferred        winspool.so
ELF	00007fb6276c6000-00007fb6276cb000	Deferred        libdl.so.2
ELF	00007fb6276cb000-00007fb6276d3000	Deferred        libxdmcp.so.6
ELF	00007fb6276d3000-00007fb6276d8000	Deferred        libxau.so.6
ELF	00007fb6276d8000-00007fb6276f8000	Deferred        libgcc_s.so.1
ELF	00007fb6276f8000-00007fb627723000	Deferred        libxcb.so.1
ELF	00007fb627723000-00007fb627728000	Deferred        libpthread.so.0
ELF	00007fb627728000-00007fb627810000	Deferred        libm.so.6
ELF	00007fb627810000-00007fb62782a000	Deferred        libunwind.so.8
ELF	00007fb62782a000-00007fb627906000	Deferred        ntdll.so
ELF	00007fb627909000-00007fb627af0000	Deferred        libc.so.6
ELF	00007fb627b15000-00007fb627b4a000	Deferred        ld-linux-x86-64.so.2
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 start.exe
	00000024    0     
00000038 services.exe
	["C:\windows\system32\services.exe"]
	0000003c    0     
	00000040    0     
	0000004c    0     
	00000098    0     
	000000bc    0     
	000000d4    0     
	00000100    0     
00000044 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000048    0     
	00000054    0     
	00000058    0     
	0000005c    0     
	00000060    0     
	00000064    0     
	000000e0    0     
00000090 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000094    0     
	0000009c    0     
	000000a0    0     
	000000a4    0     
	000000a8    0     
	000000ac    0     
	000000b0    0     
000000b4 plugplay.exe
	[C:\windows\system32\plugplay.exe]
	000000b8    0     
	000000c0    0     
	000000c4    0     
	000000c8    0     
000000cc svchost.exe
	[C:\windows\system32\svchost.exe -k LocalServiceNetworkRestricted]
	000000d0    0     
	000000d8    0     
	000000dc    0     
000000e4 explorer.exe
	["C:\windows\system32\explorer.exe" /desktop]
	000000e8    0     
	000000ec    0     
	000000f0    0     
000000f8 rpcss.exe
	[C:\windows\system32\rpcss.exe]
	000000fc    0     
	00000104    0     
	00000108    0     
	0000010c    0     
	00000110    0     
	00000114    0     
	0000081c    0     
00000124 (D) Z:\usr\bin\yabridge-host.exe
	["Z:\usr\bin\yabridge-host.exe.so" VST2 "/home/****/.wine/drive_c/Program Files/VSTPlugins/iZotope BreakTweaker.dll" "/run/user/1000/yabridge-iZotope BreakTweaker-0CDFSdel" 9387]
	0000012c    0     
	00000130    0     
	00000134    0 <== 
	00000138    0     
	0000013c   15     
	00000140    0     
	00000144    0     
	00000148    0     
	0000014c    0     
	00000150    0     
	00000328    0     
	00000468    0     
	00000558    0     
	00000560    0     
	0000056c    0     
	00000078    0     
	000000f4    0     
	00000164    0     
	00000170    0     
	00000414    0     
	00000418    0     
	00000440    0     
	00000458    0     
	00000734    0     
	00000738    0     
	00000808    0     
0000080c explorer.exe
	["C:\windows\system32\explorer.exe" /desktop]
	00000810    0     
	00000814    0     
	00000818    0     
System information:
    Wine build: wine-7.18 (Staging)
    Platform: x86_64
    Version: Windows 7
    Host system: Linux
    Host version: 5.19.0-3-rt10-MANJARO

### Anything else?

I've been trying hard to make Mixbus and BreakTweaker play nice in Linux, all three being my essential software choices. Admittedly it's a stretch, as iZotope plugins don't seem to be Linux-friendly. I had to resort to a not quite legit copy of BreakTweaker, but I do own a license and I paid more than $10, which was the last discounted price for this brilliant abandonware. It does work for awhile in Mixbus, quite well actually, but eventually yabridge crashes and I get the "Program Error" warning.

The above file is not a debug log. It's a backtrace file from the Program Error. Unfortunately I haven't been able to launch Mixbus from a terminal.

**Comment by robbert-vdh** [comment]
The plugin should probably work fine in demo mode (haven't tried Breaktweaker, but all other iZotope plugins do). But you won't be able to activate it anyways due to [Wine bug #52330](https://bugs.winehq.org/show_bug.cgi?id=52330) so trying to fix this is moot. Regardless, whatever's going on is a general Wine issue unrelated to yabridge itself.
