### ISSUE TITLE
Ardour 7 support

### ISSUE THREAD

**Issue by SavageLogic** [robbert-vdh/yabridge#208]
### Feature description

Ardour 7 (flatpak) doesn't seem to be working with yabridge. I am getting this error:

`[Info]: Scanning: /home/myuser/Documents/Music/vsts/Theremin.so
19:50:43 [error] 
19:50:43 [error] Error during initialization:
19:50:43 [error] Could not locate 'yabridge-host-32.exe'
19:50:43 [error] 
[ERROR]: ** ERROR ** VSTFX : Theremin could not be instantiated :(
`

Or this error:

`01:55:40 [error] Could not find 'libyabridge-vst3.so'`

Downgrading to yabridge < 4.x made no difference.
Using Flatseal, I gave Ardour all the file system permissions I could find but that made no difference as well.

Ardour 6 works with no issues. 

*Edit Just realized the logs I had showed the vst path from when I downgraded yabridge to < 4.x but the error persists even using ~/.vst

**Comment by robbert-vdh** [comment]
Flatpak Ardour is not supported by Ardour's developers and like all other Flatpak DAWs, you're going to have issues using third party plugins. Yabridge also won't work. Try using a regular non-Flatpak Ardour build instead.
