### ISSUE TITLE
Aborted (core dumped) on 4.0.2

### ISSUE THREAD

**Issue by carlthome** [robbert-vdh/yabridge#209]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

On Ubuntu 22.10 with winehq-staging, I'm unable to load a synced VST inside REAPER. The same dll has worked on past versions of yabridge (IIRC 1.* versions).

### What did you expect to happen?

Windows compiled VST plugins running inside REAPER.

### What actually happened?

REAPER crashes upon loading a VST.

### Operating system

Ubuntu 22.10

### How did you install yabridge?

Latest GitHub Releases release downloaded to ~/.local/share/yabridge

### yabridge version

4.0.2

### yabridgectl version

4.0.2

### Wine version

wine-7.19 (Staging)

### Plugin

MDA Ambience

### Plugin type

VST2

### Plugin architecture

32-bit

### Host

REAPER 6.69

### Debug log

```
13:55:29 [mdaAmbience-7CWknotw] Initializing yabridge version 3.8.1
13:55:29 [mdaAmbience-7CWknotw] host:          '/home/carl/.local/share/yabridge/yabridge-host-32.exe'
13:55:29 [mdaAmbience-7CWknotw] plugin:        '/home/carl/Dropbox/VSTs/MDA/mdaAmbience.dll'
13:55:29 [mdaAmbience-7CWknotw] plugin type:   'VST2'
13:55:29 [mdaAmbience-7CWknotw] realtime:      'no'
13:55:29 [mdaAmbience-7CWknotw] sockets:       '/run/user/1000/yabridge-mdaAmbience-7CWknotw'
13:55:29 [mdaAmbience-7CWknotw] wine prefix:   '<default>'
13:55:29 [mdaAmbience-7CWknotw] wine version:  '7.19 (Staging)'
13:55:29 [mdaAmbience-7CWknotw] 
13:55:29 [mdaAmbience-7CWknotw] config from:   '<defaults>'
13:55:29 [mdaAmbience-7CWknotw] hosting mode:  'individually, 32-bit'
13:55:29 [mdaAmbience-7CWknotw] other options: '<none>'
13:55:29 [mdaAmbience-7CWknotw] 
13:55:29 [mdaAmbience-7CWknotw] Enabled features:
13:55:29 [mdaAmbience-7CWknotw] - bitbridge support
13:55:29 [mdaAmbience-7CWknotw] - VST3 support
13:55:29 [mdaAmbience-7CWknotw] 
13:55:29 [mdaAmbience-7CWknotw] [Wine STDERR] 002c:fixme:winediag:LdrInitializeThunk wine-staging 7.19 is a testing version containing experimental patches.
13:55:29 [mdaAmbience-7CWknotw] [Wine STDERR] 002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
13:55:29 [mdaAmbience-7CWknotw] [Wine STDERR] 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
13:55:29 [mdaAmbience-7CWknotw] [Wine STDERR] 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
13:55:29 [mdaAmbience-7CWknotw] [Wine STDERR] 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
13:55:29 [mdaAmbience-7CWknotw] [Wine STDERR] 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
13:55:31 [mdaAmbience-7CWknotw] [Wine STDERR] Initializing yabridge host version 4.0.2 (32-bit compatibility mode)
13:55:31 [mdaAmbience-7CWknotw] [Wine STDERR] Preparing to load VST2 plugin at '/home/carl/Dropbox/VSTs/MDA/mdaAmbience.dll'
13:55:31 [mdaAmbience-7CWknotw] [Wine STDERR] Error while initializing the Wine plugin host:
13:55:31 [mdaAmbience-7CWknotw] [Wine STDERR] connect: No such file or directory
13:55:31 [mdaAmbience-7CWknotw] The Wine host process has exited unexpectedly. Check the output above for more information.
```

**Comment by robbert-vdh** [comment]
You're using an old yabridge 3.8.1 plugin. That won't work with your yabridge 4.0.2 installation. `yabridgectl sync` should have prompted you to remove it as mentioned in the migration instructions: https://github.com/robbert-vdh/yabridge/releases/tag/4.0.0

**Comment by carlthome** [comment]
Thanks for the quick reply! :partying_face: 

For anyone else reading this, I had some sloppy symlinking. Next to the original plugin DLLs I also had *.so files created by yabridge from a past version.

I did `rm -rf ~/.vst ~/.wine ~/.local/share/yabridge` before downloading the latest release back into `~/.local/share`. No other WINEPREFIX set.

However, the *.so files still lingered around in my Dropbox so removing them and re-running `yabridgectl sync` again did the trick! Thanks @robbert-vdh!
