### ISSUE TITLE
"could not find libyabridge-vst2.so"

### ISSUE THREAD

**Issue by GitCrush** [robbert-vdh/yabridge#211]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

After reinstallation of Yabridge and wine-tkg-testing on Fedora 36, I am running into the issue that I receive system erro "could not find libyabridge-vst2.so" when my DAW (Bitwig 4.2.2) is trying to load the synced plugins from `~/.vst/yabridge`. 

After installation I found the shared object files located at 
`/usr/lib64/`

I manually copied them over to the default path 
`/home/user/.local/share/yabridge/`

Trying to change the location via `yabridgectl -set -path` did not help either. 
I still receive the error as soon as Bitwig tries to initiate any of the Plugins. 

```
yabridgectl status
yabridge path: '/home/user/.local/share/yabridge'
VST2 location: '/home/user/.vst/yabridge'
VST3 location: '/home/user/.vst3/yabridge'
CLAP location: '/home/user/.clap/yabridge'

libyabridge-chainloader-vst2.so: '/home/user/.local/share/yabridge/libyabridge-chainloader-vst2.so' (64-bit)
libyabridge-chainloader-vst3.so: '/home/user/.local/share/yabridge/libyabridge-chainloader-vst3.so' (64-bit)
libyabridge-chainloader-clap.so: <not found>

yabridge-host.exe: '/usr/bin/yabridge-host.exe'
yabridge-host-32.exe: '/usr/bin/yabridge-host-32.exe'

/home/user/.wine/drive_c/VST/
  FL Studio VSTi (Multi).dll :: VST2, 64-bit, synced
  FL Studio VSTi.dll :: VST2, 64-bit, synced
  Loopcloud.dll :: VST2, 64-bit, synced
  Loopcloud32.dll :: VST2, 32-bit, synced
  OTT_x64.dll :: VST2, 64-bit, synced
  Serum.dll :: VST2, 32-bit, synced
  Serum_x64.dll :: VST2, 64-bit, synced

```

 Many thanks! 

### Operating system

fedora 5.18.13-200.fc36.x86_64

### How did you install yabridge?

COPR patrickl/yabridge-stable

### yabridge version

yabridge-5.0.0-2

### yabridgectl version

yabridge-5.0.0-2

### Wine version

wine-7.20.r0.gacb05462 

### Plugin

Serum

### Host

Bitwig Studio 4.4.2

**Comment by robbert-vdh** [comment]
1. There's something very very wrong with your setup. `yabridge-host.exe` and `yabridge-host-32.exe` are coming from `/usr/bin`, while `libyabridge-chainloader-vst2.so` and `libyabridge-chainloader-vst3.so` are coming from `~/.local/share/yabridge`.
2. Are you using Bitwig through Flatpak? If so, don't. You can't reliably use plugins from outside of Flatpak with Flatpak DAWs. That also goes for yabridge.

**Comment by GitCrush** [comment]
Yes, I indeed installed the update to Bitwig 4.2.2 via Flatpak. 
I will then try to install Bitwig again via .deb package (which is already quite a pain) and do another re-installation of Yabridge.

**Comment by GitCrush** [comment]
Got it to work again! 
I performed some manual intervention in order to transform the Debian file into a working .rpm. 
[Bitwig Studio on Fedora](https://blog.lambda.cx/posts/bitwig-studio-on-fedora-32/)

Thank you so much for the fast response and the gelpful hint!
