### ISSUE TITLE
Polyverse Supermodal GUI only redrawing on window drag

### ISSUE THREAD

**Issue by samborkent** [robbert-vdh/yabridge#212]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Hello,

First of all, thank you for this incredible tool. All my plugins are working flawlessly. (except for some lag updates and reging in Cableguys Shaperbox)
I just pruchased Polyverse's Supermodal to try if it would work through yabridge 4.0.2 in Bitwig Studio 4.4.2. I'm on PopOS! 22.04.
Unfortunately, there is a redrawing issue with the GUI, it only redraws when I move the plugin window. The plugin parameters are working normally, as can be heard and seen in the Bitwig studio interface.
The problem seems very similar to the problem listed for Sforzando, although there is no solution mentioned there.
Do you have any idea what the problem could be and if I could fix it?

### What did you expect to happen?

The GUI to be responsive to mouse changes.

### What actually happened?

The GUI only updates when the plugin window is being dragged. Plugin parameters are functioning normally and can be modulated within Bitwig without any problems. The plugin is usable, but after every click you have t move the window to see when change you made.

### Operating system

PopOS! 22.04

### How did you install yabridge?

release page

### yabridge version

4.0.2

### yabridgectl version

4.0.2

### Wine version

Wine Staging 7.19

### Plugin

Polyverse Supermodal

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Bitwig Studio 4.4.2

### Desktop environment or WM

GNOME 42.4

### GPU model

iGPU: Radeon Graphing (Ryzen 7 5800h) / dGPU: Nvidia RTX 3050

### GPU drivers and kernel

iGPU: unknown / dGPU: Nvidia 515.65.01 on Linux 5.19.16-76051916-generic

### Debug log

14:27:05 [Supermodal-19Saoptu] Initializing yabridge version 4.0.2
14:27:05 [Supermodal-19Saoptu] library:       '/home/sam/.local/share/yabridge/libyabridge-vst3.so'
14:27:05 [Supermodal-19Saoptu] host:          '/home/sam/.local/share/yabridge/yabridge-host.exe'
14:27:05 [Supermodal-19Saoptu] plugin:        '/home/sam/.wine/drive_c/Program Files/Common Files/VST3/Supermodal.vst3'
14:27:05 [Supermodal-19Saoptu] plugin type:   'VST3'
14:27:05 [Supermodal-19Saoptu] realtime:      'yes'
14:27:05 [Supermodal-19Saoptu] sockets:       '/run/user/1000/yabridge-Supermodal-19Saoptu'
14:27:05 [Supermodal-19Saoptu] wine prefix:   '/home/sam/.wine'
14:27:05 [Supermodal-19Saoptu] wine version:  '7.19 (Staging)'
14:27:05 [Supermodal-19Saoptu] 
14:27:05 [Supermodal-19Saoptu] config from:   '/home/sam/.vst3/yabridge/yabridge.toml, section "Supermodal.vst3"'
14:27:05 [Supermodal-19Saoptu] hosting mode:  'individually, 64-bit'
14:27:05 [Supermodal-19Saoptu] other options: 'editor: force drag-and-drop', 'frame rate: 24 fps', 'hack: hide DAW name'
14:27:05 [Supermodal-19Saoptu] unrecognized options: 'editor_disable_host_scaling'
14:27:05 [Supermodal-19Saoptu] 
14:27:05 [Supermodal-19Saoptu] Enabled features:
14:27:05 [Supermodal-19Saoptu] - bitbridge support
14:27:05 [Supermodal-19Saoptu] - VST3 support
14:27:05 [Supermodal-19Saoptu] 
14:27:05 [Supermodal-19Saoptu] [Wine STDERR] 002c:fixme:winediag:LdrInitializeThunk wine-staging 7.19 is a testing version containing experimental patches.
14:27:05 [Supermodal-19Saoptu] [Wine STDERR] 002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
14:27:06 [Supermodal-19Saoptu] [Wine STDERR] 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
14:27:06 [Supermodal-19Saoptu] [Wine STDERR] 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
14:27:06 [Supermodal-19Saoptu] [Wine STDERR] 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
14:27:06 [Supermodal-19Saoptu] [Wine STDERR] 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
14:27:06 [Supermodal-19Saoptu] [Wine STDERR] Initializing yabridge host version 4.0.2
14:27:06 [Supermodal-19Saoptu] [Wine STDERR] Preparing to load VST3 plugin at '/home/sam/.wine/drive_c/Program Files/Common Files/VST3/Supermodal.vst3'
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> GetPluginFactory()
14:27:07 [Supermodal-19Saoptu] [vst -> host] >> Requesting <Configuration>
14:27:07 [Supermodal-19Saoptu] [vst <- host]    <Configuration>
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] Finished initializing '/home/sam/.wine/drive_c/Program Files/Common Files/VST3/Supermodal.vst3'
14:27:07 [Supermodal-19Saoptu] [host <- vst]    <IPluginFactory3* with 2 registered classes>
14:27:07 [Supermodal-19Saoptu] [query interface] In IPluginFactory::queryInterface(): {0x0007B650, 0xF24B4C0B, 0xA464EDB9, 0xF00B2ABB}
14:27:07 [Supermodal-19Saoptu] [query interface] In IPluginFactory::queryInterface(): {0x4555A2AB, 0xC1234E57, 0x9B122910, 0x36878931}
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> IPluginFactory::createInstance(cid = {0xABCDEF01, 0x9182FAEB, 0x504C566D, 0x5076536D}, _iid = IComponent::iid, &obj)
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] 0124:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00000000027FFE10
14:27:07 [Supermodal-19Saoptu] [host <- vst]    <FUnknown* #0>
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IPluginBase::initialize(context = <FUnknown*>)
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] [query interface] In FUnknown::queryInterface(): {0x58E595CC, 0xDB2D4969, 0x8B6AAF8C, 0x36A664E5}
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:07 [Supermodal-19Saoptu] [query interface] In FUnknown::queryInterface(): {0x42043F99, 0xB7DA453C, 0xA569E79D, 0x9AAEC33D}
14:27:07 [Supermodal-19Saoptu] [unknown interface] In FUnknown::queryInterface(): {0x309ECE78, 0xEB7D4FAE, 0x8B2225D9, 0x09FD08B6}
14:27:07 [Supermodal-19Saoptu] [unknown interface] In FUnknown::queryInterface(): {0x6C389611, 0xD391455D, 0xB870B833, 0x94A0EFDD}
14:27:07 [Supermodal-19Saoptu] [unknown interface] In FUnknown::queryInterface(): {0x8683B01F, 0x7B354F70, 0xA2651DEC, 0x353AF4FF}
14:27:07 [Supermodal-19Saoptu] [unknown interface] In FUnknown::queryInterface(): {0xCFCB7A3F, 0xA2CE4E79, 0xB17CA6F2, 0x59BFA939}
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IComponent::getControllerClassId(&classId)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk, {0xABCDEF01, 0x1234ABCD, 0x504C566D, 0x5076536D}
14:27:07 [Supermodal-19Saoptu] [unknown interface] In FUnknown::queryInterface(): {0xDCD7BBE3, 0x7742448D, 0xA874AACC, 0x979C759E}
14:27:07 [Supermodal-19Saoptu] [unknown interface] In FUnknown::queryInterface(): {0xDCD7BBE3, 0x7742448D, 0xA874AACC, 0x979C759E}
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> IPluginFactory::createInstance(cid = {0xABCDEF01, 0x1234ABCD, 0x504C566D, 0x5076536D}, _iid = IEditController::iid, &obj)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    <FUnknown* #1>
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 1: IPluginBase::initialize(context = <FUnknown*>)
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] [query interface] In FUnknown::queryInterface(): {0x58E595CC, 0xDB2D4969, 0x8B6AAF8C, 0x36A664E5}
14:27:07 [Supermodal-19Saoptu] [vst -> host] >> 1: IHostApplication::getName(&name)
14:27:07 [Supermodal-19Saoptu] [vst <- host]    kResultOk, "Get yabridge'd"
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 1: IEditController::setComponentHandler(handler = <IComponentHandler*>)
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] [query interface] In IComponentHandler::queryInterface(): {0xF040B4B3, 0xA36045EC, 0xABCDC045, 0xB4D5A2CC}
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] [query interface] In IComponentHandler::queryInterface(): {0xF040B4B3, 0xA36045EC, 0xABCDC045, 0xB4D5A2CC}
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:07 [Supermodal-19Saoptu] [query interface] In FUnknown::queryInterface(): {0x7F4EFE59, 0xF3204967, 0xAC27A3AE, 0xAFB63038}
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 1: IEditController2::setKnobMode(mode = 2)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:07 [Supermodal-19Saoptu] [unknown interface] In FUnknown::queryInterface(): {0xC1271208, 0x70594098, 0xB9DD34B3, 0x6BB0195E}
14:27:07 [Supermodal-19Saoptu] [query interface] In FUnknown::queryInterface(): {0xDF0FF9F7, 0x49B74669, 0xB63AB732, 0x7ADBF5E5}
14:27:07 [Supermodal-19Saoptu] [unknown interface] In FUnknown::queryInterface(): {0x4CC80877, 0x47B04A83, 0x85A71AD4, 0x9DDE6F72}
14:27:07 [Supermodal-19Saoptu] [unknown interface] In FUnknown::queryInterface(): {0x8B4BC7F6, 0xC3AA493F, 0x872DA5B4, 0xD779DAEB}
14:27:07 [Supermodal-19Saoptu] [unknown interface] In FUnknown::queryInterface(): {0xB7F8F859, 0x41234872, 0x91169581, 0x4F3721A3}
14:27:07 [Supermodal-19Saoptu] [query interface] In FUnknown::queryInterface(): {0x3D4BD6B5, 0x913A4FD2, 0xA886E768, 0xA5EB92C1}
14:27:07 [Supermodal-19Saoptu] [query interface] In FUnknown::queryInterface(): {0x0F194781, 0x8D984ADA, 0xBBA0C1EF, 0xC011D8D0}
14:27:07 [Supermodal-19Saoptu] [unknown interface] In FUnknown::queryInterface(): {0x6B2449CC, 0x419740B5, 0xAB3C79DA, 0xC5FE5C86}
14:27:07 [Supermodal-19Saoptu] [query interface] In FUnknown::queryInterface(): {0x70A4156F, 0x6E6E4026, 0x989148BF, 0xAA60D8D1}
14:27:07 [Supermodal-19Saoptu] [query interface] In FUnknown::queryInterface(): {0x70A4156F, 0x6E6E4026, 0x989148BF, 0xAA60D8D1}
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IConnectionPoint::connect(other = <IConnectionPoint* #1>)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 1: IConnectionPoint::connect(other = <IConnectionPoint* #0>)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: {IComponent,IEditController}::getState(state = <IBStream* containing 0 bytes>)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk, <IBStream* containing 17118 bytes>
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 1: IEditController::setComponentState(state = <IBStream* containing 17118 bytes>)
14:27:07 [Supermodal-19Saoptu] [vst -> host] >> 1: IComponentHandler::restartComponent(flags = 4)
14:27:07 [Supermodal-19Saoptu] [vst <- host]    kResultOk
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kNotImplemented
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 1: IUnitInfo::getUnitCount()
14:27:07 [Supermodal-19Saoptu] [host <- vst]    8
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 1: IUnitInfo::getUnitInfo(unitIndex = 0, &info)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk, <UnitInfo for "Root Unit">
14:27:07 [Supermodal-19Saoptu] [unknown interface] In FUnknown::queryInterface(): {0x9EEA720F, 0xC52D4448, 0x89A8EEC1, 0xD266D041}
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IAudioProcessor::setupProcessing(setup = <SetupProcessing with mode = 0, symbolic_sample_size = 0, max_buffer_size = 1024 and sample_rate = 48000>)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IComponent::getBusCount(type = 0, dir = 0)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    2
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IComponent::getBusCount(type = 0, dir = 1)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    1
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IAudioProcessor::getBusArrangement(dir = 0, index = 0, &arr)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk, <SpeakerArrangement: 0b0000000000000000000000000000000000000000000000000000000000000011>
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IAudioProcessor::getBusArrangement(dir = 0, index = 1, &arr)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk, <SpeakerArrangement: 0b0000000000000000000000000000000000000000000000000000000000000011>
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IAudioProcessor::getBusArrangement(dir = 1, index = 0, &arr)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk, <SpeakerArrangement: 0b0000000000000000000000000000000000000000000000000000000000000011>
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IAudioProcessor::setBusArrangements(inputs = [SpeakerArrangement: 0b0000000000000000000000000000000000000000000000000000000000000011, SpeakerArrangement: 0b0000000000000000000000000000000000000000000000000000000000000011], numIns = 2, outputs = [SpeakerArrangement: 0b0000000000000000000000000000000000000000000000000000000000000011], numOuts = 1)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IComponent::getBusCount(type = 0, dir = 0)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    2
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IComponent::activateBus(type = 0, dir = 0, index = 0, state = true)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IComponent::getBusCount(type = 0, dir = 0)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    2
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IComponent::activateBus(type = 0, dir = 0, index = 1, state = false)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IComponent::getBusCount(type = 1, dir = 0)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    1
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IComponent::activateBus(type = 1, dir = 0, index = 0, state = true)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IComponent::getBusCount(type = 0, dir = 1)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    1
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IComponent::activateBus(type = 0, dir = 1, index = 0, state = true)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IComponent::getBusCount(type = 1, dir = 1)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    0
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IComponent::setActive(state = true)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk, <new shared memory configuration for "yabridge-Supermodal-19Saoptu-0", 24576 bytes>
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 1: IEditController::getParameterCount()
14:27:07 [Supermodal-19Saoptu] [host <- vst]    2456
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 0: IComponent::getBusCount(type = 1, dir = 0)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    1
: 
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 1: IEditController::getParamStringByValue(id = 65906586, valueNormalized = 0.49, &string)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk, "49.0"
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 1: IPlugView::canResize()
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultFalse
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 1: IPlugViewContentScaleSupport::setContentScaleFactor(factor = 1)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 1: IPlugView::getSize(size*)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk, <ViewRect* with left = 0, top = 0, right = 1506, bottom = 798>
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 1: IPlugView::canResize()
14:27:07 [Supermodal-19Saoptu] [vst <- host]    kResultFalse (from cache)
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 1: IPlugViewContentScaleSupport::setContentScaleFactor(factor = 1)
14:27:07 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:07 [Supermodal-19Saoptu] [host -> vst] >> 1: IPlugView::attached(parent = 50331648, type = "X11EmbedWindowID" (will be translated to "HWND"))
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: host_window: 50331648
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: parent_window: 50331648
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: wrapper_window: 65011712
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: wine_window: 62914565
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: Reparenting 65011712 to 50331648 succeeded
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: Reparenting 62914565 to 65011712 succeeded
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] 0114:fixme:combase:RoGetActivationFactory (L"Windows.UI.ViewManagement.UIViewSettings", {3694dbf9-8f68-44be-8ff5-195c98ede8a6}, 0000000004F58E18): semi-stub
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] 0114:err:combase:RoGetActivationFactory Failed to find library for L"Windows.UI.ViewManagement.UIViewSettings"
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] 0114:fixme:win:RegisterTouchWindow (000000000001007A 00000000): stub
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] 0114:fixme:msg:ChangeWindowMessageFilterEx 000000000001007A 233 1 0000000000000000
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] 0114:fixme:msg:ChangeWindowMessageFilterEx 000000000001007A 4a 1 0000000000000000
14:27:07 [Supermodal-19Saoptu] [Wine STDERR] 0114:fixme:msg:ChangeWindowMessageFilterEx 000000000001007A 49 1 0000000000000000
:
14:27:14 [Supermodal-19Saoptu] [host <- vst]    kResultOk, <AudioBusBuffers array with [2] channels>, <IParameterChanges* for 0 parameters>, host does not support event outputs
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: FocusIn for window 50331648 (wine window active)
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: Spoofing local coordinates to (527, 401)
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: Active keyboard modifiers: 256
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: Not grabbing input focus for window 50331648(current focus 50331649 is a child of 50331648)
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: Unhandled X11 event 10
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: Unhandled X11 event 10
: 
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: ConfigureNotify for window 50331648
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: Spoofing local coordinates to (527, 400)
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 0: IAudioProcessor::canProcessSampleSize(symbolicSampleSize = 0)
14:27:14 [Supermodal-19Saoptu] [vst <- host]    kResultOk (from cache)
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 0: IAudioProcessor::process(data = <ProcessData with input_channels = [2 (silence), 2], output_channels = [2], num_samples = 1024, input_parameter_changes = <IParameterChanges* for 0 parameters>, output_parameter_changes = <IParameterChanges*>, input_events = <IEventList* with 0 events>, output_events = <nullptr>, process_context = <ProcessContext*>, process_mode = 0, symbolic_sample_size = 0>)
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 1: IPlugView::canResize()
14:27:14 [Supermodal-19Saoptu] [vst <- host]    kResultFalse (from cache)
14:27:14 [Supermodal-19Saoptu] [host <- vst]    kResultOk, <AudioBusBuffers array with [2] channels>, <IParameterChanges* for 0 parameters>, host does not support event outputs
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 1: IPlugView::canResize()
14:27:14 [Supermodal-19Saoptu] [vst <- host]    kResultFalse (from cache)
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 1: IPlugView::canResize()
14:27:14 [Supermodal-19Saoptu] [vst <- host]    kResultFalse (from cache)
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 1: IPlugView::canResize()
14:27:14 [Supermodal-19Saoptu] [vst <- host]    kResultFalse (from cache)
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 0: IAudioProcessor::canProcessSampleSize(symbolicSampleSize = 0)
14:27:14 [Supermodal-19Saoptu] [vst <- host]    kResultOk (from cache)
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 0: IAudioProcessor::process(data = <ProcessData with input_channels = [2 (silence), 2], output_channels = [2], num_samples = 1024, input_parameter_changes = <IParameterChanges* for 0 parameters>, output_parameter_changes = <IParameterChanges*>, input_events = <IEventList* with 0 events>, output_events = <nullptr>, process_context = <ProcessContext*>, process_mode = 0, symbolic_sample_size = 0>)
14:27:14 [Supermodal-19Saoptu] [host <- vst]    kResultOk, <AudioBusBuffers array with [2] channels>, <IParameterChanges* for 0 parameters>, host does not support event outputs
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 1: IPlugView::canResize()
14:27:14 [Supermodal-19Saoptu] [vst <- host]    kResultFalse (from cache)
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 1: IPlugView::canResize()
14:27:14 [Supermodal-19Saoptu] [vst <- host]    kResultFalse (from cache)
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: ConfigureNotify for window 50331648
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: Spoofing local coordinates to (524, 396)
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: ConfigureNotify for window 50331648
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: Spoofing local coordinates to (524, 396)
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: ConfigureNotify for window 50331648
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: Spoofing local coordinates to (524, 396)
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: ConfigureNotify for window 50331648
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: Spoofing local coordinates to (524, 396)
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: ConfigureNotify for window 50331648
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: Spoofing local coordinates to (524, 396)
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: ConfigureNotify for window 50331648
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: Spoofing local coordinates to (524, 396)
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 0: IAudioProcessor::canProcessSampleSize(symbolicSampleSize = 0)
14:27:14 [Supermodal-19Saoptu] [vst <- host]    kResultOk (from cache)
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 0: IAudioProcessor::process(data = <ProcessData with input_channels = [2 (silence), 2], output_channels = [2], num_samples = 1024, input_parameter_changes = <IParameterChanges* for 0 parameters>, output_parameter_changes = <IParameterChanges*>, input_events = <IEventList* with 0 events>, output_events = <nullptr>, process_context = <ProcessContext*>, process_mode = 0, symbolic_sample_size = 0>)
14:27:14 [Supermodal-19Saoptu] [host <- vst]    kResultOk, <AudioBusBuffers array with [2] channels>, <IParameterChanges* for 0 parameters>, host does not support event outputs
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 1: IPlugView::canResize()
14:27:14 [Supermodal-19Saoptu] [vst <- host]    kResultFalse (from cache)
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 1: IPlugView::canResize()
14:27:14 [Supermodal-19Saoptu] [vst <- host]    kResultFalse (from cache)
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 0: IAudioProcessor::canProcessSampleSize(symbolicSampleSize = 0)
14:27:14 [Supermodal-19Saoptu] [vst <- host]    kResultOk (from cache)
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 0: IAudioProcessor::process(data = <ProcessData with input_channels = [2 (silence), 2], output_channels = [2], num_samples = 1024, input_parameter_changes = <IParameterChanges* for 0 parameters>, output_parameter_changes = <IParameterChanges*>, input_events = <IEventList* with 0 events>, output_events = <nullptr>, process_context = <ProcessContext*>, process_mode = 0, symbolic_sample_size = 0>)
14:27:14 [Supermodal-19Saoptu] [host <- vst]    kResultOk, <AudioBusBuffers array with [2] channels>, <IParameterChanges* for 0 parameters>, host does not support event outputs
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 1: IPlugView::canResize()
14:27:14 [Supermodal-19Saoptu] [vst <- host]    kResultFalse (from cache)
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: ConfigureNotify for window 50331648
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: Spoofing local coordinates to (523, 394)
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: ConfigureNotify for window 50331648
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: Spoofing local coordinates to (523, 394)
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: ConfigureNotify for window 50331648
14:27:14 [Supermodal-19Saoptu] [Wine STDERR] DEBUG: Spoofing local coordinates to (523, 394)
14:27:14 [Supermodal-19Saoptu] [host -> vst] >> 1: IPlugView::canResize()
14:27:14 [Supermodal-19Saoptu] [vst <- host]    kResultFalse (from cache)
: 
4:27:19 [Supermodal-19Saoptu] [host -> vst] >> 0: IAudioProcessor::process(data = <ProcessData with input_channels = [2 (silence), 2], output_channels = [2], num_samples = 1024, input_parameter_changes = <IParameterChanges* for 0 parameters>, output_parameter_changes = <IParameterChanges*>, input_events = <IEventList* with 0 events>, output_events = <nullptr>, process_context = <ProcessContext*>, process_mode = 0, symbolic_sample_size = 0>)
14:27:19 [Supermodal-19Saoptu] [host <- vst]    kResultOk, <AudioBusBuffers array with [2] channels>, <IParameterChanges* for 0 parameters>, host does not support event outputs
14:27:19 [Supermodal-19Saoptu] [host -> vst] >> 0: IAudioProcessor::getTailSamples()
14:27:19 [Supermodal-19Saoptu] [host <- vst]    1728000000
14:27:19 [Supermodal-19Saoptu] [host -> vst] >> 0: IAudioProcessor::setProcessing(state = false)
14:27:19 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:19 [Supermodal-19Saoptu] [host -> vst] >> 0: {IComponent,IEditController}::getState(state = <IBStream* containing 0 bytes>)
14:27:19 [Supermodal-19Saoptu] [host <- vst]    kResultOk, <IBStream* containing 17122 bytes>
14:27:19 [Supermodal-19Saoptu] [host -> vst] >> 1: {IComponent,IEditController}::getState(state = <IBStream* containing 0 bytes>)
14:27:19 [Supermodal-19Saoptu] [host <- vst]    kNotImplemented
14:27:19 [Supermodal-19Saoptu] [host -> vst] >> 0: IConnectionPoint::disconnect(other = <IConnectionPoint* #1>)
14:27:19 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:19 [Supermodal-19Saoptu] [host -> vst] >> 1: IConnectionPoint::disconnect(other = <IConnectionPoint* #0>)
14:27:19 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:19 [Supermodal-19Saoptu] [host -> vst] >> 1: IPluginBase::terminate()
14:27:19 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:19 [Supermodal-19Saoptu] [host -> vst] >> 0: IPluginBase::terminate()
14:27:19 [Supermodal-19Saoptu] [host <- vst]    kResultOk
14:27:19 [Supermodal-19Saoptu] [host -> vst] >> 1: FUnknown::~FUnknown()
14:27:19 [Supermodal-19Saoptu] [host <- vst]    ACK
14:27:19 [Supermodal-19Saoptu] [host -> vst] >> 0: FUnknown::~FUnknown()
14:27:21 [Supermodal-19Saoptu] [Wine STDERR] 0114:fixme:font:NtGdiRemoveFontMemResourceEx (0xf8493a21) stub
14:27:21 [Supermodal-19Saoptu] [Wine STDERR] 0114:fixme:font:NtGdiRemoveFontMemResourceEx (0xf9e08141) stub
14:27:21 [Supermodal-19Saoptu] [host <- vst]    ACK

**Comment by robbert-vdh** [comment]
Try installing DXVK. That sounds similar to an issue with [Beat Scholar](https://www.modalics.com/) when using WineD3D instead of DXVK.

**Comment by samborkent** [comment]
This fixed it, thank you very much!
