### ISSUE TITLE
Autotune pro crashing immedialty

### ISSUE THREAD

**Issue by SnowSquire** [robbert-vdh/yabridge#214]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

When I try to load autotune the plugin UI either doesn't load, or it crashes. I have no idea what the issue is

### What did you expect to happen?

For autotune to load and not lockup reaper

### What actually happened?

Freezes reaper

### Operating system

Fedora 36

### How did you install yabridge?

From COPR

### yabridge version

4.0.3

### yabridgectl version

5.0.1

### Wine version

wine-7.20.r0.gacb05462 ( TkG Staging Esync Fsync )

### Plugin

Antares Auto-tune

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Reaper

### Desktop environment or WM

KDE X11

### GPU model

3060 ti

### GPU drivers and kernel

Proprietary nvidia drivers, 6.0.7 kernel

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/10008743/yabridge.log)

**Comment by robbert-vdh** [comment]
Can't really help you since I don't won these plugins myself. I saw some people in the Discord that had these plugins working, so it may be a combination of what Wine version, Auto Tune version, and overrides you're using.

**Comment by McFranko** [comment]
I'm having this issue with mt-powerdrumkit. It happened after I loaded reaper, then got a message to update Mono from wine, and pressed cancel. Ever since then it's been locking up.

I'm on EndeavourOS, installed yabridge from arch linux repos

**Comment by robbert-vdh** [comment]
Closing since this is almost certainly not a yabridge issue and the original poster hasn't responded in a month.
