### ISSUE TITLE
Correction for wine downgrade

### ISSUE THREAD

**Issue by Pabloantxon** [robbert-vdh/yabridge#215]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

On the command provided for downgrading wine the variable "codename" ends up with a value of 'focal focal' instead of just 'focal':
`osc@osc-pc:~$ codename=$(shopt -s nullglob; awk '/^deb https:\/\/dl\.winehq\.org/ { print $3; exit 0 } END { exit 1 }' /etc/apt/sources.list /etc/apt/sources.list.d/*.list || awk '/^Suites:/ { print $2; exit }' /etc/apt/sources.list /etc/apt/sources.list.d/wine*.sources)
osc@osc-pc:~$ echo $codename
focal focal
`
I know this is not a bug, but I didn't know how to let you know otherwise. 
`codename=focal` fixed it and I could install it.

### What did you expect to happen?

install version 7.20 of wine staging

### What actually happened?

wine staging 7.20 focal focal was not found

### Operating system

ubuntu 20.04

### How did you install yabridge?

from releases page

### yabridge version

5.0

### yabridgectl version

5.0

### Wine version

7.20

### Plugin

all

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Bitwig Studio 4.4

### Desktop environment or WM

Xfce

### Debug log

asdf

### Anything else?

asdf

**Comment by robbert-vdh** [comment]
Can you run the two awk commands separately? It exits after the first match, so even if you do have the repo added twice (which you should fix of course) it shouldn't cause any issues.

**Comment by Pabloantxon** [comment]
Yeah, running them separately I get focal on both command outputs, but running the whole command ends up with "focal focal".
Anyhow, it is probably my fault, since I messed up a bit with the wine installation before reading what you said about 7.21 not working with yabridge and having to use 7.20.
Thanks for your work btw, it was thanks to yabridge that I could say goodbye to windows :)

**Comment by robbert-vdh** [comment]
Closing this because there hasn't been a response in a couple months, and the commands work fine for everyone else.
