### ISSUE TITLE
Issue with plugin (Pulsar Modular Abyss - not released yet) - L"Windows.UI.ViewManagement.UIViewSettings"

### ISSUE THREAD

**Issue by aklinbail** [robbert-vdh/yabridge#217]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

No gui parts will respond to the mouse 
(yes I've turned off the Wine verison notification) 

### What did you expect to happen?

plugin to work as normal 

### What actually happened?

all controls on plugin frozen .. 

message in terminal 

Failed to find library for L"Windows.UI.ViewManagement.UIViewSettings

### Operating system

Arch

### How did you install yabridge?

AUR using Yay (also tried stable) 

### yabridge version

5.0.2 

### yabridgectl version

5.0.2

### Wine version

wine-tkg-7.20

### Plugin

Pulsar Modular Abyss

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Ardour mixbus or Reaper 

### GPU model

amd rx570

### GPU drivers and kernel

6.0.0 amdgpu

### Debug log

going to bed .. will get this later. 

### Anything else?

this worked prior to updating yabridge earlier this week.

**Comment by robbert-vdh** [comment]
Are you sure that the GUI doesn't work at all and that it doesn't just not redraw? Check the known issues section in the readme, you probably need to install DXVK.

**Comment by robbert-vdh** [comment]
I downloaded the demo form https://www.pulsarmodular.com/product/p11-abyss/. It's either an issue iwth the plugin or with Wine, but not with yabridge. Running the plugin in a native Windows host under Wine does the exact same thing. So I sadly can't help you here!

**Comment by aklinbail** [comment]
Ok Thanks for checking it out.

I've tested a few versions of wine so something about the plugin..
Based on your information  I've been using wine-tkg 7.20 with fsync.
(although didn't have the environment variables correct until recently )

The developer has stated they've recently upgraded to Juce 7 and this is
their first plugin on that platform.  Thankfully they are also starting to
work on an LV2 port.

**Comment by aklinbail** [comment]
Seems I had DXVK installed but not correctly configured..

Works beautifully now.
