### ISSUE TITLE
Yabridge doesn't create bridged files for vst2 plugins

### ISSUE THREAD

**Issue by ambyshframber** [robbert-vdh/yabridge#218]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Yabridge isn't creating a bridged file for TAL-Dub II. `yabridgectl status` shows it as installed via copy. `yabridgectl sync` reported no errors.

### What did you expect to happen?

A bridged version of TAL-Dub II would appear in ~/.vst/yabridge. 

### What actually happened?

~/.vst/yabrudge was not created. After creating the directories manually and running yabridgectl again, there was still no bridged file.

### Operating system

Linux Mint 

### How did you install yabridge?

from the releases page

### yabridge version

3.8.1

### yabridgectl version

3.8.1

### Wine version

wine-7.20 (Staging)

### Plugin

TAL-Dub 2

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Ardour 6

**Comment by robbert-vdh** [comment]
You're using an ancient version of yabridge. That version of yabridge created .so files alongside the Windows VST2 plugin's .dll file, inside of the Wine prefix. Yabridge 4.0 changed the default, and also changed the way yabridge creates bridged plugins so yabridge can be updated independently of the created .so files. You should update to yabridge 5.0.2.
