### ISSUE TITLE
Large plugin window gets cut off at far end, making some controls unusable.

### ISSUE THREAD

**Issue by TheGuyWhoo** [robbert-vdh/yabridge#219]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

![Screenshot from 2022-11-30 15-48-06](https://user-images.githubusercontent.com/72744967/204815914-fbf47140-1f07-47d8-bb29-9520769db71e.png)

As you can see here a significant portion of the GUI is cut off. This plugin is resizable, but the control for resizing the plugin is in the portion that is being cut off... In windows reaper under wine there is a scroll bar at the bottom of the plugin window that you can use to position the GUI length wise. This scroll bar is not present in linux under yabridge, thus it is impossible to make use of the controls that are cut off.

### What did you expect to happen?

A scroll bar that allows me to move the gui over.

https://user-images.githubusercontent.com/72744967/204825056-6a8ff49a-efd6-4bec-af35-cc14d26d00ee.mp4

### What actually happened?

The window is cut off and there is no way to move the gui over.

### Operating system

linux mint 20

### How did you install yabridge?

From releases page

### yabridge version

4.0.0

### yabridgectl version

Whatever version came along side 4.0.0

### Wine version

wine-staging 7.9

### Plugin

fb3300 1.2.0

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

reaper 6.71

**Comment by robbert-vdh** [comment]
There not being a scroll bar is not something I can fix for you. That's on REAPER. Presumably you can just manually resize the FX window and if the Linux version also has a scroll bar it should appear. But I don't think they added scroll bars to Linux REAPER. If the plugin has scaling, try scaling it down. Or try enabling [XEmbed](https://github.com/robbert-vdh/yabridge#compatibility-options). Or you'll need to get a higher resolution display so the entire GUI can fit on your screen.

**Comment by TheGuyWhoo** [comment]
As I explained in the post, it is not possible to resize it. The control for resizing is in the part that is cut off. I could probably temporarily change my resolution settings and resize it that way, thanks for the idea.

**Comment by TheGuyWhoo** [comment]
I am a complete knob, there's a menu at the bottom that lets you set the size :)
