### ISSUE TITLE
cannot stack plugins from different wine prefixes

### ISSUE THREAD

**Issue by durutti** [robbert-vdh/yabridge#22]
Hi again, when I try to stack plugins on a (audio or midi) track or even open two plugins from different wine prefixes on separate tracks, Ardour6 crashes.
For instance. Roland synths are on prefix A and IK multimdedia on prefix B (both 64-bit)
![Screenshot from 2020-06-19 13-51-36](https://user-images.githubusercontent.com/25441390/85125884-109da880-b235-11ea-8579-861aaeb07898.png)

plugins from the same prefix work fine
here is the log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/4804303/yabridge.log)

ubuntu 18.04
wine-development 5.10
Ardour6

**Comment by robbert-vdh** [comment]
Are you sure you installed T-RackS correctly in `~/.wineIK`? The plugin is complaining that it can't find some asset files. These files should be in `~/.wineIK/drive_c/Program Files/IK Multimedia/T-RackS 5/`. I just tried it myself and I did not have any issues opening TR5 Tape Machine 24 from T-RackS 5 (which is in its own Wine prefix) and ValhallaSupermassive (which is in my default Wine prefix) at the same time in Ardour 6, and the logs show that everything is fine aside from the plugin exiting after showing the error dialog (that's not really something a VST2 plugin can do on its own, hence the crash).

**Comment by durutti** [comment]
Yes T-RACKS is installed correctly, because if I start the session and add a T-Racks plugin first it opens correctly
![Screenshot from 2020-06-20 00-19-33](https://user-images.githubusercontent.com/25441390/85180377-ffcc5180-b28b-11ea-8db0-4361b11eb799.png)
and I can add a second T-RACKS plugin. If however I add a T-Racks plugin and then add a midi track with Roland vst I have an immediate crach

The weird staff now. The above behavior is met when I start ardour form the applications launcher. If I start ardour from the terminal and add a T-racks plugin first I get the message of the first post.
If I realunch Ardour6 form the terminal and add Roland vst first the plugin works correctly....

I also tried with another combination of plugins. In a thrid prefix I have True Iron

Application Launcher: Fisrt Tue Iron (ok and registered) and then t-racks error message of first post
Application Launcher: Fisrt t-racks (ok) and then true iron (true iron opens in demo mode)

Launching Ardour6 from terminal Fisrt Tue Iron (demo mode) and roland vst (ok and registerd)
The same results for true iron and roland vsti i I change the order

Any ideas,
Thank you

**Comment by robbert-vdh** [comment]
Are you sure you don't manually override your Wine prefix somewhere? If just before you'd start Ardour from the terminal you run `echo $WINEPREFIX`, does that print anything? If the output is not empty, then that would explain the issue. If the Wine prefix is explicitly overridden using this environment variable then yabridge will honor that decision since that would be the logical behavior. I did just notice that this is not reflected in output printed on startup. Rright now it'll always say it's using the detected Wine prefix, even if it has been overridden using the `WINEPREFIX` environment variable. I'll make sure to fix that immediately.

**Comment by durutti** [comment]
Ok your first commnet was correct, I had in my .bashrc the last wine prefix. Commenting out that line fixed the issue of T-racks showing missing assets on its own. So no I am in a situation similar to what is happenning using the application launcher.

I re-downloaded the new build performed the whole proceedure and now I have the following scenarios and their logs.

Scen_1: Open session, load one T-Racks plugin, then add roland midi track -> immediate crash
here is, its log
[yabridge_1.log](https://github.com/robbert-vdh/yabridge/files/4807634/yabridge_1.log)
and the terminal output
[Ardour6_1.txt](https://github.com/robbert-vdh/yabridge/files/4807639/Ardour6_1.txt)

Scen_2; Open session, load roland midi track, and then one T-racks results in the image
![Screenshot from 2020-06-20 12-23-07](https://user-images.githubusercontent.com/25441390/85198395-135dd380-b2f1-11ea-9186-a00e1716d84e.png)

if i hit ok the same message window comes up 5-6 times until a wine crach is produced. this the wine backtrace

[backtrace.txt](https://github.com/robbert-vdh/yabridge/files/4807647/backtrace.txt)

and the yarbridge log and the terminal output

[yabridge_2_2.log](https://github.com/robbert-vdh/yabridge/files/4807648/yabridge_2_2.log)
[Ardour6_2.txt](https://github.com/robbert-vdh/yabridge/files/4807650/Ardour6_2.txt)

**Comment by robbert-vdh** [comment]
In both logs the Wine prefix is being overridden. In the first log `~/.wineIK` is being used for both plugins, and in the second log this is `~/.wineROLAND`. You can verify this by looking for the lines that start with `wine prefix:`. You probably still have a `WINEPREFIX` override set somewhere.

**Comment by durutti** [comment]
echo $WINEPREFIX is empty, 
in .bashrc all exported wineprefxies are commented out,
and winecfg m(and winetricks) gives the default  .wine prefix. Any ideas where should I look for overrides.
Thank you

**Comment by robbert-vdh** [comment]
They're definitely set somewhere, and for some reason they're also set to different values (`WINEPREFIX` is set to `~/.wineIK` in `yabridge_1.log` and to `~/.wineROLAND` in `yabridge_2_2.log`). If you launch ardour from a terminal and explicitelly unset the environment variable then it will work, but that's of course not really a solution (i.e. by running `env -u WINEPREFIX ardour6`). If you don't know where this environment variable could be set, then the only way forward would be to just search for all mentions of that variable in the hope you can find the source. If you ripgrep installed, then you could run the command below to find all mentions of `WINEPREFIX` in your home directory and a few other relevant places:

```shell
rg -uu --no-messages WINEPREFIX /usr/share/applications /etc/{bash,profile}* ~
```

**Comment by robbert-vdh** [comment]
Again sorry for having had to deal with this! I never noticed this behaviour (probably because Wine prefix overrides were not actually being shown in the startup output). I have fixed the issue in 34e3f1a1bf496e52cc48cd6d020e77b4535fc9c8. That should fix the issue you wer facing!

**Comment by durutti** [comment]
Hey, well done that solved the issue
![Screenshot from 2020-06-20 15-18-22](https://user-images.githubusercontent.com/25441390/85201638-a86cc680-b309-11ea-9a19-c6c244304ca4.png)
Thank you

**Comment by robbert-vdh** [comment]
That's great to hear! Let me know if you come across anything else that's acting up.
