### ISSUE TITLE
Omnisphere Error (PowerShell.exe)

### ISSUE THREAD

**Issue by mukundasik** [robbert-vdh/yabridge#220]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

First of all, I'd like to say BIG thank you for everything you do!
Sorry for my English, please)

When I run Omnisphere, wine shows me error: "The Program PowerShell.exe has encountered a serious problem and needs to close", but despite this, Omnisphere starts normally and fully functional BUT loading time is very slow.. this takes up to 20-30 sec to load (it's weird coz i have powerful gaming laptop with all nvme drives) and during loading shows me this powershell error.
Other plugins (FabFilter, Melodyne)  load and function as it supposed to be
What should i do? What i missed? maybe something wrong with wine config or something else?

### What did you expect to happen?

Waiting for suggest what i need to do with this error and how to solve slow loading time

### What actually happened?

issue)

### Operating system

Fedora 37

### How did you install yabridge?

from copr for fedora from your instructions from release page

### yabridge version

5.0.2

### yabridgectl version

5.0.2

### Wine version

winehq staging 7.22

### Plugin

Omnisphere

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

All

### Desktop environment or WM

Gnome 43.1 on Wayland

### GPU model

rtx 2070

### GPU drivers and kernel

nvidia 520 and kernel 6.1.0

### Debug log

Unhandled exception: 0x80000005 in 64-bit code (0x00000170025de8).
Register dump:
 rip:0000000170025de8 rsp:000000000021f730 rbp:000000000021f930 eflags:00000206 (   - --  I   - -P- )
 rax:0000000000000042 rbx:000000000021f750 rcx:000000000021f750 rdx:0000000000000000
 rsi:000000007fee3404 rdi:000000007fee3000  r8:000000000000000a  r9:000000007fee3439 r10:00007fae1efd8640
 r11:0000000000000202 r12:0000000000000042 r13:000000014000401d r14:0000000000000000 r15:0000000000000000
Stack dump:
0x0000000021f730:  000000000021f750 000000017006cc50
0x0000000021f740:  000000007fee0000 000000017007d4e8
0x0000000021f750:  0000000180000005 0000000000000000
0x0000000021f760:  0000000170025de8 0000000100000000
0x0000000021f770:  0000000000000000 000000007b61861d
0x0000000021f780:  0000000000000308 000000017007d4fc
0x0000000021f790:  000000017006cc51 000000017007d4e8
0x0000000021f7a0:  0000000000000042 000000017007d32c
0x0000000021f7b0:  000000000021f850 000000000021f930
0x0000000021f7c0:  0000000000000042 000000014000401d
0x0000000021f7d0:  000000000000001e 000000017005f1a8
0x0000000021f7e0:  0000000000000000 0000000000000000
Backtrace:
=>0 0x00000170025de8 in ntdll (+0x25de8) (0x0000000021f930)
  1 0x00000170025dfb in ntdll (+0x25dfb) (0x0000000021f930)
  2 0x0000017005f23d in ntdll (+0x5f23d) (0x0000000021f930)
  3 0x0000017005f116 in ntdll (+0x5f116) (0x0000007fee0000)
  4 0x00000140001d3b in powershell (+0x1d3b) (0x0000000033b690)
  5 0x0000014000103a in powershell (+0x103a) (0x0000000033b690)
  6 0x00000140001098 in powershell (+0x1098) (0x0000000033b690)
  7 0x000001400013f2 in powershell (+0x13f2) (0x0000000033b690)
  8 0x00000140001f61 in powershell (+0x1f61) (0000000000000000)
  9 0x0000007b627da9 in kernel32 (+0x27da9) (0000000000000000)
  10 0x0000017005f448 in ntdll (+0x5f448) (0000000000000000)
0x00000170025de8 ntdll+0x25de8: jmp	0x00000170025de0 ntdll+0x25de0
Modules:
Module	Address					Debug info	Name (13 modules)
PE	000000007b000000-000000007b51d000	Deferred        kernelbase
PE	000000007b600000-000000007b75c000	Dwarf-5         kernel32
ELF	000000007d000000-000000007d005000	Deferred        <wine-loader>
PE	0000000140000000-000000014001a000	Dwarf-5         powershell
PE	0000000170000000-00000001702cf000	Dwarf-5         ntdll
PE	0000000180000000-00000001800f4000	Deferred        ucrtbase
ELF	00007fae11589000-00007fae11700000	Dwarf           libwine.so.1
ELF	00007fae1ee28000-00007fae1ee48000	Deferred        libgcc_s.so.1
ELF	00007fae1ee48000-00007fae1ef28000	Deferred        libm.so.6
ELF	00007fae1ef28000-00007fae1ef41000	Deferred        libunwind.so.8
ELF	00007fae1ef41000-00007fae1f01f000	Deferred        ntdll.so
ELF	00007fae1f022000-00007fae1f1ff000	Deferred        libc.so.6
ELF	00007fae1f216000-00007fae1f24d000	Deferred        ld-linux-x86-64.so.2
Threads:
process  tid      prio    name (all IDs are in hex)
00000038 services.exe
	["C:\windows\system32\services.exe"]
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	0000004c    0     wine_rpcrt4_io
	00000078    0     wine_rpcrt4_io
	000000b0    0     wine_rpcrt4_io
	000000cc    0     wine_rpcrt4_io
	000000e4    0     wine_rpcrt4_io
00000044 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000048    0     
	00000054    0     
	00000058    0     wine_sechost_service
	00000064    0     
	00000068    0     
	0000006c    0     
	000000d8    0     
0000005c explorer.exe
	["C:\windows\system32\explorer.exe" /desktop]
	00000060    0     
	000000a4    0     
	000000a8    0     wine_rpcrt4_server
00000070 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000074    0     
	0000007c    0     
	00000080    0     wine_sechost_service
	00000084    0     
	00000088    0     
	0000008c    0     
	00000090    0     
	00000094    0     
	00000098    0     
0000009c plugplay.exe
	[C:\windows\system32\plugplay.exe]
	000000a0    0     
	000000b8    0     
	000000bc    0     wine_sechost_service
	000000c0    0     wine_rpcrt4_server
000000c4 svchost.exe
	[C:\windows\system32\svchost.exe -k LocalServiceNetworkRestricted]
	000000c8    0     
	000000d0    0     
	000000d4    0     wine_sechost_service
000000dc rpcss.exe
	[C:\windows\system32\rpcss.exe]
	000000e0    0     
	000000e8    0     
	000000ec    0     wine_sechost_service
	000000f0    0     wine_rpcrt4_server
	000000f4    0     wine_rpcrt4_server
	000000f8    0     wine_rpcrt4_io
	00000230    0     wine_rpcrt4_io
	00000330    0     wine_rpcrt4_io
00000224 Omnisphere.exe
	["C:\ProgramData\Spectrasonics\Omnisphere.exe"]
	00000228    0     
	0000022c    0     wine_rpcrt4_server
	0000023c    0     wine_mmdevapi_notification
	00000240   15     winepulse_mainloop
	00000244    1     
	00000248   15     winepulse_timer_loop
	0000024c    0     winealsa_midi_notify
	00000254    0     wined3d_cs
	0000025c    1     
	00000268    0     
	00000270   -1     
	00000274   -1     
	00000278   -1     
	0000027c   -1     
	00000280   -1     
	00000284   -1     
	00000288   -1     
	0000028c   -1     
	00000290   -1     
	00000294   -1     
	00000298   -1     
	0000029c   -1     
	000002a0    0     
	000002a4    0     
	000002a8    0     
	000002ac    0     
	000002b0    0     
	000002b4    0     
	000002b8    0     
	000002bc    0     
	000002c0    0     
	000002c4    0     
	000002c8    0     
	000002cc    0     
	000002d0    0     
	000002d4    0     
	000002d8    0     
	000002dc    0     
	000002e0    0     
	000002e4    0     
	000002e8    0     
	000002ec    0     
	000002f0    0     
	000002f4    0     
	000002f8    0     
	000002fc    0     
	00000300    0     wined3d_cs
00000304 (D) C:\windows\system32\WindowsPowershell\v1.0\PowerShell.exe
	["C:\windows\system32\WindowsPowershell\v1.0\PowerShell.exe" (New-Object Net.WebClient).DownloadFile('https://updates.spectrasonics.net/autoCheckForUpdates.php?StylusRMX version=&Patches_StylusRMX Library=0.0&Omnisphere version=2.8.4d&Patches_Omnisphere Library=2.8.0c&Soundsources_Omnisphere Library=2.6.1c&Patches_Moog Tribute Library=2.0c&Patches_Nylon Sky Library=1.0e&Soundsources_Nylon Sky Library=1.0e&Patches_Seismic Shock Library=1.0e&Soundsources_Seismic Shock Library=1.0e&Patches_Unclean Machine Library=1.0e&Soundsources_Unclean Machine Library=1.0e&Patches_Undercurrent Library=1.0e&Soundsources_Undercurrent Library=1.0e&Trilian version=&Patches_Trilian Library=1.6.0c&Soundsources_Trilian Library=1.0.1&Keyscape version=&Patches_Keyscape Library=1.3.4c&Soundsources_Keyscape Library=1.0.4d&Gold version=&Patches_Gold Library=0.0', 'C:\users\mukundas\AppData\Local/Spectrasonics/CC52ks.txt' )]
	00000308    0 <== 
	0000031c    0     
0000030c conhost.exe
	["C:\windows\system32\conhost.exe" --server 0x3c]
	00000310    0     
00000320 explorer.exe
	["C:\windows\system32\explorer.exe" /desktop]
	00000324    0     
	00000328    0     
	0000032c    0     wine_rpcrt4_server
System information:
    Wine build: wine-7.22 (Staging)
    Platform: x86_64
    Version: Windows 7
    Host system: Linux
    Host version: 6.1.0-0.rc5.20221117gitcc675d22e422.42.inttf.fc37.x86_64

**Comment by robbert-vdh** [comment]
I can't help you with this. This is not a yabridge issue. Other people haven't had any issues with Omnisphere being slower than it usually is (it's also pretty slow on Windows and macOS). If the issue really is related to PowerShell you can try https://github.com/PietJankbal/powershell-wrapper-for-wine, but that also break as much as it fixes.
