### ISSUE TITLE
Plugins doesn't start

### ISSUE THREAD

**Issue by wineTGH** [robbert-vdh/yabridge#221]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### What did you expect to happen?

Plugin just work.

### What actually happened?

The plugin does not start. When I tried start "yabridge-host.exe" it gives me this error: `128:err:sync:RtlpWaitForCriticalSection`.

### Operating system

Arch

### How did you install yabridge?

via pacman

### yabridge version

4.0.2-1

### yabridgectl version

4.0.2-1

### Wine version

wine 7.22

### Plugin

Any

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Any

### Desktop environment or WM

Gnome on Wayland

### Debug log

23:09:01 [Cassette Transport-AVYagnuv] Initializing yabridge version 4.0.2
23:09:01 [Cassette Transport-AVYagnuv] library:       '/usr/lib/libyabridge-vst3.so'
23:09:01 [Cassette Transport-AVYagnuv] host:          '/usr/bin/yabridge-host.exe'
23:09:01 [Cassette Transport-AVYagnuv] plugin:        '/home/winet/.win-plugins/generic/drive_c/Program Files/Common Files/VST3/Cassette Transport.vst3'
23:09:01 [Cassette Transport-AVYagnuv] plugin type:   'VST3'
23:09:01 [Cassette Transport-AVYagnuv] realtime:      'yes'
23:09:01 [Cassette Transport-AVYagnuv] sockets:       '/run/user/1000/yabridge-Cassette Transport-AVYagnuv'
23:09:01 [Cassette Transport-AVYagnuv] wine prefix:   '/home/winet/.win-plugins/generic'
23:09:01 [Cassette Transport-AVYagnuv] wine version:  '7.22'
23:09:01 [Cassette Transport-AVYagnuv] 
23:09:01 [Cassette Transport-AVYagnuv] config from:   '<defaults>'
23:09:01 [Cassette Transport-AVYagnuv] hosting mode:  'individually, 64-bit'
23:09:01 [Cassette Transport-AVYagnuv] other options: '<none>'
23:09:01 [Cassette Transport-AVYagnuv] 
23:09:01 [Cassette Transport-AVYagnuv] Enabled features:
23:09:01 [Cassette Transport-AVYagnuv] - bitbridge support
23:09:01 [Cassette Transport-AVYagnuv] - VST3 support
23:09:01 [Cassette Transport-AVYagnuv] 
23:10:15 [MT-PowerDrumKit-136Ncklt] Initializing yabridge version 4.0.2
23:10:15 [MT-PowerDrumKit-136Ncklt] library:       '/usr/lib/libyabridge-vst3.so'
23:10:15 [MT-PowerDrumKit-136Ncklt] host:          '/usr/bin/yabridge-host.exe'
23:10:15 [MT-PowerDrumKit-136Ncklt] plugin:        '/home/winet/.win-plugins/generic/drive_c/Program Files/Common Files/VST3/MT-PowerDrumKit.vst3'
23:10:15 [MT-PowerDrumKit-136Ncklt] plugin type:   'VST3'
23:10:15 [MT-PowerDrumKit-136Ncklt] realtime:      'yes'
23:10:15 [MT-PowerDrumKit-136Ncklt] sockets:       '/run/user/1000/yabridge-MT-PowerDrumKit-136Ncklt'
23:10:15 [MT-PowerDrumKit-136Ncklt] wine prefix:   '/home/winet/.win-plugins/generic'
23:10:15 [MT-PowerDrumKit-136Ncklt] wine version:  '7.22'
23:10:15 [MT-PowerDrumKit-136Ncklt] 
23:10:15 [MT-PowerDrumKit-136Ncklt] config from:   '<defaults>'
23:10:15 [MT-PowerDrumKit-136Ncklt] hosting mode:  'individually, 64-bit'
23:10:15 [MT-PowerDrumKit-136Ncklt] other options: '<none>'
23:10:15 [MT-PowerDrumKit-136Ncklt] 
23:10:15 [MT-PowerDrumKit-136Ncklt] Enabled features:
23:10:15 [MT-PowerDrumKit-136Ncklt] - bitbridge support
23:10:15 [MT-PowerDrumKit-136Ncklt] - VST3 support
23:10:15 [MT-PowerDrumKit-136Ncklt]

**Comment by robbert-vdh** [comment]
You're using an old yabridge version (4.0.2) with a Wine version (7.22) that contains a [bug](https://bugs.winehq.org/show_bug.cgi?id=53912) that breaks yabridge. Yabridge 5.0.2 contains workarounds for those bugs, or you can [downgrade](https://github.com/robbert-vdh/yabridge#downgrading-wine) to Wine Staging 7.20. (but you probably still update yabridge)
