### ISSUE TITLE
REAPER not loading VST3 plugins if in the same folder as VST2 plugins

### ISSUE THREAD

**Issue by RodrigueVaillant** [robbert-vdh/yabridge#223]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I tend to prefer adding my plugins to a folder inside my Documents folder instead of inside a WINE prefix. With version 4, I can dump all plugins in such a folder regardless of their type. With version 5.0.2, REAPER will see my VST2 plugins but fail to see VST3 plugins. If I split VST2 and VST3 plugins in different folders, REAPER then can see all of them.

### What did you expect to happen?

I expected to see all my plugins.

### What actually happened?

I only could see VST2 plugins.

### Operating system

Endeavour OS

### How did you install yabridge?

AUR

### yabridge version

5.0.2

### yabridgectl version

5.0.2

### Wine version

7.20

### Plugin

All.

### Plugin type

both VST2 and VST3

### Plugin architecture

both 64-bit and 32-bit

### Host

REAPER 6.71

### Anything else?

I cannot reproduce this bug since I've downgraded to version 4.0.2, then upgraded to version 5.0.2. Now it seems to work fine; it simply didn't when I installed 5.0.2 on a fresh OS.

**Comment by robbert-vdh** [comment]
There's too little information here to help you, sorry. But if the plugin files do exist in `~/.vst3/yabridge` and `~/.vst/yabridge` and they work fine with other DAWs, then it's on REAPER.
