### ISSUE TITLE
Yabridgectl Get Wrong With Wine-7.22

### ISSUE THREAD

**Issue by LiTEiTStudio** [robbert-vdh/yabridge#224]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I use wine 7.20 and bitwig studio to work on my Manjaro Linux,everything work fine
Yesterday I updated to wine 7.22 and I found that I stuck in `yabridgectl sync` or `yabridgectl sync --prune`when I try to sync my vst plugins.
I try to run my vst plugin in my DAWs but I stuck too.
I also found that when I run `yabridge-host.exe` and `yabridge-host-32.exe',they also stuck.
After rolling back to wine 7.20,everything became perfect again.
I think that is something change in Wine make`yabridge-host.exe` cannot work.

### What did you expect to happen?

Run `yabridgectl sync` and sync all plugins without errors

### What actually happened?

It told me `Finished setting up xxx plugins` and stuck,didn't exit
When I try to use my vst plugins in DAWs,stuck too

### Operating system

Manjaro

### How did you install yabridge?

packam

### yabridge version

5.0.2

### yabridgectl version

4.0.2

### Wine version

Wine Staging 7.22

### Plugin

All

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Bitwig Studio 4.4.0

### Desktop environment or WM

KDE 5.26.4

### GPU model

NVIDIA RTX 3070 Laptop

### GPU drivers and kernel

video-nvidia

**Comment by robbert-vdh** [comment]
You're using yabridge 4.0.2. Either update to the latest version, or [downgrade](https://github.com/robbert-vdh/yabridge#downgrading-wine) to Wine Staging 7.20.
