### ISSUE TITLE
Can't load Arturia Synths plugins

### ISSUE THREAD

**Issue by wineTGH** [robbert-vdh/yabridge#225]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I can't get any of the plugins to work. In bitwig they crash with the error "Could not initialize component: kResultFalse". In other DAWs plugins are not displayed in the list.

### What did you expect to happen?

Working plugin

### What actually happened?

Crashes with error "Could not initialize component: kResultFalse" (Bitwig Studio only)

### Operating system

Arch

### How did you install yabridge?

AUR yabridge-bin

### yabridge version

5.0.2

### yabridgectl version

5.0.2

### Wine version

wine-7.22

### Plugin

Arturia Synths Collection

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Any

### Desktop environment or WM

Gnome on Wayland

### Debug log

PluginHost: Starting new audio thread for processing plugin 0
Successfully set thread realtime priority to 50
00:18:12 [Mini V3-3CNOSZmo] Initializing yabridge version 5.0.2
00:18:12 [Mini V3-3CNOSZmo] library:       '/usr/lib/libyabridge-vst3.so'
00:18:12 [Mini V3-3CNOSZmo] host:          '/usr/bin/yabridge-host.exe'
00:18:12 [Mini V3-3CNOSZmo] plugin:        '/home/winet/.win-plugins/arturia/drive_c/Program Files/Common Files/VST3/Arturia/Mini V3.vst3'
00:18:12 [Mini V3-3CNOSZmo] plugin type:   'VST3'
00:18:12 [Mini V3-3CNOSZmo] realtime:      'yes'
00:18:12 [Mini V3-3CNOSZmo] sockets:       '/run/user/1000/yabridge-Mini V3-3CNOSZmo'
00:18:12 [Mini V3-3CNOSZmo] wine prefix:   '/home/winet/.win-plugins/arturia'
00:18:12 [Mini V3-3CNOSZmo] wine version:  '7.22'
00:18:12 [Mini V3-3CNOSZmo] 
00:18:12 [Mini V3-3CNOSZmo] config from:   '<defaults>'
00:18:12 [Mini V3-3CNOSZmo] hosting mode:  'individually, 64-bit'
00:18:12 [Mini V3-3CNOSZmo] other options: '<none>'
00:18:12 [Mini V3-3CNOSZmo] 
00:18:12 [Mini V3-3CNOSZmo] Enabled features:
00:18:12 [Mini V3-3CNOSZmo] - bitbridge support
00:18:12 [Mini V3-3CNOSZmo] - CLAP support
00:18:12 [Mini V3-3CNOSZmo] - VST3 support
00:18:12 [Mini V3-3CNOSZmo] 
00:18:12 [Mini V3-3CNOSZmo] [Wine STDERR] Initializing yabridge host version 5.0.2
00:18:12 [Mini V3-3CNOSZmo] [Wine STDERR] Preparing to load VST3 plugin at '/home/winet/.win-plugins/arturia/drive_c/Program Files/Common Files/VST3/Arturia/Mini V3.vst3'
00:18:13 [Mini V3-3CNOSZmo] [Wine STDERR] Finished initializing '/home/winet/.win-plugins/arturia/drive_c/Program Files/Common Files/VST3/Arturia/Mini V3.vst3'
00:18:13 [Mini V3-3CNOSZmo] [Wine STDERR] 0144:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011DA60 1 C) semi-stub
00:18:13 [Mini V3-3CNOSZmo] [Wine STDERR] 0144:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00:18:13 [Mini V3-3CNOSZmo] [Wine STDERR] 0144:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011DAA0 1 C) semi-stub
00:18:13 [Mini V3-3CNOSZmo] [Wine STDERR] 0144:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011D700 1 C) semi-stub
00:18:13 [Mini V3-3CNOSZmo] [Wine STDERR] 0174:fixme:ole:CoInitializeSecurity 0000000000000000, -1, 0000000000000000, 0000000000000000, 0, 3, 0000000000000000, 0, 0000000000000000 stub
00:18:13 [Mini V3-3CNOSZmo] [Wine STDERR] 0174:fixme:wbemprox:client_security_SetBlanket 00000001ED49FE40, 0000000001086130, 10, 0, (null), 3, 3, 0000000000000000, 0
00:18:13 [Mini V3-3CNOSZmo] [Wine STDERR] 0174:fixme:wbemprox:client_security_Release 00000001ED49FE40
00:18:13 [Mini V3-3CNOSZmo] [Wine STDERR] 0174:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0000000002DAF4A0 1 C) semi-stub
00:18:13 [Mini V3-3CNOSZmo] [Wine STDERR] 0174:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0000000002DAF4A0 1 C) semi-stub
00:18:13 [Mini V3-3CNOSZmo] [Wine STDERR] 0144:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011D9B0 1 C) semi-stub
00:18:13 [Mini V3-3CNOSZmo] [Wine STDERR] 0144:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E510 1 C) semi-stub
00:18:13 [Mini V3-3CNOSZmo] [Wine STDERR] 0144:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E7C0 1 C) semi-stub
00:18:13 [Mini V3-3CNOSZmo] [Wine STDERR] 0180:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (00000000033FFBF0 1 C) semi-stub
00:18:13 [Mini V3-3CNOSZmo] [Wine STDERR] 017c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (00000000031FF880 1 C) semi-stub
00:18:13 [Mini V3-3CNOSZmo] [Wine STDERR] 017c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (00000000031FF650 1 C) semi-stub
00:18:13 [Mini V3-3CNOSZmo] [Wine STDERR] 017c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (00000000031FF590 1 C) semi-stub
PluginHost: Sending error message: Could not create plugin instance: Could not initialize component: kResultFalse
Sending a shutdown request to the plugin host
PluginHost: Shutting down...
PluginHost: Unloading plugin /home/winet/.vst3/yabridge/Arturia/Mini V3.vst3
PluginHost: Unloading plugin library /home/winet/.vst3/yabridge/Arturia/Mini V3.vst3

**Comment by robbert-vdh** [comment]
Open the Arturia Software Center you installed in `/home/winet/.win-plugins/arturia` (with that WINEPREFIX set), make sure the plugins are properly authorized.
