### ISSUE TITLE
EXD-80 crashes yabridge-host-32.exe

### ISSUE THREAD

**Issue by oldcastlehq** [robbert-vdh/yabridge#227]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Qtractor cannot scan EXD-80 plugin, resulting in a prograrm error message.

### What did you expect to happen?

Complet scan without error

### What actually happened?

![2022-12-25_20-37](https://user-images.githubusercontent.com/20318144/209485352-18e46af9-fcca-4066-9845-ac6a30e367e5.png)

### Operating system

Arch Linux

### How did you install yabridge?

AUR

### yabridge version

5.0.3

### yabridgectl version

5.0.3

### Wine version

7.22

### Plugin

EXD-80

### Plugin type

VST2

### Plugin architecture

32-bit

### Host

Qtractor 0.9.29  AND Ardour 7.2

### Desktop environment or WM

KDE Plasma

### Debug log

Unhandled exception: page fault on read access to 0x7d100438 in 32-bit code (0x7d100438).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7d100438 ESP:01f4fc2c EBP:01f4fc98 EFLAGS:00010216(  R- --  I   -A-P- )
 EAX:fa5c9394 EBX:01f4fcd0 ECX:7d100440 EDX:7d100438
 ESI:01f4fcd4 EDI:01f4fccc
Stack dump:
0x01f4fc2c:  7e75fc67 fa5c9394 01f4fd40 01f4fccb
0x01f4fc3c:  7e75fc3e 7d4c8f6c 01f4fc6c f7e1fe34
0x01f4fc4c:  f7c8c8aa 00000000 7d4c3b80 7d4c3b60
0x01f4fc5c:  7e2b6870 f7c8c940 7d4c8f6c 00000001
0x01f4fc6c:  f7c8c910 01f4fc60 00000000 00000000
0x01f4fc7c:  98762f00 7d100610 00000000 00000010
Backtrace:
=>0 0x7d100438 (0x01f4fc98)
  1 0x7e66a548 in yabridge-host-32 (+0x3a548) (0x01f4fef8)
  2 0x98762f00 (0x01f4fef8)
  3 0x7e65f99a in yabridge-host-32 (+0x2f99a) (0x01f4ff28)
  4 0x7b629140 in kernel32 (+0x29140) (0x01f4ff48)
  5 0x7bc5cb97 in ntdll (+0x5cb97) (0x01f4ff5c)
  6 0x7bc5d398 in ntdll (+0x5d398) (0x01f4ffec)
0x7d100438: xorb	%al,0x0(%eax,%edx,1)
Modules:
Module	Address			Debug info	Name (87 modules)
PE	01870000-01892000	Deferred        msacm32
PE	01cb0000-01d43000	Deferred        gdiplus
PE	025b0000-025bf000	Deferred        dh_max.sem
PE	027c0000-027dd000	Deferred        dh_envseg.sem
PE	027e0000-02800000	Deferred        fmlfo.sep
PE	02900000-02938000	Deferred        dh_multifilter2.sem
PE	02940000-02953000	Deferred        kdl_v2b.sem
PE	02960000-02973000	Deferred        kdl_show_v.sem
PE	02980000-02993000	Deferred        kdl_show_b.sem
PE	04fd0000-04fe3000	Deferred        kdl_ticker.sem
PE	051f0000-05206000	Deferred        dh_patcharray-float.sem
PE	05410000-05425000	Deferred        kdl_gf2gf.sem
PE	05630000-05643000	Deferred        kdl_delay_gf.sem
PE	05850000-05865000	Deferred        kdl_gf2l.sem
PE	05a70000-05a83000	Deferred        kdl_v2gb.sem
PE	05c90000-05ca3000	Deferred        kdl_f2gb.sem
PE	05eb0000-05ec3000	Deferred        kdl_show_gb.sem
PE	060d0000-060e3000	Deferred        kdl_v2gf.sem
PE	062f0000-06303000	Deferred        kdl_i2v.sem
PE	06510000-06529000	Deferred        dh_granulator.sem
PE	06730000-06745000	Deferred        dh_modulekey.sem
PE	10000000-107f6000	Deferred        exd-80
PE	62500000-62631000	Deferred        oleaut32
PE	64180000-64219000	Deferred        winspool
PE	64a80000-64abc000	Deferred        win32u
PE	65340000-6534a000	Deferred        msimg32
PE	65480000-65518000	Deferred        rpcrt4
PE	65680000-6572e000	Deferred        msvcrt
PE	66080000-660dc000	Deferred        shlwapi
PE	66380000-664bd000	Deferred        ole32
PE	66640000-6664d000	Deferred        version
PE	667c0000-667da000	Deferred        shcore
PE	66fc0000-66fd5000	Deferred        compstui
PE	67500000-6751b000	Deferred        imm32
PE	67bc0000-67d2a000	Deferred        comctl32
PE	684c0000-68522000	Deferred        combase
PE	68880000-68a49000	Deferred        user32
PE	69040000-6914e000	Deferred        comdlg32
PE	69840000-69883000	Deferred        advapi32
PE	6aac0000-6ab99000	Deferred        ucrtbase
PE	6bb40000-6bbc0000	Deferred        winex11
PE	6bbc0000-6bbeb000	Deferred        sechost
PE	6da80000-6db0c000	Deferred        gdi32
PE	6f240000-6f308000	Deferred        winmm
PE	704c0000-704ce000	Deferred        dwmapi
PE	70d80000-70db8000	Deferred        uxtheme
PE	71400000-71d40000	Deferred        shell32
PE	7b000000-7b2a7000	Deferred        kernelbase
PE	7b600000-7b661000	Dwarf           kernel32
PE	7bc00000-7bcad000	Dwarf           ntdll
ELF	7d000000-7d005000	Deferred        <wine-loader>
ELF	7d925000-7d932000	Deferred        libxcursor.so.1
ELF	7d967000-7d97c000	Deferred        libxi.so.6
ELF	7d97c000-7d98c000	Deferred        libxrandr.so.2
ELF	7d98c000-7d99a000	Deferred        libxrender.so.1
ELF	7d99a000-7daec000	Deferred        libx11.so.6
ELF	7db0f000-7db8d000	Deferred        winex11.so
ELF	7dcfd000-7dd28000	Deferred        libexpat.so.1
ELF	7dd28000-7dd7a000	Deferred        libfontconfig.so.1
ELF	7dd7a000-7de1b000	Deferred        libpcre2-8.so.0
ELF	7de1b000-7df74000	Deferred        libglib-2.0.so.0
ELF	7df74000-7e068000	Deferred        libharfbuzz.so.0
ELF	7e068000-7e0a5000	Deferred        libpng16.so.16
ELF	7e0a5000-7e200000	Deferred        win32u.so
ELF	7e43f000-7e462000	Deferred        libbrotlicommon.so.1
ELF	7e462000-7e52f000	Deferred        libfreetype.so.6
ELF	7e52f000-7e600000	Deferred        libm.so.6
ELF	7e600000-7e924000	Dwarf           yabridge-host-32<elf>
  \-PE	7e630000-7e924000	\               yabridge-host-32
ELF	7e924000-7e92b000	Deferred        winspool.so
ELF	7e92b000-7e941000	Deferred        libxext.so.6
ELF	7e941000-7e94f000	Deferred        libbrotlidec.so.1
ELF	7e94f000-7e961000	Deferred        libbz2.so.1.0
ELF	7e961000-7e97a000	Deferred        libz.so.1
ELF	7e97a000-7e981000	Deferred        libxdmcp.so.6
ELF	7e981000-7e986000	Deferred        libxau.so.6
ELF	7ee00000-7ee25000	Deferred        libgcc_s.so.1
ELF	7ee25000-7ee2a000	Deferred        libdl.so.2
ELF	7ee2a000-7ee56000	Deferred        libxcb.so.1
ELF	7ee59000-7ee61000	Deferred        libxfixes.so.3
ELF	7ee61000-7ee69000	Deferred        libxxf86vm.so.1
ELF	7ee79000-7f000000	Dwarf           libwine.so.1
ELF	f7c00000-f7e2b000	Deferred        libc.so.6
ELF	f7e2b000-f7e30000	Deferred        libpthread.so.0
ELF	f7eb1000-f7eb6000	Deferred        librt.so.1
ELF	f7eb6000-f7f5c000	Deferred        ntdll.so
ELF	f7f5e000-f7f94000	Deferred        ld-linux.so.2
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 yabridge-host-32.exe
	00000024    0     
	00000100    0     
	00000104    0     
	00000108    0     
	0000010c    0     
	00000110    0     
00000038 services.exe
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	0000004c    0     wine_rpcrt4_io
	00000070    0     wine_rpcrt4_io
	000000a4    0     wine_rpcrt4_io
	000000bc    0     wine_rpcrt4_io
	000000e0    0     wine_rpcrt4_io
00000044 winedevice.exe
	00000048    0     
	00000054    0     
	00000058    0     wine_sechost_service
	0000005c    0     
	00000060    0     
	00000064    0     
	000000c8    0     
00000068 winedevice.exe
	0000006c    0     
	00000074    0     
	00000078    0     wine_sechost_service
	0000007c    0     
	00000080    0     
	00000084    0     
	00000088    0     
	0000008c    0     
	00000090    0     
00000094 explorer.exe
	00000098    0     
	000000cc    0     
	000000d0    0     wine_rpcrt4_server
0000009c plugplay.exe
	000000a0    0     
	000000a8    0     
	000000ac    0     wine_sechost_service
	000000b0    0     wine_rpcrt4_server
000000b4 svchost.exe
	000000b8    0     
	000000c0    0     
	000000c4    0     wine_sechost_service
000000d8 rpcss.exe
	000000dc    0     
	000000e8    0     
	000000ec    0     wine_sechost_service
	000000f0    0     wine_rpcrt4_server
	000000f4    0     wine_rpcrt4_server
	000000f8    0     wine_rpcrt4_io
00000140 yabridge-host-32.exe
	00000144    0     
	00000148    0     
	0000014c    0     
	00000150    0     
	00000154    0     
	00000158    0     
00000188 start.exe
	0000018c    0     
00000190 yabridge-host.exe
	00000194    0     
	00000198    0     
	0000019c    0     
	000001a0    0     
	000001a4    0     
	000001a8    0     
	000001ac    0     
000001b0 (D) Z:\usr\bin\yabridge-host-32.exe
	000001b4    0     
	000001b8    0 <== 
	000001cc    0     
000001c4 conhost.exe
	000001c8    0     
System information:
    Wine build: wine-7.22
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 6.1.1-arch1-1

**Comment by robbert-vdh** [comment]
You forgot the debug log. Anyways, the plugin works fine for me in a clean Wine prefix with Wine Staging 8.0-rc2 with both Qtractor 0.9.29 and Ardour 7.2. So it's almost certainly an issue with your Wine installation, and not on yabridge's side.
