### ISSUE TITLE
Yabridge crashes REAPER on my system 

### ISSUE THREAD

**Issue by esc430** [robbert-vdh/yabridge#228]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Hi I have had yabridge on my computer for about six months and it was working great until the last couple days. When I try to use yabridge hosted plugin now REAPER crashe. I have not gotten any plugins to run in REAPER since this first happened. I downgrade wine to 7.20 and upgraded yabridge to 5.0.3 using `yabridge-bin` from AUR. I noticed in the terminal it says "Initalizing yabridge version 3.8.0" and then later it says "Initializing yabridge host version 5.0.3 (32-bit compatibility mode)" so I am wondering if I maybe need updated that somehow?  I run Manjaro which means I am no super techie and would really appreciate help getting yabridge to work again.

### What did you expect to happen?

REAPER to load plugins using yabridge.

### What actually happened?

REAPER crashes when I try to use yabridge synced plugins.

### Operating system

Manjaro

### How did you install yabridge?

AUR package

### yabridge version

5.0.3

### yabridgectl version

5.0.3

### Wine version

7.20

### Plugin

All of them

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

REAPER 6.73

### Debug log

Current output when I run REAPER and it crashes:
![new_yabridge-problem-terminal](https://user-images.githubusercontent.com/122053536/210872978-37184abb-0d32-47c2-a4e2-af3ff073bfe2.png)

Message when reaper crashes:
![yabridge-problem](https://user-images.githubusercontent.com/122053536/210872990-e8659285-dd2f-4a55-b715-c54a170238d5.png)
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/10355459/yabridge.log)

**Comment by robbert-vdh** [comment]
Yes, you're trying to use a pre-yabridge 4.0 version of yabridge with the latest yabridge-host binary. When you ran `yabridgectl sync` it would have told you about a bunch of leftover `.so` files and asked you to rerun the command with the `--prune` option to remove them.

**Comment by esc430** [comment]
It worked! Thank you so much!
