### ISSUE TITLE
The window of Roland TR-808 VSTi is cut off at the bottom.

### ISSUE THREAD

**Issue by Inqb8tr-jp** [robbert-vdh/yabridge#231]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

At first, when I push EDIT button of TR-808, a new window open which is placed on the bottom of the first window like this.
https://twitter.com/Inqb8tr_jp/status/1606888275947687936/photo/1
But it can be resolved by adding "editor_xembed = true" on yabridge.toml

After that the window of TR-808 is cut off at the bottom and can't be spread down further like this.
https://twitter.com/Inqb8tr_jp/status/1616824069927886850/photo/1

### What did you expect to happen?

The window should be changed size by the mouse.

### What actually happened?

The window can't be changed its size.

### Operating system

Manjaro

### How did you install yabridge?

AUR package

### yabridge version

5.0.2

### yabridgectl version

5.0.2

### Wine version

wine-7.22

### Plugin

Roland TR-808

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Carla-git 1:2.5.1.r58.gdc9b58b4c and Ardour 7.2

### Desktop environment or WM

Xfce 4.18pre2

### GPU model

AMD ATI Radeon Vega Series

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/10473403/yabridge.log)

**Comment by robbert-vdh** [comment]
In the log you sent the plugin never tries to resize the window. So if it should, then that's a bug with the plugin. I can't help with that.

**Comment by Inqb8tr-jp** [comment]
With the first post's log, I forgot to spread down TR-808 window at the time.
I don't know exactly about "What did you expect to happen?", because I don't have Windows environment.
Maybe It's automatically spread down the window to fit TR-808's window size.
Could you please check the log which has log level 2 and +editor option below again.
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/10477751/yabridge.log)

**Comment by robbert-vdh** [comment]
> With the first post's log, I forgot to spread down TR-808 window at the time. I don't know exactly about "What did you expect to happen?", because I don't have Windows environment. Maybe It's automatically spread down the window to fit TR-808's window size. Could you please check the log which has log level 2 and +editor option below again. [yabridge.log](https://github.com/robbert-vdh/yabridge/files/10477751/yabridge.log)

The plugin still doesn't request the window be made bigger. You'd see a line containing `audioMasterSizeWindow` if it did.

**Comment by Inqb8tr-jp** [comment]
OK. Thanks.
I will try contacting Roland, although they will probably ignore me.
Thank you.
