### ISSUE TITLE
Graphical glitches on plugin's popup windows

### ISSUE THREAD

**Issue by mrtnvgr** [robbert-vdh/yabridge#232]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

![](http://0x0.st/oFse.png)

![](http://0x0.st/oFsL.png)

### What did you expect to happen?

Normal behaviour

### What actually happened?

Strange black border around the windows

### Operating system

Gentoo Linux

### How did you install yabridge?

from "Releases" section

### yabridge version

5.0.3

### yabridgectl version

5.0.3

### Wine version

wine-7.22 (Staging)

### Plugin

All

### Plugin type

both VST2 and VST3

### Plugin architecture

both 64-bit and 32-bit

### Host

Reaper 6.68

### Desktop environment or WM

[qtile](https://github.com/qtile/qtile)

### GPU model

AMD ATI 05:00.0 Renoir

### GPU drivers and kernel

dxvk on 6.1.7-gentoo-dist

### Debug log

http://0x0.st/oFs1.log

**Comment by robbert-vdh** [comment]
You didn't mention it, but are you using Sway or some other wlroots based Wayland compositor? Their XWayland implementation has been broken for years, this is a known issue with Wine applications running under those compositors. I'm not aware of any workaround that doesn't involve switching to KDE Plasma. :wink:

**Comment by mrtnvgr** [comment]
> You didn't mention it, but are you using Sway or some other wlroots based Wayland compositor? Their XWayland implementation has been broken for years, this is a known issue with Wine applications running under those compositors. I'm not aware of any workaround that doesn't involve switching to KDE Plasma. :wink: 

I don't use wayland

**Comment by robbert-vdh** [comment]
Are you sure? Because I've only ever seen those artifacts in wlroots based compositors, like the one you're using (you're using qtile, missed it the first time I read it, sorry!). If you're not sure, run `loginctl`, note the session ID (it's 2 in my case), and then run `loginctl show-session SESSION_ID -p Type`. I'm convinced you're using Wayland without knowing it.

**Comment by mrtnvgr** [comment]
> Are you sure? Because I've only ever seen those artifacts in wlroots based compositors, like the one you're using (you're using qtile, missed it the first time I read it, sorry!). If you're not sure, run `loginctl`, note the session ID (it's 2 in my case), and then run `loginctl show-session SESSION_ID -p Type`. I'm convinced you're using Wayland without knowing it.

```console
[user@tux ~] :: loginctl
SESSION  UID USER SEAT  TTY
      1 1000 user seat0 tty1

1 sessions listed.
```

```console
[user@tux ~] :: loginctl show-session 1 -p Type
Type=tty
```

I usually use picom as my compositor, but I disabled it on screenshots.

**Comment by mrtnvgr** [comment]
Wayland is not installed on my system.
```console
[user@tux ~] :: emerge -p wayland

These are the packages that would be merged, in order:

Calculating dependencies... done!
Dependency resolution took 2.90 s.

[ebuild  N     ] dev-util/wayland-scanner-1.21.0
[ebuild  N     ] dev-libs/wayland-1.21.0-r1  USE="-doc -test" ABI_X86="(64) -32 (-x32)"

```

**Comment by robbert-vdh** [comment]
Well anyways, I can't help you with bugs in your WM or compositor. You'll need to report this to qtile or picom. Something's either messing with Wine's window positioning in a way it shouldn't (remember that Windows GUIs consists of a bunch of tiny floating Windows that look like they're a single window, and Wine's X11 implementation thus does the same thing), or transparent borders aren't being composited correctly. The latter seems like the likely culprit.
