### ISSUE TITLE
Cannot build 5.0.3 with wine 8.0

### ISSUE THREAD

**Issue by hardyharz3n** [robbert-vdh/yabridge#233]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Running

`wine-8.0-169-gaabdb15458a (Staging)`

I can't seem to upgrade to yabridge 5.0.3, getting 

`ERROR: Problem encountered: Building this version of yabridge against Wine 8.0
would result in nonfunctional binaries. Either build yabridge 5.0.2 with Wine 7.22, or switch to Wine 8.0-rc2+.`

Seems unusual, as 8.0-169 > 8.0-rc2+, or so I would expect. Have you come across this error before, or could you point me to wine version that plays well here?

### What did you expect to happen?

normal update

### What actually happened?

error message with logically conflicting version reqs

### Operating system

Arch

### How did you install yabridge?

AUR

### yabridge version

5.0.3

### yabridgectl version

3.8.1

### Wine version

wine-8.0-169-gaabdb15458a (Staging)

### Plugin

Any

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Bitwig 4.4.6

**Comment by hardyharz3n** [comment]
Uhm...hold that thought. AUR actually says ' yabridge-git-5.0.2.r14.g399db4d2-1' – where to obtain 5.0.3?

**Comment by hardyharz3n** [comment]
Looks like I'm stupid. Okay, fetching yabridge-bin now...

**Comment by robbert-vdh** [comment]
Thanks for bringing this to my attention! Apparently Meson's version comparison treats `8.0` as a lower version than `8.0rc2`. I fixed this in 29acd40a9add635e2cb40ecc54c88d65604a7a2a.

**Comment by hardyharz3n** [comment]
Awesome, but do note  that I accidentally tried with a 5.0.2 (thinking it was 5.0.3), so it kinda was the expected behavior, after all.

In any case, I am now successfully running the 5.0.3 bin with 8.0 wine, and apart from some (but not all) old VST2s throwing errors, all is dandy.
