### ISSUE TITLE
yabridgectl's error messages not readable with "bright mode" terminal theme

### ISSUE THREAD

**Issue by picsel2** [robbert-vdh/yabridge#235]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I use Gnome Terminal with it's default bright colour palette.

Parts of the error message appear blank. This is caused by [these lines](https://github.com/robbert-vdh/yabridge/blob/cfca235e663ba5d76c215d8322e307a310f68aa7/tools/yabridgectl/src/util.rs#L457) hardcoding a white text colour.

### What did you expect to happen?

A readable error message to be printed.

### What actually happened?

The message is blank.

![Bildschirmfoto vom 2023-02-07 11-00-21](https://user-images.githubusercontent.com/4233457/217213722-741e1f54-4df2-4b68-b4ab-81b60d9f1cf4.png)

### Operating system

Fedora 37

### How did you install yabridge?

built from source

### yabridge version

5.0.3 (cfca235e663ba5d76c215d8322e307a310f68aa7)

### yabridgectl version

5.0.3 (cfca235e663ba5d76c215d8322e307a310f68aa7)

### Wine version

wine-8.0 (Staging)

### Plugin

null

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

null

### Anything else?

I hope not to start a dark vs. bright mode battle :smile:

**Comment by picsel2** [comment]
The help text printed with `yabridgectl set --help` has this problem, too.

**Comment by robbert-vdh** [comment]
That's an issue with your terminal's color scheme. If you go to the settings you can select another color scheme or change the settings. They likely also have a 'show bright as bold' option in addition to having different colors for bright white. If you have a white background, then the white text color shouldn't also be set to the same color white.
