### ISSUE TITLE
Build failing on Arch Linux

### ISSUE THREAD

**Issue by GideonWolfe** [robbert-vdh/yabridge#237]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

When attempting to install the [yabridge-git](https://aur.archlinux.org/packages/yabridge-git) package from the AUR, the build fails with the following error:

```
[35/35] Linking target yabridge-host-32
FAILED: yabridge-host-32
wineg++  -o yabridge-host-32 yabridge-host-32.p/meson-generated_yabridge-host-32-unity0.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -mwindows -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -Wl,--start-group src/common/vst3/libvst3_sdk_hosting_wine_32bit.a src/common/vst3/libvst3_base_wine_32bit.a src/common/vst3/libvst3_pluginterfaces_wine_32bit.a -m32 -lrt /usr/lib/libtomlplusplus.so -lole32 -lpthread -lxcb -lshell32 -luuid -Wl,--end-group
/usr/bin/ld: /usr/lib/libtomlplusplus.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/g++ failed
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'yabridge-git-5.0.2.r14.g399db4d2-1':
error: packages failed to build: yabridge-git-5.0.2.r14.g399db4d2-1
```

### What did you expect to happen?

The build to complete successfully

### What actually happened?

The above error

### Operating system

Linux ares 6.1.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000 x86_64 GNU/Linux

### How did you install yabridge?

AUR helper `paru`

### yabridge version

N/A (fails to install)

### yabridgectl version

5.0.3

### Wine version

wine-8.1 (Staging)

### Plugin

All

### Plugin type

VST2

### Plugin architecture

both 64-bit and 32-bit

### Host

REAPER

### Desktop environment or WM

i3wm

### GPU model

GeForce RTX 3050 Mobile

**Comment by robbert-vdh** [comment]
Arch has recently updated their tomlplusplus package, and tomlplusplus recently added shared library versions that are used instead of the headers only version on Arch. After fighting with tomlplusplus a bit everything should build fine again, both with the included tomlplusplus version and on Arch. Let me know if you still have issues building the package.
