### ISSUE TITLE
Spitfire plugin not working (can't load library files)

### ISSUE THREAD

**Issue by SimplyNaOH** [robbert-vdh/yabridge#239]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

This is mentioned in the known issues:

> If Spitfire Audio plugins like BBC Symphony Orchestra and LABS are unable to load their sample libraries (Error #X: Something went wrong), then you can try reinstalling those plugins to a new, clean Wine prefix. To avoid potential confusion, make sure to uninstall the Spitfire software along with the VST2 and VST3 plugins from your main Wine prefix first.

But this did not work. Also, it is unclear if the suggested fix is to do a full install (sample library + plugin) on a new Wine prefix, or keep the sample library somewhere else and install only the plugin in the new prefix. Tried both nevertheless without success.

It sporadically worked a couple of times by using the Spitfire app `repair` option; but could not reproduce.

### What did you expect to happen?

Spitfire plugin (BBC Symphony Orchestra) once opened in Reaper works.

### What actually happened?

Spitfire plugin fails to load sample library; errors look like:
```
[18 Mar 2023 19:12:53.304]	(tid:000000000000011c) "BBC Symphony Orchestra" : failed to load patch config : C:\users\naoh\Spitfire\Spitfire Audio - BBC Symphony Orchestra\Patches\v1.5.0\Core Brass\BBCSOC_BRASS.patches.zconfig
...
[18 Mar 2023 19:12:53.312]	(tid:000000000000011c) "BBC Symphony Orchestra" : failed to load preset config : C:\users\naoh\Spitfire\Spitfire Audio - BBC Symphony Orchestra\Presets\v1.5.0\Core Brass\BBCSOC_BRASS.presets.zconfig
...
```

### Operating system

EndeavourOS

### How did you install yabridge?

pacman

### yabridge version

5.0.4

### yabridgectl version

5.0.4

### Wine version

wine-8.3 (Staging)

### Plugin

Spitfire BBC Symphony Orchestra 

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Reaper

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/11009275/yabridge.log)

**Comment by SimplyNaOH** [comment]
Ok, sorry for not trying this before; with `wine-8.1 (Staging)` the problem is gone...

**Comment by robbert-vdh** [comment]
Great! Spitfire plugins have always been a bit flaky.
