### ISSUE TITLE
VSTs only load when debugging

### ISSUE THREAD

**Issue by Micjanov** [robbert-vdh/yabridge#241]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Hi and thank you very much for this program, first of all!

Due to my setup, I expected 'bugs' to arise but who knows, maybe you can help. I use Bitwig on Fedora 37 and to get yabridge working, I installed Bitwig via [this script that converts the .deb package and installs the necessary dependencies](https://github.com/teervo/bitwig-fedora) instead of via Flathub. 

The VSTs are recognized, but they don't load when I try to apply them:
'Could not create plugin instance: Failed to initialize VST plug-in' ... '<VST>.so: ModuleEntry() returned false'

I tried to run it with the debug logging (`rm -f /tmp/yabridge.log; env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=2+editor bitwig-studio`), but the plug-ins are perfectly usable while running Bitwig like this! So I wanted to know what causes this and how I can run Bitwig without creating the log on every start up.

I also use yabridge on REAPER and everything works fine there.

### What did you expect to happen?

I expected the plug-ins to crash due to my cumbersome Bitwig installation.

### What actually happened?

The plug-ins actually run, but only when I allow yabridge to make a debug log.

### Operating system

Fedora 37

### How did you install yabridge?

https://copr.fedorainfracloud.org/coprs/patrickl/yabridge-stable/

### yabridge version

5.0.4

### yabridgectl version

5.0.4

### Wine version

wine-8.0

### Plugin

No specific one

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Bitwig Studio 4.4.8 (No Flatpak)

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/11068521/yabridge.log)

**Comment by robbert-vdh** [comment]
Try grabbing a log with only `YABRIDGE_DEBUG_FILE` set. And you'll also need to fix your realtime priviliges and memory locking setup.

**Comment by Micjanov** [comment]
> Try grabbing a log with only `YABRIDGE_DEBUG_FILE` set. And you'll also need to fix your realtime priviliges and memory locking setup.

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/11076488/yabridge.log)

Here is the log with only `YABRIDGE_DEBUG_FILE` set. 

To resolve the memlock issue, I installed the [realtime-setup package for fedora](https://koji.fedoraproject.org/koji/buildinfo?buildID=1898001) . There's no documentation that I can find for the package. Running it in the terminal gives me this message: `realtime-setup: Not running on a RHEL-RT kernel, skipping rt-specific tunings.` so I am a bit lost there.

**Comment by robbert-vdh** [comment]
Is this still an issue? For things that are likely specific to your configuration and/or that aren't really yabridge issues it's usually easier and faster to just ask in the yabridge Discord.

**Comment by Micjanov** [comment]
> Is this still an issue? For things that are likely specific to your configuration and/or that aren't really yabridge issues it's usually easier and faster to just ask in the yabridge Discord.

Will do!
