### ISSUE TITLE
Total freeze on Pop!_OS with Bitwig, WINE and yabridge

### ISSUE THREAD

**Issue by nipikamusic** [robbert-vdh/yabridge#242]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I am running Bitwig on the latest Pop!_OS (very similar to Ubuntu). I installed WINE and yabridge and followed all instructions (I think). Bitwig runs totally fine when I am using only Linux-native plugins. While most of my other plugins work through yabridge and WINE, the system will randomly completely freeze up and force a hard reset of the computer. Support from Pop!_OS looked through the log files (including Pipewire) and couldn't find any error. The freeze must happen with yabridge and/or WINE. Would you be able to help with this? Are there any log files I can send you?

### What did you expect to happen?

No freeze

### What actually happened?

See above

### Operating system

Pop!_OS 22.04 LTS

### How did you install yabridge?

directly from the releases

### yabridge version

5.0.3

### yabridgectl version

5.0.3

### Wine version

8.5 staging

### Plugin

Unsure which one causes the freeze

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Bitwig Studio 4.4.8

**Comment by robbert-vdh** [comment]
Is this still an issue? And are you using regular Bitwig or did you install Flatpak version? If you used Flatpak, try installing the .deb instead.

**Comment by nipikamusic** [comment]
Yes, it still happens from time to time and I not exactly sure if it's one particular plugin, yabridge or Wine doing it. I am using the latest .deb directly from Bitwig.

------- Original Message -------

**Comment by robbert-vdh** [comment]
There's not much I can do to help then. I'd watch your memory usage and CPU utilization. Perhaps either of those is maxing out when it happens.

**Comment by nipikamusic** [comment]
Are there any log files related to yabridge or wine that can be inspected when it happens?
It appears to be a memory leak because as soon as it freezes up the fan comes on really high. And this behaviour only happens when a plugin is running through yabridge/wine.

------- Original Message -------

**Comment by robbert-vdh** [comment]
Win and yabridge print to STDERR. And you can access system logs through journalctl.

**Comment by nipikamusic** [comment]
Can you be a bit more specific what logs I can be looking for in particular and how?

------- Original Message -------

**Comment by nipikamusic** [comment]
Thank you

------- Original Message -------

**Comment by robbert-vdh** [comment]
Closing since this is an old issue.

If you still need help with something, feel free to join the Discord.
