### ISSUE TITLE
serum and d2d1

### ISSUE THREAD

**Issue by dnodno** [robbert-vdh/yabridge#243]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

disabling d2d1 for serum breaks other plugins like dune 3, spire ect
is there a way to disable d2d1 for serum only?

### Operating system

arch

### How did you install yabridge?

pacman

### yabridge version

5.0.4-1

### yabridgectl version

5.0.4-1

### Wine version

wine-8.5 (staging)

### Plugin

serum, lfotool, dune 3, spire

### Plugin type

both VST2 and VST3

### Plugin architecture

both 64-bit and 32-bit

### Host

Bitwig 4.4

### Desktop environment or WM

KDE Plasma 5.27.4

### GPU model

GTX 950

### GPU drivers and kernel

latest from nvidia package from pacman

**Comment by durutti** [comment]
install it to a different wineprefix
