### ISSUE TITLE
properly scale VST2 plugins on 4K display

### ISSUE THREAD

**Issue by jy-lefort** [robbert-vdh/yabridge#245]
### Feature description

Congratulations for your work on yabridge, most plugins run great.

However, many VST2 plugins are too small on a 4K display. Setting the DPI in winecfg has no effect on these. My DAW is Renoise.

I'd assume it's a problem with older plugins and yabridge cannot help with that? I am a proficient C++20 dev so if something can be done, it would be nice if you could give me some pointers.

Thanks!

**Comment by rw-bowman** [comment]
I am having this issue as well,  in fact nothing is scaling really. a few plugins that have an internal setting will. That is it on a 4k display. Wintdows menus will scale with the DPI setting but none of the plugins do. Also tried changing scaling via the group and config files instructions for yabridge, this also did not work.

**Comment by robbert-vdh** [comment]
Yes, there's not much you can do about this. Some plugin GUIs detect Wine's higher font DPI setting and scale accordingly, some won't. Some VST3 and CLAP plugins will use the scaling setting set by the host, some won't. In general with Wine it's easiest to avoid having to deal with DPI scaling entirely.

**Comment by robbert-vdh** [comment]
Closing since there's not really anything I can do about this on yabridge's side.
