### ISSUE TITLE
Waves VST3 Plugins Do Not Load In Bitwig, But Waves VST2 Plugins Do

### ISSUE THREAD

**Issue by dungeon-mystic** [robbert-vdh/yabridge#246]
- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

EDIT: After examining the debug output myself, I found that WaveShell requires d2d1.dll. Unfortunately I'm also using Serum, which according to yabridge docs requires d2d1 to be disabled. I'm not sure how to proceed with this.

I found that WavesCentral installs both versions of WaveShell in $HOME/.wine/drive_c/Program Files (x86)/Waves/WaveShells V14 instead of the normal Windows VST folders. After adding that folder to yabridge's directories and syncing, Bitwig picked up WavesCentral VST2, but not WavesCentral VST3.  

`yabridgectl status` output (abridged):  
```
$HOME/.wine/drive_c/Program Files/Common Files/VST3/
  Serum.vst3 :: VST3, bundle, 64-bit, synced

$HOME/.wine/drive_c/Program Files (x86)/Waves/WaveShells V14/
  WaveShell2/WaveShell1-VST 14.12_x64.dll :: VST2, 64-bit, synced
  WaveShell3/WaveShell1-VST3 14.12_x64.vst3 :: VST3, legacy, 64-bit, synced
```

I deleted ~/BitwigStudio/index and the VST metadata files in ~/.BitwigStuio/cache, then ran Bitwig.

When I start Bitwig, yabridge pops up with an error saying that WaveShell1-VST3 14.12_x64.so caused a problem and to check the DAW's logs.

Bitwig's log (~/BitwigStudio/engine.log):
```
[Fri May 05 11:17:25 CDT 2023] Starting audio engine.
Using asoundlib-1.2.6.1
Detected instruction set: x64, SSE41
Registering modules...
Connecting to server :1234
Loading audio system...
Loading audio host API plug-in: PipeWire from /opt/bitwig-studio/lib/audio-host-api-plugins/PipeWireAudioHostApiPlugin.so
[pipewire] info: Using PipeWire library version: 0.3.48
[pipewire] info: Core info: name pipewire-0 version 0.3.48
Opening audio device using PipeWire driver model ...
Opening audio device...
[pipewire] info: Filter and ports created
[pipewire] info: Sample rate and block size set: 48000.0, 1024
Audio device opened with sample rate 48000.0 and block size 1024
Device opened with sample rate 48000.0, block size 1024, input channel count 256, output channel count 256
Connecting to active project 8...
Error setting realtime priority for thread to -10
Error setting realtime priority for thread to -10
Error setting realtime priority for thread to -10
Error setting realtime priority for thread to -10
Error setting realtime priority for thread to -10
Error setting realtime priority for thread to -10
Error setting realtime priority for thread to -10
Error setting realtime priority for thread to -10
Error setting realtime priority for thread to -10
Error setting realtime priority for thread to -10
Error setting realtime priority for thread to -10
Error setting realtime priority for thread to -10
Error setting realtime priority for thread to -10
Error setting realtime priority for thread to -10
Error setting realtime priority for thread to -10
Error setting realtime priority for thread to -10
Connected to project 8
Set active project to 0
Disconnecting from project 8...
Stopped project client
Scheduling project delete
Deleting project
Project deleted
Project disconnecting from has been deleted
Disconnected from project 8
Closing audio device ...
```

I found some solutions in this [ancient thread]() but they didn't help with the current version.  

### What did you expect to happen?

WaveShell VST3 and its nested plugins should load in Bitwig Studio.

### What actually happened?

WaveShell VST2 and its plugins load, but the VST3 plugins do not. Serum VST3 does load, however.  

### Operating system

Mint 21.1

### How did you install yabridge?

From releases

### yabridge version

5.0.4 (not aware if this is actually different than yabrigectl version)

### yabridgectl version

5.0.4

### Wine version

wine-8.5 (Staging)

### Plugin

WaveShell

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Bitwig Studio 4.4.10

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/11408501/yabridge.log)

**Comment by robbert-vdh** [comment]
> EDIT: After examining the debug output myself, I found that WaveShell requires d2d1.dll. Unfortunately I'm also using Serum, which according to yabridge docs requires d2d1 to be disabled. I'm not sure how to proceed with this.

Use multiple Wine prefixes. For things with invasive DRM like Waves and iLoK I'd recommend always installing them into their own Wine prefix regardless. You'll want to remove all Waves things from your main Wine prefix (deactivating the licenses first) and then reinstall them to a new clean Wine prefix.

**Comment by dungeon-mystic** [comment]
Thanks so much, this solved my issue.
