### ISSUE TITLE
Missing DLL Error Even After Adding It In winecnf

### ISSUE THREAD

**Issue by dungeon-mystic** [robbert-vdh/yabridge#247]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

EDIT: I went into system32 and syswow64 and found dxgi.dll.orig in both folders. I removed .orig from both extensions and now Deelay loads. I have no idea why that worked or what it means.

I examined the debug output when Bitwig failed to load Deelay. It said that dxgi.dll was missing. I added an override for it in `winecfg`, but it still keeps throwing the same error.

### What did you expect to happen?

Deelay will load into Bitwig after adding the dll that the error message is missing.

### What actually happened?

Yabridge says the dll is missing and the plugin still does not load.

### Operating system

Mint 21.1

### How did you install yabridge?

From releases

### yabridge version

5.0.4 (not aware if this is actually different than yabrigectl version)

### yabridgectl version

5.0.4

### Wine version

wine-8.5 (Staging)

### Plugin

Sixth Sample Deelay

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Bitwig Studio 4.4.10

### Debug log

15:46:30 [Deelay-9IRfhiqv] plugin type:   'VST3'
15:46:30 [Deelay-9IRfhiqv] realtime:      'no'
15:46:30 [Deelay-9IRfhiqv] sockets:       '/run/user/1000/yabridge-Deelay-9IRfhiqv'
15:46:30 [Deelay-9IRfhiqv] wine prefix:   '/home/stirling/.wine'
15:46:30 [Deelay-9IRfhiqv] wine version:  '8.5 (Staging)'
15:46:30 [Deelay-9IRfhiqv] 
15:46:30 [Deelay-9IRfhiqv] config from:   '<defaults>'
15:46:30 [Deelay-9IRfhiqv] hosting mode:  'individually, 64-bit'
15:46:30 [Deelay-9IRfhiqv] other options: '<none>'
15:46:30 [Deelay-9IRfhiqv] 
15:46:30 [Deelay-9IRfhiqv] Enabled features:
15:46:30 [Deelay-9IRfhiqv] - bitbridge support
15:46:30 [Deelay-9IRfhiqv] - CLAP support
15:46:30 [Deelay-9IRfhiqv] - VST3 support
15:46:30 [Deelay-9IRfhiqv] 
15:46:30 [Deelay-9IRfhiqv] [Wine STDERR] Initializing yabridge host version 5.0.4
15:46:30 [Deelay-9IRfhiqv] [Wine STDERR] Preparing to load VST3 plugin at '/home/stirling/.wine/drive_c/Program Files/Common Files/VST3/Deelay.vst3'
15:46:30 [Deelay-9IRfhiqv] [Wine STDERR] 077c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\Common Files\\VST3\\Deelay.vst3") not found
15:46:30 [Deelay-9IRfhiqv] [Wine STDERR] Error while initializing the Wine plugin host:
15:46:30 [Deelay-9IRfhiqv] [Wine STDERR] Could not load the VST3 module for '/home/stirling/.wine/drive_c/Program Files/Common Files/VST3/Deelay.vst3': LoadLibray failed: Module not found.
15:46:30 [Deelay-9IRfhiqv] [Wine STDERR] 
15:46:30 [Deelay-9IRfhiqv] The Wine host process has exited unexpectedly. Check the output above for more information.

**Comment by robbert-vdh** [comment]
You may have had the remnants of a DXVK installation in there.
