### ISSUE TITLE
Phoscyon 2 VST plugin activation doesn't work

### ISSUE THREAD

**Issue by franticnick** [robbert-vdh/yabridge#248]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

When I try to activate that plugin it says that I should reload the plugin to activate. However, after reloading it asks for activation again. It seems that activation is not saved or something.

### What did you expect to happen?

Activation to work.

### What actually happened?

Activation is not working.

### Operating system

Linux Mint

### How did you install yabridge?

from the release page

### yabridge version

5.0.5

### yabridgectl version

5.0.5

### Wine version

wine-8.7 (Staging)

### Plugin

Phoscyon 2

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Bitwig Studion 5.0.6 beta

**Comment by robbert-vdh** [comment]
This is not a yabridge issue: https://helpdesk.d16.pl/knowledge_base/article/177

**Comment by franticnick** [comment]
Thanks for pointing out!

**Comment by hexahive** [comment]
I stumbled upon this because I have the same problem with d16
Wine version: 9.17 staging
Os: Ubuntu studio 24.04
Yabridge: 5.0.5
VST 2 & 3

... Now, what's interesting is that it worked on my previous Ubuntu studio 22 installation without any problems.
