### ISSUE TITLE
Plugins don't get recognized in either Tracktion Waveform or REAPER

### ISSUE THREAD

**Issue by ghost** [robbert-vdh/yabridge#25]
So I followed the instructions in the readme file, and whenever I scan for plugins in either Waveform or REAPER, they don't get recognized. Waveform states "Note that the following files appeared to be plugin files, but failed to load correctly". I have set up the yabridge folder in the $PATH, as shown by the terminal output below for echo $PATH:
`/home/lukas/.local/share/yabridge:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`

I'm on Pop_OS 20.04, wine 5.12 staging by the way. Any ideas on what the issue could be?

EDIT: I tried adding the yabridge folder to PATH to /.profile instead of /.bash_profile and Waveform managed to recognize one of the plugins (PG-8X), but when it gets to the Roland Cloud stuff, I get a WINE error stating "yabridge-host.exe has stopped working", and then the plugins don't show up in the list. When I tried loading PG-8X, it loaded up (albeit without a title bar, but I guess that's Waveform's fault) but when I tried changing patches I got the same "yabridge-host.exe has stopped working". REAPER still won't load up anything.

**Comment by robbert-vdh** [comment]
Hi,

So the first step would probably be to make sure that it's actually a search path issue. You could try doing the following:

1. Open a terminal window.
2. Run `yabridge-host.exe` in that terminal to make sure that the path is set up correctly at least for that shell session. It should print a bunch of debug info from Wine followed by `Usage: yabridge-host.exe <vst_plugin_dll> <unix_domain_socket>`.
3. Run `env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=1 reaper` to start REAPER. This will write any debug output from yabridge to `/tmp/yabridge.log`, so if things still don't work that will at least give a hint as to what's wrong.
4. Try to load a plugin in REAPER just like you were doing earlier.

If this works, then great! That would indicate that the `PATH` environment variable was not set correctly for your login shell (and thus anything launched from the GUI). If there were still issues, then the contents of `/tmp/yabridge.log` will probably give a hint as to what's wrong. In that case you could upload the contents of `/tmp/yabridge.log` here or to Hastebin and we can try to figure out what's wrong.

**Comment by robbert-vdh** [comment]
I'll close this since the creator of the issue has deleted their GitHub account. If you read this and need any more assistance, feel free to shoot me a message or to create a new issue.
