### ISSUE TITLE
GUI of plugins suddenly not working

### ISSUE THREAD

**Issue by nipikamusic** [robbert-vdh/yabridge#252]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

The plugins suddenly don't show the proper GUI anymore. The top left quarter shows parts of the GUI, but the remaining plugin window just shows a replication of the Bitwig window, and it flickers when trying to resize it.
Also, wine now appears to be opening a window called wine desktop, which I haven't noticed previously.

### What did you expect to happen?

That the plugin GUI would show as normal

### What actually happened?

The plugin GUI is partially black and flickers when resizing the window

### Operating system

Pop!_OS 22.04 LTS

### How did you install yabridge?

directly from the releases

### yabridge version

5.0.5

### yabridgectl version

5.0.5

### Wine version

8.8 staging

### Plugin

Scaler 2 and others

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Bitwig Studio 5.0 Beta 7

### Desktop environment or WM

GNOME 42.5 on X11

### GPU model

Mesa Intel Graphics (RPL-S)

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/11561493/yabridge.log)

**Comment by sleeplessKomodo** [comment]
> wine now appears to be opening a window called wine desktop, which I haven't noticed previously.

strange, I had this issue with yabridge on Arch + wayland (sway) with an NVIDIA GPU. I switched to fedora, and for whatever reason, this specific issue went away.

**Comment by robbert-vdh** [comment]
Closing since this issue is quite old at this point. If you still need help, feel free to join the Discord.
