### ISSUE TITLE
Missing DLL Error Even After Installing It In Winetricks and Overriding in Winecfg

### ISSUE THREAD

**Issue by dungeon-mystic** [robbert-vdh/yabridge#253]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I'm attempting to install [Sonible's Entropy EQ](https://www.sonible.com/entropyeq/) with Wine. The installer errors out with the following: `0114:err:module:import_dll Library MFC42.DLL (which is needed by L"C:\\users\\stirlingjoyner\\Temp\\is-61APS.tmp\\isskin.dll") not found`.  

I added mfc42.dll in winetricks, and added an override for it in winecfg, but got the same error. I tried adding an override for isskin, but that did not solve the problem either.

### What did you expect to happen?

Entropy EQ installs after adding the DLLs required in the error message

### What actually happened?

It still fails and returns the same message.

### Operating system

AV Linux (MX x86_64)

### How did you install yabridge?

Releases

### yabridge version

5.05

### yabridgectl version

5.05

### Wine version

wine-8.5 (Staging)

### Plugin

Entropy EQ

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Bitwig Studio 4.4.10

### Desktop environment or WM

Xfce 4.18

### Debug log

002c:fixme:winediag:LdrInitializeThunk wine-staging 8.5 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
010c:fixme:thread:GetThreadUILanguage : stub, returning default language.
010c:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 0072D97C, 00000000 0072D9A4
010c:fixme:nls:get_dummy_preferred_ui_language (0x38 0x409 0072D97C 00000000 0072D9A4) returning a dummy value (current locale)
010c:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 0072D97C, 0243A680 0072D9A4
010c:fixme:nls:get_dummy_preferred_ui_language (0x38 0x409 0072D97C 0243A680 0072D9A4) returning a dummy value (current locale)
0114:fixme:thread:GetThreadUILanguage : stub, returning default language.
0114:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 0095D9C8, 00000000 0095D9F0
0114:fixme:nls:get_dummy_preferred_ui_language (0x38 0x409 0095D9C8 00000000 0095D9F0) returning a dummy value (current locale)
0114:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 0095D9C8, 0266A680 0095D9F0
0114:fixme:nls:get_dummy_preferred_ui_language (0x38 0x409 0095D9C8 0266A680 0095D9F0) returning a dummy value (current locale)
0114:fixme:wtsapi:WTSRegisterSessionNotification Stub 0001009E 0x00000000
0114:fixme:uxtheme:BufferedPaintInit Stub ()
0114:fixme:win:DisableProcessWindowsGhosting : stub
008c:fixme:imm:ImeSetActiveContext himc 0000000000010026, flag 0 stub!
0114:fixme:imm:ImeSetActiveContext himc 00010096, flag 0x1 stub!
0114:fixme:imm:ImmReleaseContext (0001009E, 00010096): stub
008c:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000010026): stub
0114:fixme:graphics:ShutdownBlockReasonDestroy (0001009E): stub
0114:fixme:graphics:ShutdownBlockReasonCreate (0001009E, L"Installing"): stub
0114:fixme:rstrtmgr:RmStartSession 006D778C, 0, 006D7790 stub!
0114:err:module:import_dll Library MFC42.DLL (which is needed by L"C:\\users\\stirlingjoyner\\Temp\\is-61APS.tmp\\isskin.dll") not found
0114:fixme:rstrtmgr:RmEndSession 3735928559 stub!
0114:fixme:graphics:ShutdownBlockReasonDestroy (0001009E): stub
0114:fixme:wtsapi:WTSUnRegisterSessionNotification Stub 0001009E
0114:fixme:uxtheme:BufferedPaintUnInit Stub ()

**Comment by robbert-vdh** [comment]
You may want to install vcrun6 instead of mfc42. Also make sure you're doing this for the right prefix. Closing this since it's not a yabridge issue.
