### ISSUE TITLE
Improve Frozen GUI Solution in Common Issues

### ISSUE THREAD

**Issue by dungeon-mystic** [robbert-vdh/yabridge#258]
### Feature description

The troubleshooting section of the readme states that installing DXVK can solve the problem of frozen GUIs. I had to follow more steps than simply installing DXVK, so I think the troubleshooting section should be updated to save users time.

I have an AMD GPU running AV Linux MX.

Steps I followed:
1. Install DXVK using the instructions [here](https://github.com/doitsujin/dxvk/)
1. Install DirectX drivers: `libvulkan1 libvulkan-dev vulkan-utils`
1. Install Mesa drivers mesa-vulkan-drivers

Installing DXVK without the other steps actually caused to GUI to not open at all, and the plugin to eventually crash.

### Anything else?

I found [this](https://linuxconfig.org/improve-your-wine-gaming-on-linux-with-dxvk) webpage of great help.

**Comment by robbert-vdh** [comment]
I added an extra note mentioning that you need to install Vulkan drivers if you haven't already for DXVK to work.
