### ISSUE TITLE
GUI scale seems to be wrong when using VST3 with Carla Rack on LMMS

### ISSUE THREAD

**Issue by nwkyz** [robbert-vdh/yabridge#260]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

The GUI of VST3 plugins with Carla comes with a black block at the bottom right of the window.

Screenshot:
[https://postimg.cc/hJwGGsMF](https://postimg.cc/hJwGGsMF)
[https://postimg.cc/5Xs0hbC2](https://postimg.cc/5Xs0hbC2)

### What did you expect to happen?

GUI shows properly

### What actually happened?

GUI went wrong

### Operating system

Zorin OS 16.2 (based on Ubuntu 20.04)

### How did you install yabridge?

directly from the release page (also tried the latest development build 7250c89, but it has the same problem)

### yabridge version

5.0.5

### yabridgectl version

5.0.5

### Wine version

wine 8.0

### Plugin

LABS / Dystortion by Stoff Audio

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

LMMS 1.2.2 with Carla Rack 2.6.0-alpha1

### Desktop environment or WM

GNOME 3.38 on Wayland

### GPU model

Intel HD Graphics 5000

### GPU drivers and kernel

Mesa 21.2.6 on Linux 5.15.0-75-generic

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/11881120/yabridge.log)

### Anything else?

I tried to use Wine 7.x but it doesn't work at all, so I tried Wine 8.0 and 8.7. It's actually wine 8.0 but it shows `wine-5.12-23491-gd48c657a136 (Staging)` when execute `wine --version`, and this may because I'm using `Wine GE Proton 8-8' for some plugins' need. The original wine 8.0 and 8.7 has the same problems with the GUI, too.

VST2 plugins works perfectly, and this problem is only caused by VST3 plugins.

**Comment by robbert-vdh** [comment]
I have not seen anything like that (have never used LMMS' Carla integration), but it's almost certainly an issue with Carla's VST3 hosting if it doesn't happen with the VST2 versions. Does it happen with other hosts? (e.g. Bitwig, REAPER, standalone Carla)

**Comment by nwkyz** [comment]
Oh, it works well with REAPER, so that might be a bug of Carla Rack's VST3 loader. Thank you very much.

**Comment by nwkyz** [comment]
(It works perfectly on Carla Rack 2.5.5, the problem is from the latest alpha Carla build 2.6.0-alpha1)
