### ISSUE TITLE
Can add DaVinci Resolve support?

### ISSUE THREAD

**Issue by MR-Samy-726** [robbert-vdh/yabridge#265]
### Feature description

I would love to be able to use Yabridge to use VST plugins inside Davinci Resolve.Currently with Wine 8.12 (Staging) and Yabridge 5.0.5, Davinci is not able to detect VST plugins within my established routes.It would be great to be able to do it since its audio editing module (Fairlight) is quite powerful and would be a great option to edit the audio of the video with plugins without resorting to an external DAW. Thank you.

### Anything else?

![Nothing](https://github.com/robbert-vdh/yabridge/assets/65687644/eb01e13b-d5df-4636-b0d8-9f1f8a404739)

**Comment by robbert-vdh** [comment]
Are you sure Resolve supports VST2 plugins on Linux? According to a quick Google search it does not.

**Comment by robbert-vdh** [comment]
Closing since Resolve doesn't support VST2 plugins on Linux so there's nothing we can do here.
