### ISSUE TITLE
Ardour freezes after load some plug-ins

### ISSUE THREAD

**Issue by heit0r** [robbert-vdh/yabridge#266]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

When I load "Rare" from Analog Obsession, Ardour freezes (the playhead freezes) and the audio becomes mute. The plug-in loads and the GUI works, knobs can be turned but no audio comes. This plug-in was not updated and used to work nice. Other plug-ins from them load normally.

### What did you expect to happen?

To load not only the GUI, but the plug-in itself. Not freezing the DAW.

### What actually happened?

I choose the plug-in from plug-in list and after I click "Insert Plug-in" the plug-in GUI appears, but playhead freezes and ardour becomes not clickable, without any response at all. I try to solve this by completely delete wine, but no sucess. This seems to happen after 2 or 3 versiosn ago. I didn't try to downgrade wine, should I?

### Operating system

Manjaro

### How did you install yabridge?

pacman -S yabridge, pacman -S yabridgectl

### yabridge version

yabridge host version 5.0.5

### yabridgectl version

yabridgectl 5.0.5

### Wine version

wine-8.12 (Staging)

### Plugin

Rare, RareSE

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Ardour 7

### Desktop environment or WM

XFCE

### GPU model

NVIDIA 1650

### GPU drivers and kernel

NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/12099244/yabridge.log)

### Anything else?

I had the yabridge.log uploaded above, but I'm also including what terminal showed earlier:

15:31:15 [RareSE-4DNeimwy] Initializing yabridge version 5.0.5
15:31:15 [RareSE-4DNeimwy] library:       '/usr/lib/libyabridge-vst3.so'
15:31:15 [RareSE-4DNeimwy] host:          '/usr/bin/yabridge-host.exe'
15:31:15 [RareSE-4DNeimwy] plugin:        '/home/mojo/Audio/Plug-ins/AO/RareSE.vst3'
15:31:15 [RareSE-4DNeimwy] plugin type:   'VST3'
15:31:15 [RareSE-4DNeimwy] realtime:      'yes'
15:31:15 [RareSE-4DNeimwy] sockets:       '/run/user/1000/yabridge-RareSE-4DNeimwy'
15:31:15 [RareSE-4DNeimwy] wine prefix:   '<default>'
15:31:15 [RareSE-4DNeimwy] wine version:  '8.12 (Staging)'
15:31:15 [RareSE-4DNeimwy] 
15:31:15 [RareSE-4DNeimwy] config from:   '<defaults>'
15:31:15 [RareSE-4DNeimwy] hosting mode:  'individually, 64-bit'
15:31:15 [RareSE-4DNeimwy] other options: '<none>'
15:31:15 [RareSE-4DNeimwy] 
15:31:15 [RareSE-4DNeimwy] Enabled features:
15:31:15 [RareSE-4DNeimwy] - bitbridge support
15:31:15 [RareSE-4DNeimwy] - CLAP support
15:31:15 [RareSE-4DNeimwy] - VST3 support
15:31:15 [RareSE-4DNeimwy] 
15:31:15 [RareSE-4DNeimwy] [Wine STDERR] Initializing yabridge host version 5.0.5
15:31:15 [RareSE-4DNeimwy] [Wine STDERR] Preparing to load VST3 plugin at '/home/mojo/Audio/Plug-ins/AO/RareSE.vst3'
15:31:15 [RareSE-4DNeimwy] [Wine STDERR] Finished initializing '/home/mojo/Audio/Plug-ins/AO/RareSE.vst3'
15:31:16 [RareSE-4DNeimwy] [Wine STDERR] 0140:fixme:dwrite:dwritefontface5_HasVariations 0000000002198BA0: stub

**Comment by heit0r** [comment]
I noticed that this issue has something to do with graphics. Another already working plug-in made Ardour freezes the same way as above as I clicked on Analog Obsession logo to activate oversampling. The logo turns from white to red and Ardour crashes the same way. Here is another log.

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/12100542/yabridge.log)

**Comment by robbert-vdh** [comment]
Sorry for not getting to this earlier. Is this still a problem? If so, does this work fine in other DAWs?

**Comment by heit0r** [comment]
No problem. I switched to Fedora XFCE for other reasons, but this is still an issue even with the noveau drivers. I've installed the nvidia proprietary drivers, but nothing changed. I'm beginning to think this is not a video issue, because i've managed to get plugins loaded properly with Carla. Please, don't get me wrong, I just wanted to try alternatives. Everything works with carla loaded as an lv2 plugin rack within Ardour: the GUI, sound, oversampling. The drawback with carla is that next time I open the session the plugin sounds bypassed no matter what, but this is an issue that doesn't matter here. I'll never use carla because i have to click much more times to load a plugin and i like the way yabridge make the plugins behave like if they were native. But the fact is that carla is doing something. I don't know what, but the answer might be around carla. Or I should test another daw. This is the last thing I want to do now because i love ardour.
I ran ```env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log ardour7``` to generate the logs below, but I don't know why these logs are much more shorter than the generated within Manjaro. I repeated the process above with dxvk installed and uninstalled (running ```setup_dxvk.sh install``` and ```setup_dxvk.sh install```)

[yabridge carla dxvk.log](https://github.com/robbert-vdh/yabridge/files/13196881/yabridge.carla.dxvk.log)
[yabridge d3d.log](https://github.com/robbert-vdh/yabridge/files/13196882/yabridge.d3d.log)
[yabridge dxvk.log](https://github.com/robbert-vdh/yabridge/files/13196883/yabridge.dxvk.log)
[yabridge carla d3d.log](https://github.com/robbert-vdh/yabridge/files/13196884/yabridge.carla.d3d.log)


I like these plugins, rare and lala from AO. They used to work fine around a year ago, i've even recorded a video using them. I hope the logs above help. Ill try them with another daw, reaper maybe. Thank you so much for checking up on this.

**Comment by heit0r** [comment]
Well.. Everything seems works flawlessly in Reaper. I've just tried it now. I love Ardour, but I think I'll give Reaper a shot. I feel a bit sad. I'd love to see this solved in Ardour, but I don't really know if I should open an issue, because they have no intention AFAIK to support windows plug-ins. Thank you. I'll close the issue.

**Comment by heit0r** [comment]
Well.. Everything seems works flawlessly in Reaper. I've just tried it now. I love Ardour, but I think I'll give Reaper a shot. I feel a bit sad because I'd love to see this solved in Ardour. I'll see if I can open an issue in their project. Thanks a lot. I'll close the issue.

**Comment by heit0r** [comment]
After searching about this issue I've found that this was already being tracked by Ardour community. These plug-ins used to word fine on Ardour, but the VST3 host changed a bit after ardour 7.2. There's some debug logs attached in their forum here https://tracker.ardour.org/view.php?id=9274&nbn=15

**Comment by heit0r** [comment]
Downgraded Ardour to version 7.2.0 and everything came back to normal. Despite everything working well, this does not completely solve the issue.

**Comment by robbert-vdh** [comment]
Sorry, only just got around to taking a look at this. This change in Ardour 7.3 is the culprit: https://github.com/Ardour/ardour/commit/b27467157b38c976de8da04c9ef5642336898c56

There's no universal way to schedule callbacks on the host's UI thread in VST3. It would be possible to work around this when the UI is open, but there's no way for yabridge to not cause a deadlock here when the UI is not open. I'll ask the Ardour developers if they have a suggested way to work around this, but I don't think there's a way to do that without requiring changes to Ardour.

**Comment by x42** [comment]
What thread is used to call `restartComponent`

> restartComponent should be called in the UI Thread
(https://forums.steinberg.net/t/how-to-use-restartcomponent-and-which-flags-are-the-right-one-when-changing-all-characteristics-parameters-except-size/202031)

Also if you don't heed that, Ardour will not lock if restartComponent is directly called from the plugin's main process callback.

**Comment by robbert-vdh** [comment]
On Linux there is no such thing as 'the UI thread', so there's sadly also no universal way to schedule callbacks on that thread. These callbacks need to happen from another, yabridge-owned thread.

**Comment by x42** [comment]
It would be fine if the plugin would just emit it from the process thread (like it happen on native windows), but I understand this is not an option with yabridge :(

**Comment by robbert-vdh** [comment]
Just double checked with the latest nightly and this does indeed (as expected) solve the freezes with the plugins mentioned by @heit0r! I'm releasing this as part of yabridge 5.1.0 in a couple hours, so I'll close the issue.

**Comment by heit0r** [comment]
Hello. Unfortunately, for me it still crashes with the plugins aforementioned. I'm attaching a new [yabridge.log](https://github.com/robbert-vdh/yabridge/files/13789786/yabridge.log)

yabridgectl --version
yabridgectl 5.1.0

ardour8 --version
Ardour8.1.0 (built using 8.1 and GCC version 13.2.1 20231011 (Red Hat 13.2.1-4))

Since I'm using Fedora, it may take a while to update from Ardour 8.1 to 8.2. Is this the probable cause of Ardour still crashing? Wich version did you use?

Huge thanks to everyone involved.

**Comment by x42** [comment]
Yes, you need Ardour 8.2 in conjunction with recent yabridge
