### ISSUE TITLE
Frozen GUI in Deelay plugin

### ISSUE THREAD

**Issue by Fazarel** [robbert-vdh/yabridge#270]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Deelay is a free plugin : https://sixthsample.com/deelay/

It loads and works in bitwig studio, but the GUI is frozen.
I can change parameters, I see the changes in the device window (integrated in bitwig, bottom left in the image below, see "diffusion size"), but in the main plugin window nothing changes.
As suggested in the "Known issues and fixes", I installed DXVK and it doesn't fix it.

![deelay](https://github.com/robbert-vdh/yabridge/assets/35377747/712082b8-d1ce-427e-a98a-1daacaf52000)

### What did you expect to happen?

The GUI updates when I interact with it.

### What actually happened?

The GUI never updates.

### Operating system

Ubuntu 20.04.1 LTS

### How did you install yabridge?

from the releases page

### yabridge version

 5.0.5

### yabridgectl version

 5.0.5

### Wine version

wine-8.13 (Staging)

### Plugin

Deelay (Sixthsample)

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Bitwig Studio 5.0.4

### Desktop environment or WM

Gnome 3.36.8 on X11

### GPU model

Mesa Intel® Xe Graphics

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/12343186/yabridge.log)

### Anything else?

Any idea or other tweaks to suggest ?

**Comment by Fazarel** [comment]
I also tried to install `libvulkan1` `libvulkan-dev` `vulkan-utils` and `mesa-vulkan-drivers` as suggested here #258 
And I tried `sysctl dev.i915.perf_stream_paranoid=0` as suggested in log file.
None of them solved the problem.

**Comment by robbert-vdh** [comment]
> 12:12:48 [Deelay-0IPZfgvy] [Wine STDERR] warn:  Skipping Vulkan 1.2 adapter: Intel(R) Xe Graphics (TGL GT2)
> 12:12:48 [Deelay-0IPZfgvy] [Wine STDERR] warn:  Skipping Vulkan 1.1 adapter: llvmpipe (LLVM 12.0.0, 256 bits)
> 12:12:48 [Deelay-0IPZfgvy] [Wine STDERR] warn:  DXVK: No adapters found. Please check your device filter settings and Vulkan setup.
> 12:12:48 [Deelay-0IPZfgvy] [Wine STDERR] warn:  DXGI: Found monitors not associated with any adapter, using fallback

You need to get your Vulkan drivers set up (assuming your iGPU supports Vulkan). Try testing with `vkcube`.

**Comment by Fazarel** [comment]
`vkcube` was working fine and gave no indication of the source of the problem.
If it helps others, thanks to your indications I solved the problem by updating the Mesa/Vulkan drivers for my Intel graphics card. I followed the procedure given in the Lutris documentation: https://github.com/lutris/docs/blob/master/InstallingDrivers.md
Many thanks for your help and your work!
