### ISSUE TITLE
UI not showing in DAW

### ISSUE THREAD

**Issue by sschuhmann** [robbert-vdh/yabridge#271]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

The plugin UI is not showing in DAW. The plugin is loading standalone, but if I load it in the DAW, the UI is not showing 

However, the sound of the plugin is playing (Vinyl)

Ubuntu 23.04
Artutia V, iZotope Vinyl
Yabridge 5.0.5

### What did you expect to happen?

UI should be displayed 

### What actually happened?

UI is just a copy of the background 

### Operating system

Ubuntu 23.04

### How did you install yabridge?

Copied the files using the tar command 

### yabridge version

5.0.5

### yabridgectl version

5.0.5

### Wine version

Tried different Versions. 8.0 Staging from repos, Gnome bottles and crossover linux

### Plugin

Artutia V, iZotope Vinyl

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Waveform 12

### Desktop environment or WM

Gnome on Xorg 

### GPU model

Intel

**Comment by robbert-vdh** [comment]
See the note about UI's not showing and DXVK in the readme.

Sorry for not getting to this earlier. If you still have issues, feel free to join the Discord. There's a lot more people who can answer questions there!
