### ISSUE TITLE
VST scan error on Bitwig (.deb to .rpm)

### ISSUE THREAD

**Issue by deusnovus** [robbert-vdh/yabridge#273]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

The VST plugins are not scanned in the Plugins panel in Bitwig's settings.

### What did you expect to happen?

I was expecting the plugins to load up on the Plugins panel in Bitwig's settings.

### What actually happened?

They all result in error and failing to process.

### Operating system

Fedora 38

### How did you install yabridge?

From Fedora's COPR repo

### yabridge version

5.0.5

### yabridgectl version

5.0.5

### Wine version

wine-8.16 (Staging)

### Plugin

Various

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Bitwig 5.0.7 (.deb to .rpm)

### Desktop environment or WM

Fedora 38 on Wayland

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/12706623/yabridge.log)

### Anything else?

1. All my plugins are installed and handled via Bottles. The standalone version of these apps run fine.

2. There were no errors during `yabridgectl sync` and `yabridgeclt status`.

3. From what I understand, due to the Flatpak version working within a sandbox, it cannot process wrapped VST plugins, so I converted the .deb version via [teervo's bitwig-fedora script](https://github.com/teervo/bitwig-fedora). I wish we could simply use the Flatpak version without any problems, since it's readily available on Flathub.

**Comment by robbert-vdh** [comment]
```
17:08:51 [Kontakt-8BLNjpxy] [Wine STDERR] wine: could not open working directory L"unix\\home\\yiannis\\", starting in the Windows directory.
17:08:51 [Kontakt-8BLNjpxy] [Wine STDOUT] Application could not be started, or no application associated with the specified file.
17:08:51 [Kontakt-8BLNjpxy] [Wine STDOUT] ShellExecuteEx failed: File not found.
```

Sounds like you removed the default `Z:` drive in winecfg. Open winecfg and make sure there's a drive letter that points to the root filesystem.

**Comment by deusnovus** [comment]
I haven't changed anything via winecfg, but just to confirm, Z: points to root, as seen below:

![Screenshot from 2023-09-23 18-09-23](https://github.com/robbert-vdh/yabridge/assets/32219080/59c2f8d2-4706-48e3-8439-6093414bf397)

(I have changed the default Z: drive directory within Bottles though, I don't know if there's any overlap or not, since everything I've done in regards to yabridge + wine-staging was through the Terminal and all plugins are inside the Home folder)

**Comment by robbert-vdh** [comment]
And that's using the same Wine prefix the plugin is coming from? Run `WINEPREFIX=/home/yiannis/.var/app/com.usebottles.bottles/data/bottles/bottles/VST winecfg` in a terminal and open the Drives tab there.

**Comment by deusnovus** [comment]
Right, yes, that's the "VST" bottle's winecfg I edited via Bottles, where the Z: drive points to 'mnt/external/'. Should the drive be set to root no matter what for yabridge to work or is there a yabridge parameter I can change to leave it as is?

**Comment by robbert-vdh** [comment]
Yes. Otherwise Wine can't find the files it's looking for. Usually it's best to leave those things alone unless you really know what you're doing.

**Comment by deusnovus** [comment]
Yes of course, thank you very much for all your help. I'll be closing this one now.
