### ISSUE TITLE
Error loading vst

### ISSUE THREAD

**Issue by cdhainaut** [robbert-vdh/yabridge#274]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I am trying to use a windows VST with Reaper via yabridge. 
I installed the VST (neural dsp plini) on Wine and syncronized the paths with yabridge-ctl add and sync commands like detailed in the tutorial. The VST fails to be loaded

### What did you expect to happen?

Expected the VST to be loaded correctly

### What actually happened?

The VST fails to be loaded

### Operating system

Linux Mint 21.1

### How did you install yabridge?

directly from the release page

### yabridge version

5.0.5

### yabridgectl version

5.0.5

### Wine version

8.0.2

### Plugin

Neural dsp archetype plini

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Reaper

### Debug log

17:10:20 [Archetype Plini-6FUXbkuw] Initializing yabridge version 5.0.5
17:10:20 [Archetype Plini-6FUXbkuw] library:       '/home/charles/.local/share/yabridge/libyabridge-vst3.so'
17:10:20 [Archetype Plini-6FUXbkuw] host:          '/home/charles/.local/share/yabridge/yabridge-host.exe'
17:10:20 [Archetype Plini-6FUXbkuw] plugin:        '/home/charles/.wine/drive_c/Program Files/Common Files/VST3/Archetype Plini.vst3'
17:10:20 [Archetype Plini-6FUXbkuw] plugin type:   'VST3'
17:10:20 [Archetype Plini-6FUXbkuw] realtime:      'no'
17:10:20 [Archetype Plini-6FUXbkuw] sockets:       '/run/user/1000/yabridge-Archetype Plini-6FUXbkuw'
17:10:20 [Archetype Plini-6FUXbkuw] wine prefix:   '/home/charles/.wine'
17:10:20 [Archetype Plini-6FUXbkuw] wine version:  '8.0.2'
17:10:20 [Archetype Plini-6FUXbkuw] 
17:10:20 [Archetype Plini-6FUXbkuw] config from:   '<defaults>'
17:10:20 [Archetype Plini-6FUXbkuw] hosting mode:  'individually, 64-bit'
17:10:20 [Archetype Plini-6FUXbkuw] other options: '<none>'
17:10:20 [Archetype Plini-6FUXbkuw] 
17:10:20 [Archetype Plini-6FUXbkuw] Enabled features:
17:10:20 [Archetype Plini-6FUXbkuw] - bitbridge support
17:10:20 [Archetype Plini-6FUXbkuw] - CLAP support
17:10:20 [Archetype Plini-6FUXbkuw] - VST3 support
17:10:20 [Archetype Plini-6FUXbkuw] 
17:10:20 [Archetype Plini-6FUXbkuw] [Wine STDERR] ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
17:10:20 [Archetype Plini-6FUXbkuw] [Wine STDERR] ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
17:10:20 [Archetype Plini-6FUXbkuw] [Wine STDERR] 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
17:10:20 [Archetype Plini-6FUXbkuw] [Wine STDERR] 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
17:10:20 [Archetype Plini-6FUXbkuw] [Wine STDERR] 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
17:10:20 [Archetype Plini-6FUXbkuw] [Wine STDERR] 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
17:10:20 [Archetype Plini-6FUXbkuw] [Wine STDERR] Initializing yabridge host version 5.0.5
17:10:20 [Archetype Plini-6FUXbkuw] [Wine STDERR] Preparing to load VST3 plugin at '/home/charles/.wine/drive_c/Program Files/Common Files/VST3/Archetype Plini.vst3'
17:10:21 [Archetype Plini-6FUXbkuw] [Wine STDERR] 0128:err:module:import_dll Library libxml2.dll (which is needed by L"C:\\users\\charles\\Temp\\pfa3b1.tmp") not found
17:10:21 [Archetype Plini-6FUXbkuw] [Wine STDERR] 0128:err:module:LdrInitializeThunk Importing dlls for L"C:\\users\\charles\\Temp\\pfa3b1.tmp" failed, status c0000135
17:10:21 [Archetype Plini-6FUXbkuw] [Wine STDERR] 00d4:fixme:icon:NtUserDrawIconEx Error retrieving icon frame 0
17:10:21 [Archetype Plini-6FUXbkuw] [Wine STDERR] 00d4:fixme:icon:NtUserDrawIconEx Error retrieving icon frame 0
17:10:21 [Archetype Plini-6FUXbkuw] [Wine STDERR] 00d4:fixme:icon:NtUserDrawIconEx Error retrieving icon frame 0
17:10:21 [Archetype Plini-6FUXbkuw] [Wine STDERR] 00d4:fixme:icon:NtUserDrawIconEx Error retrieving icon frame 0
17:10:21 [Archetype Plini-6FUXbkuw] [Wine STDERR] 00d4:fixme:imm:ImeSetActiveContext (000000000001002E, 0): stub
17:10:21 [Archetype Plini-6FUXbkuw] [Wine STDERR] 00d4:fixme:imm:ImmReleaseContext (0000000000010020, 000000000001002E): stub
17:10:21 [Archetype Plini-6FUXbkuw] [Wine STDERR] Error while initializing the Wine plugin host:
17:10:21 [Archetype Plini-6FUXbkuw] [Wine STDERR] Could not load the VST3 module for '/home/charles/.wine/drive_c/Program Files/Common Files/VST3/Archetype Plini.vst3': LoadLibray failed: �chec d'initialisation de la DLL.
17:10:21 [Archetype Plini-6FUXbkuw] [Wine STDERR] 
17:10:21 [Archetype Plini-6FUXbkuw] The Wine host process has exited unexpectedly. Check the output above for more information.
17:10:21 [Archetype Plini-0GLWZdef] Initializing yabridge version 5.0.5
17:10:21 [Archetype Plini-0GLWZdef] library:       '/home/charles/.local/share/yabridge/libyabridge-vst2.so'
17:10:21 [Archetype Plini-0GLWZdef] host:          '/home/charles/.local/share/yabridge/yabridge-host.exe'
17:10:21 [Archetype Plini-0GLWZdef] plugin:        '/home/charles/.wine/drive_c/Program Files/VstPlugins/Archetype Plini.dll'
17:10:21 [Archetype Plini-0GLWZdef] plugin type:   'VST2'
17:10:21 [Archetype Plini-0GLWZdef] realtime:      'no'
17:10:21 [Archetype Plini-0GLWZdef] sockets:       '/run/user/1000/yabridge-Archetype Plini-0GLWZdef'
17:10:21 [Archetype Plini-0GLWZdef] wine prefix:   '/home/charles/.wine'
17:10:21 [Archetype Plini-0GLWZdef] wine version:  '8.0.2'
17:10:21 [Archetype Plini-0GLWZdef] 
17:10:21 [Archetype Plini-0GLWZdef] config from:   '<defaults>'
17:10:21 [Archetype Plini-0GLWZdef] hosting mode:  'individually, 64-bit'
17:10:21 [Archetype Plini-0GLWZdef] other options: '<none>'
17:10:21 [Archetype Plini-0GLWZdef] 
17:10:21 [Archetype Plini-0GLWZdef] Enabled features:
17:10:21 [Archetype Plini-0GLWZdef] - bitbridge support
17:10:21 [Archetype Plini-0GLWZdef] - CLAP support
17:10:21 [Archetype Plini-0GLWZdef] - VST3 support
17:10:21 [Archetype Plini-0GLWZdef] 
17:10:21 [Archetype Plini-0GLWZdef] [Wine STDERR] ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
17:10:21 [Archetype Plini-0GLWZdef] [Wine STDERR] ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
17:10:21 [Archetype Plini-0GLWZdef] [Wine STDERR] Initializing yabridge host version 5.0.5
17:10:21 [Archetype Plini-0GLWZdef] [Wine STDERR] Preparing to load VST2 plugin at '/home/charles/.wine/drive_c/Program Files/VstPlugins/Archetype Plini.dll'
17:10:21 [Archetype Plini-0GLWZdef] [Wine STDERR] 0144:err:module:import_dll Library libxml2.dll (which is needed by L"C:\\users\\charles\\Temp\\pfa559.tmp") not found
17:10:21 [Archetype Plini-0GLWZdef] [Wine STDERR] 0144:err:module:LdrInitializeThunk Importing dlls for L"C:\\users\\charles\\Temp\\pfa559.tmp" failed, status c0000135
17:10:21 [Archetype Plini-0GLWZdef] [Wine STDERR] Error while initializing the Wine plugin host:
17:10:21 [Archetype Plini-0GLWZdef] [Wine STDERR] Could not load the Windows .dll file at '/home/charles/.wine/drive_c/Program Files/VstPlugins/Archetype Plini.dll'
17:10:21 [Archetype Plini-0GLWZdef] The Wine host process has exited unexpectedly. Check the output above for more information.

**Comment by robbert-vdh** [comment]
Like it says in the error message, you're missing `libxml2.dll`. If that's not installed as part of the plugin's installer or by iLoK, then you may need to manually install it through winetricks.

**Comment by robbert-vdh** [comment]
Closing the issue since it's stale. Please leave a comment or hop onto the Discord if you still need assistance!
