### ISSUE TITLE
Spitfire plugin BBC Symphony Orchestra: could not find libyabridge-vst3.so

### ISSUE THREAD

**Issue by fvoncken** [robbert-vdh/yabridge#275]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

After installing a Spitfire-app by the use of PlayOnLinux and setting up yabridge I encountered two errors in Ardour, one saying that Ardour could not find libyabridge-vst3.so and the other saying "Invalid VST3 Module Path: '' "

### What did you expect to happen?

The Ardour status of the VST3 plugin being "OK"

### What actually happened?

The Ardour status of the plugin is "Error"

### Operating system

Tuxedo OS 2

### How did you install yabridge?

directly from the release page

### yabridge version

5.0.5

### yabridgectl version

5.0.5

### Wine version

6.0.3

### Plugin

Spitfire BBC Symphony Orchestra

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Ardour 8

### Desktop environment or WM

KDE Plasma 5.27.8

### GPU model

NVIDIA GeForce RTX 3060

### GPU drivers and kernel

6.2.0

### Debug log

$ ~/.local/share/yabridge/yabridgectl status
yabridge path: <auto>
VST2 location: '/home/samuel/.vst/yabridge'
VST3 location: '/home/samuel/.vst3/yabridge'
CLAP location: '/home/samuel/.clap/yabridge'

libyabridge-chainloader-vst2.so: '/home/samuel/.local/share/yabridge/libyabridge-chainloader-vst2.so' (64-bit)
libyabridge-chainloader-vst3.so: '/home/samuel/.local/share/yabridge/libyabridge-chainloader-vst3.so' (64-bit)
libyabridge-chainloader-clap.so: '/home/samuel/.local/share/yabridge/libyabridge-chainloader-clap.so' (64-bit)

yabridge-host.exe: '/home/samuel/.local/share/yabridge/yabridge-host.exe'
yabridge-host-32.exe: '/home/samuel/.local/share/yabridge/yabridge-host-32.exe'

/home/samuel/.var/app/com.playonlinux.PlayOnLinux4/data/PlayOnLinux/wineprefix/spitfire/drive_c/Program Files/Common Files/VST3/
  BBC Symphony Orchestra (64 Bit).vst3 :: VST3, bundle, 64-bit, synced

/home/samuel/.var/app/com.playonlinux.PlayOnLinux4/data/PlayOnLinux/wineprefix/spitfire/drive_c/Program Files/VstPlugins/
  BBC Symphony Orchestra (64 Bit).dll :: VST2, 64-bit, synced

(end of the stat log)

Now the error message in Ardour (there are two VST3 lines in the plugin list, both referring to BBC Symphony Orchestra, the error below refers to the first VST3 line):

VST3 module-path '/home/samuel/.vst3/yabridge/BBC Symphony Orchestra (64 Bit).vst3/Contents/x86_64-linux/BBC Symphony Orchestra (64 Bit).so'
[Info]: Scanning: /home/samuel/.vst3/yabridge/BBC Symphony Orchestra (64 Bit).vst3
18:41:27 [error] 
18:41:27 [error] Could not find 'libyabridge-vst3.so'
18:41:27 [error] 
18:41:27 [error] Make sure you followed the installation instructions from yabridge's readme.
18:41:27 [error] 
18:41:27 [error] Source: '/home/samuel/.vst3/yabridge/BBC Symphony Orchestra (64 Bit).vst3/Contents/x86_64-linux/BBC Symphony Orchestra (64 Bit).so'
18:41:27 [error] 
Error: signal 11
 ---8<---
  /usr/lib/x86_64-linux-gnu/libc.so.6(+0x3ee80) [0x7fbbea251e80]
 --->8---
Scan Failed.

(other error message in Ardour, referring to the second VST3 line):
Invalid VST3 Module Path: ''

### Anything else?

For the Spitfire app we use PlayOnLinux version 4.4 to download it. There the selected Wine version is 6.17-staging.

**Comment by fvoncken** [comment]
Anyone? My son would like to use the plugin BBC Symphony Orchestra within Ardour. It is still not possible...

**Comment by robbert-vdh** [comment]
How did you install Ardour? If you used Flatpak, then that's the problem here. 

Oh and for setup questions you'll probably get a quicker response if you use the support channel in the Discord instead.

**Comment by robbert-vdh** [comment]
Closing the issue since it's stale. Please leave a comment or hop onto the Discord if you still need assistance!
