### ISSUE TITLE
yabridge symlinks are evil

### ISSUE THREAD

**Issue by Calendis** [robbert-vdh/yabridge#276]
### Feature description

In my attempt to make this work with my DAW I (wrongly) made a synlink to the /usr/bin/yabridge host .so file in my plugins directory.
When I ran yabridgectl --sync, I noticed it asked to prune all my plugin directories. I did it, mostly to see if it would really delete all my plugins.

### Anything else?

Although I used this incorrectly, the fact that symlinking to the .so can delete files in the same directory as the symlink feels wrong.

**Comment by hanspaerna** [comment]
That's how my native u-he VSTs from the same directory were accidentally removed. Can confirm. Maybe it's better to track each symlink precisely and not by filename mask.

**Comment by robbert-vdh** [comment]
It will only ask to delete unmanaged files in the directories you explicitly added as Windows plugin directories using `yabridgectl add`, and pruning is not the default behavior for this reason. It will only list the files it would delete with the `--prune` option if you run `yabridgectl sync` without the option.
