### ISSUE TITLE
Yabridge on Steam Deck, wine error

### ISSUE THREAD

**Issue by nnbveh** [robbert-vdh/yabridge#277]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I've installed both the yabridge and the Wine through flatpak. Probles is, yabridge doesn't see the wine, this is what it gives me if i try to sync:

(deck@steamdeck ~)$ yabridgectl sync
Setting up VST2, VST3, and CLAP plugins using:
- /home/deck/.local/share/yabridge/libyabridge-chainloader-vst2.so
- /home/deck/.local/share/yabridge/libyabridge-chainloader-vst3.so
- /home/deck/.local/share/yabridge/libyabridge-chainloader-clap.so

Finished setting up 4 plugins (4 new), skipped 0 non-plugin .dll files
Error: Could not run 'wine', make sure Wine is installed

Caused by:
    No such file or directory (os error 2)

So it DOES see the files inside wine drive, but doesn't see the wine app itself, i guess it has something to do with the flatpak...

### What did you expect to happen?

To finish the sync

### What actually happened?

Can not find Wine

### Operating system

Steam os

### How did you install yabridge?

From the github

### yabridge version

th

### yabridgectl version

bb

### Wine version

bb

### Plugin

bbb

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

none

**Comment by robbert-vdh** [comment]
See #135 for a more general discussion about Flatpak.

Flatpak just isn't meant for applications that work together in an ecosystem (in fact, it's not supposed to by design, since that makes sandboxing less useful from a security point of view).

**Comment by nnbveh** [comment]
So instead of providing the solution you've just closed the issue...I guess people better stay away from anything developed by you.

**Comment by robbert-vdh** [comment]
The solution is in the linked thread. Someone would need to package yabridge, Wine, and your DAW in such a way that they all use the exact same Flatpak runtime. Or you'd need to put yabridge's and Wine's files in your home directory, set a bunch of environment variables, and hope that it works. It's just that someone needs to do the work, and no matter what you do thanks to Flatpak's nature (it isn't designed to do this) it's going to be a bit brittle.
