### ISSUE TITLE
Jamstix 4 plugin not visible or not starting

### ISSUE THREAD

**Issue by magillos** [robbert-vdh/yabridge#280]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I tried running plugin in Reaper with or without DXVK installed. 

Without  DXVK it starts but I can't see anything within the plugin window. It shows for a second and then it goes black. It seems that it runs okay and if I click in random places I can sometimes see some of the buttons briefly. Same if I right click. Dragging the window doesn't help.
With DXVK installed I get a pop up error saying: "Cannot create swap chain for 'TCanvasD2D'" and plugin doesn't start and Reaper may hang after a while. I had memory leak too when loaded the plugin for the first time. 

Clean .wine has been used for testing. 

Jamstix doesn't have a stand-alone version so I can't test if that works.  

### What did you expect to happen?

Plugin to load and run. 

### What actually happened?

As explained in the problem description. 

### Operating system

Arch

### How did you install yabridge?

Aur

### yabridge version

5.0.5

### yabridgectl version

5.0.5

### Wine version

wine-staging 8.18

### Plugin

Jamstix 4 free version

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Reaper

### Desktop environment or WM

KDE Plasma

### GPU model

Built in AMD in Ryzen 5500

### GPU drivers and kernel

Mesa

### Debug log

[yabridge-without-dxvk.log](https://github.com/robbert-vdh/yabridge/files/13042503/yabridge-without-dxvk.log)

[yabridge-with-dxvk.log](https://github.com/robbert-vdh/yabridge/files/13042512/yabridge-with-dxvk.log)

**Comment by robbert-vdh** [comment]
You can't combine DXVK with Direct2D without the prerequisite patches. Try it with wine-tkg instead.

Closing the issue since unless it works fine with Windows REAPER under Wine, it's not a yabridge issue. Feel free to join the Discord server if you want to chat!

**Comment by magillos** [comment]
Thanks for response and clarifying that. I'm using [Wine-NSPA](url) as I was hoping it has all the patches for audio. I'll try tkg and if it doesn't help I may pop into Discord.
