### ISSUE TITLE
Low RTTIME Detected issue

### ISSUE THREAD

**Issue by aidanhadley** [robbert-vdh/yabridge#281]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

When running REAPER with yabridge, i get about 3-10 errors all saying the same thing:
"Low RTTIME limit detected
RLIMIT_RTTIME is set to 200000 us. This can happen when using PipeWire's JACK backend with RTKit instead of regular realtime scheduling. Some plugins may crash during initialization because of this, so it's recommended to set up proper realtime priveleges for your user. Check the readme for instructions on how to do that"

I've been troubleshooting this all day, and i followed everything in #154, yet it didn't work.

### What did you expect to happen?

For that error to not occur

### What actually happened?

The error occured

### Operating system

Endeavour OS

### How did you install yabridge?

the AUR

### yabridge version

5.0.5

### yabridgectl version

5.0.5

### Wine version

wine staging 8.18

### Plugin

N/A

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

REAPER (also tested on Bitwig Studio)

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/13059402/yabridge.log)

### Anything else?

i'll be glad to give any more info, it's been a long day lol. it worked on my previous laptop until the most recent release

**Comment by wastee** [comment]
I had the same problem, even after following the readme.

| Package                    | Version              |
| -------------------------- | -------------------- |
| Pipewire                   | 0.3.83               |
| Yabridge                   | 5.0.5                |
| wine-tkg-staging-fsync-git | 8.17.1.r10.g9497ddf2 |

**Comment by robbert-vdh** [comment]
Something is using rtkit in your desktop session. PipeWire is the likely culprit. Make sure you have realtime priviliges set up correctly. If you have, you can always mask the rtkit service.

Closing since this is not an issue with yabridge.
