### ISSUE TITLE
key-value error preventing any plugin from loading

### ISSUE THREAD

**Issue by Multipixelone** [robbert-vdh/yabridge#282]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

All plugins give a vague output upon loading, warning about a key-value error but providing no information about where that error is. Let me know what more information I can provide or how I can get yabridge to be more verbose about where the error is. I have tried reinstalling and deleting all of my config files and restarting my WINEPREFIX from scratch, and none of these have helped.

Thanks so much!

### What did you expect to happen?

Plugins load

### What actually happened?

No plugins will load for me

### Operating system

Arch

### How did you install yabridge?

AUR Package

### yabridge version

5.0.5.r7.g2089c035-1

### yabridgectl version

5.0.5.r7.g2089c035-1

### Wine version

Wine Staging 8.18

### Plugin

Any

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

REAPER & Carla & carla-single

### Debug log

16:11:35 [error] 
16:11:35 [error] Error during initialization:
16:11:35 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:35 [error] 
16:11:35 [error] 
16:11:35 [error] Error during initialization:
16:11:35 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:35 [error] 
16:11:35 [error] 
16:11:35 [error] Error during initialization:
16:11:35 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:35 [error] 
16:11:36 [error] 
16:11:36 [error] Error during initialization:
16:11:36 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:36 [error] 
16:11:36 [error] 
16:11:36 [error] Error during initialization:
16:11:36 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:36 [error] 
16:11:36 [error] 
16:11:36 [error] Error during initialization:
16:11:36 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:36 [error] 
16:11:37 [error] 
16:11:37 [error] Error during initialization:
16:11:37 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:37 [error] 
16:11:37 [error] 
16:11:37 [error] Error during initialization:
16:11:37 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:37 [error] 
16:11:38 [error] 
16:11:38 [error] Error during initialization:
16:11:38 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:38 [error] 
16:11:38 [error] 
16:11:38 [error] Error during initialization:
16:11:38 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:38 [error] 
16:11:38 [error] 
16:11:38 [error] Error during initialization:
16:11:38 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:38 [error] 
16:11:39 [error] 
16:11:39 [error] Error during initialization:
16:11:39 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:39 [error] 
16:11:39 [error] 
16:11:39 [error] Error during initialization:
16:11:39 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:39 [error] 
16:11:39 [error] 
16:11:39 [error] Error during initialization:
16:11:39 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:39 [error] 
16:11:40 [error] 
16:11:40 [error] Error during initialization:
16:11:40 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:40 [error] 
16:11:40 [error] 
16:11:40 [error] Error during initialization:
16:11:40 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:40 [error] 
16:11:40 [error] 
16:11:40 [error] Error during initialization:
16:11:40 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:40 [error] 
16:11:41 [error] 
16:11:41 [error] Error during initialization:
16:11:41 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:41 [error] 
16:11:41 [error] 
16:11:41 [error] Error during initialization:
16:11:41 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:41 [error] 
16:11:41 [error] 
16:11:41 [error] Error during initialization:
16:11:41 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:41 [error] 
16:11:42 [error] 
16:11:42 [error] Error during initialization:
16:11:42 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:42 [error] 
16:11:42 [error] 
16:11:42 [error] Error during initialization:
16:11:42 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:42 [error] 
16:11:42 [error] 
16:11:42 [error] Error during initialization:
16:11:42 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:42 [error] 
16:11:42 [error] 
16:11:42 [error] Error during initialization:
16:11:42 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:42 [error] 
16:11:42 [error] 
16:11:42 [error] Error during initialization:
16:11:42 [error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
16:11:42 [error]

**Comment by Multipixelone** [comment]
Here is the full command I am using: 
`~ > rm -f /tmp/yabridge.log; env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=2+editor carla-single vst3 ~/.vst3/yabridge/Deelay.vst3/
['/usr/lib/carla/carla-bridge-native', 'vst3', '/home/tunnel/.vst3/yabridge/Deelay.vst3/', '(none)', '0']
[carla] Failed to set high priority, error 1: Operation not permitted
libjack.so.0 loaded successfully!
JUCE Assertion failure in juce_VST3PluginFormat.cpp:999
JUCE Assertion failure in juce_VST3PluginFormat.cpp:3802
[carla] Plugin failed to load, error was:
Failed to get plugin description
fish: Job 1, 'env YABRIDGE_DEBUG_FILE=/tmp/ya?' terminated by signal SIGSEGV (Address boundary error)
~ | 139 > cat /tmp/yabridge.log 
[error] 
[error] Error during initialization:
[error] Error while parsing key-value pair: expected a comment or whitespace, saw '['
[error] `
These are the full commands I'm using. Anybody have any helpful advice? I've been trying to use gdb for debugging but because nothing stays open long I'm having trouble attaching to it

**Comment by robbert-vdh** [comment]
You created a `yabridge.toml` file with invalid syntax. You'll need to fix or remove that file in `~/.vst3/yabridge` or any of its parent directories.

**Comment by Multipixelone** [comment]
Oh man rookie mistake. I had the in-progress yabridge.toml in my home folder because I figured it was the problem and moved it out, didn't realize it would still be picked up.

Thanks so much for your reply and your dope software man.

**Comment by robbert-vdh** [comment]
Parsing failures should probably not actually cause the whole plugin to fail to load though! I'll address that in the next update.
