### ISSUE TITLE
Build failure of 5.0.5 on Fedora 39

### ISSUE THREAD

**Issue by plaimbock** [robbert-vdh/yabridge#283]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Build of 5.0.5 fails on Fedora 39.

### What did you expect to happen?

Build succeeds

### What actually happened?

Build fails with:

/builddir/build/BUILD/yabridge-5.0.5/build/../src/wine-host/../common/logging/common.cpp:78:60: error: invalid initialization of reference of type â€˜const std::wstring&â€™ {aka â€˜const std::__cxx11::basic_string<wchar_t>&â€™} from expression of type â€˜std::stringâ€™ {aka â€˜std::__cxx11::basic_string<char>â€™}
   78 |         verbosity_level = static_cast<Verbosity>(std::stoi(verbosity));

### Operating system

Fedora 39 x86_64

### How did you install yabridge?

Not yet installed

### yabridge version

5.0.5

### yabridgectl version

N/A

### Wine version

wine-tkg 8.18

### Plugin

N/A

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

N/A

### Desktop environment or WM

N/A

### GPU model

N/A

### GPU drivers and kernel

N/A

### Debug log

See https://download.copr.fedorainfracloud.org/results/patrickl/yabridge/fedora-39-x86_64/06573424-yabridge/builder-live.log.gz

**Comment by robbert-vdh** [comment]
Seems to be an issue with Fedora's multilib GCC (or at least, it doesn't happen on Arch with the same version). Compiling this with `g++ -m32` will also fail in the same way:

```cpp
#include <string>

int main() {
    std::stoi("4");
}
```

You'll need to check if there's a bug report for this on Fedora's issue tracker already. Multilib stuff isn't super popular anymore so it may have just slipped under the radar.

**Comment by plaimbock** [comment]
This is a bug in GCC and not a bug in yabridge so closing.
