### ISSUE TITLE
Hangs after sync

### ISSUE THREAD

**Issue by Lazerbeak12345** [robbert-vdh/yabridge#287]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Yabridge hangs after/during a sync. While it doesn't seem to break the plugins (they run perfectly), it does break any scripts I have set up, since the process simply never terminates.

Steps:

1. Have multiple plugins installed and set up, usable in the plugin host
2. System updates wine, and reboot
3. Run `yabridgectl sync --prune`

### What did you expect to happen?

1. Have that window popup that wine does when wine is re-configuring things after an update
2. After an amount of time, preferably with a progress indicator of some sort, the program exits without an error code.

### What actually happened?

1. The window pops up
2. After that wine window closes on it's own, the app appears to hang.

If I `^C` yabridge, then I try to use the bridged plugins in my plugin host - they still work perfectly.

### Operating system

Fedora (38 and 39)

### How did you install yabridge?

Fedora COPR, following the guide here: https://copr.fedorainfracloud.org/coprs/patrickl/yabridge/ and this one here https://copr.fedorainfracloud.org/coprs/patrickl/wine-tkg/

### yabridge version

5.0.5 according to dnf?

### yabridgectl version

5.0.5

### Wine version

Multiple, current: wine-8.21.r0.ge546e2f1 ( TkG Staging Esync Fsync )

### Plugin

Multiple.

### Plugin type

both VST2 and VST3

### Plugin architecture

both 64-bit and 32-bit

### Host

Ardour

### Desktop environment or WM

N/A

### GPU model

N/A

### GPU drivers and kernel

N/A

### Debug log

Can't easily obtain - I could get this the next time wine updates though. (I've disabled my cronjob so I can do exactly this when wine next updates)

### Anything else?

List of plugins `ls ~/.vst3/yabridge ~/.vst/yabridge/ | grep "^[^/].*" | cat -n`

```
     1  LOVE-FI 2 LITE 2.0.0 VST3 WIN 64 BIT
     2  LOVE-FI 3 LITE VST3 WIN
     3  Speldosa.vst3
     4  Delay Lama
     5  Frohmage_vstwin_x64.dll -> ~/.wine/drive_c/Program Files/Steinberg/VSTPlugins/Frohmage_vstwin_x64.dll
     6  Frohmage_vstwin_x64.so
     7  LOVE-FI 2 LITE 2.0.0 VST WIN 64 BIT
     8  MeowSynth
     9  OTT_x64.dll -> ~/.wine/drive_c/Program Files/Steinberg/VSTPlugins/OTT_x64.dll
    10  OTT_x64.so
    11  Speldosa.dll -> ~/.wine/drive_c/Program Files/Steinberg/VSTPlugins/Speldosa.dll
    12  Speldosa.so
    13  VSTSpeek-1.3 (64bit)
```

**Comment by robbert-vdh** [comment]
Yabridge just launches a regular Wine process to check your Wine install. You can get it to do the same thing it does when Wine is updated by running `wineboot -u`. That may make it easier to figure out if there's anything wrong with your `~/.wine` prefix.

Closing since this is not an issue with yabridge(ctl) itself.

**Comment by Lazerbeak12345** [comment]
I don't know how to report this upstream.

**Comment by robbert-vdh** [comment]
> resource to learn how to report this to the relevant wine subproject (I have no idea what project, since I don't know how yabridge works), if applicable

Yabridge just runs `yabridge-host.exe`. Like I said before, you can run `wineboot -u` to have Wine do the same thing it does after a version upgrade.
