### ISSUE TITLE
Reaper 7.07 -> Yabridge 5.05 -> Wine 9.0-RC2 -> Momentum 1.5.1 (Drag & Drop not working)

### ISSUE THREAD

**Issue by OzFalcon** [robbert-vdh/yabridge#290]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Unable to drag and drop samples into plugin (Either VST/VST3)
Setup yabridge.toml for Reaper in both ~/.vst/yabridge/ and ~/.vst3/yabridge/
```
# These options would be applied to all plugins that do not already have their
# own configuration set
["*"]
editor_force_dnd = true
editor_disable_host_scaling = true
```

### What did you expect to happen?

Drag and Drop to work and place sample in plugin.

### What actually happened?

When using Reaper Media Explorer:
Sample was dropped into reaper as a new track and ignored the open plugin GUI.

When using NEMO/Thunar with `editor_force_dnd = true`
Nothing happens. The sample is neither dropped into the plugin or dropped as a new track.
(This is a positive, As it seems the dnd is actually being intercepted by the plugin window)

When using NEMO/Thunar with `editor_force_dnd = false`
Sample was dropped into reaper as a new track and ignored the open plugin GUI.

### Operating system

Debian 12.4

### How did you install yabridge?

Manualy into ~/.local/share/yabridge/

### yabridge version

5.0.5

### yabridgectl version

5.0.5

### Wine version

Wine 9.0 RC2 (devel branch)

### Plugin

Momentum 1.5.1 (Free plugin / Requires registration)
https://www.bigfishaudio.com/momentum.html

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Reaper 7.0.7

### Desktop environment or WM

XFCE 4.18

### GPU model

NVidia RTX 3060

### GPU drivers and kernel

NVidia driver 525.147.05

### Debug log

`rm -f /tmp/yabridge.log; env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=2+editor pw-jack /opt/REAPER/reaper`

Updated logfile with clear actions:
1. Load Reaper
2. Add new track
3. Add Momentum VST3i plugin to track FX
4. Drag and Drop sample from NEMO
5. Close Reaper
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/13721711/yabridge.log)

### Anything else?

Linux file explorers tried are Thunar and Nemo.
When using Reapers media explorer the sample is dropped as a new track.
If I run wine explorer - I am able to drag and drop from there. But using windows explorer is a pita.

I also tried `yabridgectl sync` after adding the yabridge.toml files to the .vst/.vst3 directories.

The plugin seems to work ok. I can download and use bigfish sample set from the plugin itself.

Both Reaper 7.07 and Reaper 6.82 produce the same result. 
Both Wine-devel and Wine-staging produce the same result.
The plugins fail to run in Wine 8.x stable.

Problem appears with other dnd plugins, Possibly a problem with dnd in general.
https://decomposer.de/sitala/releases/Sitala-1.0-Setup-64.msi

**Comment by OzFalcon** [comment]
Updated logfile with clear actions:
1. Load Reaper
2. Add new track
3. Add Momentum plugin to track FX
4. Drag and Drop sample from NEMO
5. Close Reaper
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/13721711/yabridge.log)

**Comment by robbert-vdh** [comment]
> When using Reaper Media Explorer:

Does it work when dragging the sample from an external program, like Dolphin or Nautilus? Alternatively, does it work when using the Windows version of REAPER running under Wine? I'd be very surprised if REAPER's internal drag and drop mechanism used Xdnd, and I'd expect dragging things from REAPER's own GUI to a plugin to not work.

**Comment by TheGuyWhoo** [comment]
This is a linux issue, as far as I'm aware. Drag and drop in a plugin doesn't work in any daw that I've tested under linux mint 20, only in stock plugins and standalone.

**Comment by OzFalcon** [comment]
> Does it work when dragging the sample from an external program, like Dolphin or Nautilus?
No, Dragging from a native Linux file browser into the windows plugin does not work. 

> Alternatively, does it work when using the Windows version of REAPER running under Wine?
Yes, If I drag and drop a sample into WinReaper/Sitala-1.0 plugin running under wine from a typical Linux file manager (Nemo) it does work.

I'll keep an eye on the "host-issue" using the latest Wine-Staging release.

**Comment by OzFalcon** [comment]
> This is a linux issue, as far as I'm aware. Drag and drop in a plugin doesn't work in any daw that I've tested under linux mint 20, only in stock plugins and standalone.

Yes, Seems to be the same for Debian 12 (Desktop -> Xfce) + Wine Staging.

**Comment by OzFalcon** [comment]
> This is a linux issue, as far as I'm aware.
But the question is why, Does the problem lay in Wine or X11?

**Comment by OzFalcon** [comment]
> Does it work when dragging the sample from an external program, like Dolphin or Nautilus? 

README, https://github.com/robbert-vdh/yabridge#drag-and-drop
Yabridge supports drag-and-drop both from a native (X11) Linux application to plugins running under yabridge...

Can you please give an example of this being used and working. I'd like to understand the typical usage more.

**Comment by OzFalcon** [comment]
This problem has been mostly solved - But It raises more questions in doing so.

I finally had some time to have another look at this issue.
To be thorough I decided to try ALL the browsers mentioned by robbert-vdh (Dolphin or Nautilus).
The results were interesting and successful in one browser only!

Here are the results of drag and drop into the windows VST.

Nemo		Failed
Thunar		Failed
Dolphin		Success
Nautilus		Failed

So YES drag and drop from Dolphin file manager into Linux Reaper with Windows VST using yabridge DOES work.
Why Nemo, Thunar and Nautilus fail to work is a mystery for another day.

**Comment by OzFalcon** [comment]
Screenshot of Dolphin Drag and Drop working.
![Dolphin Drag](https://github.com/robbert-vdh/yabridge/assets/13824723/86aa73f0-1595-408d-b74a-464c46b56a6b)
![Dolphin Drop](https://github.com/robbert-vdh/yabridge/assets/13824723/d13e7498-63e1-4b95-b923-387752e6b3e0)
