### ISSUE TITLE
yabridge + Ardour + Neutone plugin: invalid ELF header

### ISSUE THREAD

**Issue by jin-eld** [robbert-vdh/yabridge#294]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I am trying to get the Neutone VST3 plugin to work with Ardour 7 via yabridge and while `yabridgectl sync` does not show any errors, Ardour fails to load the plugin with the following error message:

```
VST3 module-path '/home/xxx/.vst3/yabridge/neutone.vst3/Contents/x86_64-win/neutone.vst3'
[Info]: Scanning: /home/xxx/.vst3/yabridge/neutone.vst3/Contents/x86_64-win/neutone.vst3
[ERROR]: Could not load VST3 plugin '/home/xxx/.vst3/yabridge/neutone.vst3/Contents/x86_64-win/neutone.vst3': /home/xxx/.vst3/yabridge/neutone.vst3/Contents/x86_64-win/neutone.vst3: invalid ELF header
Cannot load VST3 module: '/home/xxx/.vst3/yabridge/neutone.vst3/Contents/x86_64-win/neutone.vst3'
Scan Failed.
```

I am not sure if this is really a yabridge bug, but perhaps someone has ideas on how to proceed here.

I am on Fedora 37 (wine version wine-8.18-1.fc37.x86_64) and I compiled yabridge 5.1.0 from source (I took the Fedora 38 spec file and used it to compile an rpm on Fedora 37).

I downloaded the Neutone plugin from here https://storage.neutone.ai/installers/neutone-windows-1.4.2.exe and installed it using wine64.

I then added the plugin directory as descrbed in the docs:
`yabridgectl add "$HOME/.wine/drive_c/Program Files/Common Files/VST3"` and called `yabridgectl sync` which found the plugin and exited without an error. So far so good.

Now, when scanning for the plugin in Ardour it fails with the error I posted above. 

When I inspect neutone.vst3 with the `readelf -h` command it says:
```
readelf: /home/xxx/.wine/drive_c/Program Files/Common Files/VST3/neutone.vst3/Contents/x86_64-win/neutone.vst3: Error: Not an ELF file - it has the wrong magic bytes at the start
```

And indeed, looking at it with hexedit - this is not an ELF file?
```
00000000   4D 5A 90 00  03 00 00 00  04 00 00 00  FF FF 00 00  MZ..............
00000010   B8 00 00 00  00 00 00 00  40 00 00 00  00 00 00 00  ........@.......
00000020   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
00000030   00 00 00 00  00 00 00 00  00 00 00 00  28 01 00 00  ............(...
00000040   0E 1F BA 0E  00 B4 09 CD  21 B8 01 4C  CD 21 54 68  ........!..L.!Th
00000050   69 73 20 70  72 6F 67 72  61 6D 20 63  61 6E 6E 6F  is program canno
00000060   74 20 62 65  20 72 75 6E  20 69 6E 20  44 4F 53 20  t be run in DOS
00000070   6D 6F 64 65  2E 0D 0D 0A  24 00 00 00  00 00 00 00  mode....$.......
```

In `/home/xxx/.vst3/yabridge/neutone.vst3/Contents` there are two directories:
`x86_64-linux` and `x86_64-win`, the windows one containts the link to the above file, the linux one contains an `.so` library which indeed is a valid ELF file.

So I am somewhat confused now - is Ardour scanning the wrong file, is it supposed to find the `.so` instead of the `.vst3`?

The stats command refers to the vst3 though:
```
yabridgectl status
yabridge path: <auto>
VST2 location: '/home/xxx/.vst/yabridge'
VST3 location: '/home/xxx/.vst3/yabridge'
CLAP location: '/home/xxx/.clap/yabridge'

libyabridge-chainloader-vst2.so: '/usr/lib64/libyabridge-chainloader-vst2.so' (64-bit)
libyabridge-chainloader-vst3.so: '/usr/lib64/libyabridge-chainloader-vst3.so' (64-bit)
libyabridge-chainloader-clap.so: '/usr/lib64/libyabridge-chainloader-clap.so' (64-bit)

yabridge-host.exe: '/usr/bin/yabridge-host.exe'
yabridge-host-32.exe: '/usr/bin/yabridge-host-32.exe'

/home/xxx/.wine/drive_c/Program Files/Common Files/VST3/
  neutone.vst3 :: VST3, bundle, 64-bit, synced
```

I am now somewhat confused and would appreciate a hint on how to proceed.

### What did you expect to happen?

I expected the plugin to load and be usable.

### What actually happened?

The DAW showed an error message:
```
VST3 module-path '/home/xxx/.vst3/yabridge/neutone.vst3/Contents/x86_64-win/neutone.vst3'
[Info]: Scanning: /home/xxx/.vst3/yabridge/neutone.vst3/Contents/x86_64-win/neutone.vst3
[ERROR]: Could not load VST3 plugin '/home/xxx/.vst3/yabridge/neutone.vst3/Contents/x86_64-win/neutone.vst3': /home/xxx/.vst3/yabridge/neutone.vst3/Contents/x86_64-win/neutone.vst3: invalid ELF header
Cannot load VST3 module: '/home/xxx/.vst3/yabridge/neutone.vst3/Contents/x86_64-win/neutone.vst3'
Scan Failed.
```

### Operating system

Fedora 38

### How did you install yabridge?

self compiled RPM yabridge-5.1.0-1.fc37.x86_64

### yabridge version

5.1.0 release

### yabridgectl version

5.1.0 release

### Wine version

wine-8.18 (Staging)

### Plugin

neutone

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Ardour 7

### Desktop environment or WM

MATE Desktop

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/13773654/yabridge.log)

### Anything else?

In the above log I spotted:
```
21:49:07 [neutone-4EJNXglt] [Wine STDERR] _ivalue_ INTERNAL ASSERT FAILED at "C:\\actions-runner\\_work\\pytorch\\pytorch\\builder\\windows\\pytorch\\torch/csrc/jit/api/object.h":37, please report a bug to PyTorch. ^M
21:49:07 [neutone-4EJNXglt] [Wine STDERR] Exception raised from _ivalue at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch/csrc/jit/api/object.h:37 (most recent call first):^M
```

Now I am wondering, is this coming from the plugin, or is this something else? Still wondering what the wrong ELF header error is all about...

**Comment by robbert-vdh** [comment]
Ardour's been trying to load Windows VST3 modules on Linux for a while now. That obviously doesn't work. There should be a second entry in your plugin list for the Linux plugin.
