### ISSUE TITLE
Spitfire's library manager software doesn't work without "winetricks dxvk1103" (or newer)

### ISSUE THREAD

**Issue by aki-k** [robbert-vdh/yabridge#295]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Spitfire's library manager software installs fine with wine-staging 9.0-rc3 but when I try to open it after install with 
```
wine "C:\Program Files\Spitfire Audio\Spitfire Audio.exe"
```
I only get an unresponsive UI.

### What did you expect to happen?

To open Spitfire library manager software with a working UI

### What actually happened?

The Spitfire library manager software opens, but the UI is non-responsive

### Operating system

Ubuntu 22.04

### How did you install yabridge?

from the releases page

### yabridge version

5.1.0

### yabridgectl version

5.1.0

### Wine version

wine-staging 9.0-rc3

### Plugin

Spitfire BBC Symphony Orchestra Discover

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Ardour 8.1

### Desktop environment or WM

MATE

### GPU model

Intel HD Graphics 4000

### GPU drivers and kernel

Mesa 23.0.4

### Anything else?

These are the other winetricks I install:

gdiplus corefonts mfc42 msxml3 msxml4 msxml6 vcrun2005 vcrun2010 vcrun2012 vcrun2015

**Comment by aki-k** [comment]
The error I originally saw when opening the Spitfire library manager is:
```
err:combase:RoGetActivationFactory Failed to find library for L"Windows.UI.ViewManagement.UIViewSettings
```
I found the fix at https://www.reddit.com/r/linuxaudio/comments/zs7gys/spitfire_audio_labs_broke_after_latest_update/

**Comment by robbert-vdh** [comment]
Closing, since this is not a yabridge issue.
