### ISSUE TITLE
Issue with Spire: error code 126: Module not found.

### ISSUE THREAD

**Issue by TheGuyWhoo** [robbert-vdh/yabridge#296]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

When I try to load spire in my daw, I'm getting this error. Do you have any tips on how to troubleshoot this on wine? I tried windows version of process monitor, but unfortunately that doesn't work under wine.

### What did you expect to happen?

The plugin to load

### What actually happened?

error code 126: Module not found.

### Operating system

linux mint 20

### How did you install yabridge?

directly from releases

### yabridge version

latest

### yabridgectl version

latest

### Wine version

staging 7.9

### Plugin

Spire

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

reaper

**Comment by TheGuyWhoo** [comment]
Nvm, it needs d2d1.dll.

**Comment by robbert-vdh** [comment]
Marking as solved.
