### ISSUE TITLE
Ability to append text to plugin names during scan.

### ISSUE THREAD

**Issue by mcoyle1960** [robbert-vdh/yabridge#297]
### Feature description

I currently have 36 bridged plugins. It's hard to remember with all my plugins which are bridged or not. I want to keep track because it may affect my decision to use a plugin based on stability, resources, etc. So, I append the name of each plugin with "-WIN". 

It would be cool if yabridgectl gave you the ability to append a suffix to bridged plugins. Something like:

`yabeidgectl sync --append '-WIN'
`

Thanks for all your work.

**Comment by robbert-vdh** [comment]
Your DAW may be able to show the location of the plugin on disk, which would be able to give you this information. Or you may be able to add tags manually in your DAW's plugin manager. Changing the behavior of plugins unless absolutely necessary is kind of against the design goals of yabridge.
