### ISSUE TITLE
cmake, pkg-config and libxcb not found by meson on Fedora 32

### ISSUE THREAD

**Issue by plaimbock** [robbert-vdh/yabridge#31]
**Problem description**
cmake, pkg-config and libxcb are not found by meson on Fedora 32

**What did you expect to happen?**
Deps are found

**What actually happened?**

Pkg-config binary for MachineChoice.HOST is cached as not found.
Pkg-config binary for machine MachineChoice.HOST not found. Giving up.
CMake binary for MachineChoice.HOST is not cached
None of 'CMAKE' are defined in the environment, not changing global flags.
CMake binary missing from cross or native file, or env var undefined.
Default target is not allowed for cross use
Found CMake: NO
No CMake binary for machine MachineChoice.HOST not found. Giving up.
Run-time dependency xcb found: NO 

Meson version 0.55.0.

The cmake, pkg-config, and libxcb-devel RPMs are installed:

$ rpm -qa | egrep 'cmake|pkg-config|libxcb' | sort
cmake-3.17.4-1.fc32.x86_64
cmake-data-3.17.4-1.fc32.noarch
cmake-filesystem-3.17.4-1.fc32.x86_64
cmake-rpm-macros-3.17.4-1.fc32.noarch
libxcb-1.13.1-4.fc32.x86_64
libxcb-devel-1.13.1-4.fc32.x86_64
pkgconf-pkg-config-1.6.3-3.fc32.x86_64

$ which cmake
/usr/bin/cmake

$ ls /usr/include/xcb/xcb.h
/usr/include/xcb/xcb.h
$ ls /usr/lib64/libxcb.*
/usr/lib64/libxcb.so  /usr/lib64/libxcb.so.1  /usr/lib64/libxcb.so.1.1.0

$ which pkg-config
/usr/bin/pkg-config

**System information**
- Operating system: Fedora 32 x86_64
- Wine version: Wine Staging 5.14
- Installation method: not there yet :-)
- yabridge version: 1.4.1
- yabridgectl version: 1.4.1

Please let me know if you need more information.

**Comment by robbert-vdh** [comment]
I know very little about Fedora's package situation so I'm not sure what they've changed since Fedora 31 that would break cross-compilation, but I've got the build working after manually telling meson which `pkgconfig` binary to use in `cross-wine.conf`. I've added this as the default in commit be1a9c64962a2e41dc8df2e9f0f3bdad5aaf65e, so the build should work fine again on Fedora:

```shell
dnf install git pkg-config gcc-c++ meson glibc-devel.x86_64 glibc-devel.i686 libstdc++-devel.x86_64 libstdc++-devel.i686 wine-devel.x86_64 wine-devel.i686 boost-devel.x86_64 boost-devel.i686 libxcb-devel.x86_64 libxcb-devel.i686

git clone https://github.com/robbert-vdh/yabridge.git
cd yabridge
meson setup build --buildtype release --cross-file cross-wine.conf -Dwith-bitbridge=true
ninja -C build
```

**Comment by plaimbock** [comment]
That worked like a charm. Thanks for the quick fix!
