### ISSUE TITLE
Log files on $HOME

### ISSUE THREAD

**Issue by rolodoom** [robbert-vdh/yabridge#314]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I've notice on UbuntuStudio that everytime I load a VST plugin on Reaper, some log files are generated on the $HOME folder:

* yabridge-host.exe.so_d3d10.log
* yabridge-host.exe.so_d3d11.log
* yabridge-host.exe.so_dxgi.log
* yabridge-host.exe.so.dxvk-cache

Is this behavior expected? The plugins are working fine, but, if I delete this logs, and re-open the plugin, the logs are re-generated.

The yabridge installation is on `~/.local/share/yabridge` as instructed on the README and is working.

Wine 9.3 Stagin
Yabridgectl 5.1.0
Reaper 7.11 Linux
UbuntuStudio 23.10

### What did you expect to happen?

Not to see log files on the $HOME folder

### What actually happened?

There are log files on the $HOME folder

### Operating system

UbuntuStudio 23.10

### How did you install yabridge?

As instructed on the Readme on ~/.local/share/yabridge

### yabridge version

5.1.0

### yabridgectl version

5.1.0

### Wine version

9.3 Stagin

### Plugin

Some VST

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Reaper 7.11

### Desktop environment or WM

Plasma 5.27.8

**Comment by robbert-vdh** [comment]
Those files are created by DXVK, not yabridge. They'll be created the current directory of your DAW is when it loads the plugins.
