### ISSUE TITLE
Error with yabridge sync 

### ISSUE THREAD

**Issue by Srjosep** [robbert-vdh/yabridge#321]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I get this error when I try to sync yabridge 5.1.0:

Warning: Could not run 'yabridge-host.exe'. Wine reported the following error:
    0098:err:hid:udev_bus_init UDEV monitor creation failed
    Make sure that you have downloaded the correct version of yabridge for your distro.
    This can also happen when using a version of Wine that's not compatible with this version of
    yabridge, in which case you'll need to upgrade Wine. Your current Wine version is '9.5
    (Staging)'

If I call yabridge-host directly I get:

~/.local/share/yabridge/yabridge-host.exe
002c:fixme:winediag:loader_init wine-staging 9.5 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
0098:err:hid:udev_bus_init UDEV monitor creation failed
La aplicación no se pudo ejecutar, o no hay ninguna aplicación asociada con el archivo especific
ado.
ShellExecuteEx fallido: Archivo no encontrado.

### What did you expect to happen?

Add win vst

### What actually happened?

crash

### Operating system

Kubuntu 22.04F

### How did you install yabridge?

From releases page

### yabridge version

5.1.0

### yabridgectl version

5.1.0

### Wine version

9.5

### Plugin

Amplitube 5

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Reaper

**Comment by DaemonMorningstar** [comment]
having same issue on arch, i'm assuming its because of the new wine update. worked for me just 3 days ago before updating wine.

**Comment by mluckau** [comment]
I have the same problem with manjaro and wine 9.5

![Screenshot_20240324_222216](https://github.com/robbert-vdh/yabridge/assets/6820488/08e4a0c4-f0f9-46c7-adec-fcecdd7f24bf)

**Comment by robbert-vdh** [comment]
Try [downgrading](https://github.com/robbert-vdh/yabridge?tab=readme-ov-file#downgrading-wine) to Wine Staging 9.5 for now. See #320.
