### ISSUE TITLE
Superior drummer 2 "drag 'n drop"

### ISSUE THREAD

**Issue by Brynildsen** [robbert-vdh/yabridge#33]
When you grab a midiloop from inside the wine window frame and move it a few mm, that exact midifile instantly gets created in `~/.wine/drive_c/ProgramData/Toontrack/Superior2`. Keeping a filemanger pinned and open right next to the vst window, makes it sort of possible to have an okay workflow, using this "sudo" drag 'n drop technique.  [Example here](https://i.imgur.com/BU91jdj.mp4).

It might be worth mentioning in README.md, and it might be worth looking into if other plugins do the same.

**Comment by robbert-vdh** [comment]
The suggestions for working around these current limitations are now part of the readme. Please let me know if there are any other developments in Wine -> X11 drag-and-drop!
