### ISSUE TITLE
Do you have any plans to port it to macOS? I really hope to be able to use it on macOS！

### ISSUE THREAD

**Issue by Darling-Lee** [robbert-vdh/yabridge#330]
### Feature description

Do you have any plans to port it to macOS? I really hope to be able to use it on macOS！

### Anything else?

Please!

**Comment by robbert-vdh** [comment]
No plans, no. That would take a lot of effort, and in the last couple decades I have not seen any commercial audio plugins launch without macOS support. Also see #268.
