### ISSUE TITLE
UDEV monitor creation failed

### ISSUE THREAD

**Issue by jadonyack** [robbert-vdh/yabridge#336]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Hi, I was following along with the guide, and everything seemed to be working smoothly. Then when I tried to sync I received the following output:

`Setting up VST2, VST3, and CLAP plugins using:
- /usr/lib/libyabridge-chainloader-vst2.so
- /usr/lib/libyabridge-chainloader-vst3.so
- /usr/lib/libyabridge-chainloader-clap.so

Finished setting up 2 plugins (0 new), skipped 0 non-plugin .dll files

Warning: Could not run 'yabridge-host.exe'. Wine reported the following error:

    008c:err:hid:udev_bus_init UDEV monitor creation failed

    Make sure that you have downloaded the correct version of yabridge for your distro.
    This can also happen when using a version of Wine that's not compatible with this version of yabridge,
    in which case you'll need to upgrade Wine. Your current Wine version is '9.7'. See the link below
    for instructions on how to upgrade your installation of Wine.

    https://github.com/robbert-vdh/yabridge#troubleshooting-common-issues
`

### Operating system

Arch Linux 6.8.7

### How did you install yabridge?

pacman -S yabridge yabridgectl

### yabridge version

5.1.0-3

### yabridgectl version

5.1.0-3

### Wine version

9.7

### Plugin

NadIR and Emissary

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Reaper 7.15-1

**Comment by jadonyack** [comment]
Seems like this issue was fixed by a recent update from either yabridge or wine, as it works as it should now.

**Comment by Lopuzal** [comment]
I seem to run into the same problem

Either from the pre-built binaries or when I built it myself

If you have a solution, thank you

**Comment by jadonyack** [comment]
Updating Wine fixed it for me. I'm on 9.9 now, but 9.8 worked for me. Maybe try one of those versions?

**Comment by Ayutac** [comment]
Have the problem on 9.13

![image](https://github.com/user-attachments/assets/2350cd65-dada-4b62-b061-73f8aa2e2952)
