### ISSUE TITLE
Crash on sync => DAW crashes on project opening (wine 9.7)

### ISSUE THREAD

**Issue by vlig** [robbert-vdh/yabridge#337]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Reaper have crashed on project opening. So, I've tried to sync - no luck. Then I tried to reinstall from official Arch Linux repo (instead of AUR) - on the next run Reaper started to scan all of the plugins with bunch of yabridge errors, then crashed. On the next run it started OK, but again - it crashes on project opening and on many VST plugins add to a track.

### What did you expect to happen?

I'd like sync to work and VST plugins to load successfully in DAW, as usually.

### What actually happened?

Reaper first crashes on VST plugin loading, yabridge sync says:
```
Warning: Could not run 'yabridge-host.exe'. Wine reported the following error:

00a8:err:hid:stop_polling_device could not find poll entry matching device 0x784b2402d4a0 fd
```

### Operating system

Arch Linux up to date

### How did you install yabridge?

an AUR package, then reinstalled from official repo - no luck

### yabridge version

5.1.0-3

### yabridgectl version

5.1.0-3

### Wine version

wine-staging 9.7-1

### Plugin

bunch of VST2 or VST3 plugins, 64 or 32 bit - doesn't matter

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Reaper

### Desktop environment or WM

KDE Plasma 6.0.4, KDE Frameworks 6.1.0, Qt 6.7.0

### Debug log

https://raw.githubusercontent.com/vlig/err/main/yabridge-sync-error
(log file is too too large to paste it here)

### Anything else?

It happened right after Arch Linux upgrade, certainly wine - to version 9.7.

**Comment by cleinias** [comment]
Confirmed. I'm in the same situation, Archlinux system with Reaper DAW. After today's system update, Reaper stopped launching (crash on launch as per OP's report). Now trying to downgrade Wine

**Comment by cleinias** [comment]
Ha, I had missed the big thread  about wine 9.5 and 9.6 on the issues page. Downgrading to the regular wine 9.4 package (not staging) solved the issue.

**Comment by vlig** [comment]
> Ha, I had missed the big thread about wine 9.5 and 9.6 on the issues page. Downgrading to the regular wine 9.4 package (not staging) solved the issue.

yes, I'm too =) downgraded to wine-staging 8.21-1
