### ISSUE TITLE
`dxvk` for certain plugins

### ISSUE THREAD

**Issue by mrtnvgr** [robbert-vdh/yabridge#342]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Hi! I've encountered an issue. `Cab-Lab 4` requires `dxvk` to render the UI, but `pitchproof` won't update the UI with `dxvk` 😕 How I can apply `dxvk` or any other libraries from `winetricks` only for certain plugins?

### Operating system

NixOS unstable

### How did you install yabridge?

from nixpkgs-unstable

### yabridge version

5.1.0

### yabridgectl version

5.1.0

### Wine version

Wine Staging 9.8

### Plugin type

both VST2 and VST3

### Plugin architecture

both 64-bit and 32-bit

### Host

Reaper

**Comment by BeZaBel** [comment]
I was having a similar trouble with Ignite Amps plugins and Waves plugins. Waves needs the `d2d1.dll` to load properly, but if `dxvk` is present Ignite Amps plugins wont load the UI and [just output a black screen](https://github.com/robbert-vdh/yabridge/issues/339). What I did was to simply make a fresh wine prefix without `dxvk` for Ignite Amps and placed the plugins there. Everything pretty much just works.
