### ISSUE TITLE
plz add "skip directory" feature to config

### ISSUE THREAD

**Issue by F4SH4RP** [robbert-vdh/yabridge#347]

**Comment by visagemsc** [comment]
you can use yabridgectl's blacklist to handle that. just run `yabridgectl blacklist add` to add a folder to the indexing blacklist.

**Comment by F4SH4RP** [comment]
thx, seems to be working (now i dont get the "indexed over 100 000 files" warning) sorry for not reading the --help, altho *blacklist* isn't the most obvious way name for a feature that basically *skips* dirs but whatever

**Comment by F4SH4RP** [comment]
thx, seems to be working (now i dont get the "indexed over 100 000 files" warning) sorry for not reading the --help, altho *blacklist* isn't the most obvious way name for a feature that basically *skips* dirs but whatever

**Comment by F4SH4RP** [comment]
thx, seems to be working (now i dont get the "indexed over 100 000 files" warning) sorry for not reading the --help, altho *blacklist* isn't the most obvious way name for a feature that basically *skips* dirs but whatever
