### ISSUE TITLE
Plugins not showing up in Reaper (Zorin 17.1)

### ISSUE THREAD

**Issue by tonyxln** [robbert-vdh/yabridge#349]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I installed WINE and Yabridge.

I installed Reaper.

I added the VSTs as per the Yabridge instructions and successfully synced them (see screen grab below):

![image](https://github.com/robbert-vdh/yabridge/assets/6032540/7a50892d-b2a9-4c2f-83d1-b0fb7447ae25)

However, Reaper is not seeing my VSTs.

It's a bit frustrating as once I've got my music production working on Linux, I'll be saying goodbye to Windows forever :-)

### What did you expect to happen?

I expected to see my VSTs listed in Reaper.

### What actually happened?

VSTs are not showing in Reaper.

### Operating system

Zorin Pro 17.1

### How did you install yabridge?

I downloaded package and installed as per instructions on the code screen.

### yabridge version

commit 8d0507a

### yabridgectl version

5.1

### Wine version

wine 9.0

### Plugin

all plugins (I've installed 2: one vst 2 and one VST 3 - see screen grab above)

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Reaper

### Desktop environment or WM

not sure

### GPU model

n/a

**Comment by tonyxln** [comment]
I didn't realise this previously but Reaper shows you which plugins had issues while,scanning...

![image](https://github.com/robbert-vdh/yabridge/assets/6032540/2d6968d5-f87c-446c-b66f-8e7862909e8d)

**Comment by tonyxln** [comment]
UPDATE: Sorry guys! My bad, I think, as I'm new to Linux. I initially installed Reaper via the Software center (via FlatPak). I've been looking through posts and forums and it struck me that using FlatPak has issues. So I uninstalled Reaper and them downloaded the Reaper package from the website directly and followed the instructions. And voila, the plugins are now visible in Reaper.

I guess you learn something new everyday - and in Linux's case, you learn a thousand things everyday!!

**Comment by tonyxln** [comment]
Closing this issue...

**Comment by slafniy** [comment]
> initially installed Reaper via the Software center (via FlatPak)

thank man, I had the same issue!
