### ISSUE TITLE
l'assertion « size <= maxSize » a échoué.

### ISSUE THREAD

**Issue by okayawright** [robbert-vdh/yabridge#35]
**Problem description**
Hello,
some, but not all VSTs, I've tried to use with yabridge failed; the strange thing is that all fail the same way, with the same error message: 
`renoise: ../subprojects/bitsery-d24dfe14f5a756c0f8ad3d56ae6949ecc2c99b2e/include/bitsery/serializer.h :292 : void bitsery::Serializer<TOutputAdapter, TContext>::container(const T&, size_t, Fnc&&) [with T = std::vector<VstSpeaker>; Fnc = DynamicSpeakerArrangement::serialize(S&) [with S = bitsery::Serializer<bitsery::OutputBufferAdapter<std::vector<unsigned char>, bitsery::DefaultConfig>, void>]::<lambda(bitsery::Serializer<bitsery::OutputBufferAdapter<std::vector<unsigned char>, bitsery::DefaultConfig>, void>&, VstSpeaker&)>; TOutputAdapter = bitsery::OutputBufferAdapter<std::vector<unsigned char>, bitsery::DefaultConfig>; TContext = void; size_t = long unsigned int]:  l'assertion « size <= maxSize » a échoué.`
My host is Renoise through Jack, I've only experimented with yabridge end Renoise together.
Is there anything I can do?

Thank you for this wonderful piece of software!

**System information**
- Operating system: Fedora 32
- Wine version: Wine staging 5.15
- Installation method: copies through yabridgectl
- yabridge version: 1.5.0
- yabridgectl version: 1.5.0

**Debug log**
example for NostalgiaVST
[wine.log](https://github.com/robbert-vdh/yabridge/files/5152613/wine.log)
[renoise.log](https://github.com/robbert-vdh/yabridge/files/5152615/renoise.log)

**Comment by robbert-vdh** [comment]
Hi,

The issue was due to a limit on the number of audio channels and speakers. I'd set this limit to 256 (because who uses more than 256 audio channels, right? Or so I thought), but Renoise seems to use speaker arrangement with 112 speakers per audio channel. In your case Renoise was trying to use 1792 speakers , so that was causing the serialization errors you'd been seeing. I've increased the limit significantly in 504102ef7924387b67b29eb792e7214139e13d13 so this should no longer be an issue. If you want to try that build you can either compile from source or you can grab a prebuilt version from the [automated builds](https://github.com/robbert-vdh/yabridge/actions?query=workflow%3A%22Automated+builds%22+branch%3Amaster) page.

Since you're using Renoise you may also want to take a look at the top item in the [known issues list](https://github.com/robbert-vdh/yabridge#runtime-dependencies-and-known-issues) in the readme. Some plugins may freeze Renoise, but you can work around this by creating a config file and enabling an option there.

**Comment by okayawright** [comment]
thanks! issue fixed

**Comment by Levitanus** [comment]
```
reaper: /usr/include/bitsery/serializer.h:294: void bitsery::Serializer<TOutputAdapter, TContext>::container(const T&, size_t, Fnc&&) [with T = boost::container::small_vector<VstEvent, 64>; Fnc = DynamicVstEvents::serialize<bitsery::Serializer<bitsery::OutputBufferAdapter<boost::container::small_vector_base<unsigned char, void, void>, bitsery::LittleEndianConfig>, void> >(bitsery::Serializer<bitsery::OutputBufferAdapter<boost::container::small_vector_base<unsigned char, void, void>, bitsery::LittleEndianConfig>, void>&)::<lambda(bitsery::Serializer<bitsery::OutputBufferAdapter<boost::container::small_vector_base<unsigned char, void, void>, bitsery::LittleEndianConfig>, void>&, VstEvent&)>; TOutputAdapter = bitsery::OutputBufferAdapter<boost::container::small_vector_base<unsigned char, void, void>, bitsery::LittleEndianConfig>; TContext = void; size_t = long unsigned int]: Proverochnoe utverzhdenie <<size <= maxSize>> ne vy`polneno.
```
This happens on loading my kontakt templates with at least orchestraltools, which serializes a lot. For the LinVST @osxmidi spetially made the serialization buffer bigger.

yabridgectl version 3.8.1
5.15.38-1-MANJARO #1 SMP PREEMPT Mon May 9 07:52:21 UTC 2022 x86_64 GNU/Linux
wine-7.7

**Comment by robbert-vdh** [comment]
Is that plugin really outputting more than 2048 MIDI events? That sounds...intense. Anyways, I've increased the limit considerably in https://github.com/robbert-vdh/yabridge/compare/78858b98f77336f627e7987ee27dd873fc1efb0a...65cf9cd78287a51d792a3b611ae6d6559ea95d76. Give that a try. You can find instructions on how to install a development build of yabridge here: https://github.com/robbert-vdh/yabridge#installing-a-development-build

Keep in mind that the master branch version of yabridge has had significant changes compared to yabridge 3.8.1. All of the changes are listed in the [changelog](https://github.com/robbert-vdh/yabridge/blob/master/CHANGELOG.md). Make sure you install both `yabridge-git` and `yabridgectl-git`. The new version of yabridge comes with a new way to load yabridge by chainloading the actual plugin libraries from smaller shim libraries that make it so you don't need to rerun `yabridgectl sync` when yabridge gets updated. VST2 plugins are now also set up in `~/.vst/yabridge` by default, so when running `yabridgectl sync` you'll want to check the list of now orphan .so files and then rerun the command with the `--prune` option to get rid of those.

**Comment by Levitanus** [comment]
Thank You, looks like everything is OK.
