### ISSUE TITLE
yabridgectl status/sync prints "Indexed over 100.000 files" twice, then freezes.

### ISSUE THREAD

**Issue by visagemsc** [robbert-vdh/yabridge#350]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I tried scanning for FL synths in `"~/.wine/drive_c/Program Files/Image-Line/FL Studio 21/Plugins/Fruity/Generators"` and status/sync worked once. Then the second time, it printed "Indexed over 100.000 files, press Ctrl+C to cancel this operation if this was not intentional." twice and froze. I tried removing FL's install folder frum yabtidgectl, reinstalling yabridge from the tar archive, deleting the config file and redoing the configuration, blacklisting FL Studio's install folder, and even deleting the yabridge shell plugins to no avail.

### What did you expect to happen?

For yabridgectl to function properly.

### What actually happened?

yabridgectl prints `Indexed over 100.000 files, press Ctrl+C to cancel this operation if this was not intentional.` twice, then freezes.

### Operating system

Debian 12 stable

### How did you install yabridge?

GitHub Relases

### yabridge version

5.1.0

### yabridgectl version

5.1.0

### Wine version

wine-9.8 (Staging)

### Plugin

All of them.

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Bitwig Studio 5.1.8

### Debug log

None got created.

### Anything else?

This was all inside an LXC container.

**Comment by visagemsc** [comment]
Check your symlinks, they could recurse.

**Comment by DCFOS** [comment]
I also have this problem even after resintalling.
Any news, did you manage to fix this?
