### ISSUE TITLE
MONSTER plugins no longer persist patch information

### ISSUE THREAD

**Issue by windowsrefund** [robbert-vdh/yabridge#359]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Somewhere along the way I've ended up with an inability to persist patch data when I load the latest version of [these plugins](https://agushardiman.tv/) into either Carla 2.5.8 or the latest Qtractor (compiled from master).

There are obviously a ton of variables here so I'd like to just see if anyone here has them working. By working, I mean you can load the plugin into (whatever), select a patch, save your session in (whatever), restart the session, and your previously selected patch is restored in the plugin.

Here are just a few details about my environment to start the conversation:

Ubuntu 24.04
yabridge 5.1.0

```
dpkg -l | grep -E 'wine|carla' | awk '{ print $2, $3 }'
carla 6:2.5.8-1kxstudio2
carla-bridge-win32:i386 5:2.6.0~git20240203.2
carla-bridge-win64 5:2.6.0~git20240203.2
carla-data 6:2.5.8-1kxstudio2
libkwineffects14 4:5.27.11-0ubuntu3
wine-staging 9.14~noble-1
wine-staging-amd64 9.14~noble-1
wine-staging-i386:i386 9.14~noble-1
winehq-staging 9.14~noble-1
```

and finally, what yabridge sees

```
yabridgectl status
yabridge path: <auto>
VST2 location: '/home/windowsrefund/.vst/yabridge'
VST3 location: '/home/windowsrefund/.vst3/yabridge'
CLAP location: '/home/windowsrefund/.clap/yabridge'

libyabridge-chainloader-vst2.so: '/home/windowsrefund/.local/share/yabridge/libyabridge-chainloader-vst2.so' (64-bit)
libyabridge-chainloader-vst3.so: '/home/windowsrefund/.local/share/yabridge/libyabridge-chainloader-vst3.so' (64-bit)
libyabridge-chainloader-clap.so: '/home/windowsrefund/.local/share/yabridge/libyabridge-chainloader-clap.so' (64-bit)

yabridge-host.exe: '/home/windowsrefund/.local/share/yabridge/yabridge-host.exe'
yabridge-host-32.exe: '/home/windowsrefund/.local/share/yabridge/yabridge-host-32.exe'

/home/windowsrefund/.vst/win/
  CM-505.dll :: VST2, 32-bit, synced

/home/windowsrefund/.vst3/win/
  GOLDEN Piano v2.2022.08.vst3 :: VST3, legacy, 64-bit, synced
  MONSTER Bass v2-2022.08.vst3 :: VST3, legacy, 64-bit, synced
  MONSTER Drum v3-2022.07.vst3 :: VST3, legacy, 64-bit, synced
  MONSTER OctaChord v1/MONSTER OctaChord v1.vst3 :: VST3, legacy, 64-bit, synced
  MONSTER Strings v1.2022.09.vst3 :: VST3, legacy, 64-bit, synced
  MONSTER Synth v2.2022.10.vst3 :: VST3, legacy, 64-bit, synced

/home/windowsrefund/.wine/drive_c/Program Files/Common Files/VST3/
  Haunted Guitar Lite.vst3 :: VST3, legacy, 64-bit, synced
```

### What did you expect to happen?

Explained above

### What actually happened?

Explained above

### Operating system

Ubuntu 24.04

### How did you install yabridge?

I followed the instructions

### yabridge version

5.1.0

### yabridgectl version

5.1.0

### Wine version

9.14 staging

### Plugin

MONSTER Drum v3-2022.07.vst3

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

It doesn't matter right? The whole point is that yabridge creates a native plugin.

**Comment by robbert-vdh** [comment]
I downloaded the VST3 version of MONSTER Toys v1 2023.10 and wine-tkg 9.8 (will also try with 9.14 in a bit). State seemed to be preserved just fine (tested Carla 2.6.0 alpha 1 and Bitwig Studio 5.2). Maybe try again https://agushardiman.tv/monster-toys-v1-the-ultimate-free-toy-instruments-plugin-for-your-musical-masterpieces/ again with a clean Wine prefix.

> BTW, I really wish I could have brought this up via a discussion rather than an issue.

There's a Discord for things like this. You'll probably get a lot more responses there than here.

**Comment by windowsrefund** [comment]
Thanks so much for the response. I really appreciate it! I realize a Discord exists but real-time chat on a proprietary network is always going to be my last resort when it comes to chasing down a root cause like this. There are just too many variables and things to compare and having a record in a public forum (e.g. not in a silo'd network) is always going to be better for everyone in the long run.

I am very encouraged by your results. I see you went with the `carla-git` package. If you wouldn't mind, I'd love to know more about your actual Carla setup.

Under `Experimental`, are the following enabled?
* `Enable plugin bridges`
* `Enable Wine bridges`

I love your suggestion to try the Toys v1 2023.10 plugin so I'll do that tonight as well as creating a new ~/.wine directory in order for that to do whatever it does. Probably some kind of re-initialization thing.

Thanks again, I'll report back..... hopefully with a win.

**Comment by windowsrefund** [comment]
OK. I have some progress to report. The persistence issue seems to have been resolved as I can load the plugin, change the patch, save to a .carxp file, restart Carla, and then load the session file to see the plugin assigned to the previously saved patch. This is good. However, with `carla-git`, the plugin's UI is all !#$QSDFQ'd up (as you can see)

![toys-ui-carla-git](https://github.com/user-attachments/assets/136e88eb-4349-43af-9465-50efa9746233)

Even though I rm'd my ~/.wine directory, I could not overcome the persistence issue on Carla 2.5.8 so I upgraded as well as downgraded wine-staging to 9.8. Here is a list of all related packages and their versions:

```
> dpkg -l | grep -E 'wine|carla' | awk '{ print $2, $3 }'
carla-bridge-win32:i386 5:2.6.0~git20240203.2
carla-bridge-win64 5:2.6.0~git20240203.2
carla-git 5:2.6.0~git20240203.2
carla-git-data 5:2.6.0~git20240203.2
libkwineffects14 4:5.27.11-0ubuntu3
wine-staging 9.8~noble-1
wine-staging-amd64 9.8~noble-1
wine-staging-i386:i386 9.8~noble-1
winehq-staging 9.8~noble-1
```

and here's what yabridge has synced

```
> yabridgectl status
yabridge path: <auto>
VST2 location: '/home/windowsrefund/.vst/yabridge'
VST3 location: '/home/windowsrefund/.vst3/yabridge'
CLAP location: '/home/windowsrefund/.clap/yabridge'

libyabridge-chainloader-vst2.so: '/home/windowsrefund/.local/share/yabridge/libyabridge-chainloader-vst2.so' (64-bit)
libyabridge-chainloader-vst3.so: '/home/windowsrefund/.local/share/yabridge/libyabridge-chainloader-vst3.so' (64-bit)
libyabridge-chainloader-clap.so: '/home/windowsrefund/.local/share/yabridge/libyabridge-chainloader-clap.so' (64-bit)

yabridge-host.exe: '/home/windowsrefund/.local/share/yabridge/yabridge-host.exe'
yabridge-host-32.exe: '/home/windowsrefund/.local/share/yabridge/yabridge-host-32.exe'

/home/windowsrefund/.vst/win/
  CM-505.dll :: VST2, 32-bit, synced

/home/windowsrefund/.vst3/win/
  GOLDEN Piano v2.2022.08.vst3 :: VST3, legacy, 64-bit, synced
  MONSTER Bass v2-2022.08.vst3 :: VST3, legacy, 64-bit, synced
  MONSTER Drum v3-2022.07.vst3 :: VST3, legacy, 64-bit, synced
  MONSTER OctaChord v1/MONSTER OctaChord v1.vst3 :: VST3, legacy, 64-bit, synced
  MONSTER Strings v1.2022.09.vst3 :: VST3, legacy, 64-bit, synced
  MONSTER Synth v2.2022.10.vst3 :: VST3, legacy, 64-bit, synced
  MONSTER Toys v1.vst3 :: VST3, legacy, 64-bit, synced
```

Next, I'll go through the [Known Issues and fixes](https://github.com/robbert-vdh/yabridge?tab=readme-ov-file#known-issues-and-fixes) section again in the hopes of finding something related to overcoming the UI issue. Other than that, I may be out of bright ideas.

**Comment by windowsrefund** [comment]
A small update here with regards to the Qtractor side of this investigation. Turns out, [this](https://github.com/rncbc/qtractor/commit/ff36c6a251e9da8c0a9d16995be63255279c8282) is the commit that broke VST3 patch persistence.

**Comment by windowsrefund** [comment]
Actually, I'm going to close this as I have no evidence this is related in any way to yabridge itself. I've discovered where Qtractor introduced a bug related to persisting VST3 data and Carla is just a big POS IMHO which will probably never get fixed. Thank you @robbert-vdh for the assist here. I do appreciate the feedback given as there are a bunch of things involved and ruling out this or that can get a bit nuts.
