### ISSUE TITLE
Poise (One Small Clue) fails assertion "current_bridge_instance" during initalization

### ISSUE THREAD

**Issue by yaanae** [robbert-vdh/yabridge#361]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I am moving my audio production to Linux and successfully transferred most of my plugins (_Thanks to you!_). The only one who wouldn't run correctly was Poise, the now free drum sampler from One Small Clue, something which is particularly odd since Grace, the other plugin by One Small Clue works fine.

I have tried both 64-bit and 32-bit versions, and have even tried it in a Pop-OS virtual machine to no success (Grace and other VSTs continues to work).

Reproducing it should be as simple as downloading and installing Poise from the [website](https://www.onesmallclue.com/), and then trying to load it.

### What did you expect to happen?

Loading like other plugins. For example, Grace (also by One Small Clue) loads fine.

### What actually happened?

Plugin fails to load, no visual feedback is produced, failing with the assertion "current_bridge_instance". 

### Operating system

NixOS

### How did you install yabridge?

nixpkgs-unstable

### yabridge version

5.1.0

### yabridgectl version

5.1.0

### Wine version

wine-9.12 (Staging)

### Plugin

Poise (by One Small Clue)

### Plugin type

VST2

### Plugin architecture

both 64-bit and 32-bit

### Host

Reaper 7.18

### Debug log

[yabridge.log](https://github.com/user-attachments/files/16575867/yabridge.log)

**Comment by robbert-vdh** [comment]
I have not yet had the time to actually download the plugin and investigate, but the only thing that could cause this is if the plugin overwrites the second pointer reserved for the host in its `AEffect` object. That's a bug that would need to be fixed on Poise's side. For some more technical context, [this check](https://github.com/robbert-vdh/yabridge/blob/8d0507add7cbe8df0f4a8da65d720a725dbafeaf/src/wine-host/bridges/vst2.cpp#L132-L135) against `plugin->ptr2` now fails. I don't think there are any other fields on the plugin's objects this plugin is allowed to write to, so working around this is going to e tricky. There's a longer explanation for why this works the way it does at the definition of [`yabridge_ptr2_magic`](https://github.com/robbert-vdh/yabridge/blob/8d0507add7cbe8df0f4a8da65d720a725dbafeaf/src/wine-host/bridges/vst2.cpp#L32-L41).

**Comment by yaanae** [comment]
Thanks for looking over this!

I really don't know enough C++ to try and fix this myself, and Poise is closed source and long abandoned, so I guess this  is the final nail in the coffin for me. Luckily switching only took a couple hours, nothing major! *A great thank you for allowing me to finally move over my production!*
