### ISSUE TITLE
Kontakt 7 crashing DAW after attempting to open the rack

### ISSUE THREAD

**Issue by sidoka-contact** [robbert-vdh/yabridge#372]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

When trying to open the rack view of Kontakt 7, the GUI weirdly glitches out, and then both the plugin and the DAW hang, leading to a crash. It seems that it also occupied a bunch of memory, because the system started to lag hard.
How to reproduce:

- Open Reaper
- Create a new project
- Create a new track in said project
- Add Kontakt 7 plugin to said track
- Click the "Library" button
- Click the "Rack view" button
- GUI crashes.

### What did you expect to happen?

Kontakt successfully opening the rack, and updating the GUI normally, without hanging the DAW.

### What actually happened?

Kontakt crashed the DAW.

Video showcase:

https://github.com/user-attachments/assets/732450f9-18e5-4d3b-8b7a-e39cd4ba1156

### Operating system

Arch

### How did you install yabridge?

"yabridge-bin" AUR

### yabridge version

5.1.0

### yabridgectl version

5.1.0

### Wine version

wine-9.18.r1.g3dfacea3 ( TkG Staging Esync Fsync )

### Plugin

Kontakt 7.10.1

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

REAPER 7.22

### Desktop environment or WM

KDE Plasma 6.1.5, KWin (X11)

### GPU model

NVIDIA GeForce GTX 1650

### GPU drivers and kernel

nvidia-open 560.35.03 on Linux 6.10.10

### Debug log

[yabridge.log](https://github.com/user-attachments/files/17193623/yabridge.log)

**Comment by relaborn** [comment]
I'm not sure whether this is your problem (I don't use the portable version) but you appear to have DXVK installed your prefix and Kontakt is one of those plugins that needs to be able to open child windows. Have you tried it without DXVK?

**Comment by usrmusicman** [comment]
Version 8.0.1 portable works just fine with yabridge, don't use dxvk though as that will crash the gui on launch on wine 9.18.

**Comment by robbert-vdh** [comment]
There is no portable version of Kontakt. Please install the latest or an older version through Native Access and see if that works for you.
