### ISSUE TITLE
How do I change the default prefix ~/.wine to another path?

### ISSUE THREAD

**Issue by procobain** [robbert-vdh/yabridge#375]
How do I change the default prefix ~/.wine to another path?

I don't want to use ~/.wine for several reasons, I prefer to create a specific prefix, in this case I would like to use it in: /home/MYUSER/.local/share/bottles/bottles/Yabridge/

How do I do it?

Arch Linux - Kernel-6.11.4 (10/2024)
5.1.0-1 (last 10/2024)
Wine-Stagging 9.12

**Comment by luciorgomes** [comment]
https://simpler-website.pages.dev/html/2021/1/wine-environment-variables/

**Comment by procobain** [comment]
> https://simpler-website.pages.dev/html/2021/1/wine-environment-variables/

But doesn't Yabridge do this automatically? When it generates the .vst3 in /home/USER/.vst3/yabridge/, doesn't this information stay inside the file?

And for example, when opening a vst3 with Reaper, wouldn't it use the folder that Yabridge configured internally?

**Comment by luciorgomes** [comment]
You need to list the folders with the VST files in all your environments (you have more than one). This in mine:
[luciorg@lucio-dellg155530 ~]$ yabridgectl list
/home/luciorg/.local/share/bottles/bottles/Default/drive_c/Program Files/Common Files/VST3
/home/luciorg/.local/share/bottles/bottles/Default/drive_c/Vst
/home/luciorg/.vst/WIN
/home/luciorg/.vst3/WIN
/home/luciorg/.wine/drive_c/Program Files/Common Files/VST3
/home/luciorg/.wine/drive_c/vst
/home/luciorg/.wine_alt/drive_c/Program Files/Common Files/VST3
/home/luciorg/.wine_alt/drive_c/vst
/home/luciorg/.wine_spitfire/drive_c/Vst

**Comment by robbert-vdh** [comment]
If you don't have `$WINEPREFIX` set, yabridge will detect the Wine prefix a plugin is in and use that. See the readme section on Wine prefixes:

https://github.com/robbert-vdh/yabridge?tab=readme-ov-file#wine-prefixes

Otherwise `~/.wine` is the default prefix Wine will use. Yabridge doesn't change anything about that behavior.
