### ISSUE TITLE
Yabridge plug-ins GUI have wrong scaling 

### ISSUE THREAD

**Issue by UNLEASHEDKnifes** [robbert-vdh/yabridge#383]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I believe after some research And troubleshooting that wine-staging 9.22 is causing the GUI of windows plug-ins to scale wrong

### What did you expect to happen?

Like before work as intended But then suddenly two days ago 

### What actually happened?

The mouse was offset in the plug-in GUI window And the scaling was wrong

### Operating system

Ubuntu 24.04.1 LTS

### How did you install yabridge?

From release page 

### yabridge version

5.1.0

### yabridgectl version

5.1.0

### Wine version

Wine 9.22 (staging)

### Plugin

Arturia V collection and Vallhalla

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Ardour 8.10.0

### Desktop environment or WM

KDE plasma 5.27.11

### GPU model

AMD Radeon 780M

### GPU drivers and kernel

6.8.0.49-lowlatency (64-bit)

### Anything else?

Maybe a GUI for yabridgectl would be nice and I have lots of copy of the same plugin but it works fine in terminal

**Comment by robbert-vdh** [comment]
Try upgrading to yabridge 5.1.1. That should address scaling issues with Wine 9.17 onwards.
