### ISSUE TITLE
DAW does not recognize .so plugins

### ISSUE THREAD

**Issue by marko-lazic** [robbert-vdh/yabridge#48]
Given using  
Pop_OS! 20.04
yabridge 1.7.1
yabridgectl 1.7.1
wine 5.20
When installed any VST plugin
And yabridgectl sync
Then in c_drive VSTPlugins directory next to each .dll one .so is created for each .dll
And .so are all 1.3 MB

But when Bitwig scans for plugins $HOME/.wine/c_drive/VSTPlugins/ nothing happens

**Comment by robbert-vdh** [comment]
Hi,

Do you get see any errors why you go to Settings -> Plug-ins -> Show plug-in errors? And did you get any warnings or errors when you ran `yabridgectl sync`?

**Comment by marko-lazic** [comment]
Everything seems fine. Message outputs _Finished setting up 4 plugins using copies (0 new), skipped 0 non-plugin .dll files_
Is size of .so fine if .dll plugin is 90 mb to be 1.3 mb?

**Comment by robbert-vdh** [comment]
Yeah, yabridgectl is creating copies of `~/.local/share/yabridge/libyabridge.so`, so they should all be the same size as that. With the copy-based installation method you'll have to make sure that `~/.local/share/yabridge` is in your PATH when starting Bitwig, but since there are no warnings when running `yabridgectl sync` that's set up properly. Have you checked Bitwig's 'Show plug-in errors' dialog yet?

**Comment by marko-lazic** [comment]
Log says Could not read metadata,

> java.io.IOException: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: createAEffectInstance returned NULL
	at WLa.rLY(SourceFile:47)
	at WLa.CRd(SourceFile:23)
	at kRs.Stj(SourceFile:840)
	at kRs.aXe(SourceFile:771)
	at qhN.aXe(SourceFile:643)
	at hEI.Stj(SourceFile:74)
	at hEI.visitFile(SourceFile:16)
	at java.base/java.nio.file.Files.walkFileTree(Unknown Source)
	at BCX.Stj(SourceFile:622)
	at BCX.aXe(SourceFile:604)
	at Esm.aXe(SourceFile:276)
	at IHA.aXe(SourceFile:881)
	at kRs.aXe(SourceFile:565)
	at kRs.Stj(SourceFile:189)
	at kRs.aXe(SourceFile:139)
	at twA.aXe(SourceFile:573)
	at OGK.aXe(SourceFile:1025)
	at OGK.Stj(SourceFile:897)
	at yXq.Stj(SourceFile:110)
	at yXq.run(SourceFile:91)
	at d1z.run(SourceFile:20)
Caused by: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: createAEffectInstance returned NULL
	at q3v.aXe(SourceFile:163)
	at q3v.CRd(SourceFile:30)
	at N3q.CRd(SourceFile:14)
	at WLa.rLY(SourceFile:43)
	... 20 more
Caused by: java.io.IOException: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: createAEffectInstance returned NULL
	at KU.aXe(SourceFile:157)
	at KU.Stj(SourceFile:178)
	at KU.aXe(SourceFile:286)
	at q3v.aXe(SourceFile:159)
	... 23 more

**Comment by robbert-vdh** [comment]
You'll have to go to the Settings screen in Bitwig, then to Plug-ins, and then to 'Show plug-in errors' to get see the plugin output in Bitwig. Alternatively, close Bitwig, run `yabridgectl sync -f` to force Bitwig to rescan all plugins, and then open Bitwig with the following command:

```shell
env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=1 bitwig-studio
```

Let Bitwig scan the plugins, and then upload the log over at `/tmp/yabridge.log` to hastebin or directly to GitHub by attaching the file to a comment.

**Comment by marko-lazic** [comment]
It says 
com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Communications error with plugin host process
exit code:1
stdout:
PluginHost: Reading VST 2.4 plugin metadata for /home/marko/.wine/drive_c/VSTPlugins/...
For one plugin but of other does not even show errors..

**Comment by robbert-vdh** [comment]
That's not a very useful error. And after running Bitwig with the command I mentioned above there are also no log file created at `/tmp/yabridge.log`, right? What's the output of `ld ~/.wine/drive_c/VSTPlugins/<one_of_your_plugins>.so`?

**Comment by robbert-vdh** [comment]
Have you mamaged to figure out what the issue was?

**Comment by marko-lazic** [comment]
Sorry for the late response, I will let you know today after work.

**Comment by robbert-vdh** [comment]
Also, in the meantime I've released [yabridge 2.0.0/2.0.1](https://github.com/robbert-vdh/yabridge/releases). That's not going to fix whatever's causing issues on your end, but you'll probably want to update anyways (overwrite your existing yabridge files and rerun `yabridgectl sync`) since there are a lot of nice changes, fixes and improvements in there!

**Comment by marko-lazic** [comment]
Today I got very lucky. Usually I was testing with two plugins dpMeter4 and Autotune. The dpMeter4 suddenly starts working, as for autotune I've managed to catch this from the log:

> 15:10:51 [Auto-Tune EFX-5BOWYmpq] hosting mode:  'individually, 64-bit'
15:10:51 [Auto-Tune EFX-5BOWYmpq] other options: '<none>'
15:10:51 [Auto-Tune EFX-5BOWYmpq] 
15:10:51 [Auto-Tune EFX-5BOWYmpq] Enabled features:
15:10:51 [Auto-Tune EFX-5BOWYmpq] - bitbridge support
15:10:51 [Auto-Tune EFX-5BOWYmpq] 
15:10:52 [Auto-Tune EFX-5BOWYmpq] [Wine STDERR] INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
15:10:52 [Auto-Tune EFX-5BOWYmpq] [Wine STDERR] 
15:10:52 [Auto-Tune EFX-5BOWYmpq] [Wine STDOUT] Initializing yabridge host version 1.7.1
15:10:52 [Auto-Tune EFX-5BOWYmpq] The Wine host process has exited unexpectedly. Check the output above for more information.
I will test the new version now.

**Comment by marko-lazic** [comment]
Same log for 2.0.1

> 15:23:35 [Auto-Tune EFX-014Qaglq] 
15:23:35 [Auto-Tune EFX-014Qaglq] config from:   '<defaults>'
15:23:35 [Auto-Tune EFX-014Qaglq] hosting mode:  'individually, 64-bit'
15:23:35 [Auto-Tune EFX-014Qaglq] other options: '<none>'
15:23:35 [Auto-Tune EFX-014Qaglq] 
15:23:35 [Auto-Tune EFX-014Qaglq] Enabled features:
15:23:35 [Auto-Tune EFX-014Qaglq] - bitbridge support
15:23:35 [Auto-Tune EFX-014Qaglq] 
15:23:35 [Auto-Tune EFX-014Qaglq] [Wine STDOUT] Initializing yabridge host version 2.0.1
15:23:35 [Auto-Tune EFX-014Qaglq] The Wine host process has exited unexpectedly. Check the output above for more information.

**Comment by marko-lazic** [comment]
The ldd output 

> marko@pop-os:~/.wine/drive_c/VSTPlugins/Antares$ ldd Auto-Tune\ EFX.so 
	linux-vdso.so.1 (0x00007ffc659cd000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2456384000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f24561a3000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2456188000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2456166000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2455f7c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f245649d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2455e2d000)

and

> marko@pop-os:~/.wine/drive_c/VSTPlugins/TBProAudio$ ldd dpMeter4.so 
	linux-vdso.so.1 (0x00007ffc9efd0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6aaaa96000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6aaa8b5000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6aaa89a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6aaa878000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6aaa68e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6aaabaf000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6aaa53f000)

**Comment by robbert-vdh** [comment]
Do you perhaps have something like `WINEDEBUG=-all` set? According to that `Auto-Tune EFX` log the host process started correctly and it has loaded the plugin's .dll file (otherwise there'd be an error about that), but then it suddenly crashes without any errors or warnings which is very odd. To get a better idea of what's happening, could you run Bitwig from a terminal with:

```env
env WINEDEBUG=warn+all YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=2 bitwig-studio
```

And then try to scan/open the auto tune plugin, and post the log at `/tmp/yabridge.log` here (you can just drag and drop it onto the text field).

**Comment by robbert-vdh** [comment]
Are you still having issues with this?

**Comment by olek-arsee** [comment]
### Hi, I've got a very similiar problem like Marko also with Antares Auto Tune. 
I've installed yabridge correctly with instructions from README. 
It's worth mentioning that all stuff from Klanghelm work well.

_At the screenshot you can see errors from reaper. The file below contains logs._

![image](https://user-images.githubusercontent.com/74045117/149568839-085f902c-ef5c-499e-8ac8-604332bc997b.png)

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/7872558/yabridge.log)

**Comment by robbert-vdh** [comment]
@olek-arsee There's something wrong with your Wine setup. It's complaining about a lot of files that should exist not existing, and your Wine processes are apparently exiting without any other obvious reasons. If you had `YABRIDGE_DEBUG_LEVEL` set to 1 or higher here then that's even more suspicious.
