### ISSUE TITLE
Soundtoys knobs don't work anymore

### ISSUE THREAD

**Issue by lentferj** [robbert-vdh/yabridge#53]
**Problem description**
When you move ny knob in Soundtoys plugins (tried with FilterFreak and EchoBoy) with the mouse, the knob will turn full left and can't be turned to any position.
Tested in Bitwig 3.2.7

**What did you expect to happen?**
Be able to use the knobs with mouse

**What actually happened?**
see above

**System information**
- Operating system: Debian Buster
- Wine version: wine-staging 5.8-buster from WineHQ
- Installation method: copies / manual
- yabridge version: 2.0.1
- yabridgectl version: not in use

**Debug log**
attached
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/5548897/yabridge.log)

**Comment by robbert-vdh** [comment]
Hi,

You say 'don't work anymore', did this ever work? I don't have any Soundtoys plugins installed, but it sounds like there might be a slight chance that the plugin is doing some weird things with screen coordinates. To test this, you can move the plugin window to the top left of your screeen first so that the GUI (not just the title bar of the plugin window, but the GUI within that window) is in the top left corner of your screen. Do the knobs then work as expected? If so, then you could try using the [`editor_double_embed`](https://github.com/robbert-vdh/yabridge#compatibility-options) option, maybe that helps.

**Comment by lentferj** [comment]
I am pretty sure it did, as I have a the Soundtoys range and EchoBoy in my Bitwig default template.
I will give your suggestions a try and report back.

**Comment by lentferj** [comment]
Moving the plugin window to 0,0 doesn't change anything.
When I change the knob values from Bitwig the knobs in the plugin gui move along nicely..
![grafik](https://user-images.githubusercontent.com/5664183/99296416-08c74c00-2847-11eb-8860-e822b04db813.png)

I just tried with Mixbus32C v6.2, too. Same problem there.

**Comment by lentferj** [comment]
I just quickly downgraded EchoBoy to using yabridge 1.7.1 and must admit it has the same problem there :/
I am sure though, it used to work with LinVST.

**Comment by robbert-vdh** [comment]
Perhaps a Wine update broke it somewhere along the way? I just tried the plugins using Wine Staging 5.21, and everything seems to work fine here in a clean Wine prefix without any overrides. I did have to use the 32-bit versions of the plugins as the 64-bit versions would crash.

**Comment by lentferj** [comment]
Upgrading to 5.21 staging did not solve the problem for me :(
I'll keep investigating.

**Comment by lentferj** [comment]
I also tried the editor_double_embed setting (hopefully correctly), still doesn't work

```
~/.wine64/drive_c/Program Files/VstPlugins$ ls -al | grep Soundtoys
drwxr-xr-x  2 lentferj lentferj     4096 Nov 14  2019 Soundtoys
lentferj@ts-d20:~/.wine64/drive_c/Program Files/VstPlugins$ cat yabridge.toml 
["Soundtoys"]
editor_double_embed = true
```

**Comment by robbert-vdh** [comment]
I'm assuming you're using versions 5.0.1 of the plugins, right? Have you tried installing the plugins to a new, clean Wine prefix and using the 32-bit versions of the plugins? That's what worked for me when I tested with Wine Staging 5.21. Maybe one of the overrides in your main Wine prefix (e.g. native GDI+, MSVC++ runtimes etc.) is causing this issue.

**Comment by lentferj** [comment]
I reinstalled (upgraded to latest available version from Soundtoys) and now everything works within the "old" prefix and 64bit. Thank you for your effort. Still strange it just stopped working. The combination of old plugins and old wine should have been ok. Anyway, solved and closed. Thanks again.

**Comment by robbert-vdh** [comment]
Great! If an update fixed it, then whatever caused this issue was probably also causing issues on Windows.
