### ISSUE TITLE
problems installing with 

### ISSUE THREAD

**Issue by eoghanmurray** [robbert-vdh/yabridge#55]
**System information**
- Operating system: Ubuntu 20.04
- Wine version: 5.03 (from winehq)
- Installation method: symlinks + yabridgectl]
- yabridge version: 2.0.2
- yabridgectl version: 2.0.2

**Installation log**

```
yabridgectl$ ./yabridgectl sync
Using '/home/eoghan/.local/share/yabridge/libyabridge.so'

Finished setting up 0 plugins using copies (0 new), skipped 0 non-plugin .dll files

Warning: Could not run 'yabridge-host.exe'. Wine reported the following error: 
    
    0009:err:module:__wine_process_init L"Z:\\home\\eoghan\\.local\\share\\yabridge\\yabridge-
    host.exe.so" 64-bit application not
    supported in 32-bit prefix
    
    This can happen when using a version of Wine that is much older than the version that has been
    used to compile yabridge with. Your current Wine version is '5.0 (Ubuntu 5.0-3ubuntu1)'.
    See the troubleshooting section of the readme for more information on how to upgrade your
    installation of Wine.
    
    https://github.com/robbert-vdh/yabridge#troubleshooting-common-issues

```

I also tried installing a 64 bit 'environment' for wine:

```
yabridgectl$ WINEARCH=win64 WINEPREFIX=~/.wine64 ./yabridgectl sync
Using '/home/eoghan/.local/share/yabridge/libyabridge.so'

Finished setting up 0 plugins using copies (0 new), skipped 0 non-plugin .dll files

Warning: Could not run 'yabridge-host.exe'. Wine reported the following error: 
    
    0049:err:module:__wine_process_init failed to load
    L"Z:\\home\\eoghan\\.local\\share\\yabridge\\yabridge-host.exe.so", error c000012f
    
    This can happen when using a version of Wine that is much older than the version that has been
    used to compile yabridge with. Your current Wine version is '5.0 (Ubuntu 5.0-3ubuntu1)'.
    See the troubleshooting section of the readme for more information on how to upgrade your
    installation of Wine.
    
    https://github.com/robbert-vdh/yabridge#troubleshooting-common-issues
```

It's not clear to me from a careful read of the documentation what the prerequisites are in terms of wine and 32/64bit; any pointers helpful!

**Comment by robbert-vdh** [comment]
Hi,

Like it says in the error message, your version of Wine (5.0) is too old compared to the version used to compile yabridge with. At around Wine 5.5 they've made some backwards incompatible changes to the format, so the builds up on GitHub are compiled with newer versions of Wine. To fix this issue, you should add the [WineHQ repositories](https://wiki.winehq.org/Ubuntu) and then install winehq-staging (`sudo apt install --install-recommends winehq-staging`). Wine 5.0 is quite old at this point anyways, and Wine Staging 5.21 will give you much better plugin compatibility.

**Comment by eoghanmurray** [comment]
Thank you, I had actually tried out the `wine-hq` packages but just did the main one, I assumed the `staging` was for wine developers themselves.
I get a different error now unfortunately:
```$ ./yabridgectl sync
Using '/home/eoghan/.local/share/yabridge/libyabridge.so'

Finished setting up 0 plugins using copies (0 new), skipped 0 non-plugin .dll files

Warning: Could not run 'yabridge-host.exe'. Wine reported the following error: 
    
    0024:err:process:exec_process failed to load L"Z:\\home\\eoghan\\.local\\share\\yabridge\\yabridge-host.exe.so" error c000035a
    
    This can happen when using a version of Wine that is much older than the version that has been used to compile yabridge with. Your current Wine version is '5.21 (Staging)'. See the
    troubleshooting section of the readme for more information on how to upgrade your installation of Wine.
    
    https://github.com/robbert-vdh/yabridge#troubleshooting-common-issues
```

**Comment by robbert-vdh** [comment]
That is odd. Have you removed the other Wine versions? (I'm not sure if Ubuntu lets you install them side by side, but it does for lots of other things) It looks like the file is still being run with an older version. I would nuke every Wine related package first (`sudo apt-get purge '.*wine.*', double check the `The following packages will be REMOVED` list to make sure that's not removing anything unrelated) and then reinstall Wine Staging (`sudo apt install --install-recommends winehq-staging`).

**Comment by eoghanmurray** [comment]
These are the ones removed:
```
The following packages will be REMOVED
  fonts-wine* libwine* wine-stable* wine-stable-amd64* wine-staging* wine-staging-amd64* wine64* winehq-staging*
```
Still no luck:
```
wineserver -k; yabridge-host.exe
002c:fixme:winediag:LdrInitializeThunk wine-staging 5.21 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
INTEL-MESA: warning: Haswell Vulkan support is incomplete
INTEL-MESA: warning: Haswell Vulkan support is incomplete
INTEL-MESA: warning: Haswell Vulkan support is incomplete
INTEL-MESA: warning: Haswell Vulkan support is incomplete
INTEL-MESA: warning: Haswell Vulkan support is incomplete
INTEL-MESA: warning: Haswell Vulkan support is incomplete
INTEL-MESA: warning: Haswell Vulkan support is incomplete
INTEL-MESA: warning: Haswell Vulkan support is incomplete
INTEL-MESA: warning: INTEL-MESA: warning: Haswell Vulkan support is incompleteHaswell Vulkan support is incomplete

INTEL-MESA: warning: Haswell Vulkan support is incomplete
INTEL-MESA: warning: Haswell Vulkan support is incomplete
INTEL-MESA: warning: Haswell Vulkan support is incomplete
INTEL-MESA: warning: Haswell Vulkan support is incomplete
0024:err:process:exec_process failed to load L"Z:\\home\\eoghan\\.local\\share\\yabridge\\yabridge-host.exe.so" error c000035a
```
Thanks for your help so far!

**Comment by robbert-vdh** [comment]
That's so weird! Just to make sure that nothing broke at some point I installed Ubuntu 20.04 in a virtual machine, installed `winehq-staging`, downloaded yabridge 2.0.2 from the releases page, and ran `yabridge-host.exe`. And everything works like you'd expect there.

So some things to try from the top of my head:

- Does running `winecfg` work? That's another Winelib application just like yabridge-host.
- Does `ldd ~/.local/share/yabridge-host.exe.so`  report anything as not found? That shouldn't be the case since everything in there should also be a dependency of Wine, but who knows.
- Maybe something's wrong with your Wine prefix? You can try renaming `~/.wine` to `~/.wine2` (so you can easily restore it when that doesn't work).
- And do you also get the same error when running `yabridge-host-32.exe` from a terminal?

**Comment by eoghanmurray** [comment]
Thank you! re-generation of .wine (by moving) seems to have resulted in no errors!
