### ISSUE TITLE
00d0:err:process:exec_process L"...\\yabridge-host.exe.so" not supported on this system

### ISSUE THREAD

**Issue by jasonlevaillant** [robbert-vdh/yabridge#57]
**Problem description**
I get the following message when I run yabridge sync:

Warning: Could not run 'yabridge-host.exe'. Wine reported the following error: 
    
    00d0:err:process:exec_process
    L"Z:\\home\\jason\\.local\\share\\yabridge\\yabridge-host.exe.so" not       
    supported on this system

If I try to run yabridge-host.exe I get errors:

    0064:err:ole:start_rpcss Failed to start RpcSs service  
    00d0:err:process:exec_process L"Z:\\home\\jason\\.local\\share\\yabridge\\yabridge-host.exe.so" not supported on this system

**System information**
- Operating system: Debian 10
- Wine version: Wine Development 5.22 (from the WineHQ repo)
- Installation method: copies, yabridgectl
- yabridge version: 2.1.0
- yabridgectl version: 2.1.0

**Comment by robbert-vdh** [comment]
HI, 

I've never seen this particular Wine error before, but it sounds very similar to [this one](https://github.com/robbert-vdh/yabridge/issues/55#issuecomment-730643420) from a few days where there was some weird things going on with the default Wine prefix. 'not supported on this system' sounds to me like your main Wine perfix might be set to 32-bit only (for instance if you had set `WINEARCH=win32` when it was first being created). I would try renaming your `~/.wine` directory to for instance `~/.wine-bak` and then try again.

**Comment by jasonlevaillant** [comment]
> HI,
> 
> I've never seen this particular Wine error before, but it sounds very similar to [this one](https://github.com/robbert-vdh/yabridge/issues/55#issuecomment-730643420) from a few days where there was some weird things going on with the default Wine prefix. 'not supported on this system' sounds to me like your main Wine perfix might be set to 32-bit only (for instance if you had set `WINEARCH=win32` when it was first being created). I would try renaming your `~/.wine` directory to for instance `~/.wine-bak` and then try again.

I removed ~/.wine and ran wineserver -k, but there was no change.

Any other suggestions to debug this?

**Comment by robbert-vdh** [comment]
I'd double check that you downloaded the archive called 'yabridge-2.1.0-ubuntu-18.04.tar.gz', and _not_ `yabridge-2.1.0.tar.gz`. If you're sure you've downloaded the version of Ubuntu 18.04/Linux Mint 19/Debian 10, then you could also check whether you didn't accidentally install only the i386 version of Wine (I'd also recommend using `winehq-staging` over `winehq-devel`, but that's not the issue here).

**Comment by jasonlevaillant** [comment]
> I'd double check that you downloaded the archive called `yabridge-2.1.0-ubuntu-18.04.tar.gz`, and _not_ `yabridge-2.1.0.tar.gz`. If you're sure you've downloaded the version for Ubuntu 18.04/Linux Mint 19/Debian 10, then you could also check whether you didn't accidentally install only the i386 version of Wine (I'd also recommend using `winehq-staging` over `winehq-devel`, but that's not the issue here).

Ah, how embarrassing. That was precisely the issue! I'd misread the installation instructions and downloaded the wrong archive. Thank you!

**Comment by robbert-vdh** [comment]
Great! Let me know if you run into any other issues.
