### ISSUE TITLE
Incompatible GLIBC on Debian Buster

### ISSUE THREAD

**Issue by tank-trax** [robbert-vdh/yabridge#59]
Operating System: Debian GNU/Linux 10
KDE Plasma Version: 5.14.5
Qt Version: 5.11.3
KDE Frameworks Version: 5.54.0
Kernel Version: 5.9.0-11.1-liquorix-amd64
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-3470 CPU @ 3.20GHz
Memory: 11.4 GiB of RAM

```
ldd libyabridge.so
./libyabridge.so: /lib/x86_64-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.26' not found (required by ./libyabridge.so)
```

```
ldd --version
ldd (Debian GLIBC 2.28-10) 2.28
```

No luck building it locally either

**Comment by robbert-vdh** [comment]
Hi, 

As mentioned under 'Compatibility' and in the usage section of the readme, you'll have to download the archive that ends with `-ubuntu-18.04.tar.gz` when using Debian 10 or any other distro that's older than Ubuntu 20.04. That version is built for older glibc versions and statically links the libstdc++.

**Comment by tank-trax** [comment]
my apologies and thanks

**Comment by robbert-vdh** [comment]
Ha things like that can always be easy to miss. Let me know if you run into anything else!

**Comment by tank-trax** [comment]
am using Wine-Staging 4.21 so it did not work. The one app I need it for I've migrated to PlayForLinux so can commence the upgrade soon but at a later date as I will likely have to rebuild the ~/.wine folder from scratch and that will take a while

which version of WINE would you suggest?

**Comment by robbert-vdh** [comment]
On Debian Buster (or any distro based on Debian, Ubuntu, or Linux Mint) you'll want to install Wine Staging from WineHQ's [official repositories](https://wiki.winehq.org/Debian). They've made some major strides with Wine's development in the last year both when it comes to compatibility and general responsiveness, and it's still getting better with every release. One thing to be aware of is that Debian Buster (or any Ubuntu version prior to 18.10) doesn't include faudio in its repositories, and you'll get some cryptic errors from apt if you try to install winehq-staging without having faudio in your repositories. I found the easiest way to get faudio on those distros to be through this [SDL2 backports PPA](https://launchpad.net/~cybermax-dexter/+archive/ubuntu/sdl2-backport). After adding this PPA you can just follow the instructions from the WineHQ wiki page as usual. Hope that helps!

**Comment by tank-trax** [comment]
yes I had the SUSE faudio from back when I initially installed Buster, but noticed that backports has since updated to its version

re-upped to the latest Wine Staging and the app that had issues works now and yabridge also works like a charm
