### ISSUE TITLE
After loading first plugin you cannot load another one

### ISSUE THREAD

**Issue by ChuckDaniels87** [robbert-vdh/yabridge#6]
* __SO:__ ArchLinux
* __yabridge:__ 1.0.0-1 (AUR)
* __Wine:__ 5.7-1

First, thank you for putting together this project. I was looking for something like this for a long time. The code is very clean and well documented, congrats!

It seems that after I load a plugin, every plugin I tried to load is the same as the first one. Tested it with Carla and Ardour. 

Images for clarifiying the issue: 
1. Load Amplitube 4:
![Captura de pantalla de 2020-05-04 20-48-11](https://user-images.githubusercontent.com/8478202/81002025-e476c580-8e48-11ea-81e7-72aae47afb23.png)

2. Load MT-Power DrumKit
![Captura de pantalla de 2020-05-04 20-48-20](https://user-images.githubusercontent.com/8478202/81002064-f35d7800-8e48-11ea-9bac-eb9e73b74277.png)

It seems that it is loaded as Amplitube 4 (2) and if you open the configuration are actually two different instances of Amplitube 4 running.

If you need more info, [log with level 2](https://gist.github.com/ChuckDaniels87/2794c3f4adcc582ff53830838d18ee17).

**Comment by robbert-vdh** [comment]
That's an issue with the way Carla loads plugins (though I was sure that it wasn't also the case with Ardour). When Carla first tries to opens a symlink to `libyabridge.so` it will store information about the plugin somewhere in a cache. If you then load another plugin, it will see that the symlinks both point to the same `.so` file and it will then somehow open another instance of the first symlink since it thinks they're the same instead of treating both symlinks as different plugins. I'm not sure why Carla does this, and I don't think it's something we can fix on our side. The workaround is to create copies to andstead of symlinks of `libyabridge.so` as described in the [copying](https://github.com/robbert-vdh/yabridge#copying) section of the readme. Let me know if you're still having issues after trying that!

**Comment by ChuckDaniels87** [comment]
You are right, working with copies of the `.so` is working fine. However, this can be a bit of a pain to handle if there is an update in `yabridge`.

I agree with you that it may be difficult to fix in `yabridge` side without large changes in the project structure. Maybe, a feasible approach would be changing a bit the workflow and create helper scripts. For example:
1. Create a common `$HOME/.local/lib/yabridge` directory.
2. Symlink all `*.dll` to that directory.
3. Run script over that directory to copy `libyabridge.so` and rename it to match all `*.dll`.

To update `yabridge`, you should only need to run the step 3 again. This are just my two cents about the problem.

In the meantime, I have created a script to automate a bit the process for myself and it is working fine. This is the script if it is of any use for anyone:
```bash
#!/bin/env bash
libyabridge="/usr/lib/libyabridge.so"

targets+=("$HOME/.wine/drive_c/Program Files/VstPlugIns/AmpliTube 4.dll")
targets+=("$HOME/.wine/drive_c/Program Files/VstPlugIns/MT-PowerDrumKit.dll")
targets+=("$HOME/.wine/drive_c/Program Files/Native Instruments/VSTPlugins 64 bit/Guitar Rig 5.dll")

# Generate links
for target in "${targets[@]}"; do
    ln -fs "${target}" .
done
# Copy and rename libyabridge
for dll in ./*.dll; do
    cp "${libyabridge}" "${dll%.dll}.so"
done

```

PS: I can confirm that is also failing in Ardour:
![Captura de pantalla de 2020-05-04 22-43-13](https://user-images.githubusercontent.com/8478202/81013417-5e17af00-8e5b-11ea-8e8f-e348215f8430.png)

**Comment by robbert-vdh** [comment]
Right now in the master branch all different symlink setups I could think of are supported. You could even use both a symlink to `libyabridge.so` and a symlink to the .dll file if you're really feeling adventurous haha. I'll add Ardour to the list of hosts that do not play well with symlinks, thanks! It seems like Bitwig is the only host that does support this behavior.

My personal preference installation wise is to just have everything bridged and to just add the `~/.wine/drive_c/Program Files/Steinberg/VstPlugins` directory to your DAW's plugin search path, using something like the snippets listed in the readme:

```shell
yabridge_home=$HOME/.local/share/yabridge

find "$HOME/.wine/drive_c/Program Files/Steinberg/VstPlugins" -type f -iname '*.dll' -print0 |
  xargs -0 -P$(nproc) -I{} bash -c "(winedump -j export '{}' | grep -qE 'VSTPluginMain|main|main_plugin') && printf '{}\0'" |
  sed -z 's/\.dll$/.so/' |
  xargs -0 -n1 cp "$yabridge_home/libyabridge.so"
```

That way you you can easily keep everything up to date and you can pretty much forget that you're even running a bridge (if nothing suddenly breaks, of course).

**Comment by anoadragon453** [comment]
I'm experiencing this issue using the bash snippet mentioned in the README with BitwigStudio v3.1.3, wine 5.6, yabridge e40f90085cb5e1d1b79cec63180f321d014472c7. I needed to use @ChuckDaniels87's workaround.

**Comment by robbert-vdh** [comment]
I've changed the recommendation to use symlinks only with Bitwig Studio, since it looks like there area  lot more hosts that don't support it than there are hosts that do. Feel free to create a new issue if you find any other problems with yabridge 1.1.0.

**Comment by ChuckDaniels87** [comment]
Working fine so far, thanks! :wink:
