### ISSUE TITLE
Korg ms-20 performance problem

### ISSUE THREAD

**Issue by martinbangens** [robbert-vdh/yabridge#64]
**Problem description**
[Korg ms-20 vst](https://id.korg.com/static_pages/3) makes xruns with whatever sample rate I set in jack. and using the gui makes more, scrolling in the gui always gives 3-4 xruns.

**What did you expect to happen?**
run at any sample rate without xruns, plugin is broken.

**What actually happened?**
plugin makes xruns a lot.

**System information**
- Operating system: Manjaro
- [Wine version](https://github.com/nine7nine/pkgbuilds_nspa/tree/master/wine-nspa) 
- yabridge AUR
- yabridgectl AUR

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/5618596/yabridge.log)

**Comment by robbert-vdh** [comment]
First of all, I see your yabridge host applications are at version `2.1.0-11-gcbf276b`, but your `libyabridge.so` copy is from commit `83652a4`. I can't find any commit with that hash so I'm not sure what happened there, but you should always run `yabridgectl sync` after updating to make sure those two stay in sync or weird things can happen.

I downloaded Korg MS-20 1.4.2, installed it to a clean Wine prefix with [wine-tkg 5.22](https://github.com/Frogging-Family/wine-tkg-git) and ran the 64-bit version, and the CPU usage is very low for me with no spikes. Only weird thing is that the editor only updates once every minute or so (which is super weird and also happens in the 32-bit version, but if that doesn't happen for you then that's not an issue). Do those spikes you're experiencing also happen when the editor is closed? 

Other things to try are the 64-bit version of the plugin (you're using the 32-bit version), you could also try enabling fsync by running your DAW with `env WINEFSYNC=1 <daw_name>`. In that case the output should start with `fsync: up and running.`. If that doesn't change anything, then I'd also try installing wine-tkg to see if that helps (although the GUI may also be broken for you there).

**Comment by martinbangens** [comment]
I installed wine-tkg and reinstalld the 64-bit korg vst in a new wine prefix and run `yabridgectl sync`. the plugin seem to be working perfectly right now. I just played a minute. this was probably a wine problem. ZzZz

**Comment by robbert-vdh** [comment]
Great! Does the editor also work like it should? It was probably a compatibility issue with Wine then.

**Comment by martinbangens** [comment]
Scrolling works without xruns and this time registering the plugin looks like it should whit no missing text. No xruns with this wine. From what I saw like 3 minutes. Wine problem for sure. Will test the plugin tomorrow more.

**Comment by martinbangens** [comment]
It runs lovely, play on it for 3 hours on 512 buffer size with no xruns. I only got 1 xrun the first time I opened the gui (that is another problem I noticed with a lot of plugins). The plugin works with wine-tkg 5.22.
`yabridge version 2.1.0-11-gcbf276b`
`wine version: 5.22.r11.g47fea9ff ( TkG Staging Esync Fsync )`
used use this
`env WINEFSYNC_SPINCOUNT=128 WINEFSYNC=1 WINE_RT_POLICY=RR WINE_RT_PRIO=78`

**Comment by robbert-vdh** [comment]
Great! Keep in mind that those `WINE_RT` environment variables are not part of Wine (Staging) but rather part of a custom patch set included in wine-nspa, so here with wine-tkg they weren't doing anything. It's also possible to run either wineserver or the entire Wine user space with realtime priorit,y but from my testing that only makes performance worse so yabridge doesn't automatically do that for you.
