### ISSUE TITLE
window focus in Renoise xfce4

### ISSUE THREAD

**Issue by martinbangens** [robbert-vdh/yabridge#65]
**Problem description**
sometimes if I move the gui window of any plugin and click on the Renoise window again. Renoise windows don't get the focus from xfwm and keyboard input wont work. So I have to close the gui to get around this.
this doesn't happen always.

**What did you expect to happen?**
Renoise to get keyboard focus back 

**What actually happened?**
Renoise don't get keyboard input

**Comment by robbert-vdh** [comment]
I can't reproduce this with Renoise 3.2.4 and the latest master branch yabridge version. If you do find a way to reliably reproduce this, then please let me know.

**Comment by martinbangens** [comment]
oh shit when did they upgrade? I got 3.2.2 downloaded a week ago. I try the new one

**Comment by martinbangens** [comment]
it's still there, to reproduce it you have input notes on the computer keyboard at the same time as you klick on the gui windows border. This is happening with all plugins, so its a renoise bug
