### ISSUE TITLE
LFOTools crashes Reaper

### ISSUE THREAD

**Issue by jarkk0sakkinen** [robbert-vdh/yabridge#71]
Otherwise, most of the Windows plugins work without issues but LFOTool hangs, and finally crashes Reaper.  I tried to use the "Serum workarounds" documented in the README.md but they did not help with this issue (LFOTool is not Serum but just felt worth of a shot anyway).

Can you give me some pointers how to start tracing/debugging this issue? Is there some stripped down VST host that I can pick so that I could try to reproduce this in an environment with less moving parts?

**Comment by robbert-vdh** [comment]
Hi,

LFOTool (and any VST2 plugin that uses VSTGUI) indeed requires native GDI+ and disabled d2d1, but I don't quite remember whether it just doesn't render properly without it (like Serum) or if that would cause it to flat out not work. Have you made sure to install those? You can do so with `winetricks --force gdiplus`, and by opening `winecfg`, adding `d2d1` in the libraries tab and setting its status to disabled. That should of course be done with the same prefix that LFOTool is located in. 

Does the plugin crash when opening the GUI? As in, does the initial scan when you first open REAPER after installing the plugin go through correctly? In that case it might very well be related to that gdiplus thing. Also make sure you're using the latest Wine Staging 5.22 or 6.0rc2 (LFOTool's been working correctly for ages, but being up to date never hurts :grin:). To isolate the plugin, I find it often easiest to open Carla from the command line with `env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=1 carla`, and to then just drag the `LFOTool_x64.so` file created by yabridgectl onto there from your file manager. Yabridge will then write its log output, Wine's output and a lot of additional debugging information to `/tmp/yabridge.log`.

**Comment by jarkk0sakkinen** [comment]
Yeah, it first hangs for some seconds, and then follows the crash. I'll check the other remarks a bit later when I have a bit of bandwidth, and give more inquiry. Thank you!

**Comment by robbert-vdh** [comment]
If it hangs/crashes when opening the GUI it's very likely the GDI+/D2D1 thing. I think I remember this happening without the correct overrides with either OTT or LFOTool (can't remember exactly which one). Serum and the other one of the two works mostly fine but with a lot of graphical glitches when not using those overrides.

**Comment by jarkk0sakkinen** [comment]
First I did **winetricks alldlls=default** for the sake of a known state, nothing else.

This is the initial state in the patchbay view of Carla.

![image](https://user-images.githubusercontent.com/112336/102516330-65609580-4097-11eb-8e0c-38a3b1595195.png)

Then, I added LFOTool, which resulted the following to the log:

```
======= Starting engine =======
======= Engine started ========
Carla engine started, details:
  Driver name:  JACK
  Sample rate:  48000
  Process mode: Multi client
18:41:50 [LFOTool_x64-9AJXijot] Initializing yabridge version 2.2.1
18:41:50 [LFOTool_x64-9AJXijot] host:         '/home/jarkko/.local/share/yabridge/yabridge-host.exe'
18:41:50 [LFOTool_x64-9AJXijot] plugin:       '/home/jarkko/.wine/drive_c/Program Files/Common Files/VST2/Xfer/LFOTool_x64.dll'
18:41:50 [LFOTool_x64-9AJXijot] realtime:     'yes'
18:41:50 [LFOTool_x64-9AJXijot] sockets:      '/run/user/1000/yabridge-LFOTool_x64-9AJXijot'
18:41:50 [LFOTool_x64-9AJXijot] wine prefix:  '/home/jarkko/.wine'
18:41:50 [LFOTool_x64-9AJXijot] wine version: '6.0-rc2'
18:41:50 [LFOTool_x64-9AJXijot] 
18:41:50 [LFOTool_x64-9AJXijot] config from:   '<defaults>'
18:41:50 [LFOTool_x64-9AJXijot] hosting mode:  'individually, 64-bit'
18:41:50 [LFOTool_x64-9AJXijot] other options: '<none>'
18:41:50 [LFOTool_x64-9AJXijot] 
18:41:50 [LFOTool_x64-9AJXijot] Enabled features:
18:41:50 [LFOTool_x64-9AJXijot] - bitbridge support
18:41:50 [LFOTool_x64-9AJXijot] 
18:41:50 [LFOTool_x64-9AJXijot] [Wine STDERR] 002c:fixme:winediag:LdrInitializeThunk wine-staging 6.0-rc2 is a testing version containing experimental patches.
18:41:50 [LFOTool_x64-9AJXijot] [Wine STDERR] 002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDERR] 002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDERR] 002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDERR] 0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDERR] 0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDERR] 005c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDERR] 005c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDERR] 0064:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDERR] 0064:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDERR] 006c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDERR] 006c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDERR] 00f4:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDERR] 00f4:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDERR] 00fc:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDERR] 00fc:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDOUT] Initializing yabridge host version 2.2.1
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDERR] 00f4:fixme:d2d:d2d_factory_init Ignoring factory type 0x1.
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDERR] 00f4:fixme:ver:GetCurrentPackageId (000000000021EF50 0000000000000000): stub
18:41:51 [LFOTool_x64-9AJXijot] [Wine STDOUT] Finished initializing '/home/jarkko/.wine/drive_c/Program Files/Common Files/VST2/Xfer/LFOTool_x64.dll'
```
I got a visual contact of something alive but when I try to open the plugin UI, Carla gets knocked off together with the plugin.

![image](https://user-images.githubusercontent.com/112336/102516945-1b2be400-4098-11eb-8995-784736269175.png)

**Comment by jarkk0sakkinen** [comment]
Remark: LFOTool is still in unregistered state for obvious reasons (cannot copy-paste my serial).

**Comment by jarkk0sakkinen** [comment]
Correction what I've said earlier: Neither Carla nor Reaper literally crash, now that I checked. Carla has been over 30 minutest freezed but not crashed after I tickled LFOTool again.

**Comment by jarkk0sakkinen** [comment]
I do have my Windows machine in easy reach (is actually just a VM residing in the same desktop having a real physical SSD). If I figure out, which files, registry entries or whatever contain my reg info, I could inject that data to my wine folder to same locations and see what happens. I'll hold up for follow-up comments for now, tho.

**Comment by robbert-vdh** [comment]
> First I did **winetricks alldlls=default** for the sake of a known state, nothing else.
>
> ...

You really do need those overrides. I downloaded LFOTool v1.731, installed it to a clean Wine prefix, set up yabridge for it, and then opened the .so file in Carla. As expected, that would cause Carla to freeze when trying to open the editor. Then I ran `winetricks gdiplus` and I set d2d1 in winecfg to disabled, like this:

![afbeelding](https://user-images.githubusercontent.com/748520/102531915-744d4500-40a3-11eb-84e5-f69923a6f92b.png)

After those changes opening the editor works as expected:

![afbeelding](https://user-images.githubusercontent.com/748520/102532134-cc844700-40a3-11eb-84b1-3b81f33e4be9.png)

**Comment by jarkk0sakkinen** [comment]
The reason I did **winetricks alldlls=default** before running the test was just to give the reference for reproducing the issue. I think it is useful to have this data attached for future reference. I'll try today the workaround.

**Comment by jarkk0sakkinen** [comment]
Took care of it:

![image](https://user-images.githubusercontent.com/112336/102615538-ca22fb00-413e-11eb-8c20-87a15717288a.png)

Thanks a lot, got a framework from this how to give a better quality bug report next time.

**Comment by robbert-vdh** [comment]
Great! Yeah native `gdiplus` + disabled `d2d1.dll` are usually the only things needed to get plugins to render properly (and that's only needed for plugins that use VSTGUI, like the Xfer and VoS plugins). Feel free to open a new issue if you into anything else! (or you can join us on the Discord for a quick question)
