### ISSUE TITLE
F33, yabridge 2.2.1 & wine-staging-6.0rc6 32bit linking issue

### ISSUE THREAD

**Issue by plaimbock** [robbert-vdh/yabridge#76]
**Problem description**
/usr/bin/ld: relocatable linking with relocations from format elf64-x86-64 (/usr/lib64/wine/libwinecrt0.a(exe_entry.o)) to format elf32-i386 (yabridge-host-32.MaxGhS.o) is not supported

**What did you expect to happen?**
Linking to succeed :-)

**What actually happened?**
Build failure.

**System information**
- Plugin: n/a
- Plugin type: n/a
- Host: n/a
- Operating system: Fedora 33
- Wine version: wine-staging-6.0rc6
- Installation method: n/a
- yabridge version: 2.2.1
- yabridgectl version: n/a

**Build log**
Build initiated with:
Project name: yabridge
Project version: 2.2.1
C++ compiler for the build machine: c++ (gcc 10.2.1 "c++ (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)")
C++ linker for the build machine: c++ ld.bfd 2.35-15
Using 'CXXFLAGS' from environment with value: '-march=native -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
Using 'LDFLAGS' from environment with value: '-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'
C++ compiler for the host machine: wineg++ (gcc 10.2.1 "g++ (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)")
C++ linker for the host machine: wineg++ ld.bfd 2.35-15
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Configuring config.h using configuration
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Run-time dependency Boost found: YES 1.73.0 (/usr)
Run-time dependency Boost (found: filesystem) found: YES 1.73.0 (/usr)
Using bitsery source from cache.
Downloading bitsery patch from file:./subprojects/bitsery-patch-5.2.0.tar.xz
Download size: 300
Downloading: ..........

|Executing subproject bitsery method meson 
|
|Using 'PKG_CONFIG_PATH' from environment with value: ':/usr/lib64/pkgconfig:/usr/share/pkgconfig'
|Project name: bitsery
|Project version: 5.2.0
|C++ compiler for the build machine: c++ (gcc 10.2.1 "c++ (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)")
|C++ linker for the build machine: c++ ld.bfd 2.35-15
|C++ compiler for the host machine: wineg++ (gcc 10.2.1 "g++ (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)")
|C++ linker for the host machine: wineg++ ld.bfd 2.35-15
|Build targets in project: 1
|Subproject bitsery finished.

|Executing subproject function2 method meson 
|
|Using 'PKG_CONFIG_PATH' from environment with value: ':/usr/lib64/pkgconfig:/usr/share/pkgconfig'
|Project name: function2
|Project version: 4.1.0
|C++ compiler for the build machine: c++ (gcc 10.2.1 "c++ (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)")
|C++ linker for the build machine: c++ ld.bfd 2.35-15
|C++ compiler for the host machine: wineg++ (gcc 10.2.1 "g++ (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)")
|C++ linker for the host machine: wineg++ ld.bfd 2.35-15
|Build targets in project: 1
|Subproject function2 finished.

Run-time dependency threads found: YES

|Executing subproject tomlplusplus method meson 
|
|Using 'PKG_CONFIG_PATH' from environment with value: ':/usr/lib64/pkgconfig:/usr/share/pkgconfig'
|Project name: tomlplusplus
|Project version: 2.1.0
|C++ compiler for the build machine: c++ (gcc 10.2.1 "c++ (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)")
|C++ linker for the build machine: c++ ld.bfd 2.35-15
|C++ compiler for the host machine: wineg++ (gcc 10.2.1 "g++ (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)")
|C++ linker for the host machine: wineg++ ld.bfd 2.35-15
|Build targets in project: 1
|Subproject tomlplusplus finished.

Using 'PKG_CONFIG_PATH' from environment with value: ':/usr/lib64/pkgconfig:/usr/share/pkgconfig'
Run-time dependency xcb found: YES 1.13.1
Message: Bitbridge enabled, configuring a 32-bit host application
Library boost_filesystem found: YES
Library xcb found: YES
Build targets in project: 6

yabridge 2.2.1

  Subprojects
         bitsery: YES
       function2: YES
    tomlplusplus: YES

[snip]

[43/53] wineg++  -o yabridge-host-32 yabridge-host-32.p/src_common_configuration.cpp.o yabridge-host-32.p/src_common_logging.cpp.o yabridge-host-32.p/src_common_serialization.cpp.o yabridge-host-32.p/src_common_communication.cpp.o yabridge-host-32.p/src_common_utils.cpp.o yabridge-host-32.p/src_wine-host_bridges_vst2.cpp.o yabridge-host-32.p/src_wine-host_editor.cpp.o yabridge-host-32.p/src_wine-host_utils.cpp.o yabridge-host-32.p/src_wine-host_individual-host.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -march=native -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -m32 -Wl,--start-group /usr/lib/libboost_filesystem.so -lpthread -lxcb -Wl,--end-group
FAILED: yabridge-host-32 
wineg++  -o yabridge-host-32 yabridge-host-32.p/src_common_configuration.cpp.o yabridge-host-32.p/src_common_logging.cpp.o yabridge-host-32.p/src_common_serialization.cpp.o yabridge-host-32.p/src_common_communication.cpp.o yabridge-host-32.p/src_common_utils.cpp.o yabridge-host-32.p/src_wine-host_bridges_vst2.cpp.o yabridge-host-32.p/src_wine-host_editor.cpp.o yabridge-host-32.p/src_wine-host_utils.cpp.o yabridge-host-32.p/src_wine-host_individual-host.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -march=native -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -m32 -Wl,--start-group /usr/lib/libboost_filesystem.so -lpthread -lxcb -Wl,--end-group
/usr/bin/ld: relocatable linking with relocations from format elf64-x86-64 (/usr/lib64/wine/libwinecrt0.a(exe_entry.o)) to format elf32-i386 (yabridge-host-32.MaxGhS.o) is not supported
winebuild: /usr/bin/ld failed with status 1
winegcc: /usr/bin/winebuild failed
ninja: build stopped: subcommand failed.

**Comment by robbert-vdh** [comment]
Make sure you have the multilib versions of all dependencies including wine-devel itself installed. I listed everything you need for yabridge 2.2.1 on Fedora here: https://github.com/robbert-vdh/yabridge/issues/31#issuecomment-674545556

And yabridge 2.2.1 won't build correctly with Wine 6.0 and up because of some internal changes Wine made. You need to build from commit ae71536639d4966c6cf83e347059b5440005ac0c or from the latest master branch to get a binary that doesn't immediately segfault.

**Comment by plaimbock** [comment]
I rebuilt from HEAD and all is well now.
