### ISSUE TITLE
Jamstix is crashing when interacting with the UI and file system.

### ISSUE THREAD

**Issue by taji** [robbert-vdh/yabridge#78]
I have the Jamstix version 4 VST plugin working with yabridge along with Wine Staging and DXVK. However, there are some user flows in Jamstix that consistently cause the plugin and Reaper to crash.  Details below. Any guidance is appreciated.

**Problem description**
Steps to reproduce:
- Load Jamstix in a new track in Reaper
- Open the UI
- Click on the KIT tab
- Click on the LOAD button, Kit dialog should appear
- Select a Kit (Electronic | 808ish)
- Click “Load Kit”
- Kit should load.
- Click on the GROOVE tab
- Click on the blue “No Style” button next to BRAIN, style dialog should appear
- Select a Style (Electronic | E-Kustom))
- Click “Load Style”
- EXPECTED:  Style should load.
- ACTUAL: UI freezes on the load dialog.  Sometimes it freezes after the "Load Style" dialog almost disappears leaving a single vertical line from on the right side of the dialog.  See attached image

![jamstix-freezes](https://user-images.githubusercontent.com/702031/105651486-a6a94980-5e7c-11eb-9f03-d8f323b5d11c.png)

**System information**
Operating system: Ubuntu Studio 20.04
wine version: '6.0-0 (Staging)'
Installation method: copies, yabridgectl
yabridge version: 2.2.1
yabridgectl version: 2.2.1
Dxvk : Version 1.7.3

Debug log attached.
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/5863688/yabridge.log)

**Comment by robbert-vdh** [comment]
If you take a look at the Wine crash dialog that pops up you might get some indication as to where the memory error occurs, but sadly this is almost certainly a Wine bug and there's probably not much we can do about it. You could try downgrading to Wine Staging 5.22/5.21 or to a non-staging version of Wine to see if that somehow improves the situation.

**Comment by taji** [comment]
Not seeing a wine crash dialog.  Let me investigate a bit.

**Comment by robbert-vdh** [comment]
Since this is not an issue with yabridge, I'll close this issue. If this is still happening with Wine Staging 6.4, have you tried submitting a bug report to Wine's bug tracker?
