### ISSUE TITLE
yabridge-host.exe won't run – err:seh:segv unexpected trap 14

### ISSUE THREAD

**Issue by hardyharz3n** [robbert-vdh/yabridge#83]
Just performed an upgrade to the newest yabridge (3.0.1) which I had postponed because of the regression error in earlier 6.x wine staging. Unfortunately, 'yabridgectl sync' now yields:

> Warning: Could not run 'yabridge-host.exe'. Wine reported the following error: 
>     
>     0138:err:seh:segv_handler_early Got unexpected trap 14 during process initialization

 Using Wine Staging 6.3 (on a current Arch), so it's most likely not due to an outdated Wine package as suggested in the FAQ. Debug log omitted for obvious reasons...

**Comment by robbert-vdh** [comment]
Wine 6.3 breaks all Winelib applications, including yabridge ([wine bug #50731](https://bugs.winehq.org/show_bug.cgi?id=50731)). You'll have to temporarily downgrade to Wine Staging 6.2 until this is fixed in the next batch of Wine commits.

**Comment by hardyharz3n** [comment]
Alright, will try. Thanks for the heads-up!

**Comment by hardyharz3n** [comment]
So...after downgrading to WS 6.2, the yabridge host now runs, apparently! Though sadly, my DAW (Bitwig 3.3.3) now refuses to index any of the bridged plugins – essentially acting like they aren't even there. Restarted wine server, resynced via yabridgectl (which enumerated the plugins correctly and successfully), yet no dice. Dayum. Guess that's something on my end, though...

**Comment by robbert-vdh** [comment]
Go to Settings -> Plug-ins -> Show plug-in errors and then click on 'Rescan all' to rescan all plugins that previously couldn't be initialized.

**Comment by hardyharz3n** [comment]
I did, but it makes no difference, and most plugins didn't throw an error in the first place. Meanwhile, Bitwig seems to be "Indexing VST3 plugins" – as evidenced by a spinner in the upper right – indefinitely. It's been doing that before, might get stuck somewhere and never getting to the plugins in question.

**Comment by robbert-vdh** [comment]
Try restarting Bitwig. And maybe Wine got stuck in some broken state after the downgrade? Try killing all Wine processes with `wineserver -k` if there are any still running.

**Comment by tjblackheart** [comment]
Same problem here. Fixed it by downgrading to 6.2, running `yabridgectl rm <your-vst-dir>`, start Bitwig, let it reindex, kill Bitwig, run `yabridgectl add <your-vst-dir> && yabridgectl sync`, restart Bitwig. Phew! :)

Thanks for this great tool btw, it's the only vstbridge that runs flawlessly - at least on my machine.

**Comment by hardyharz3n** [comment]
How long did it take your BW to reindex, tjblackheart? Seconds, minutes, hours? I suspect my BW's indexing is broken wholesale and am considering wiping the .index files...

**Comment by robbert-vdh** [comment]
@hardyharz3n Did you restart Bitwig? If you click on the little cogwheel icon it should tell you which plugin it's indexing. Should not take more than 100-150 ms per plugin for most plugins.

**Comment by tjblackheart** [comment]
@hardyharz3n Reindex was fast, as I removed all the .so files with `rm` before.

**Comment by hardyharz3n** [comment]
Thanks for the info.

I restarted multiple times. Alas, the tooltip on my spinner isn't quite as specific and only says "indexing VST3 plugins" – and appears intent on maintaining this state until the Sun goes nova.

**Comment by robbert-vdh** [comment]
That uh sounds like a bug in Bitwig haha. Yeah I'd just nuke `~/.BitwigStudio/index/*vst3*` and let it rescan everything.

**Comment by hardyharz3n** [comment]
Funnily enough, there isn't even any vst3.index, merely 'vst2' and 'vsts'...

**Comment by robbert-vdh** [comment]
Huh well maybe that's part of the problem haha. Those 'vsts' index files haven't been written to for me since February 2019, so I guess they had the VST2 and VST3 indices merged in older versions of Bitwig. I'd just nuke (or rename) the entire directory then and have it rescan all plugins and samples just to be safe.

**Comment by hardyharz3n** [comment]
Through some inexplicable dark magic (...and the removal of one seemingly irrelevant, empty library directory?!), it now successfully indexed! Hooray! Thanks for the help, and have fun making music.

**Comment by robbert-vdh** [comment]
Since Wine 6.4 is now in all repos, I'll close this issue. If anyone's reading this, there is another separate issue with Wine 6.5 now (that I've reported [here](https://bugs.winehq.org/show_bug.cgi?id=50869)) that will prevent yabridge 3.0.2 from exiting. yabridge's current master branch has a workaround for this, but you might also want to consider pinning Wine Staging 6.4 since these changes in Wine 6.5 could potentially also break some other things.
