### ISSUE TITLE
Make yabridge run on Windows platform

### ISSUE THREAD

**Issue by FFFF0h** [robbert-vdh/yabridge#86]
Could you make it run on Windows platform ? 
This way, yabridge can be used to sandbox plugins on the Windows platform and also as 32/64 bit bridge for old plugins and VST2/VST3 bridge. 
Thanks

**Comment by FFFF0h** [comment]
Thank you for your detail answer.

**Comment by robbert-vdh** [comment]
I'll close this since I won't be working on this myself, but if anyone else wants to give it a shot feel free to reply and I'll reopen the issue.
