### ISSUE TITLE
Add a blacklist option for yabridgectl

### ISSUE THREAD

**Issue by mitchell-gil96** [robbert-vdh/yabridge#88]
Hi, The current way yabridgectl sync works (correct me if im wrong) is it searches for vst dlls in whatever folder was specified by yabridgectl add, and creates .so bridges for all the plugins indiscriminately, and will do so every time the sync function is run. There are certain plugins in my VST folder that for varying reasons I wish to not create a bridge of. I'd like a way to individually blacklist certain dlls in the folder. 

Is this something that could be possible to implement?

**Comment by robbert-vdh** [comment]
Hi,

In what situation do you have plugins installed that you do not want to use but also don't want to uninstall? I could add blacklists, but I feel like that could start getting very complicated quite quickly (do you blacklist individual plugins? entire directories? does it work based on glob patterns?). The goal of yabridgectl was to have a simple workflow where you add your directories once, and then sync does all of the magic without much else to it. Other than slightly longer scanning times (which should be about 100-200 milliseconds per plugin) having more plugins installed shouldn't have any negative effect, and you could also just uninstall/delete the plugins you don't need. or am I missing something?

**Comment by mitchell-gil96** [comment]
I have a single vst folder that has accumulated over 500 dlls in over 7 years. Some of them crash wine outright, and are unimportant enough that I simply ignore them, others have authorization issues, some are daw-specific and do some sort of self check where if they detect they're not in the intended daw, they shutdown with an error message, etc. Lots of varying reasons.

This folder is located in both linux and windows as my sole source of vsts.

I only blacklist individual plugins, not folders since they are all crammed in a single folder. I dont want to uninstall the plugins because I do occasionally use them in windows.

Also I appreciate the speed in which you respond to your issues page. A rare thing indeed!

**Comment by robbert-vdh** [comment]
Ouch yeah that sounds like a use case for blacklists. Out of curiosity, does that actually not cause a lot of issues? Since most plugins will require being installed to the Wine prefix or they will crash outright because of missing dependencies/data files/settings. An alternative that would be possible right now without blacklists would be to create a second VstPlugins directory right next to the one you currently use, symlink the VST2 plugin .dll files that you want to use to there, and then use that directory instead of the real VstPlugins directory.

**Comment by mitchell-gil96** [comment]
Believe it or not, I never actually installed the plugins in wine! Simply linking the existing dlls with .so bridges and installing a few visual c++ distributables in the wine prefix, adding exceptions, and installing some microsoft fonts allows 90% of my plugins to run fine as is!

As for your suggestion, creating a whitelist folder with symlinked dlls does seem like a viable alternative for the time being.

**Comment by robbert-vdh** [comment]
Sorry that it took so long, I didn't have a lot of time to work on yabridge itself in the last month. Yabridgectl now has a `yabridgectl blacklist` for managing a blacklist that lets you skip over individual files and entire directories in the indexing process. This will be part of the 3.1.0 update due for tomorrow.

**Comment by robbert-vdh** [comment]
This is now part of yabridge 3.1.0! Please open a new ticket if you run into any issues with it.
