### ISSUE TITLE
Plogue plugins

### ISSUE THREAD

**Issue by jarkk0sakkinen** [robbert-vdh/yabridge#90]
Plogue plugins require the workaround for Serum to be removed in order to work, i.e. they require Direct2D. Any means to make both work at the same time? E.g. Chipsynth MD would be one example.

**Comment by robbert-vdh** [comment]
You'll have to create a separate Wine prefix for the Plogue plugins. I know Sforzando also doesn't like disabled D2D1. If you use uninstall the plugins from your main Wine prefix first (make sure the VST2 and VST3 plugins are removed as well), run  `env WINEPREFIX=$HOME/.wine-plogue wine path/to/plugin/installer.exe` to install the plugin to a new prefix, add `~/.wine-plogue/drive_c/Program\ Files/Common\ Files/VST3` to yabridgectl and then run `yabridgectl sync`, those plugins should work. Yabridge will detect which Wine prefix the plugins are in and use that to host the plugin in. Just make sure that you don't have `WINEPREFIX` set when you launch your DAW.

**Comment by jarkk0sakkinen** [comment]
Right, that should work yes, thanks for the tip!
