### ISSUE TITLE
MK Power Drum Kit 2 fails to load

### ISSUE THREAD

**Issue by daniel-j** [robbert-vdh/yabridge#92]
**Problem description**
I try to use MT Power Drum Kit 2 (Linux optimized Windows 64-bit dll) as an instrument in REAPER, and the DAW freezes for a few seconds and then show an error that the plugin couldn't be loaded. I tried another 64-bit Windows plugin called Youlean Loudness Meter and it works fine. I don't have other Windows VST plugins at the moment to test with. I am using PipeWire with PulseAudio and JACK emulation.
I put the dll and its dependency in ~/.vst and ran yabridgectl sync, then started Reaper and created a new virtual instrument track, and selected the plugin.

**What did you expect to happen?**
On my other computer running Fedora 34 with REAPER and yabridge (manually installed), the instrument works fine and the gui shows up. I tried the same Wine build (lutris-6.4) on both machines, since Fedora comes with Wine 6.3 which doesn't work with yabridge.

**What actually happened?**
The plugin fails to load and REAPER shows a message where the plugin's ui is supposed to be, not instantly though, but after several seconds.
![Screenshot from 2021-04-17 21-16-25](https://user-images.githubusercontent.com/1264014/115124396-4f6dcd80-9fc2-11eb-95c9-32f3d27e4bf0.png)
The yabridge debug log ends with an error message (see below)

**System information**
- Plugin: MK Power Drum Kit 2
- Plugin type: VST2
- Host: REAPER
- Operating system: Arch Linux
- Wine version: Wine 6.6-1, Wine 6.4.r0.g7ec998e1 ( TkG Staging Esync Fsync )
- Installation method: yabridge-bin from AUR
- yabridge version: 3.1.0
- yabridgectl version: 3.1.0

**Debug log**
Here is the log with YABRIDGE_DEBUG_LEVEL unset (setting it to 2 hides the wine error)
```
21:04:37 [MT-PowerDrumKit-0HJUWYqu] Initializing yabridge version 3.1.0
21:04:37 [MT-PowerDrumKit-0HJUWYqu] host:          '/usr/bin/yabridge-host.exe'
21:04:37 [MT-PowerDrumKit-0HJUWYqu] plugin:        '/home/djazz/.vst/MT/MT-PowerDrumKit.dll'
21:04:37 [MT-PowerDrumKit-0HJUWYqu] plugin type:   'VST2'
21:04:37 [MT-PowerDrumKit-0HJUWYqu] realtime:      'yes'
21:04:37 [MT-PowerDrumKit-0HJUWYqu] sockets:       '/run/user/1000/yabridge-MT-PowerDrumKit-0HJUWYqu'
21:04:37 [MT-PowerDrumKit-0HJUWYqu] wine prefix:   '<default>'
21:04:37 [MT-PowerDrumKit-0HJUWYqu] wine version:  '6.6'
21:04:37 [MT-PowerDrumKit-0HJUWYqu] 
21:04:37 [MT-PowerDrumKit-0HJUWYqu] config from:   '<defaults>'
21:04:37 [MT-PowerDrumKit-0HJUWYqu] hosting mode:  'individually, 64-bit'
21:04:37 [MT-PowerDrumKit-0HJUWYqu] other options: '<none>'
21:04:37 [MT-PowerDrumKit-0HJUWYqu] 
21:04:37 [MT-PowerDrumKit-0HJUWYqu] Enabled features:
21:04:37 [MT-PowerDrumKit-0HJUWYqu] - bitbridge support
21:04:37 [MT-PowerDrumKit-0HJUWYqu] - VST3 support
21:04:37 [MT-PowerDrumKit-0HJUWYqu] 
21:04:38 [MT-PowerDrumKit-0HJUWYqu] [Wine STDOUT] Initializing yabridge host version 3.1.0
21:04:38 [MT-PowerDrumKit-0HJUWYqu] [Wine STDOUT] Preparing to load VST2 plugin at '/home/djazz/.vst/MT/MT-PowerDrumKit.dll'
21:04:44 [MT-PowerDrumKit-0HJUWYqu] [Wine STDERR] 0090:err:rpc:I_RpcReceive we got fault packet with status 0x1c010003
21:04:45 Error during initialization:
21:04:45 read: End of file
```

**Comment by daniel-j** [comment]
I just tried the same instrument plugin with LinVst, and it works fine. I can play drums on Arch Linux now atleast :)

**Comment by robbert-vdh** [comment]
Do you also get that `0090:err:rpc:I_RpcReceive we got fault packet with status 0x1c010003` there? I can't reproduce this with `yabridnge-bin` from the AUR and both `wine-6.6-1` and `wine-tkg-staging-fsync-git-6.4.r0.g7ec998e1-322`. I also haven't heard of anyone else with these kinds of issues, so it be nice to know what could cause that. Do you perhaps use sandboxes/firejail? Or do you have some sort of firewall running? Running REAPER from the terminal (or if you have Carla installed, `carla-single vst2 ~/.vst/MT/MT-PowerDrumKit.dll`) might show you more Wine output if the actual error is being hidden by the startup getting terminated. Could you try that for me?

![afbeelding](https://user-images.githubusercontent.com/748520/115128327-4f2efb80-9fdd-11eb-84de-f86093d2993f.png)

**Comment by daniel-j** [comment]
After a lot of testing without success, I tried setting the audio device to Dummy in Reaper and restarted it, then I can load the plugin! :open_mouth: Also works if I use PulseAudio. But if JACK is loaded before I the plugin, it plugin will fail to load. Might be an issue with PipeWire here, since that's what I'm using (but I also use it on Fedora, same version without issue). I don't see any warnings or errors in the PipeWire logs.

**Comment by robbert-vdh** [comment]
That's odd! PipeWire isn't really ready yet for pro audio usage (the latency and overhead are still a bit high, and it's missing jACK features like freewheeling and latency compensation), but it should probably work. But yeah, I've seen PipeWire cause a lot of headaches for DAW-users lately. Anyways, yabridge doesn't and can't interact with the audio system at all, so this would be a PipeWire and/or REAPER issue.

**Comment by daniel-j** [comment]
I tried Ardour 6 and the instrument doesn't appear in the list at all when making a new Midi track. I can see other Windows plugins, but not this one... I tried cleaning the plugin cache, but still nothing. I'm not very familiar with Ardour though.

**Comment by daniel-j** [comment]
Seems to be same issue as #77
LinVst works with PipeWire though, so something yabridge does specifically is not compatible with PipeWire's JACK.

**Comment by robbert-vdh** [comment]
Interesting. I can't think of what the issue could be (from your reports it sounds like Wine is being terminated when using PipeWire/JACK), but I'll at least try to replicate this. Thanks!
