### ISSUE TITLE
UVI Plugsound Free (32-bit) not initializing

### ISSUE THREAD

**Issue by artscoop** [robbert-vdh/yabridge#93]
Hello,

**Problem description**
Using yabridge for the UVI Plugsound Free plugin fails. (It's the only one I could find that fails in a list of ~200).

**What did you expect to happen?**
The plugin loads properly.

**What actually happened?**
The bridge fails to initialize in Carla with the following error:
```
19:21:04 [Plugsound Free-CRSWadls] [Wine STDERR] Error while initializing the Wine plugin host:
19:21:04 [Plugsound Free-CRSWadls] [Wine STDERR] VST plugin at '/mnt/Coulomb/Documents/Track/VSTi/PlugSound Free/Plugsound Free.dll' failed to initialize.
19:21:10 Error during initialization:
19:21:10 read: End of file
Plugin failed to load, error was:
Plugin failed to initialize
```

**System information**
- Plugin: UVI Plugsound Free 32-bit (2006, cannot find it anymore on the web)
- Uploaded it on my server for you to download it: http://self.autotion.net/nextcloud/index.php/s/gMm3XcxDKPNCB3Y 
- Plugin type: VST2
- Host: Carla, Renoise
- Operating system: Manjaro
- Wine version: Staging 6.6
- Sound: Jack2-dbus
- Installation method: symlinks and copies
- yabridge version: 3.1.0

**Debug log**
[Output yabridge.log](https://github.com/robbert-vdh/yabridge/files/6370228/yabridge.log)

**Comment by robbert-vdh** [comment]
Ha, good idea to put the audio system in the system information list, I'll have to add that as well.

The plugin was for some reason passing random garbage data to the `data` argument of the VST2 host callback interface when it requested MIDI support, and yabridge would try to read that as a string. 671c6a4c1812afb8261a83c3328ce064a7e88bc6 will prevent this from happening for that opcode, and the plugin thus works fine now. If you want to give it a shot, then you can temporarily switch to the `yabridge-git` AUR package to build yabridge from this commit. Only issue is that Wine 6.6 broke the Wine include paths, so you'll have to upgrade to Wine Staging 6.7 first to be able to compile yabridge. If you install the `downgrade` tool from the repos, then you'll be able to install wine-staging 6.7 using `sudo env DOWNGRADE_FROM_ALA=1 downgrade wine-staging`. Don't forget to rerun `yabridgectl sync` after upgrading!

**Comment by artscoop** [comment]
Hi,
This is perfect. I didn't know about `downgrade`, I could compile/build git master using Wine 6.7 and indeed, the plugin loaded like nothing happened. I seriously am in awe at this.
Again, thanks a lot!
