### ISSUE TITLE
Problems with PSP InfiniStrip 

### ISSUE THREAD

**Issue by rlb303** [robbert-vdh/yabridge#94]
Hello :) i'm trying to use yabridge with PSP InfiniStrip (both VST3 and VST2 to see if either works) but i'm having problems. Would appreciate if you could tell me what's going on. 

My system specs: 

CPU: Ryzen 5900X 
DAW: Bitwig 3.3.7 
System: Linux Mint 20.1 Ulyssa
Kernel:  5.11.0-16.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.11-30ubuntu1~focal (2021-04-21) x86_64 x86_64 x86_64 GNU/Linux
Wine version: wine-staging 6.7 (winetricks installed) 

The VST2 versions pass the plugin scan on Bitwig, but when i drop it on a track, it just hangs while loading and terminal output hangs on "Loading plugins..." 
The VST3 versions don't pass the scan and i get error messages from each, i'll paste down below.  
iLok License Center is installed and the plugin is authorized through machine activation.  
 
Here's the error message from the stereo VST3:

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Communications error with plugin host process
exit code:134
stdout:
PluginHost: Reading VST 3 plugin metadata for /home/rlb303/.vst3/yabridge/PSPaudioware/PSP InfiniStrip stereo.vst3

stderr:
ereo-ABMSZcfk] [Wine STDERR] 0b00:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011B7E0 1 C) semi-stub
13:20:13 [PSP InfiniStrip stereo-ABMSZcfk] [Wine STDERR] 0b00:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011C500 1 C) semi-stub
13:20:13 [PSP InfiniStrip stereo-ABMSZcfk] [Wine STDERR] 0b00:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011C5A0 1 C) semi-stub
13:20:13 [PSP InfiniStrip stereo-ABMSZcfk] [Wine STDERR] 0b00:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011C740 1 *) semi-stub
13:20:13 [PSP InfiniStrip stereo-ABMSZcfk] [Wine STDERR] 0b00:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0000000000116030 1 C) semi-stub
13:20:13 [PSP InfiniStrip stereo-ABMSZcfk] [Wine STDERR] 0b00:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0000000000115CD0 1 C) semi-stub
13:20:13 [PSP InfiniStrip stereo-ABMSZcfk] [Wine STDERR] 0b00:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0000000000116248 1 *) semi-stub
13:20:13 [PSP InfiniStrip stereo-ABMSZcfk] [Wine STDERR] wine: Read access denied for device L"\\??\\G:\\", FS volume label and serial are not available.
13:20:13 [PSP InfiniStrip stereo-ABMSZcfk] [Wine STDERR] wine: Read access denied for device L"\\??\\I:\\", FS volume label and serial are not available.
13:20:13 [PSP InfiniStrip stereo-ABMSZcfk] [Wine STDERR] wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
13:20:13 [PSP InfiniStrip stereo-ABMSZcfk] [Wine STDERR] 0b00:err:ole:com_get_class_object apartment not initialised
13:20:13 [PSP InfiniStrip stereo-ABMSZcfk] [Wine STDERR] Error while initializing the Wine plugin host:
13:20:13 [PSP InfiniStrip stereo-ABMSZcfk] [Wine STDERR] Could not load the VST3 module for '/home/rlb303/.wine/drive_c/Program Files/Common Files/VST3/PSPaudioware/PSP InfiniStrip stereo.vst3': Calling 'GetPluginFactory' returned nullptr!
13:20:13 [PSP InfiniStrip stereo-ABMSZcfk] The Wine host process has exited unexpectedly. Check the output above for more information.
terminate called without an active exception

And here for the mono VST3: 

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Communications error with plugin host process
exit code:134
stdout:
PluginHost: Reading VST 3 plugin metadata for /home/rlb303/.vst3/yabridge/PSPaudioware/PSP InfiniStrip mono.vst3

stderr:
b
13:20:13 [PSP InfiniStrip mono-15HINhly] [Wine STDERR] 0acc:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011B7E0 1 C) semi-stub
13:20:13 [PSP InfiniStrip mono-15HINhly] [Wine STDERR] 0acc:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011C500 1 C) semi-stub
13:20:13 [PSP InfiniStrip mono-15HINhly] [Wine STDERR] 0acc:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011C5A0 1 C) semi-stub
13:20:13 [PSP InfiniStrip mono-15HINhly] [Wine STDERR] 0acc:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011C740 1 *) semi-stub
13:20:13 [PSP InfiniStrip mono-15HINhly] [Wine STDERR] 0acc:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0000000000116030 1 C) semi-stub
13:20:13 [PSP InfiniStrip mono-15HINhly] [Wine STDERR] 0acc:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0000000000115CD0 1 C) semi-stub
13:20:13 [PSP InfiniStrip mono-15HINhly] [Wine STDERR] 0acc:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0000000000116248 1 *) semi-stub
13:20:13 [PSP InfiniStrip mono-15HINhly] [Wine STDERR] wine: Read access denied for device L"\\??\\G:\\", FS volume label and serial are not available.
13:20:13 [PSP InfiniStrip mono-15HINhly] [Wine STDERR] wine: Read access denied for device L"\\??\\I:\\", FS volume label and serial are not available.
13:20:13 [PSP InfiniStrip mono-15HINhly] [Wine STDERR] wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
13:20:13 [PSP InfiniStrip mono-15HINhly] [Wine STDERR] 0acc:err:ole:com_get_class_object apartment not initialised
13:20:13 [PSP InfiniStrip mono-15HINhly] [Wine STDERR] Error while initializing the Wine plugin host:
13:20:13 [PSP InfiniStrip mono-15HINhly] [Wine STDERR] Could not load the VST3 module for '/home/rlb303/.wine/drive_c/Program Files/Common Files/VST3/PSPaudioware/PSP InfiniStrip mono.vst3': Calling 'GetPluginFactory' returned nullptr!
13:20:13 [PSP InfiniStrip mono-15HINhly] The Wine host process has exited unexpectedly. Check the output above for more information.
terminate called without an active exception

**Comment by robbert-vdh** [comment]
Hi,

It seemsl ike the plugin loads successfully, but then intentionally returns a null pointer when creating the plugin's plugin factory. Do you have the iLoK licenser application actively running in the background (in the same Wine prefix as the plugin)? If so, could you please create a proper debug log? Instructions on how to do so are in the [issue template](https://github.com/robbert-vdh/yabridge/blob/master/.github/ISSUE_TEMPLATE/setup_help.md).

**Comment by robbert-vdh** [comment]
(whoops apparently GitHub thinks 'may fix #94' means 'definitely does fix #94' :sweat_smile:)

I tried running the plugin locally, and I could not even get it to load. Apparently the plugin expects Microsoft COM to be initialized by the host, and it will just fail to load if it is not. I've never seen a plugin do that before, but as of commit 86bd19cd80102aca2ff28a94cc78ecc20d7b5209 if a plugin fails to load, yabridge will initialize COM and then try again. It sounds like on your computer the plugin somehow loaded just fine so it could be a different issue, but can you still try the latest master branch commit to see if that changes anything for you? You can download a binary from the [automated builds page](https://github.com/robbert-vdh/yabridge/actions?query=workflow%3A%22Automated+builds%22+branch%3Amaster) (select the latest commit, scroll down to the binaries, and download the correct version for your system). Just replace yabridge's existing files in ~/.local/share with the new ones and rerun `yabridgectl sync`.

And again, also make sure that iLoK is running in the background when you try to use the plugin!

**Comment by rlb303** [comment]
OMG the latest automated build worked! VST3 versions shows up and the plugin opens in Bitwig! THANK YOU!  
VST2 versions pass the scan but are not selectable in Bitwig (weird! but i preffer VST3 anyway) 

The plugin GUI is really "sluguish" takes a while to refresh. I read about the compatibility option, was wondering how do i enable the editor_double_embed option? 

Here's the debug log before i updated to the latest build:  (below this,  i'll post a bit of the debug of the plugin running.. related to the GUI issues) 

17:13:55 [PSP InfiniStrip stereo-KORXjotu] host:          '/home/rlb303/.local/share/yabridge/yabridge-host.exe'
17:13:55 [PSP InfiniStrip stereo-KORXjotu] plugin:        '/home/rlb303/.wine/drive_c/Program Files/Common Files/VST3/PSPaudioware/PSP InfiniStrip stereo.vst3'
17:13:55 [PSP InfiniStrip stereo-KORXjotu] plugin type:   'VST3'
17:13:55 [PSP InfiniStrip stereo-KORXjotu] realtime:      'yes'
17:13:55 [PSP InfiniStrip stereo-KORXjotu] sockets:       '/run/user/1000/yabridge-PSP InfiniStrip stereo-KORXjotu'
17:13:55 [PSP InfiniStrip stereo-KORXjotu] wine prefix:   '/home/rlb303/.wine'
17:13:55 [PSP InfiniStrip stereo-KORXjotu] wine version:  '6.7'
17:13:55 [PSP InfiniStrip stereo-KORXjotu]
17:13:55 [PSP InfiniStrip stereo-KORXjotu] config from:   '<defaults>'
17:13:55 [PSP InfiniStrip stereo-KORXjotu] hosting mode:  'individually, 64-bit'
17:13:55 [PSP InfiniStrip stereo-KORXjotu] other options: '<none>'
17:13:55 [PSP InfiniStrip stereo-KORXjotu]
17:13:55 [PSP InfiniStrip stereo-KORXjotu] Enabled features:
17:13:55 [PSP InfiniStrip stereo-KORXjotu] - bitbridge support
17:13:55 [PSP InfiniStrip stereo-KORXjotu] - VST3 support
17:13:55 [PSP InfiniStrip stereo-KORXjotu]
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] 044c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] 044c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] 0454:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] 0454:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] 045c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] 045c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDOUT] Initializing yabridge host version 3.1.0
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDOUT] Preparing to load VST3 plugin at '/home/rlb303/.wine/drive_c/Program Files/Common Files/VST3/PSPaudioware/PSP InfiniStrip stereo.vst3'
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] 045c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E2E0 1 C) semi-stub
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] 045c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011B7E0 1 C) semi-stub
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] 045c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011C500 1 C) semi-stub
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] 045c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011C5A0 1 C) semi-stub
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] 045c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011C740 1 *) semi-stub
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] 045c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0000000000116030 1 C) semi-stub
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] 045c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0000000000115CD0 1 C) semi-stub
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] 045c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0000000000116248 1 *) semi-stub
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] wine: Read access denied for device L"\\??\\G:\\", FS volume label and serial are not available.
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] wine: Read access denied for device L"\\??\\I:\\", FS volume label and serial are not available.
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] 045c:err:ole:com_get_class_object apartment not initialised
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] Error while initializing the Wine plugin host:
17:13:55 [PSP InfiniStrip stereo-KORXjotu] [Wine STDERR] Could not load the VST3 module for '/home/rlb303/.wine/drive_c/Program Files/Common Files/VST3/PSPaudioware/PSP InfiniStrip stereo.vst3': Calling 'GetPluginFactory' returned nullpt>
17:13:55 [PSP InfiniStrip stereo-KORXjotu] The Wine host process has exited unexpectedly. Check the output above for more information.
17:14:12 [PSP InfiniStrip mono-7LNVbclq] Initializing yabridge version 3.1.0
17:14:12 [PSP InfiniStrip mono-7LNVbclq] host:          '/home/rlb303/.local/share/yabridge/yabridge-host.exe'
17:14:12 [PSP InfiniStrip mono-7LNVbclq] plugin:        '/home/rlb303/.wine/drive_c/Program Files/Common Files/VST3/PSPaudioware/PSP InfiniStrip mono.vst3'
17:14:12 [PSP InfiniStrip mono-7LNVbclq] plugin type:   'VST3'
17:14:12 [PSP InfiniStrip mono-7LNVbclq] realtime:      'yes'
17:14:12 [PSP InfiniStrip mono-7LNVbclq] sockets:       '/run/user/1000/yabridge-PSP InfiniStrip mono-7LNVbclq'
17:14:12 [PSP InfiniStrip mono-7LNVbclq] wine prefix:   '/home/rlb303/.wine'
17:14:12 [PSP InfiniStrip mono-7LNVbclq] wine version:  '6.7'
17:14:12 [PSP InfiniStrip mono-7LNVbclq]
17:14:12 [PSP InfiniStrip mono-7LNVbclq] config from:   '<defaults>'
17:14:12 [PSP InfiniStrip mono-7LNVbclq] hosting mode:  'individually, 64-bit'
17:14:12 [PSP InfiniStrip mono-7LNVbclq] other options: '<none>'
17:14:12 [PSP InfiniStrip mono-7LNVbclq]

Now the GUI issues 

17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_DrawTextLayout Failed to draw text layout, hr 0x80004005.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_DrawGeometry Ignoring stroke style 00000000075218A0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_DrawGeometry Ignoring stroke style 00000000075218A0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_DrawTextLayout Failed to draw text layout, hr 0x80004005.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_DrawGeometry Ignoring stroke style 00000000075218A0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_DrawTextLayout Failed to draw text layout, hr 0x80004005.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_PushAxisAlignedClip Ignoring antialias_mode 0.
17:23:09 [PSP InfiniStrip stereo-4BJNSgoq] [Wine STDERR] 0578:fixme:d2d:d2d_device_context_DrawTextLayout Failed to draw text layout, hr 0x80004005.

The debug log has like 3000 lines and most are from the GUI issues, just a few seconds turning the knobs LOL.

**Comment by robbert-vdh** [comment]
> VST2 versions pass the scan but are not selectable in Bitwig (weird! but i preffer VST3 anyway)

That's probably Bitwig hiding the VST2 version since there's also a VST3 version of the same plugin. You can control that behavior in the settings under the Behavior tab.

And yes the plugin is also very slow to draw on my machine. That's probably just a combination of the plugin somehow doing a lot of draw calls, and Wine's D2D1 implementation not being very well optimized yet. I wouldn't try this but if you disable Wine's D2D1 support, the plugin will fall back to software rendering and it will be slower than it already is right now. By a wide margin. So the plugin itself is likely also to blame here.

**Comment by rlb303** [comment]
>the plugin will fall back to software rendering and it will be slower than it already is right now. By a wide margin.

Ah! So that's what i experienced when i used the other bridge (LinVST3-X) with D2D1 disabled.. yeah i can live with the GUI a little sluguish i guess  untill D2D1 gets some attention from the wine devs. I talked with PSP support few weeks back and they said they are working on an new engine that might fix this problem for those who use it with Wine on Linux. 

Anyway, thank you very much! bug fixed and issue closed.
