### ISSUE TITLE
VST3 of W.A Production Ascension not working

### ISSUE THREAD

**Issue by fooltopia** [robbert-vdh/yabridge#96]
**Problem description**

The VST3 version of Ascension can be loaded, but the GUI doesn't resize properly (see screenshot below)
The VST2 version works fine. 

The demo is available at this link, but you'll need to give an email adress. If that's a problem, I'll upload it to another hosting service.
https://www.waproduction.com/plugins/view/ascension-w-a-production-edition

It's not a big issue since the VST2 works for me, but I thought you might be interested anyway. 

**System information**
- Plugin: Ascension
- Plugin type: VST3
- Host: REAPER 
- Operating system: Manjaro]
- Wine version: Wine 6.4 (and some earlier versions)
- Audio: ACK2
- Installation method: yabridgectl default
- yabridge version: 3.1.0-1
- yabridgectl version: 3.1.0-1

**Debug log**
Please also include a debug log if possible. If you are reporting an issue with yabridgectl, then you can omit this section.

[yabridge_ascension.log](https://github.com/robbert-vdh/yabridge/files/6385177/yabridge_ascension.log)

![ascension_gui_cut_off](https://user-images.githubusercontent.com/9214469/116252833-373f4080-a770-11eb-9afc-9224c6594b75.png)

**Comment by robbert-vdh** [comment]
Thanks for the report! I'll take a look to see if it's something we can fix on our side or if they're doing something odd.

**Comment by robbert-vdh** [comment]
On a closer look, this may be related to HiDPI scaling since the resizing behaviour looks absolutely correct from the log. HiDPI scaling in Wine tends to only work with the built in gdiplus (and not the native override from winetricks), and it also only works consistently-ish when setting a 192 font DPI in winecfg. So your options are to either set a 192 font DPI in winecfg, or to disable VST3 plugin scaling by creating a `yabridge.toml` config file over at `~/.vst3/yabridge/yabridge.toml` containing the following:

```
["Ascension/Ascension.vst3"]
vst3_no_scaling = true
```

See the [compatibilty options](https://github.com/robbert-vdh/yabridge#compatibility-options) section of the readme (and the rest of the Configuration section around it) for more information on what this does.

**Comment by fooltopia** [comment]
Thanks for your quick response. I've added the 'vst3_no_scaling' option and it works better now. The first time I add the plugin, REAPER's window is even smaller, but after closing and reopening the UI it looks good. 

Here's another log where I added the plugin, closed the too small gui window, and opened it again where it had the correct size if you're interested in investigating this further. 
[yabridge_ascension_2.log](https://github.com/robbert-vdh/yabridge/files/6385963/yabridge_ascension_2.log)


Other plugins like  MeldaProduction seem to handle my winecfg scaling of 144dpi correctly. Do you have an idea why that is?

**Comment by robbert-vdh** [comment]
It's likely because they use different drawing libraries. Have you tried setting your font DPI in Wine to 192? One user in the Discord reported that that fixed these kinds of issues for him.

**Comment by fooltopia** [comment]
I just tried setting the DPI to 192 and the Plugin's UI is now much bigger (too big for my screen), but REAPER's window size remains the same. (with vst3_no_scaling set to false)

I also tried setting it to 96, and then the Plugin's UI is smaller, but REAPER's window is too big. When I use the plugin's scaling setting, it becomes bigger, but REAPER's window also gets bigger with an unnecessary margin. 

I guess there's something weird going on with this plugin and I'll just keep using the VST2 version, so feel free to close this. 

Thanks for looking into it, though. Yabridge is really great.

**Comment by robbert-vdh** [comment]
You'd probably need to leave VST3 scaling enabled, and then mess with the font DPI to find the sweet spot. But yeah, HiDPI in Wine is quite a mess. I love my 1440p ThinkPad, but I'm very glad I don't do any music production with it :grin:.

There's sadly nothing I can do for you to fix this, but I'm glad that the VST2 version at least works fine!

**Comment by fooltopia** [comment]
Just an update: I reset wine scaling to 96dpi (lowest possible value) and  set "vst3_no_scaling = true" and it works now. This also solved the scaling issues I had with Initial Audio Heat Up 3 and Sektor. 

Thanks for your help :)
