### ISSUE TITLE
WA Production Imperfect VST3 Crashes

### ISSUE THREAD

**Issue by fooltopia** [robbert-vdh/yabridge#97]
**Problem description**
When I load the VST3 version of Imperfect, my DAW crashes. The VST2 version works fine. 
The Demo can be downloaded here: https://www.waproduction.com/plugins/view/imperfect

It's not a big issue since the VST2 works for me, but I thought you might be interested anyway. 

**System information**
- Plugin: Ascension
- Plugin type: VST3
- Host: REAPER 
- Operating system: Manjaro]
- Wine version: Wine 6.4 (and some earlier versions)
- Audio: ACK2
- Installation method: yabridgectl default
- yabridge version: 3.1.0-1
- yabridgectl version: 3.1.0-1

**Debug log**
Please also include a debug log if possible. If you are reporting an issue with yabridgectl, then you can omit this section.

[yabridge_imperfect.log](https://github.com/robbert-vdh/yabridge/files/6385175/yabridge_imperfect.log)

**Comment by robbert-vdh** [comment]
Also thanks for reporting this one! I'll check if we can do something about this this in yabridge. In the log the plugin is also complaining that it can't load some files, that may or may not be related.

**Comment by fooltopia** [comment]
It's weird that it complains about the missing file because the directory exists and the VST2 version is using it just fine.

**Comment by robbert-vdh** [comment]
Does the VST2 version also print the same message (even if it does work)?

**Comment by fooltopia** [comment]
It doesn't. Here's the log 
[yabridge_imperfect_vst2.log](https://github.com/robbert-vdh/yabridge/files/6386112/yabridge_imperfect_vst2.log)

W.A. Production plugins do weird things with files on wine, though. I had to use `strace` to figure out where to place the license files because they were at different locations than the documentation said.

**Comment by robbert-vdh** [comment]
This next yabridge release is going to 'fix' a whole lot of buggy plugins haha. This synth somehow expects there to be an input speaker arrangement, even if the plugin has zero inputs. The latest master branch contains a workaround for this. If you want to give this a try, then you can install/rebuild the `yabridge-git` AUR package. Don't forget to rerun `yabridgectl sync` after upgrading the package!
